GRANT SELECT, DELETE, INSERT, UPDATE ON MIS.SMS_ALERT_CAPTURE TO fdstore_ststg01;
GRANT SELECT, DELETE, INSERT, UPDATE ON MIS.SMS_ALERT_CAPTURE TO fdtrn_ststg01;
GRANT SELECT ON MIS.SMS_ALERT_CAPTURE TO appdev;

GRANT SELECT, DELETE, INSERT, UPDATE ON MIS.SMS_RECEIVED TO fdstore_ststg01;
GRANT SELECT, DELETE, INSERT, UPDATE ON MIS.SMS_RECEIVED TO fdtrn_ststg01;
GRANT SELECT ON MIS.SMS_RECEIVED TO appdev;

GRANT SELECT ON MIS.SMS_ALERT_SEQ TO fdstore_ststg01;
GRANT SELECT ON MIS.SMS_ALERT_SEQ TO appdev;

GRANT SELECT ON MIS.SMS_RECEIVED_SEQ TO fdstore_ststg01;
GRANT SELECT ON MIS.SMS_RECEIVED_SEQ TO appdev;

GRANT SELECT, DELETE, INSERT, UPDATE ON DLV.SMS_TRANSIT_EXPORT TO fdstore_ststg01;
GRANT SELECT, DELETE, INSERT, UPDATE ON DLV.SMS_TRANSIT_EXPORT TO fdtrn_ststg01;
GRANT SELECT ON DLV.SMS_TRANSIT_EXPORT TO appdev;

GRANT SELECT, DELETE, INSERT, UPDATE ON DLV.NEXTSTOP_SMS TO fdstore_ststg01;
GRANT SELECT, DELETE, INSERT, UPDATE ON DLV.NEXTSTOP_SMS TO fdtrn_ststg01;
GRANT SELECT ON DLV.NEXTSTOP_SMS TO appdev;

GRANT SELECT ON DLV.TRANSIT TO appdev;
GRANT SELECT ON DLV.TRANSIT TO fdstore_ststg01;
GRANT SELECT ON DLV.TRANSIT TO fdtrn_ststg01;