CREATE TABLE CUST.LOGISTICS_FDX_ORDER
(
  ORDER_ID                 VARCHAR2(16 BYTE)    NOT NULL,
  PARENT_ID                VARCHAR2(16 BYTE),
  TIP                      NUMBER(5,2),
  RESERVATION_ID           VARCHAR2(16 BYTE),
  MOBILE_NUMBER            VARCHAR2(15 BYTE),
  DELIVERY_INSTRUCTIONS    VARCHAR2(255 BYTE),
  UNATTENDED_INSTRUCTIONS  VARCHAR2(55 BYTE),
  SERVICE_TYPE             VARCHAR2(25 BYTE),
  FIRST_NAME               VARCHAR2(55 BYTE),
  LAST_NAME                VARCHAR2(55 BYTE),
  STATUS                   VARCHAR2(25 BYTE)
) TABLESPACE FDCUSDAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE CUST.LOGISTICS_FDX_ORDER ADD (
  PRIMARY KEY
 (ORDER_ID)
    USING INDEX 
    TABLESPACE FDCUSDAT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));




GRANT DELETE, INSERT, SELECT, UPDATE ON CUST.LOGISTICS_FDX_ORDER TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUST.LOGISTICS_FDX_ORDER TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUST.LOGISTICS_FDX_ORDER TO FDSTORE_STPRD01;
GRANT SELECT ON CUST.LOGISTICS_FDX_ORDER TO FDLOGISTICS;
GRANT SELECT ON CUST.LOGISTICS_FDX_ORDER TO APPDEV;
