CREATE TABLE CUST.LOGISTICS_FDX_ORDER
(
  ORDER_ID                 VARCHAR2(16 BYTE)    NOT NULL,
  PARENT_ID                VARCHAR2(16 BYTE),
  TIP                      NUMBER(5,2),
  RESERVATION_ID           VARCHAR2(16 BYTE),
  MOBILE_NUMBER            VARCHAR2(15 BYTE),
  DELIVERY_INSTRUCTIONS    VARCHAR2(255 BYTE),
  UNATTENDED_INSTRUCTIONS  VARCHAR2(55 BYTE),
  SERVICE_TYPE             VARCHAR2(25 BYTE),
  FIRST_NAME               VARCHAR2(55 BYTE),
  LAST_NAME                VARCHAR2(55 BYTE),
  STATUS                   VARCHAR2(25 BYTE)
);