CREATE TABLE TRANSP.FDX_EMPLOYEE
(
  EMPLOYEE_ID  VARCHAR2(25 BYTE),
  FIRST_NAME   VARCHAR2(55 BYTE),
  LAST_NAME    VARCHAR2(55 BYTE),
  JOB_TYPE     VARCHAR2(25 BYTE),
  COMPANY      VARCHAR2(25 BYTE),
  ID           VARCHAR2(55 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

ALTER TABLE TRANSP.FDX_EMPLOYEE ADD (
  CONSTRAINT FDX_EMPLOYEE_PK
 PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.FDX_EMPLOYEE TO FDSTORE_STPRD01;
GRANT SELECT ON TRANSP.FDX_EMPLOYEE TO APPDEV;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.FDX_EMPLOYEE TO FDLOGISTICS;

Insert into TRANSP.MENU
   (MENU_ID, LINK, MENU_TITLE, ORIENTATION, MENU_PARENT_ID)
 Values
   ('ADO026', 'fdxEmployee.do', 'Manage FDX Employee', 'RIGHT', 'MNM006');

Insert into TRANSP.PAGES
   (PAGE_ID, PAGE_URI)
 Values
   (165, 'fdxEmployee.do');

Insert into TRANSP.MENU_PAGE
   (MENU_ID, PAGE_ID)
 Values
   ('ADO026', 165);

Insert into TRANSP.MENU_COMPANY_CODE
   (MENU_ID, COMPANY_CODE)
 Values
   ('ADO026', 'fdx');

Insert into TRANSP.MENU_ROLE
   (MENU_ID, ROLE_ID)
 Values
   ('ADO026', 6);



 