--Create table DLV.SERVICETIME
CREATE TABLE DLV.SERVICETIME
(
  SERVICETIME_TYPE       VARCHAR2(8 BYTE)       NOT NULL,
  ZONE_TYPE              VARCHAR2(16 BYTE)      NOT NULL,
  FIXED_SERVICE_TIME     NUMBER(10,2),
  VARIABLE_SERVICE_TIME  NUMBER(10,2)
)

GRANT ALL ON DLV.SERVICETIME TO fdstore_stprd01;
GRANT ALL ON DLV.SERVICETIME TO fdtrn_stprd01;
GRANT SELECT ON  DLV.SERVICETIME TO appdev;

ALTER TABLE DLV.SERVICETIME ADD (
  CONSTRAINT PK_SERVICETIME
 PRIMARY KEY
 (SERVICETIME_TYPE, ZONE_TYPE)

ALTER TABLE DLV.SERVICETIME ADD (
  CONSTRAINT ACT_SERVICETIME_FK 
 FOREIGN KEY (SERVICETIME_TYPE) 
 REFERENCES DLV.SERVICETIME_TYPE (CODE));

--DROP FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME from dlv.servicetime_type
ALTER TABLE 
    DLV.SERVICETIME_TYPE
drop(FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME);
    
--SERVICETIME_SCENARIO
ALTER TABLE DLV.SERVICETIME_SCENARIO
    add (
           DEFAULT_SERVICETIME_TYPE    VARCHAR2(8 BYTE),
	   DEFAULT_ZONE_TYPE           VARCHAR2(16 BYTE),
	 );

ALTER TABLE DLV.SERVICETIME_SCENARIO ADD (
  CONSTRAINT ACT_SCENARIO_STTYPE_FK 
 FOREIGN KEY (DEFAULT_SERVICETIME_TYPE) 
 REFERENCES DLV.SERVICETIME_TYPE (CODE));

--drop Table (DLV.SCENARIO_DAYS)
DROP TABLE DLV.SCENARIO_DAYS CASCADE CONSTRAINTS;

--drop sequence
DROP SEQUENCE DLV.DELIVERY_SCENARIO_SEQ;

--drop Table (DLV.SCENARIO_ZONES)
DROP TABLE DLV.SCENARIO_ZONES CASCADE CONSTRAINTS;

--drop Servicetime_type from Zone table
ALTER TABLE 
    TRANSP.ZONE
drop column SERVICETIME_TYPE;

--drop columns from DELIVERY_BUILDING table
ALTER TABLE DLV.DELIVERY_BUILDING
drop (SERVICETIME_OVERRIDE,SERVICETIME_OPERATOR,SERVICETIME_ADJUSTMENT);

--drop new columns from DLV.DELIVERY_BUILDING_DETAIL
Alter table DLV.DELIVERY_BUILDING_DETAIL 
drop(SVC_TIME_TYPE,SVC_TIME_OVERRIDE,SVC_TIME_OPERATOR,SVC_TIME_ADJUSTMENT);

Alter table DLV.DELIVERY_BUILDING_DETAIL
add column SVC_TIME_OVERRIDE  VARCHAR2(255 BYTE);

--drop new columns from DELIVERY_LOCATION table
ALTER TABLE DLV.DELIVERY_LOCATION
drop (
        SERVICETIME_OVERRIDE,
        SERVICETIME_OPERATOR,
        SERVICETIME_ADJUSTMENT
     );