CREATE TABLE CUST.SALE_CRO_MOD_DATE
(
  SALE_ID   VARCHAR2(16 BYTE)                   NOT NULL,
  MAX_DATE  DATE                                NOT NULL, 
  CONSTRAINT "PK_SALE_CRO_MOD_DATE" PRIMARY KEY ("SALE_ID")
);

CREATE INDEX SALE_CRO_MOD_MAX_DATE_IDX ON CUST.SALE_CRO_MOD_DATE
(MAX_DATE) compute statistics;

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.SALE_CRO_MOD_DATE TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.SALE_CRO_MOD_DATE TO FDSTORE_PRDB;

INSERT INTO CUST.SALE_CRO_MOD_DATE 
select sale_id, max(action_date)
from cust.salesaction
where action_type in ('CRO', 'MOD')
group by sale_id;