ALTER TABLE "CUST"."SO_HOLIDAY_ALT_DATE" 
drop column "DESCRIPTION"; 

ALTER TABLE "CUST"."SO_HOLIDAY_ALT_DATE"
drop CONSTRAINT PK_SO_HOLIDAY_ALT_DATE;

ALTER TABLE "CUST"."SALE"
drop column "SO_HOLIDAY_MOVEMENT"; 
