insert into ss_variant_assignment values ('C2', sysdate, 'srch');
insert into ss_variant_assignment values ('C6', sysdate, 'srch');
insert into ss_variant_assignment values ('C9', sysdate, 'srch');
insert into ss_variant_assignment values ('C10', sysdate, 'srch');
insert into ss_variant_assignment values ('C11', sysdate, 'srch');
insert into ss_variant_assignment values ('C12', sysdate, 'srch');
insert into ss_variant_assignment values ('C18', sysdate, 'srch');
insert into ss_variant_assignment values ('C19', sysdate, 'srch');
insert into ss_variant_assignment values ('C20', sysdate, 'srch');

insert into ss_variant_assignment values ('C2', sysdate, 'ymal');
insert into ss_variant_assignment values ('C6', sysdate, 'ymal');
insert into ss_variant_assignment values ('C9', sysdate, 'ymal');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal');

insert into ss_variant_assignment values ('C2', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C6', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C9', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal_pdtl');

insert into ss_variant_assignment values ('C2', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C6', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C9', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C10', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C11', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C12', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C18', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C19', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C20', sysdate, 'srch_pers');

insert into ss_variant_assignment values ('C2', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C6', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C9', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C10', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C11', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C12', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C18', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C19', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C20', sysdate, 'srch_rltd');

insert into ss_variant_assignment values ('C3', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C5', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C7', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C8', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C13', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C14', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C15', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C16', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C17', sysdate, 'ymal_pdtl');

insert into ss_variant_assignment values ('C3', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C5', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C7', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C8', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C13', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C14', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C15', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C16', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C17', sysdate, 'srch_pers');

insert into ss_variant_assignment values ('C3', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C5', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C7', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C8', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C13', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C14', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C15', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C16', sysdate, 'srch_rltd');
insert into ss_variant_assignment values ('C17', sysdate, 'srch_rltd');
commit;