--
-- Restore tab strategy table had existed before SAVINGS variants were removed
--
-- @author gsebestyen
-- @ticket APPDEV-2320
--

-- Remove content
--
delete from CUST.SS_TAB_STRATEGY_PRIORITY;

-- Fill in with the content having savings variants
--
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_SAVE_YF',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','DYF',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_SAVE_FDF',10,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','FAVORITES',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_HEALTHY_SNACKS',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_DEALS',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_YMAL',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_PEAK_FRUIT',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_PEAK_PRODUCE',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_NEW_PRODUCTS',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_PEAK_FRUIT',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_PEAK_PRODUCE',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_NEW_PRODUCTS',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_SAVE_YF',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','DYF',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_SAVE_FDF',20,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','FAVORITES',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_HEALTHY_SNACKS',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_DEALS',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_YMAL',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_HEALTHY_SNACKS',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_DEALS',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_YMAL',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_PEAK_FRUIT',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_PEAK_PRODUCE',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_NEW_PRODUCTS',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_SAVE_YF',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','DYF',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_SAVE_FDF',30,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','FAVORITES',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_SAVE_YF',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','DYF',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_SAVE_FDF',10,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','FAVORITES',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_YMAL',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_YMAL_YF',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_DEALS',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_HEALTHY_SNACKS',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_NEW_PRODUCTS',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_PEAK_PRODUCE',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','FAVORITES',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','COS_FDF',10,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','COS_FDF',20,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','COS_FDF',30,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','COS_FDF',10,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','COS_FDF',10,9);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','COS_FDF',10,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','COS_FDF',10,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','COS_FDF',10,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave','C_SAVE_COS_FDF',10,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1peak','C_SAVE_COS_FDF',20,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1deal','C_SAVE_COS_FDF',30,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var2fave','C_SAVE_COS_FDF',10,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_SAVE_COS_FDF',10,8);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_SAVE_COS_FDF',10,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_SAVE_COS_FDF',10,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_SAVE_COS_FDF',10,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','SCARAB_CART',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','DYF',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_SAVE_COS_FDF',10,23);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','COS_FDF',10,24);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_SAVE_FDF',10,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','FAVORITES',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','SCARAB_PERSONAL',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_PEAK_FRUIT',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_PEAK_PRODUCE',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_NEW_PRODUCTS',20,40);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_HEALTHY_SNACKS',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_DEALS',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb3','C_YMAL',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_SAVE_YF',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','DYF',10,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_SAVE_FDF',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_SAVE_YF',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_HEALTHY_SNACKS',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_DEALS',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_YMAL',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_PEAK_FRUIT',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_PEAK_PRODUCE',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','DYF',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_SAVE_FDF',10,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','FAVORITES',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_HEALTHY_SNACKS',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_DEALS',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_YMAL',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_PEAK_FRUIT',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_PEAK_PRODUCE',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c2','C_NEW_PRODUCTS',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_SAVE_YF',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','DYF',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_SAVE_FDF',10,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','FAVORITES',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','SCARAB_PERSONAL',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_PEAK_FRUIT',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_PEAK_PRODUCE',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_NEW_PRODUCTS',20,40);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_HEALTHY_SNACKS',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_DEALS',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb2','C_YMAL',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1fave_c','C_NEW_PRODUCTS',30,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_SAVE_YF',10,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','DYF',10,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_SAVE_FDF',10,25);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','FAVORITES',10,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','SCARAB_PERSONAL',20,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_PEAK_FRUIT',20,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_PEAK_PRODUCE',20,30);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_NEW_PRODUCTS',20,40);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_HEALTHY_SNACKS',30,10);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_DEALS',30,20);
Insert into CUST.SS_TAB_STRATEGY_PRIORITY (TAB_STRATEGY_ID,SITE_FEATURE_ID,PRIMARY_PRIORITY,SECONDARY_PRIORITY) values ('tabs_var1f_scrb','C_YMAL',30,30);
