insert into ss_variant_assignment values ('C02', sysdate, 'srch');
insert into ss_variant_assignment values ('C06', sysdate, 'srch');
insert into ss_variant_assignment values ('C09', sysdate, 'srch');
insert into ss_variant_assignment values ('C10', sysdate, 'srch');
insert into ss_variant_assignment values ('C11', sysdate, 'srch');
insert into ss_variant_assignment values ('C12', sysdate, 'srch');
insert into ss_variant_assignment values ('C18', sysdate, 'srch');
insert into ss_variant_assignment values ('C19', sysdate, 'srch');
insert into ss_variant_assignment values ('C20', sysdate, 'srch');

insert into ss_variant_assignment values ('C02', sysdate, 'ymal');
insert into ss_variant_assignment values ('C06', sysdate, 'ymal');
insert into ss_variant_assignment values ('C09', sysdate, 'ymal');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal');

insert into ss_variant_assignment values ('C02', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C06', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C09', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal_pdtl');

insert into ss_variant_assignment values ('C02', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C06', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C09', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C10', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C11', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C12', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C18', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C19', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C20', sysdate, 'srch_pers');

insert into ss_variant_assignment values ('C03', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C05', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C07', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C08', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C13', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C14', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C15', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C16', sysdate, 'ymal_pdtl');
insert into ss_variant_assignment values ('C17', sysdate, 'ymal_pdtl');

insert into ss_variant_assignment values ('C03', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C05', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C07', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C08', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C13', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C14', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C15', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C16', sysdate, 'srch_pers');
insert into ss_variant_assignment values ('C17', sysdate, 'srch_pers');
commit;