-- 
-- APPDEV-3179
-- Attributes for PDP feature
-- Be sure to apply this changeset to CMS schema!

INSERT INTO relationshipdefinition (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,READONLY,LABEL,CARDINALITY_CODE)
 	VALUES ('PDP_UPSELL','Product.PDP_UPSELL','Product','F','F','F','F','Upsell','Many');
INSERT INTO relationshipdefinition (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,READONLY,LABEL,CARDINALITY_CODE)
	VALUES ('PDP_XSELL','Product.PDP_XSELL','Product','F','F','F','F','Cross-Sell','Many');


INSERT INTO relationshipdestination (ID, RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,REVERSE_ATTRIBUTE_NAME,REVERSE_ATTRIBUTE_LABEL)
	VALUES ('Product.PDP_UPSELL.Product','Product.PDP_UPSELL','Product',NULL,NULL);
INSERT INTO relationshipdestination (ID, RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,REVERSE_ATTRIBUTE_NAME,REVERSE_ATTRIBUTE_LABEL)
	VALUES ('Product.PDP_UPSELL.ConfiguredProduct','Product.PDP_UPSELL','ConfiguredProduct',NULL,NULL);

INSERT INTO relationshipdestination (ID, RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,REVERSE_ATTRIBUTE_NAME,REVERSE_ATTRIBUTE_LABEL)
	VALUES ('Product.PDP_XSELL.Product','Product.PDP_XSELL','Product',NULL,NULL);
INSERT INTO relationshipdestination (ID, RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,REVERSE_ATTRIBUTE_NAME,REVERSE_ATTRIBUTE_LABEL)
	VALUES ('Product.PDP_XSELL.ConfiguredProduct','Product.PDP_XSELL','ConfiguredProduct',NULL,NULL);
