insert into ss_variant_assignment values ('C02', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C06', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C09', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'srch_certona');

insert into ss_variant_assignment values ('C02', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C06', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C09', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal_certona');

insert into ss_variant_assignment values ('C02', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C06', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C09', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal_pdtl_certona');

insert into ss_variant_assignment values ('C02', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C06', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C09', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'right_nav_certona');

insert into ss_variant_assignment values ('C02', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C06', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C09', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'brws_cat_list_certona');

insert into ss_variant_assignment values ('C02', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C06', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C09', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'brws_prd_list_certona');

insert into ss_variant_assignment values ('C03', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C05', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C07', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C08', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C13', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C14', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C15', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C16', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C17', sysdate, 'right_nav_scarab');

insert into ss_variant_assignment values ('C03', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C05', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C07', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C08', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C13', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C14', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C15', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C16', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C17', sysdate, 'brws_cat_list_scr_pers');

insert into ss_variant_assignment values ('C03', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C05', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C07', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C08', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C13', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C14', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C15', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C16', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C17', sysdate, 'brws_prd_list_scr_pers');
commit;