--
-- APPDEV-5266 - Create TimeToComplete field
--
INSERT INTO attributedefinition (NAME,ID,CONTENTTYPE_ID,ATTRIBUTETYPE_CODE,INHERITABLE,REQUIRED,LABEL,CARDINALITY_CODE,LOOKUP_CODE)
VALUES ('TIME_TO_COMPLETE','Product.TIME_TO_COMPLETE','Product','I','F','F','Time To Complete','One',NULL);
