insert into ss_variant_assignment values ('C2', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C6', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C9', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'srch_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'srch_certona');

insert into ss_variant_assignment values ('C2', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C6', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C9', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal_certona');

insert into ss_variant_assignment values ('C2', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C6', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C9', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'ymal_pdtl_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'ymal_pdtl_certona');

insert into ss_variant_assignment values ('C2', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C6', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C9', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'right_nav_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'right_nav_certona');

insert into ss_variant_assignment values ('C2', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C6', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C9', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C10', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C11', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C12', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C18', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C19', sysdate, 'right_nav_certona_rltd');
insert into ss_variant_assignment values ('C20', sysdate, 'right_nav_certona_rltd');

insert into ss_variant_assignment values ('C2', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C6', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C9', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'brws_cat_list_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'brws_cat_list_certona');

insert into ss_variant_assignment values ('C2', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C6', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C9', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C10', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C11', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C12', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C18', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C19', sysdate, 'brws_prd_list_certona');
insert into ss_variant_assignment values ('C20', sysdate, 'brws_prd_list_certona');

insert into ss_variant_assignment values ('C3', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C5', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C7', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C08', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C13', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C14', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C15', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C16', sysdate, 'right_nav_scarab');
insert into ss_variant_assignment values ('C17', sysdate, 'right_nav_scarab');

insert into ss_variant_assignment values ('C3', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C5', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C7', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C8', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C13', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C14', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C15', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C16', sysdate, 'right_nav_scarab_rltd');
insert into ss_variant_assignment values ('C17', sysdate, 'right_nav_scarab_rltd');

insert into ss_variant_assignment values ('C3', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C5', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C7', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C8', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C13', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C14', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C15', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C16', sysdate, 'brws_cat_list_scr_pers');
insert into ss_variant_assignment values ('C17', sysdate, 'brws_cat_list_scr_pers');

insert into ss_variant_assignment values ('C3', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C5', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C7', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C8', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C13', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C14', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C15', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C16', sysdate, 'brws_prd_list_scr_pers');
insert into ss_variant_assignment values ('C17', sysdate, 'brws_prd_list_scr_pers');
commit;