CREATE TABLE CRM_SESSION_STATUS
(
  AGENT_ID     VARCHAR2(16 BYTE),
  SALE_ID      VARCHAR2(16 BYTE),
  CASE_ID      VARCHAR2(16 BYTE),
  CUSTOMER_ID  VARCHAR2(16 BYTE)
);


CREATE UNIQUE INDEX CSS_PK ON CRM_SESSION_STATUS
(AGENT_ID);


ALTER TABLE CRM_SESSION_STATUS ADD (
  CONSTRAINT CSS_PK PRIMARY KEY (AGENT_ID));


GRANT DELETE, INSERT, SELECT, UPDATE ON  CRM_SESSION_STATUS TO FDSTORE;