ALTER TABLE DLV.ZIPPLUSFOUR_EXCEPTIONS
  ADD CITY VARCHAR2(28)

CREATE TABLE DLV.MUNICIPALITY_INFO
(
  STATE               VARCHAR2(2)          NOT NULL,
  COUNTY              VARCHAR2(40),
  CITY                VARCHAR2(40),
  TAX_RATE            NUMBER(7,5)               NOT NULL,
  BOTTLE_DEPOSIT      NUMBER(4,2)               NOT NULL,
  GL_CODE             VARCHAR2(25),
  ALCOHOL_RESTRICTED  VARCHAR2(1)
);


CREATE INDEX DLV.MUNICIPALITY_INFO_IDX ON DLV.MUNICIPALITY_INFO
(STATE, CITY)
LOGGING
NOPARALLEL;


GRANT SELECT ON  DLV.MUNICIPALITY_INFO TO FDSTORE_PRDA;
GRANT SELECT ON  DLV.MUNICIPALITY_INFO TO FDSTORE_PRDB;
GRANT SELECT ON  DLV.MUNICIPALITY_INFO TO APPDEV;

insert into dlv.municipality_info(state, tax_rate, bottle_deposit, gl_code) values ('NY', '0.08625', '0.05', 'NY-2005');

