ALTER TABLE CUST.ADDRESS
  ADD ALT_CONTACT_PHONE VARCHAR2(15)
  ADD ALT_CONTACT_EXT VARCHAR2(5)
  
ALTER TABLE CUST.DELIVERYINFO
  ADD ALT_CONTACT_PHONE VARCHAR2(15)
  ADD ALT_CONTACT_EXT VARCHAR2(5)