INSERT INTO CUST.PROMOTION (ID, CODE, NAME, DESCRIPTION, MAX_USAGE, START_DATE, EXPIRATION_DATE, REDEMPTION_CODE,
	   					   	 CAMPAIGN_CODE, MIN_SUBTOTAL, MAX_AMOUNT, CATEGORY_NAME, PRODUCT_NAME )
VALUES ( 
CUST.system_seq.nextval,
'FD_MORTEN', '$30 Discount', '$30 Discount', 
1,  TO_Date( '01/15/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/31/2005 11:59:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'CAR3005', 'REDEMPTION'
, 0, 30, null, null ); 