--
-- RESTRICTEDPAYMENTMETHOD  (Table) 
--
CREATE TABLE "RESTRICTEDPAYMENTMETHOD"
(
"ID" VARCHAR2(16) NOT NULL,
"CUSTOMER_ID" VARCHAR2(16),
"PAYMENT_METHOD_ID" VARCHAR2(16),
"FIRST_NAME" VARCHAR2(80),
"LAST_NAME" VARCHAR2(80),
"PAYMENT_METHOD_TYPE" VARCHAR2(2),  	-- i.e. 'CC' - credit card, 'EC' - eChecks
"CARD_TYPE" VARCHAR2(6),  	-- for credit cards i.e. 'VISA', 'AMEX', 'MC', 'DISC'
"EXPIRATION_DATE" DATE,		-- for credit cards
"BANK_NAME" VARCHAR2(80),	-- for eChecks
"BANK_ACCOUNT_TYPE" VARCHAR2(1),-- for eChecks i.e 'C', 'S' and 'X' 
"ABA_ROUTE_PATTERN_TYPE" VARCHAR2(2), -- for eChecks i.e. 'EQ', 'SW', 'EW', 'CT'
"ABA_ROUTE_NUMBER" VARCHAR2(9), -- for eChecks
"ACCOUNT_PATTERN_TYPE" VARCHAR2(2), -- i.e. 'EQ', 'SW', 'EW', 'CT'
"ACCOUNT_NUMBER" VARCHAR2(25),
"STATUS" VARCHAR2(3) NOT NULL, -- i.e. BAD, PND (pending approval), DEL (deleted)
"SOURCE" VARCHAR2(3) NOT NULL, -- i.e. CRM, SYS
"CREATE_USER" VARCHAR2(16) NOT NULL, 
"LAST_MODIFY_USER" VARCHAR2(16), 
"CREATE_DATE" DATE NOT NULL, 
"LAST_MODIFY_DATE" DATE, 
"CASE_ID" VARCHAR2(16),
"REASON_CODE" VARCHAR2(4),
"NOTE" VARCHAR2(256),
CONSTRAINT "PK_RESTRICTEDPAYMENTMETHOD" PRIMARY KEY ("ID")
);


--
-- RPM_CUST_IDX  (Index) 
--
CREATE INDEX CUST.RPM_CUST_IDX ON CUST.RESTRICTEDPAYMENTMETHOD(CUSTOMER_ID);

--
-- RPM_PM_IDX  (Index) 
--
CREATE INDEX CUST.RPM_PM_IDX ON CUST.RESTRICTEDPAYMENTMETHOD(PAYMENT_METHOD_ID);

--
-- RPM_ABA_ACCT_IDX  (Index) 
--
CREATE INDEX CUST.RPM_ABA_ACCT_IDX ON CUST.RESTRICTEDPAYMENTMETHOD(ACCOUNT_NUMBER, ABA_ROUTE_NUMBER);

--
-- RPM_LN_FN_IDX  (Index) 
--
CREATE INDEX CUST.RPM_LN_FN_IDX ON CUST.RESTRICTEDPAYMENTMETHOD(LAST_NAME, FIRST_NAME);

--
-- RPM_RC_IDX  (Index) 
--
CREATE INDEX CUST.RPM_RC_IDX ON CUST.RESTRICTEDPAYMENTMETHOD(REASON_CODE);

--
-- RPM_CRDT_IDX  (Index) 
--
CREATE INDEX CUST.RPM_CRDT_IDX ON CUST.RESTRICTEDPAYMENTMETHOD(CREATE_DATE);

--
-- RPM_ST_IDX  (Index) 
--
CREATE INDEX CUST.RPM_ST_IDX ON CUST.RESTRICTEDPAYMENTMETHOD(STATUS);

GRANT ALL PRIVILEGES on CUST.RESTRICTEDPAYMENTMETHOD to fdstore_prda;
GRANT ALL PRIVILEGES on CUST.RESTRICTEDPAYMENTMETHOD to fdstore_prdb;
