ALTER TABLE  TRANSP.SCRIB ADD  EQUIPMENT_TYPE        VARCHAR2(100 BYTE);
ALTER TABLE  TRANSP.PLAN ADD  EQUIPMENT_TYPE        VARCHAR2(100 BYTE);
ALTER TABLE  TRANSP.WAVE_INSTANCE ADD  EQUIPMENT_TYPE        VARCHAR2(100 BYTE);

ALTER TABLE TRANSP.WAVE_INSTANCE  DROP CONSTRAINT WAVEINSTANCE_UK;

CREATE UNIQUE INDEX TRANSP.WAVEINSTANCE_UK ON WAVE_INSTANCE
(ORIGIN_FACILITY, DELIVERY_DATE, AREA, DISPATCH_TIME, FIRST_DLV_TIME, 
LAST_DLV_TIME, CUTOFF_DATETIME,EQUIPMENT_TYPE);

ALTER TABLE TRANSP.WAVE_INSTANCE ADD 
CONSTRAINT WAVEINSTANCE_UK
 UNIQUE (ORIGIN_FACILITY, DELIVERY_DATE, AREA, DISPATCH_TIME, FIRST_DLV_TIME, LAST_DLV_TIME, CUTOFF_DATETIME,EQUIPMENT_TYPE);
