
CREATE TABLE TRANSP.PLANT_CAPACITY
(
  DISPATCH_TIME  DATE,
  DAY_OF_WEEK    VARCHAR2(5 BYTE),
  CAPACITY       NUMBER(10)
);

ALTER TABLE TRANSP.PLANT_CAPACITY ADD (
  PRIMARY KEY
 (DISPATCH_TIME, DAY_OF_WEEK));
 
 CREATE TABLE TRANSP.DISPATCH_MAPPING
(
  DISPATCH_TIME   DATE,
  PLANT_DISPATCH  DATE
);

ALTER TABLE TRANSP.DISPATCH_MAPPING ADD (
  PRIMARY KEY
 (DISPATCH_TIME));
 
 CREATE TABLE MIS.DISPATCH_VOLUME
(
  SNAPSHOT_TIME     DATE,
  DISPATCH_TIME     DATE,
  PLANNED_CAPACITY  NUMBER(10),
  ORDERS            NUMBER(10),
  TRUCKS            NUMBER(10),
  PLANT_CAPACITY    NUMBER(10),
  DISPATCH_DATE     DATE
);
