ALTER TABLE  TRANSP.SCRIB ADD  EQUIPMENT_TYPE        VARCHAR2(100 BYTE);
ALTER TABLE  TRANSP.PLAN ADD  EQUIPMENT_TYPE        VARCHAR2(100 BYTE);
ALTER TABLE  TRANSP.WAVE_INSTANCE ADD  EQUIPMENT_TYPE        VARCHAR2(100 BYTE);
