ALTER TABLE DLV.RESERVATION ADD  ( SCRUBBED_ADDRESS VARCHAR2(255), ZIPCODE VARCHAR2(10) );

ALTER TABLE DLV.RECURRING_RESERVATION ADD  ( SF_SCRUBBED_ADDRESS VARCHAR2(255), SF_ZIPCODE VARCHAR2(10) );