package com.freshdirect.dataloader.payment.reconciliation.paypal.parsers;

public interface FooterDataParserHelper {
	
	static final String CURRENCY_OF_BALANCE = "CURRENCY_OF_BALANCE";
	static final String TOTAL_GROSS_AMOUNT_CREDITS = "TOTAL_GROSS_AMOUNT_CREDITS";
	static final String TOTAL_GROSS_AMOUNT_DEBITS = "TOTAL_GROSS_AMOUNT_DEBITS";
	static final String TOTAL_TRANSACTION_FEE_CREDITS = "TOTAL_TRANSACTION_FEE_CREDITS";
	static final String TOTAL_TRANSACTION_FEE_DEBITS = "TOTAL_TRANSACTION_FEE_DEBITS";
	static final String BEGINNING_AVAILABLE_BALANCE_DEBIT_OR_CREDIT =
										"BEGINNING_AVAILABLE_BALANCE_DEBIT_OR_CREDIT";
	static final String BEGINNING_AVAILABLE_BALANCE_IN_THIS_CURRENCY =
										"BEGINNING_AVAILABLE_BALANCE_IN_THIS_CURRENCY";
	static final String ENDING_AVAILABLE_BALANCE_DEBIT_OR_CREDIT =
										"ENDING_AVAILABLE_BALANCE_DEBIT_OR_CREDIT";
	static final String ENDING_AVAILABLE_BALANCE_IN_THIS_CURRENCY =
										"ENDING_AVAILABLE_BALANCE_IN_THIS_CURRENCY";
	static final String BEGINNING_TOTAL_BALANCE_DEBIT_OR_CREDIT = 
										"BEGINNING_TOTAL_BALANCE_DEBIT_OR_CREDIT";
	static final String BEGINNING_TOTAL_BALANCE_IN_THIS_CURRENCY = 
										"BEGINNING_TOTAL_BALANCE_IN_THIS_CURRENCY";
	static final String ENDING_TOTAL_BALANCE_DEBIT_OR_CREDIT = 
										"ENDING_TOTAL_BALANCE_DEBIT_OR_CREDIT";
	static final String ENDING_TOTAL_BALANCE_IN_THIS_CURRENCY = 
										"ENDING_TOTAL_BALANCE_IN_THIS_CURRENCY";
	static final String BEGINNING_PAYABLE_BALANCE_DEBIT_OR_CREDIT = 
										"BEGINNING_PAYABLE_BALANCE_DEBIT_OR_CREDIT";
	static final String BEGINNING_PAYABLE_BALANCE = "BEGINNING_PAYABLE_BALANCE";
	static final String ENDING_PAYABLE_BALANCE_DEBIT_OR_CREDIT = "ENDING_PAYABLE_BALANCE_DEBIT_OR_CREDIT";
	static final String ENDING_PAYABLE_BALANCE = "ENDING_PAYABLE_BALANCE";
}
