INSERT INTO cms.relationshipdefinition (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,READONLY,LABEL,CARDINALITY_CODE) VALUES ('FEATURED_CATEGORIES','Brand.FEATURED_CATEGORIES','Brand','F','F','F','F','Featured Categories','Many');
INSERT INTO cms.relationshipdestination (ID, RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,REVERSE_ATTRIBUTE_NAME,REVERSE_ATTRIBUTE_LABEL) VALUES ('Brand.FEATURED_CATEGORIES.Category','Brand.FEATURED_CATEGORIES','Category',NULL,NULL);

-- Rollback
-- DELETE FROM cms.relationshipdefinition WHERE id='Brand.FEATURED_CATEGORIES';
-- DELETE FROM cms.relationshipdestination WHERE id='Brand.FEATURED_CATEGORIES.Category';
