package com.freshdirect.routing.constants;



public enum EnumRoutingNotification {
	RouteStartNotification,OriginDepartNotification,RouteChangeNotification,DestinationArriveNotification,RouteCompleteNotification,TextMessageNotification,StopArriveNotification,StopSequenceNotification,StopDepartNotification,StopCancelNotification,GPSNotification,DeliveryDetailNotification,RoutePathDeviationExceptionNotification,RPDExitPointExceptionNotification,UnplannedStopExceptionNotification,EarlyArrivalExceptionNotification,LateDepartureExceptionNotification,ServiceTimeExceptionNotification,GpsGapExceptionNotification,LateGpsExceptionNotification,NoGpsExceptionNotification,TimeOffPlannedExceptionNotification,OutOfSequenceExceptionNotification,OSDMonitoringExceptionNotification,DriverCancelExceptionNotification,UndeliverableStopExceptionNotification,OutOfContactExceptionNotification,UserExceptionNotification,SpeedViolationExceptionNotification,EventReceiptExceptionNotification,StartCompleteOutOfBoundsExceptionNotification,DutyPeriodViolationException,OrdersSentNotification,SchedulerSuccessfulOptimizeNotification,SchedulerUpdateOrderFailedNotification,SchedulerOrdersCanceledNotification;
	
}
