CREATE TABLE "CUST"."COREMETRICS_USERINFO"
  (
    "ID"            VARCHAR2(16 BYTE) NOT NULL,
    "FIRST_SO_FLAG" NUMBER(4) NOT NULL,
    CONSTRAINT "PK_COREMETRICS_USERINFO" PRIMARY KEY ("ID"),
    CONSTRAINT "FK_ON_FDUSER" FOREIGN KEY (id) REFERENCES "CUST"."FDUSER" ("ID")
  )
;

GRANT DELETE ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDA";
GRANT INSERT ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDA";
GRANT SELECT ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDA";
GRANT UPDATE ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDA";
GRANT DELETE ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDB";
GRANT INSERT ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDB";
GRANT SELECT ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDB";
GRANT UPDATE ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_PRDB";
GRANT DELETE ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_STPRD01";
GRANT INSERT ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_STPRD01";
GRANT SELECT ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_STPRD01";
GRANT UPDATE ON "CUST"."COREMETRICS_USERINFO" TO "FDSTORE_STPRD01"; 
