Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'SEC', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'SYS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'NEW', 'OPEN', 'TRNSP', 'NOTE');

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SEC', 'NOTE');
 Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'TRNSP', 'NOTE');

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'DEV', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'MOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'COS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'TRN', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'FIN', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'NCS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'CSR', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SCS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'SEC', 'CAS_EDT');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'OPEN', 'TRNSP', 'CAS_EDT');

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'DEV', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'MOP', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'COS', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'TRN', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'FIN', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'NCS', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'CSR', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'SCS', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'SEC', 'CLOSE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'OPEN', 'CLSD', 'TRNSP', 'CLOSE');

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'SEC', 'NOTE');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values   ('OAQ-001', 'CLSD', 'CLSD', 'TRNSP', 'NOTE');

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OAQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-011',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-012',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-013',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-014',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-015',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-016',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-017',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-018',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'OUT-019',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-011',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-012',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-013',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-014',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-015',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ORQ-016',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';


Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-011',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-012',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-013',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-014',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'NOQ-015',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'PRQ-011',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'LDQ-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-011',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-012',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-013',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'CAQ-014',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'GCQ-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'TCQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='TRN')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='TRN')));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-010',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-013',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-014',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-015',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-016',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-017',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-018',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-019',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-020',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-021',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-022',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-023',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-024',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-025',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-026',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-027',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-028',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-029',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-030',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-031',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-032',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-033',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-034',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ROLE in('ADM','SUP','OPS','SOP');


Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-011',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-012',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','OPS','SOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','OPS','SOP')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-011',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','OPS','SOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','OPS','SOP')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DSQ-012',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','OPS','SOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','OPS','SOP')));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-100',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-101',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-102',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-103',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-104',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-100',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-101',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-102',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-103',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'ASQ-104',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and ROLE in('ADM','SUP','SOP','SCS')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','SCS')));


Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'SEQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'SEQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'SEQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD') OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='NOTE'));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'SEQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='SEC')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='SEC')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'SEQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='SEC')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='SEC')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'SEQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' AND CASEACTION_TYPE='CLOSE' and (ROLE='ADM' or ROLE='SEC')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and (ROLE='ADM' or ROLE='SEC')));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-001',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-002',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-003',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-007',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-008',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-009',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001';

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN' and ROLE in('ADM','SUP','SOP','MOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' and ROLE in('ADM','SUP','SOP','MOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','MOP')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN' and ROLE in('ADM','SUP','SOP','MOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' and ROLE in('ADM','SUP','SOP','MOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','MOP')));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='NEW' and END_CASE_STATE='OPEN' and ROLE in('ADM','SUP','SOP','MOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='CLSD' and ROLE in('ADM','SUP','SOP','MOP')) OR (START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' AND CASEACTION_TYPE='CAS_EDT' and ROLE in('ADM','SUP','SOP','MOP')));

Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-004',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' and CASEACTION_TYPE='NOTE') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-005',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' and CASEACTION_TYPE='NOTE') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD'));
Insert into CUST.CASE_OPERATION   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE) select 'DPQ-006',START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE from CUST.CASE_OPERATION where CASE_SUBJECT='OAQ-001' and ((START_CASE_STATE='OPEN' and END_CASE_STATE='OPEN' and CASEACTION_TYPE='NOTE') OR (START_CASE_STATE='CLSD' and END_CASE_STATE='CLSD'));
