CREATE TABLE TRANSP.WAVE_INSTANCE
(
  WAVEINSTANCE_ID                       VARCHAR2(20 BYTE)    NOT NULL,
  DELIVERY_DATE            DATE    NOT NULL,
  AREA                     VARCHAR2(5 BYTE)    NOT NULL,
  DISPATCH_TIME            DATE    NOT NULL ,
  FIRST_DLV_TIME           DATE    NOT NULL ,
  LAST_DLV_TIME            DATE    NOT NULL ,
  CUTOFF_DATETIME       DATE     NOT NULL   ,
  RESOURCE_COUNT           INTEGER,
  STATUS                   VARCHAR2(10 BYTE),
  MODIFIED_DTTM            DATE,
  SOURCE                   VARCHAR2(20 BYTE),
  CHANGED_BY               VARCHAR2(20 BYTE),
  REFERENCE_ID             VARCHAR2(40 BYTE),
  NOTIFICATION_MSG         VARCHAR2(4000 BYTE),
  FORCE_SYNCHRONIZE        VARCHAR2(1 BYTE)
);

ALTER TABLE TRANSP.WAVE_INSTANCE ADD (CONSTRAINT PK_WAVE_INSTANCE  PRIMARY KEY (WAVEINSTANCE_ID));

ALTER TABLE TRANSP.WAVE_INSTANCE ADD (CONSTRAINT ACT_WAVE_INSTANCE_UK UNIQUE (DELIVERY_DATE, AREA, DISPATCH_TIME, FIRST_DLV_TIME, LAST_DLV_TIME, CUTOFF_DATETIME)); 

CREATE INDEX TRANSP.IDX_WAVE_INSTANCE_DD ON TRANSP.WAVE_INSTANCE(DELIVERY_DATE);

CREATE INDEX TRANSP.IDX_WAVE_INSTANCE_DA ON TRANSP.WAVE_INSTANCE(DELIVERY_DATE, AREA);

CREATE SEQUENCE TRANSP.WAVE_INSTANCE_SEQ
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE TRANSP.WAVE_INSTANCE_PUBLISH
(
  DELIVERY_DATE            DATE    NOT NULL,
  SOURCE                   VARCHAR2(20 BYTE),
  PUBLISHED_BY             VARCHAR2(20 BYTE),
  PUBLISHED_AT             DATE
);

ALTER TABLE TRANSP.WAVE_INSTANCE_PUBLISH ADD (CONSTRAINT PK_WAVE_INSTANCE_PUBLISH  PRIMARY KEY (DELIVERY_DATE));
