GRANT SELECT ON TRANSP.WAVE_INSTANCE_SEQ TO fdstore_stprd01;
GRANT SELECT ON TRANSP.WAVE_INSTANCE_SEQ TO fdtrn_stprd01;   
GRANT SELECT ON TRANSP.WAVE_INSTANCE_SEQ TO APPDEV;  
  
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.WAVE_INSTANCE TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.WAVE_INSTANCE TO fdtrn_stprd01;
GRANT SELECT ON TRANSP.WAVE_INSTANCE TO APPDEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.WAVE_INSTANCE_PUBLISH TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.WAVE_INSTANCE_PUBLISH TO fdtrn_stprd01;
GRANT SELECT ON TRANSP.WAVE_INSTANCE_PUBLISH TO APPDEV;
