CREATE TABLE "MIS"."IPLOCATOR_EVENT_LOG" (
  "ID"                    VARCHAR2(16 BYTE) NOT NULL,
  "INSERT_TIMESTAMP"             DATE NOT NULL,
  "IP"                    VARCHAR2(39 BYTE), --IPv6

  "IPLOC_ZIPCODE"         VARCHAR2(10 BYTE),
  "IPLOC_COUNTRY"         VARCHAR2(50 BYTE),
  "IPLOC_REGION"          VARCHAR2(50 BYTE),
  "IPLOC_CITY"            VARCHAR2(50 BYTE),

  "FDUSER_ID"             VARCHAR2(16 BYTE),
  "FD_ZIPCODE"            VARCHAR2(50 BYTE),
  "FD_STATE"              VARCHAR2(50 BYTE),
  "FD_CITY"               VARCHAR2(50 BYTE),
  "USER_AGENT"            VARCHAR2(300 BYTE),
  "UA_HASH_PERCENT"       NUMBER(3),
  "IPLOC_ROLLOUT_PERCENT" NUMBER(3),
 
  CONSTRAINT "PK_IPLOCATOR_EVENT_LOG" PRIMARY KEY ("ID")
);

CREATE INDEX "MIS"."IPLOCEVENT_IDX_FDUSER_ID" ON "MIS"."IPLOCATOR_EVENT_LOG" ("FDUSER_ID");

CREATE INDEX "MIS"."IPLOCEVENT_IDX_INSERT_TS" ON "MIS"."IPLOCATOR_EVENT_LOG" ("INSERT_TIMESTAMP");


CREATE SEQUENCE MIS.IPLOCATOR_EVENT_LOG_SEQ
  START WITH 1
  MAXVALUE 9999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
