-- rollout
CREATE TABLE CUST.FDCARTLINE_CLIENTCODE (
	CLIENT_CODE VARCHAR2(32) NOT NULL,
	QUANTITY NUMBER(10, 0) NOT NULL,
	ORDINAL NUMBER(10, 0) NOT NULL,
	FDUSER_ID VARCHAR2(16) NOT NULL,
	CARTLINE_ID VARCHAR2(16) NOT NULL,
	CONSTRAINT FDCARTLINE_CLIENTCODE_PK PRIMARY KEY (FDUSER_ID, CARTLINE_ID, ORDINAL) ENABLE
);

GRANT SELECT, DELETE, INSERT, UPDATE ON FDCARTLINE_CLIENTCODE TO FDSTORE_PRDA;
GRANT SELECT, DELETE, INSERT, UPDATE ON FDCARTLINE_CLIENTCODE TO FDSTORE_PRDB;

CREATE TABLE CUST.ORDERLINE_CLIENTCODE (
	CLIENT_CODE VARCHAR2(32) NOT NULL,
	QUANTITY NUMBER(10, 0) NOT NULL,
	ORDINAL NUMBER(10, 0) NOT NULL,
	CUSTOMER_ID VARCHAR2(16) NOT NULL,
	CARTLINE_ID VARCHAR2(16) NOT NULL,
	SALE_ID VARCHAR2(16) NOT NULL,
	UNIT_PRICE NUMBER(10, 2) NOT NULL,
	TAX_RATE NUMBER(6, 5) NOT NULL,
	PRODUCT_DESCRIPTION VARCHAR2(255) NOT NULL,
	DELIVERY_DATE DATE NOT NULL,
	CONSTRAINT ORDERLINE_CLIENTCODE_PK PRIMARY KEY (CUSTOMER_ID, SALE_ID, CARTLINE_ID, ORDINAL) ENABLE
);

GRANT SELECT, DELETE, INSERT, UPDATE ON ORDERLINE_CLIENTCODE TO FDSTORE_PRDA;
GRANT SELECT, DELETE, INSERT, UPDATE ON ORDERLINE_CLIENTCODE TO FDSTORE_PRDB;

CREATE INDEX IDX_OL_CC_DD ON ORDERLINE_CLIENTCODE (CUSTOMER_ID, DELIVERY_DATE);

