INSERT INTO cms.attributedefinition (NAME,ID,CONTENTTYPE_ID,ATTRIBUTETYPE_CODE,INHERITABLE,REQUIRED,LABEL,CARDINALITY_CODE,LOOKUP_CODE) VALUES ('CHEF_NAME','Brand.CHEF_NAME','Brand','S','F','F','Chef name','One',NULL);
INSERT INTO cms.attributedefinition (NAME,ID,CONTENTTYPE_ID,ATTRIBUTETYPE_CODE,INHERITABLE,REQUIRED,LABEL,CARDINALITY_CODE,LOOKUP_CODE) VALUES ('CHEF_BLURB','Brand.CHEF_BLURB','Brand','S','F','F','Chef blurb text','One',NULL);
INSERT INTO cms.relationshipdefinition (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,READONLY,LABEL,CARDINALITY_CODE) VALUES ('CHEF_IMAGE','Brand.CHEF_IMAGE','Brand','F','F','F','F','Chef image','One');
INSERT INTO cms.relationshipdestination (ID, RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,REVERSE_ATTRIBUTE_NAME,REVERSE_ATTRIBUTE_LABEL) VALUES ('Brand.CHEF_IMAGE.Image','Brand.CHEF_IMAGE','Image',NULL,NULL);

-- Rollback
-- DELETE FROM cms.attributedefinition WHERE name='CHEF_NAME';
-- DELETE FROM cms.attributedefinition WHERE name='CHEF_BLURB';
-- DELETE FROM cms.relationshipdefinition WHERE name='CHEF_IMAGE';
-- DELETE FROM cms.relationshipdestination WHERE id='Brand.CHEF_IMAGE.Image';
