Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '43', 'Phetchaburi', '858');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '42', 'Phetchabun', '859');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '41', 'Phayao', '860');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '40', 'Phatthalung', '861');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '22', 'Lop Buri', '862');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '23', 'Mae Hong Son', '863');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '24', 'Maha Sarakham', '864');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '25', 'Mukdahan', '865');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '26', 'Nakhon Nayok', '866');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '27', 'Nakhon Pathom', '867');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '28', 'Nakhon Phanom', '868');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '29', 'Nakhon Ratchasima', '869');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '3', 'Buriram', '870');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '2', 'Ang Thong', '871');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '1', 'Amnat Charoen', '872');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '7', 'Chanthaburi', '873');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '30', 'Nakhon Sawan', '874');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '6', 'Chaiyaphum', '875');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '5', 'Chai Nat', '876');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '32', 'Nan', '877');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '4', 'Chachoengsao', '878');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '31', 'Nakhon Si Thammarat', '879');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '9', 'Chiang Rai', '880');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '8', 'Chiang Mai', '881');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', 'E', 'East', '882');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '19', 'Lampang', '883');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', 'C', 'Central', '884');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '17', 'Krung Thep', '885');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '18', 'Mahanakhon', '886');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', 'N', 'North', '887');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '15', 'Khon Kaen', '888');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '16', 'Krabi', '889');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '13', 'Kamphaeng Phet', '890');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '14', 'Kanchanaburi', '891');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '11', 'Chumphon', '892');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '12', 'Kalasin', '893');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '21', 'Loei', '894');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '20', 'Lamphun', '895');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', 'W', 'West', '896');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', 'S', 'South', '897');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '49', 'Prachin Buri', '898');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '48', 'Phuket', '899');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '45', 'Phitsanulok', '900');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '44', 'Phichit', '901');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '47', 'Phrae', '902');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '46', 'Phra Nakhon Si Ayut.', '903');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '10', 'Chon Buri', '904');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'QC', 'Quebec', '905');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'NT', 'Northwest Territory', '906');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'SK', 'Saskatchewan', '907');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'NS', 'Nova Scotia', '908');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'NN', 'Northwest Territory', '909');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'NF', 'Newfoundland', '910');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'ON', 'Ontario', '911');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'AB', 'Alberta', '912');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'BC', 'British Columbia', '913');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'PE', 'Prince Edward Island', '914');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'NB', 'New Brunswick', '915');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'YT', 'Yukon Territory', '916');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CA', 'MB', 'Manitoba', '917');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '77', 'Yalova', '918');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '35', 'Izmir', '919');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '36', 'Kars', '920');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '33', 'Icel', '921');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '34', 'Istanbul', '922');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '39', 'Kirklareli', '923');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '37', 'Kastamonu', '924');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '38', 'Kayseri', '925');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '43', 'Kütahya', '926');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '42', 'Konya', '927');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '41', 'Kocaeli', '928');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '40', 'Kirshehir', '929');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '67', 'Zonguldak', '930');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '66', 'Yozgat', '931');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '69', 'Bayburt', '932');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '68', 'Aksaray', '933');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '22', 'Edirne', '934');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '23', 'Elazig', '935');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '24', 'Erzincan', '936');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '25', 'Erzurum', '937');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '26', 'Eskisehir', '938');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '27', 'Gaziantep', '939');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '28', 'Giresun', '940');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '29', 'Gümüshane', '941');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '3', 'Afyon', '942');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '2', 'Adiyaman', '943');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '1', 'Adana', '944');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '7', 'Antalya', '945');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '30', 'Hakkari', '946');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '6', 'Ankara', '947');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '5', 'Amasya', '948');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '32', 'Isparta', '949');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '4', 'Agri', '950');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '31', 'Hatay', '951');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '70', 'Karaman', '952');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '71', 'Kirikkale', '953');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '9', 'Aydin', '954');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '72', 'Batman', '955');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '8', 'Artvin', '956');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '73', 'Shirnak', '957');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '74', 'Bartin', '958');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '75', 'Ardahan', '959');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '76', 'Igdir', '960');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '59', 'Tekirdag', '961');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '58', 'Sivas', '962');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '57', 'Sinop', '963');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '56', 'Siirt', '964');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '19', 'Corum', '965');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '55', 'Samsun', '966');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '17', 'Canakkale', '967');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '18', 'Cankiri', '968');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '15', 'Burdur', '969');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '16', 'Bursa', '970');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '13', 'Bitlis', '971');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '14', 'Bolu', '972');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '11', 'Bilecik', '973');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '12', 'Bingöl', '974');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '21', 'Diyarbakir', '975');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '20', 'Denizli', '976');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '64', 'Ushak', '977');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '65', 'Van', '978');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '62', 'Tunceli', '979');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '63', 'Shanliurfa', '980');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '60', 'Tokat', '981');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '61', 'Trabzon', '982');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '49', 'Mush', '983');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '48', 'Mugla', '984');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '45', 'Manisa', '985');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '44', 'Malatya', '986');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '47', 'Mardin', '987');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '46', 'K.Marash', '988');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '10', 'Balikesir', '989');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '51', 'Nigde', '990');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '52', 'Ordu', '991');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '53', 'Rize', '992');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '54', 'Sakarya', '993');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TR', '50', 'Nevshehir', '994');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '19', 'Troms Fylke', '995');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '17', 'Nord-Trøndelag Fylke', '996');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '18', 'Nordland Fylke', '997');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '15', 'Møre og Romsdal F.', '998');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '16', 'Sør-Trøndelag Fylke', '999');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '14', 'Sogn og Fjordane F.', '1000');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '11', 'Rogaland Fylke', '1001');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '12', 'Hordaland Fylke', '1002');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '3', 'Oslo', '1003');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '20', 'Finnmark Fylke', '1004');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '2', 'Akershus Fylke', '1005');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '1', 'Østfold Fylke', '1006');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '10', 'Vest-Agder Fylke', '1007');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '7', 'Vestfold Fylke', '1008');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '6', 'Buskerud Fylke', '1009');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '5', 'Oppland Fylke', '1010');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '4', 'Hedmark Fylke', '1011');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '9', 'Aust-Agder Fylke', '1012');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NO', '8', 'Telemark Fylke', '1013');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '35', 'Ille-et-Vilaine', '1014');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '36', 'Indre', '1015');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '33', 'Gironde', '1016');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '34', 'Hérault', '1017');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '39', 'Jura', '1018');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '37', 'Indre-et-Loire', '1019');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '38', 'Isère', '1020');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '43', 'Loire (Haute)', '1021');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '42', 'Loire', '1022');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '41', 'Loir-et-Cher', '1023');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '40', 'Landes', '1024');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '2A', 'Corse-du-Sud', '1025');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '22', 'Côtes-d''Armor', '1026');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '23', 'Creuse', '1027');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '24', 'Dordogne', '1028');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '25', 'Doubs', '1029');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '26', 'Drôme', '1030');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '27', 'Eure', '1031');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '28', 'Eure-et-Loir', '1032');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '29', 'Finistère', '1033');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '3', 'Allier', '1034');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '2', 'Aisne', '1035');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '1', 'Ain', '1036');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '30', 'Gard', '1037');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '7', 'Ardèche', '1038');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '6', 'Alpes-Maritimes', '1039');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '32', 'Gers', '1040');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '5', 'Alpes (Hautes)', '1041');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '31', 'Garonne (Haute)', '1042');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '4', 'Alpes (Hte-Provence)', '1043');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '2B', 'Corse-du-Nord', '1044');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '9', 'Ariège', '1045');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '8', 'Ardennes', '1046');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '19', 'Corrèze', '1047');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '17', 'Charente-Maritime', '1048');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '18', 'Cher', '1049');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '15', 'Cantal', '1050');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '16', 'Charente', '1051');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '13', 'Bouches-du-Rhône', '1052');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '14', 'Calvados', '1053');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '11', 'Aude', '1054');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '12', 'Aveyron', '1055');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '21', 'Côte-d''Or', '1056');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '99', 'Hors-France', '1057');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '97', 'D.O.M.-T.O.M.', '1058');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '95', 'Val-d''Oise', '1059');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '94', 'Val-de-Marne', '1060');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '93', 'Seine-Saint-Denis', '1061');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '92', 'Hauts-de-Seine', '1062');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '91', 'Essonne', '1063');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '90', 'Territ.-de-Belfort', '1064');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '10', 'Aube', '1065');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '88', 'Vosges', '1066');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '89', 'Yonne', '1067');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '79', 'Sèvres (Deux)', '1068');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '78', 'Yvelines', '1069');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '77', 'Seine-et-Marne', '1070');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '82', 'Tarn-et-Garonne', '1071');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '83', 'Var', '1072');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '80', 'Somme', '1073');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '81', 'Tarn', '1074');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '86', 'Vienne', '1075');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '87', 'Vienne (Haute)', '1076');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '84', 'Vaucluse', '1077');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '85', 'Vendée', '1078');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '67', 'Bas-Rhin', '1079');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '976', 'Wallis-et-Futuna', '1080');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '66', 'Pyrénées-Orientales', '1081');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '69', 'Rhône', '1082');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '68', 'Haut-Rhin', '1083');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '971', 'Guadeloupe', '1084');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '973', 'Guyane', '1085');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '972', 'Martinique', '1086');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '975', 'Saint-Pierre-et-Miq.', '1087');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '974', 'Réunion', '1088');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '70', 'Saône (Haute)', '1089');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '71', 'Saône-et-Loire', '1090');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '72', 'Sarthe', '1091');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '73', 'Savoie', '1092');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '74', 'Savoie (Haute)', '1093');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '75', 'Paris', '1094');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '76', 'Seine-Maritime', '1095');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '59', 'Nord', '1096');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '58', 'Nièvre', '1097');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '57', 'Moselle', '1098');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '56', 'Morbihan', '1099');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '55', 'Meuse', '1100');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '64', 'Pyrénées-Atlantiques', '1101');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '65', 'Pyrénées (Hautes)', '1102');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '62', 'Pas-de-Calais', '1103');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '63', 'Puy-de-Dôme', '1104');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '60', 'Oise', '1105');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '61', 'Orne', '1106');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '49', 'Maine-et-Loire', '1107');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '48', 'Lozère', '1108');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '45', 'Loiret', '1109');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '44', 'Loire-Atlantique', '1110');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '47', 'Lot-et-Garonne', '1111');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '46', 'Lot', '1112');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '51', 'Marne', '1113');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '52', 'Marne (Haute)', '1114');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '53', 'Mayenne', '1115');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '54', 'Meurthe-et-Moselle', '1116');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FR', '50', 'Manche', '1117');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '3', 'Khaskovo', '1118');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '2', 'Grad Sofiya', '1119');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '1', 'Burgas', '1120');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '7', 'Ruse', '1121');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '6', 'Plovdiv', '1122');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '5', 'Montana', '1123');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '4', 'Lovech', '1124');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '9', 'Varna', '1125');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BG', '8', 'Sofiya', '1126');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '3', 'Hainaut', '1127');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '2', 'Brabant', '1128');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '1', 'Antwerp', '1129');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '7', 'Namur', '1130');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '6', 'Luxembourg', '1131');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '5', 'Limburg', '1132');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '4', 'Liege', '1133');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '9', 'West-Vlaanderen', '1134');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BE', '8', 'Oost-Vlaanderen', '1135');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FI', '3', 'Itä-Suomi', '1136');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FI', '2', 'Etelä-Suomi', '1137');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FI', '1', 'Ahvenanmaa', '1138');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FI', '6', 'Oulu', '1139');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FI', '5', 'Länsi-Suomi', '1140');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('FI', '4', 'Lappi', '1141');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '3', 'Praha', '1142');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '2', 'Jihomoravsky', '1143');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '1', 'Jihocesky', '1144');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '7', 'Vychodocesky', '1145');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '6', 'Stredocesky', '1146');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '5', 'Severomoravsky', '1147');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '4', 'Severocesky', '1148');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CZ', '8', 'Zapadocesky', '1149');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '15', 'Taejon-jikhalsi', '1150');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '13', 'Soul-t´ukpyolsi', '1151');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '14', 'Taegu-jikhalsi', '1152');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '11', 'Kyongsang-namdo', '1153');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '12', 'Pusan-jikhalsi', '1154');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '3', 'Cholla-namdo', '1155');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '2', 'Cholla-bukto', '1156');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '1', 'Cheju-do', '1157');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '10', 'Kyongsang-bukto', '1158');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '7', 'Kangwon-do', '1159');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '6', 'Inch´on-jikhalsi', '1160');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '5', 'Ch´ungch´ong-namdo', '1161');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '4', 'Ch´ungch´ong-bukto', '1162');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '9', 'Kyonggi-do', '1163');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('KR', '8', 'Kwangju-jikhalsi', '1164');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '19', 'Västra Götalands Län', '1165');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '17', 'Västernorrlands Län', '1166');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '18', 'Västmanlands Län', '1167');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '15', 'Värmlands Län', '1168');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '16', 'Västerbottens Län', '1169');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '13', 'Södermanlands Län', '1170');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '14', 'Uppsala Län', '1171');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '11', 'Skåne Län', '1172');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '12', 'Stockholms Län', '1173');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '21', 'Östergötlands Län', '1174');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '3', 'Gotlands Län', '1175');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '20', 'Örebro Län', '1176');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '2', 'Dalarnas Län', '1177');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '1', 'Blekinge Län', '1178');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '10', 'Norrbottens Län', '1179');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '7', 'Jönköpings Län', '1180');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '6', 'Jämtlands Län', '1181');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '5', 'Hallands Län', '1182');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '4', 'Gävleborgs Län', '1183');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '9', 'Kronobergs Län', '1184');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SE', '8', 'Kalmar Län', '1185');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SG', 'SG', 'Singapore', '1186');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '35', 'Ormoz', '1187');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '36', 'Pesnica', '1188');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '33', 'Nova Gorica', '1189');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '34', 'Novo Mesto', '1190');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '39', 'Ptuj', '1191');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '37', 'Piran', '1192');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '38', 'Postojna', '1193');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '43', 'Ribnica', '1194');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '42', 'Ravne Na Koroskem', '1195');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '41', 'Radovljica', '1196');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '40', 'Radlje Ob Dravi', '1197');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '22', 'Ljubljana-Bezigrad', '1198');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '23', 'Ljubljana-Center', '1199');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '24', 'Ljubljana-Moste-Polj', '1200');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '25', 'Ljubljana-Siska', '1201');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '26', 'Ljubljana-Vic-Rudnik', '1202');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '27', 'Ljutomer', '1203');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '28', 'Logatec', '1204');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '29', 'Maribor', '1205');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '3', 'Celje', '1206');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '2', 'Brezice', '1207');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '1', 'Ajdovscina', '1208');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '7', 'Gornja Radgona', '1209');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '30', 'Metlika', '1210');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '6', 'Dravograd', '1211');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '5', 'Crnomelj', '1212');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '32', 'Murska Sobota', '1213');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '4', 'Cerknica', '1214');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '31', 'Mozirje', '1215');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '9', 'Hrastnik Lasko', '1216');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '8', 'Grosuplje', '1217');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '59', 'Zagorje Ob Savi', '1218');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '58', 'Vrhnika', '1219');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '57', 'Velenje', '1220');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '56', 'Trzic', '1221');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '19', 'Lenart', '1222');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '55', 'Trebnje', '1223');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '17', 'Kranj', '1224');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '18', 'Krsko', '1225');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '15', 'Kocevje', '1226');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '16', 'Koper', '1227');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '13', 'Jesenice', '1228');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '14', 'Kamnik', '1229');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '11', 'Ilirska Bistrica', '1230');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '12', 'Izola', '1231');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '21', 'Litija', '1232');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '20', 'Lendava', '1233');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '60', 'Zalec', '1234');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '49', 'Slovenj Gradec', '1235');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '48', 'Skofja Loka', '1236');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '45', 'Sentjur Pri Celju', '1237');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '44', 'Ruse', '1238');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '47', 'Sezana', '1239');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '46', 'Sevnica', '1240');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '10', 'Idrija', '1241');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '51', 'Slovenske Konjice', '1242');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '52', 'Smarje Pri Jelsah', '1243');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '53', 'Tolmin', '1244');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '54', 'Trbovlje', '1245');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SI', '50', 'Slovenska Bistrica', '1246');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SK', '3', 'Stredoslovensky', '1247');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SK', '2', 'Zapadoslovensky', '1248');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SK', '1', 'Bratislava', '1249');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('SK', '4', 'Vychodoslovensky', '1250');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '35', 'Siedlce', '1251');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '36', 'Sieradz', '1252');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '33', 'Radom', '1253');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '34', 'Rzeszow', '1254');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '39', 'Suwalki', '1255');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '37', 'Skierniewice', '1256');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '38', 'Slupsk', '1257');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '43', 'Torun', '1258');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '42', 'Tarnow', '1259');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '41', 'Tarnobrzeg', '1260');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '40', 'Szczecin', '1261');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '22', 'Lomza', '1262');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '23', 'Lublin', '1263');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '24', 'Nowy Sacz', '1264');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '25', 'Olsztyn', '1265');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '26', 'Opole', '1266');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '27', 'Ostroleka', '1267');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '28', 'Pila', '1268');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '29', 'Piotrkow', '1269');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '3', 'Bielsko Biala', '1270');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '2', 'Bialystok', '1271');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '1', 'Biala Podlaska', '1272');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '7', 'Czestochowa', '1273');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '30', 'Plock', '1274');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '6', 'Ciechanow', '1275');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '5', 'Chelm', '1276');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '32', 'Przemysl', '1277');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '4', 'Bydgoszcz', '1278');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '31', 'Poznan', '1279');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '9', 'Gdansk', '1280');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '8', 'Elblag', '1281');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '19', 'Legnica', '1282');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '17', 'Krakow', '1283');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '18', 'Krosno', '1284');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '15', 'Konin', '1285');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '16', 'Koszalin', '1286');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '13', 'Katowice', '1287');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '14', 'Kielce', '1288');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '11', 'Jelenia Gora', '1289');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '12', 'Kalisz', '1290');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '21', 'Lodz', '1291');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '20', 'Leszno', '1292');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '49', 'Zielona Gora', '1293');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '48', 'Zamosc', '1294');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '45', 'Warszawa', '1295');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '44', 'Walbrzych', '1296');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '47', 'Wroclaw', '1297');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '46', 'Wloclawek', '1298');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PL', '10', 'Gorzow', '1299');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'TG', 'Thurgau', '1300');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'LU', 'Lucerne', '1301');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'GE', 'Geneva', '1302');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'VS', 'Valais', '1303');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'BS', 'Basel Stadt', '1304');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'NW', 'Nidwalden', '1305');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'TI', 'Ticino', '1306');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'ZG', 'Zug', '1307');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'ZH', 'Zurich', '1308');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'JU', 'Jura', '1309');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'FR', 'Fribourg', '1310');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'VD', 'Vaud', '1311');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'SZ', 'Schwyz', '1312');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'BE', 'Bern', '1313');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'BL', 'Basel Land', '1314');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'UR', 'Uri', '1315');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'AR', 'Ausser-Rhoden', '1316');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'SH', 'Schaffhausen', '1317');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'OW', 'Obwalden', '1318');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'SG', 'St. Gallen', '1319');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'SO', 'Solothurn', '1320');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'GR', 'Graubuenden', '1321');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'AG', 'Aargau', '1322');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'GL', 'Glarus', '1323');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'AI', 'Inner-Rhoden', '1324');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CH', 'NE', 'Neuchatel', '1325');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '79', 'The Jewish Auton.are', '1326');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '78', 'c.St-Peterburg', '1327');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '77', 'c.Moscow', '1328');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '35', 'The Vologda Area', '1329');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '36', 'The Voronezh Area', '1330');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '33', 'The Vladimir Area', '1331');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '34', 'The Volgograd Area', '1332');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '39', 'The Kaliningrad Area', '1333');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '37', 'The Ivanovo Area', '1334');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '38', 'The Irkutsk Area', '1335');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '43', 'The Kirov Area', '1336');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '42', 'The Kemerovo Area', '1337');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '41', 'The Kamchatka Area', '1338');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '40', 'The Kaluga Area', '1339');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '82', 'Korjacs Auton.distri', '1340');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '83', 'Nenekchky Auton.dist', '1341');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '80', 'Aginsk Buryat Aut.di', '1342');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '81', 'Komy Permjats.Aut.di', '1343');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '86', 'Chanti-Mansyjsky Aut', '1344');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '87', 'Chukotka Auton. dist', '1345');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '84', 'The Taymir Auton.dis', '1346');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '85', 'Ust-Ordinsky Buryat', '1347');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '67', 'The Smolensk Area', '1348');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '66', 'The Sverdlovsk Area', '1349');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '69', 'The Tver Area', '1350');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '68', 'The Tambov Area', '1351');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '22', 'Altay Territory', '1352');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '23', 'Krasnodar Territory', '1353');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '24', 'Krasnoyarsk Territor', '1354');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '25', 'Primorye Territory', '1355');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '26', 'Stavropol Territory', '1356');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '27', 'Khabarovsk Territory', '1357');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '28', 'The Amur Area', '1358');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '29', 'The Arkhangelsk Area', '1359');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '3', 'Republ.of Bashkortos', '1360');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '2', 'Highlands-Altay Rep.', '1361');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '1', 'Adigeja Republic', '1362');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '7', 'Kabardino-Balkar.Rep', '1363');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '30', 'The Astrakhan Area', '1364');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '6', 'Ingushetija Republic', '1365');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '5', 'Dagestan Republic', '1366');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '32', 'The Bryansk Area', '1367');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '4', 'Buryat Republic', '1368');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '31', 'The Belgorod Area', '1369');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '70', 'The Tomsk Area', '1370');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '71', 'The Tula Area', '1371');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '9', 'Karach.-Cherkessk Re', '1372');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '72', 'The Tyumen Area', '1373');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '8', 'Kalmyk Republic', '1374');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '73', 'The Ulyanovsk Area', '1375');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '74', 'The Chelyabinsk Area', '1376');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '75', 'The Chita Area', '1377');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '76', 'The Yaroslavl Area', '1378');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '59', 'The Perm Area', '1379');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '58', 'The Penza Area', '1380');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '57', 'The Oryol Area', '1381');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '56', 'The Orenburg Area', '1382');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '19', 'Chakassky Republic', '1383');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '55', 'The Omsk Area', '1384');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '17', 'Tuva Republic', '1385');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '18', 'The Udmurt Republic', '1386');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '15', 'North-Osetiya Republ', '1387');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '16', 'Tatarstan Republic', '1388');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '13', 'Mordovian Republic', '1389');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '14', 'Yakutiya-Saha Rrepub', '1390');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '11', 'Komi Republic', '1391');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '12', 'Marijskaya Republic', '1392');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '21', 'Chuvash Republic', '1393');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '20', 'Chechenskaya Republ.', '1394');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '64', 'The Saratov Area', '1395');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '65', 'The Sakhalin Area', '1396');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '62', 'The Ryazan Area', '1397');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HK', 'HK', 'Hong Kong Island', '1');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HK', 'KLN', 'Kowloon', '2');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HK', 'NT', 'New Territories', '3');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('LV', '0', 'Riga', '4');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'FS', 'Freestate', '5');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'WC', 'Western Cape', '6');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'NW', 'North-West', '7');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'GP', 'Gauteng', '8');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'EC', 'Eastern Cape', '9');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'MP', 'Mpumalanga', '10');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'NP', 'Northern Province', '11');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'NC', 'Northern Cape', '12');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ZA', 'KZN', 'Kwazulu/Natal', '13');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '19', 'Vukovar-Srijem', '14');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '17', 'Varazdin', '15');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '18', 'Virovitica-Podravina', '16');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '15', 'Brod-Posavina', '17');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '16', 'Split-Dalmatia', '18');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '13', 'Sisak-Moslavina', '19');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '14', 'Slavonski', '20');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '11', 'Primorje-Gorski Kot.', '21');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '12', 'Sibenik', '22');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '21', 'Zagreb', '23');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '3', 'Dubrovnik-Neretva', '24');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '20', 'Zadar-Knin', '25');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '2', 'Stadt Zagreb', '26');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '1', 'Bjelovar-Bilogora', '27');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '10', 'Pozega-Slavonija', '28');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '7', 'Lika-Senj', '29');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '6', 'Koprivnica-Krizevci', '30');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '5', 'Karlovac', '31');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '4', 'Istra', '32');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '9', 'Osijek-Baranja', '33');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HR', '8', 'Medimurje', '34');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '19', 'Galati', '35');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '35', 'Suceava', '36');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '17', 'Dimbovita', '37');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '36', 'Teleorman', '38');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '18', 'Dolj', '39');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '33', 'Satu Mare', '40');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '15', 'Constanta', '41');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '34', 'Sibiu', '42');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '16', 'Covasna', '43');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '39', 'Vaslui', '44');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '13', 'Caras-Severin', '45');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '14', 'Cluj', '46');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '37', 'Timis', '47');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '11', 'Buzau', '48');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '38', 'Tulcea', '49');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '12', 'Calarasi', '50');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '21', 'Giurgiu', '51');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '20', 'Gorj', '52');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '41', 'Vrancea', '53');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '40', 'Vilcea', '54');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '22', 'Harghita', '55');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '23', 'Hunedoara', '56');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '24', 'Ialomita', '57');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '25', 'Iasi', '58');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '26', 'Maramures', '59');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '27', 'Mehedinti', '60');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '28', 'Mures', '61');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '29', 'Neamt', '62');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '3', 'Arges', '63');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '2', 'Arad', '64');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '10', 'Bucuresti', '65');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '1', 'Alba', '66');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '30', 'Olt', '67');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '7', 'Botosani', '68');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '6', 'Bistrita-Nasaud', '69');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '32', 'Salaj', '70');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '5', 'Bihor', '71');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '31', 'Prahova', '72');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '4', 'Bacau', '73');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '9', 'Brasov', '74');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RO', '8', 'Braila', '75');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '19', 'Kecskemet', '76');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '35', 'Tolna', '77');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '17', 'Jasz-Nagykun-Szolnok', '78');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '36', 'Vas', '79');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '18', 'Kaposvar', '80');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '33', 'Szombathely', '81');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '15', 'Heves', '82');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '34', 'Tatabanya', '83');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '16', 'Hodmezovasarhely', '84');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '39', 'Zalaegerszeg', '85');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '13', 'Gyor-Moson-Sopron', '86');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '14', 'Hajdu-Bihar', '87');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '37', 'Veszprem', '88');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '11', 'Fejer', '89');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '38', 'Zala', '90');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '12', 'Gyor', '91');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '21', 'Miskolc', '92');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '20', 'Komarom-Esztergom', '93');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '22', 'Nagykanizsa', '94');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '23', 'Nograd', '95');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '24', 'Nyiregyhaza', '96');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '25', 'Pecs', '97');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '26', 'Pest', '98');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '27', 'Somogy', '99');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '28', 'Sopron', '100');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '29', 'Szabolcs-Szat.-Bereg', '101');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '3', 'Bekes', '102');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '2', 'Baranya', '103');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '10', 'Eger', '104');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '1', 'Bacs-Kiskun', '105');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '30', 'Szeged', '106');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '7', 'Csongrad', '107');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '6', 'Budapest', '108');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '32', 'Szolnok', '109');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '5', 'Borsod-Abauj-Zemplen', '110');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '31', 'Szekesfehervar', '111');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '4', 'Bekescsaba', '112');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '9', 'Dunaujvaros', '113');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('HU', '8', 'Debrecen', '114');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'ARA', 'Aragua', '115');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'MER', 'Merida', '116');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'MON', 'Monagas', '117');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'ANZ', 'Anzoategui', '118');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'DA', 'Delta Amacuro', '119');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'POR', 'Portuguesa', '120');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'TRU', 'Trujillo', '121');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'COJ', 'Cojedes', '122');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'TAC', 'Tachira', '123');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'SUC', 'Sucre', '124');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'MIR', 'Miranda', '125');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'FAL', 'Falcon', '126');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'LAR', 'Lara', '127');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'VAR', 'Vargas', '128');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'BOL', 'Bolivar', '129');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'APU', 'Apure', '130');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'YAR', 'Yaracuy', '131');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'AMA', 'Amazon', '132');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'GUA', 'Guarico', '133');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'CAR', 'Carabobo', '134');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'ZUL', 'Zulia', '135');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'DF', 'Distrito Federal', '136');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'BAR', 'Barinas', '137');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('VE', 'NE', 'Nueva Esparta', '138');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '19', 'Sulawesi Tenggara So', '139');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '17', 'Kalimantan Timur Eas', '140');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '18', 'Sulawesi Selatan Sou', '141');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '15', 'Kalimantan Barat Wes', '142');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '16', 'Kalimantan Tengah Ce', '143');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '13', 'Lampung Lampung', '144');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '14', 'Kalimantan Selatan S', '145');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '11', 'Sumatera Selatan Sou', '146');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '12', 'Bengkulu Bengkulu', '147');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '21', 'Sulawesi Utara North', '148');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '20', 'Sulawesi Tengah Cent', '149');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '22', 'Bali Bali', '150');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '23', 'Nusa Tenggara Barat', '151');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '24', 'Nusa Tenggara Timur', '152');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '25', 'Maluku Maluku', '153');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '26', 'Irian Jaya Irian Jay', '154');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '27', 'Timor Timur East Tim', '155');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '3', 'Jawa Tengah Central', '156');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '2', 'Jawa Barat West Java', '157');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '10', 'Jambi Jambi', '158');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '1', 'DKI Jakarta Jakarta', '159');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '7', 'Sumatera Utara North', '160');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '6', 'DI Aceh Aceh', '161');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '5', 'DI Yogyakarta Yogyak', '162');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '4', 'Jawa Timur East Java', '163');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '9', 'Riau Riau', '164');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ID', '8', 'Sumatera Barat West', '165');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '15', 'Saxony-Anhalt', '166');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '16', 'Thuringia', '167');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '13', 'Mecklenburg-Vorpomm.', '168');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '14', 'Saxony', '169');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '11', 'Berlin', '170');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '12', 'Brandenburg', '171');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '3', 'Lower Saxony', '172');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '2', 'Hamburg', '173');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '1', 'Schleswig-Holstein', '174');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '10', 'Saarland', '175');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '7', 'Rhineland Palatinate', '176');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '6', 'Hesse', '177');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '5', 'Nrth Rhine Westfalia', '178');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '4', 'Bremen', '179');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '9', 'Bavaria', '180');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DE', '8', 'Baden-Wurttemberg', '181');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '15', 'Viborg amt', '182');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '16', 'Grønlands amt', '183');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '13', 'Vejle amt', '184');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '14', 'Vestsjælland amt', '185');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '11', 'Sønderjylland amt', '186');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '12', 'Storstrøm amt', '187');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '3', 'Bornholm amt', '188');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '2', 'Århus amt', '189');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '1', 'Copenhagen', '190');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '10', 'Roskilde amt', '191');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '7', 'Nordjylland amt', '192');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '6', 'København amt', '193');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '5', 'Fyn amt', '194');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '4', 'Frederiksborg amt', '195');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '9', 'Ringkøbing amt', '196');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('DK', '8', 'Ribe amt', '197');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'LT', 'Louth', '198');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'RC', 'Rosscommon', '199');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'LM', 'Leitrim', '200');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'LS', 'Laois', '201');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'TP', 'Tipperary', '202');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'MH', 'Monaghan', '203');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'OF', 'Offaly', '204');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'WX', 'Wexford', '205');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'DG', 'Donegal', '206');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'KD', 'Kildare', '207');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'CW', 'Carlow', '208');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'KK', 'Kilkenny', '209');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'CV', 'Cavan', '210');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'MY', 'Mayo', '211');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'SG', 'Sligo', '212');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'DB', 'Dublin', '213');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'KY', 'Kerry', '214');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'WK', 'Wicklow', '215');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'GW', 'Galway', '216');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'MT', 'Meath', '217');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'WM', 'Westmeath', '218');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'WF', 'Waterford', '219');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'LI', 'Limerick', '220');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'CK', 'Cork', '221');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'LF', 'Longford', '222');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IE', 'CL', 'Clare', '223');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'T', 'Tyrol', '224');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'W', 'Vienna', '225');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'V', 'Vorarlberg', '226');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'ST', 'Styria', '227');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'OÖ', 'Upper Austria', '228');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'S', 'Salzburg', '229');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'B', 'Burgenland', '230');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'NÖ', 'Lower Austria', '231');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AT', 'K', 'Carinthia', '232');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'VT', 'Vermont', '233');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'RI', 'Rhode Island', '234');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'HI', 'Hawaii', '235');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'VI', 'Virgin Islands', '236');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'ME', 'Maine', '237');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'VA', 'Virginia', '238');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MI', 'Michigan', '239');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'ID', 'Idaho', '240');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'DE', 'Delaware', '241');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'IA', 'Iowa', '242');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MD', 'Maryland', '243');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MA', 'Massachusetts', '244');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'AS', 'American Samoa', '245');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'AR', 'Arkansas', '246');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'IL', 'Illinois', '247');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'UT', 'Utah', '248');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'IN', 'Indiana', '249');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MN', 'Minnesota', '250');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'AZ', 'Arizona', '251');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MP', 'Northern Mariana Isl', '252');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MO', 'Missouri', '253');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MT', 'Montana', '254');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'MS', 'Mississippi', '255');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'NH', 'New Hampshire', '256');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'NJ', 'New Jersey', '257');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'PR', 'Puerto Rico', '258');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'NM', 'New Mexico', '259');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'AK', 'Alaska', '260');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'AL', 'Alabama', '261');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'TX', 'Texas', '262');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'NC', 'North Carolina', '263');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'ND', 'North Dakota', '264');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'NE', 'Nebraska', '265');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'NY', 'New York', '266');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'GA', 'Georgia', '267');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'NV', 'Nevada', '268');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'TN', 'Tennessee', '269');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'CA', 'California', '270');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'OK', 'Oklahoma', '271');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'OH', 'Ohio', '272');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'WY', 'Wyoming', '273');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'FL', 'Florida', '274');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'SD', 'South Dakota', '275');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'SC', 'South Carolina', '276');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'CT', 'Connecticut', '277');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'WV', 'West Virginia', '278');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'DC', 'District of Columbia', '279');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'WI', 'Wisconsin', '280');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'KY', 'Kentucky', '281');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'KS', 'Kansas', '282');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'OR', 'Oregon', '283');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'LA', 'Louisiana', '284');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'GU', 'Guam', '285');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'WA', 'Washington', '286');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'CO', 'Colorado', '287');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('US', 'PA', 'Pennsylvania', '288');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '19', 'Misiones', '289');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '22', 'Rio Negro', '290');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '17', 'Chubut', '291');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '23', 'Santa Cruz', '292');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '18', 'Formosa', '293');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '24', 'Tierra de Fuego', '294');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '16', 'Chaco', '295');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '13', 'Santiago del Estero', '296');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '14', 'Tucumán', '297');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '11', 'San Luis', '298');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '12', 'Santa Fé', '299');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '21', 'La Pampa', '300');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '3', 'Córdoba', '301');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '20', 'Neuquen', '302');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '2', 'Catamarca', '303');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '1', 'Buenos Aires', '304');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '10', 'San Juan', '305');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '0', 'Capital Federal', '306');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '7', 'Mendoza', '307');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '6', 'Jujuy', '308');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '5', 'Entre Rios', '309');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '4', 'Corrientes', '310');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '9', 'Salta', '311');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AR', '8', 'La Rioja', '312');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'JAL', 'Jalisco', '313');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'ZAC', 'Zacatecas', '314');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'YUC', 'Yucatán', '315');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'QRO', 'Querétaro', '316');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'TAB', 'Tabasco', '317');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'SLP', 'San Luis Potosí', '318');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'CHI', 'Chihuahua', '319');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'BC', 'Baja California', '320');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'AGS', 'Aguascalientes', '321');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'QR', 'Quintana Roo', '322');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'MOR', 'Morelos', '323');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'DF', 'Distrito Federal', '324');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'COA', 'Coahuila', '325');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'MEX', 'Estado de México', '326');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'CHS', 'Chiapas', '327');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'NAY', 'Nayarit', '328');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'BCS', 'Baja California S', '329');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'MCH', 'Michoacán', '330');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'SIN', 'Sinaloa', '331');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'GTO', 'Guanajuato', '332');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'TMS', 'Tamaulipas', '333');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'COL', 'Colima', '334');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'DGO', 'Durango', '335');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'CMP', 'Campeche', '336');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'GRO', 'Guerrero', '337');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'PUE', 'Puebla', '338');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'TLX', 'Tlaxcala', '339');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'SON', 'Sonora', '340');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'NL', 'Nuevo Léon', '341');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'VER', 'Veracruz', '342');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'OAX', 'Oaxaca', '343');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MX', 'HGO', 'Hidalgo', '344');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IL', '3', 'Jerusalem', '345');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IL', '2', 'Haifa', '346');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IL', '1', 'Central', '347');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IL', '6', 'Tel Aviv', '348');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IL', '5', 'Southern', '349');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IL', '4', 'Northern', '350');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '19', 'Punjab', '351');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '17', 'Nagaland', '352');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '18', 'Orissa', '353');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '15', 'Megalaya', '354');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '16', 'Mizoram', '355');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '13', 'Maharashtra', '356');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '14', 'Manipur', '357');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '11', 'Kerala', '358');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '12', 'Madhya Pradesh', '359');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '21', 'Sikkim', '360');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '20', 'Rajasthan', '361');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '22', 'Tamil Nadu', '362');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '23', 'Tripura', '363');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '24', 'Uttar Pradesh', '364');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '25', 'West Bengal', '365');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '26', 'Andaman und Nico.In.', '366');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '27', 'Chandigarh', '367');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '28', 'Dadra und Nagar Hav.', '368');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '29', 'Daman und Diu', '369');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '3', 'Assam', '370');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '2', 'Arunachal Pradesh', '371');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '10', 'Karnataka', '372');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '1', 'Andra Pradesh', '373');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '30', 'Delhi', '374');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '7', 'Haryana', '375');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '6', 'Gujarat', '376');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '32', 'Pondicherry', '377');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '5', 'Goa', '378');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '31', 'Lakshadweep', '379');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '4', 'Bihar', '380');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '9', 'Jammu und Kashmir', '381');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '8', 'Himachal Pradesh', '382');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IN', '50', 'META', '383');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'TRE', 'Trengganu', '384');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'LAB', 'Labuan', '385');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'SAB', 'Sabah', '386');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'PEL', 'Perlis', '387');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'KEL', 'Kelantan', '388');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'PER', 'Perak', '389');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'PAH', 'Pahang', '390');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'SEL', 'Selangor', '391');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'MEL', 'Melaka', '392');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'SER', 'Negeri Sembilan', '393');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'SAR', 'Sarawak', '394');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'JOH', 'Johor', '395');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'PIN', 'Pulau Pinang', '396');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'KUL', 'Kuala Lumpur', '397');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('MY', 'KED', 'Kedah', '398');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'QLD', 'Queensland', '399');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'ACT', 'Aust Capital Terr', '400');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'WA', 'Western Australia', '401');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'NT', 'Northern Territory', '402');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'TAS', 'Tasmania', '403');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'NSW', 'New South Wales', '404');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'VIC', 'Victoria', '405');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('AU', 'SA', 'South Australia', '406');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'VT', 'Viterbo', '407');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'VR', 'Verona', '408');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'LU', 'Lucca', '409');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'LT', 'Latina', '410');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'LO', 'Lodi', '411');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'VI', 'Vicenza', '412');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'VE', 'Venice', '413');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'VC', 'Vercelli', '414');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'ME', 'Messina', '415');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'VA', 'Varese', '416');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'MI', 'Milan', '417');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'MC', 'Macerata', '418');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'FE', 'Ferrara', '419');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'MN', 'Mantova', '420');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'MO', 'Modena', '421');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'MT', 'Matera', '422');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'MS', 'Massa Carrara', '423');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'EN', 'Enna', '424');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'UD', 'Udine', '425');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'NA', 'Naples', '426');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TV', 'Treviso', '427');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'GE', 'Genova', '428');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'NU', 'Nuoro', '429');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'NO', 'Novara', '430');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'FR', 'Frosinone', '431');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'FO', 'Forlì', '432');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'FG', 'Foggia', '433');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'FI', 'Florence', '434');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'OR', 'Oristano', '435');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PN', 'Pordenone', '436');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PO', 'Prato', '437');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'GR', 'Grosseto', '438');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PI', 'Pisa', '439');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'GO', 'Gorizia', '440');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PD', 'Padova', '441');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'VV', 'Vibo Valentia', '442');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PE', 'Pescara', '443');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PG', 'Perugia', '444');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PA', 'Palermo', '445');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PC', 'Piacenza', '446');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RI', 'Rieti', '447');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RG', 'Ragusa', '448');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RE', 'Reggio Emilia', '449');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RC', 'Reggio Calabria', '450');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RO', 'Rovigo', '451');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RN', 'Rimini', '452');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RM', 'Rome', '453');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RA', 'Ravenna', '454');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AT', 'Asti', '455');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AR', 'Arezzo', '456');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AQ', 'L''Aquila', '457');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'IM', 'Imperia', '458');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AV', 'Avellino', '459');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'IS', 'Isernia', '460');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BA', 'Bari', '461');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PT', 'Pistoia', '462');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PV', 'Pavia', '463');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AG', 'Agriento', '464');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PR', 'Parma', '465');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PS', 'Pesaro', '466');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AL', 'Alessandria', '467');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AO', 'Aosta', '468');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AP', 'Ascoli Piceno', '469');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'PZ', 'Potenza', '470');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'AN', 'Ancona', '471');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TE', 'Teramo', '472');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BS', 'Brescia', '473');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BR', 'Brindisi', '474');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TO', 'Turin', '475');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TN', 'Trento', '476');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CB', 'Campobasso', '477');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CA', 'Cagliari', '478');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TS', 'Trieste', '479');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BZ', 'Bolzano', '480');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TR', 'Terni', '481');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TP', 'Trapani', '482');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BG', 'Bergamo', '483');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'SV', 'Savona', '484');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'SS', 'Sassari', '485');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BI', 'Biella', '486');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BN', 'Benevento', '487');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BO', 'Bologna', '488');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'BL', 'Belluno', '489');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'TA', 'Taranto', '490');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CZ', 'Catanzaro', '491');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'KR', 'Crotone', '492');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CT', 'Catania', '493');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CS', 'Cosenza', '494');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'SI', 'Siena', '495');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'SP', 'La Spezia', '496');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'SO', 'Sondrio', '497');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'SR', 'Siracusa', '498');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'LC', 'Lecco', '499');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CH', 'Chieti', '500');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CE', 'Caserta', '501');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'RV', 'Rovigo', '502');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'LI', 'Livorno', '503');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CR', 'Cremona', '504');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CO', 'Como', '505');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'LE', 'Lecce', '506');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CN', 'Cuneo', '507');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'SA', 'Salerno', '508');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('IT', 'CL', 'Caltanisetta', '509');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '17', 'Alto Trás-os-Montes', '510');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '15', 'Entre Douro e Vouga', '511');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '33', 'Médio Tejo', '512');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '16', 'Douro', '513');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '34', 'Lezíria do Tejo', '514');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '13', 'Grande Porto', '515');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '14', 'Tâmega', '516');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '11', 'Cávado', '517');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '12', 'Ave', '518');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '21', 'Baixo Mondego', '519');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '20', 'Baixo Vouga', '520');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '43', 'Baixo Alentejo', '521');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '42', 'Alentejo Central', '522');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '41', 'Alto Alentejo', '523');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '40', 'Alentejo Litoral', '524');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '60', 'Reg. Aut. dos Açores', '525');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '22', 'Pinhal Litoral', '526');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '23', 'Pinhal Interior N.', '527');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '24', 'Pinhal Interior Sul', '528');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '25', 'Dão-Lafoes', '529');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '26', 'Serra da Estrela', '530');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '27', 'Beira Interior Norte', '531');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '28', 'Beira Interior Sul', '532');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '29', 'Cova da Beira', '533');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '10', 'Minho-Lima', '534');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '30', 'Oeste', '535');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '32', 'Península de Setúbal', '536');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '31', 'Grande Lisboa', '537');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '70', 'Reg. Aut. da Madeira', '538');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PT', '50', 'Algarve', '539');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'CHV', 'Chernovits''ka', '540');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'ZAK', 'Zakarpats''ka', '541');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'VIN', 'Vinnits''ka', '542');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'ZAP', 'Zaporiz''ka', '543');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'KIR', 'Kirovograds''ka', '544');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'MIK', 'Mikolaivs''ka', '545');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'CHG', 'Chernigivs''ka', '546');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'DNP', 'Dnipropetrovs''ka', '547');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'ZHI', 'Zhitomirs''ka', '548');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'SUM', 'Sums''ka', '549');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'KIE', 'Kievs''ka', '550');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'IVF', 'Ivano-Frankivs''ka', '551');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'RIV', 'Rivnens''ka', '552');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'TER', 'Ternopil''s''ka', '553');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'CHR', 'Cherkas''ka', '554');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'M_K', 'm.Kiev', '555');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'HRS', 'Hersons''ka', '556');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'HAR', 'Harkivs''ka', '557');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'M_S', 'm.Sevastopil''', '558');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'HML', 'Hmel''nits''ka', '559');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'L''V', 'L''vivsbka', '560');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'KRM', 'Respublika Krim', '561');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'POL', 'Poltavs''ka', '562');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'DON', 'Donets''ka', '563');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'VOL', 'Volins''ka', '564');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'LUG', 'Lugans''ka', '565');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('UA', 'ODS', 'Odes''ka', '566');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '35', 'Las Palmas', '567');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '36', 'Pontevedra', '568');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '33', 'Asturias', '569');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '34', 'Palencia', '570');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '39', 'Cantabria', '571');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '37', 'Salamanca', '572');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '38', 'Sta. Cruz Tenerife', '573');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '43', 'Tarragona', '574');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '42', 'Soria', '575');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '41', 'Sevilla', '576');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '40', 'Segovia', '577');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '22', 'Huesca', '578');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '23', 'Jaen', '579');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '24', 'Leon', '580');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '25', 'Lerida', '581');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '26', 'La Rioja', '582');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '27', 'Lugo', '583');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '28', 'Madrid', '584');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '29', 'Malaga', '585');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '3', 'Alicante', '586');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '2', 'Albacete', '587');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '1', 'Alava', '588');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '7', 'Baleares', '589');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '30', 'Murcia', '590');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '6', 'Badajoz', '591');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '5', 'Avila', '592');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '32', 'Orense', '593');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '4', 'Almeria', '594');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '31', 'Navarra', '595');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '9', 'Burgos', '596');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '8', 'Barcelona', '597');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '19', 'Guadalajara', '598');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '17', 'Gerona', '599');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '18', 'Granada', '600');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '15', 'La Coruña', '601');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '16', 'Cuenca', '602');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '13', 'Ciudad Real', '603');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '14', 'Córdoba', '604');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '11', 'Cadiz', '605');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '12', 'Castellon', '606');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '21', 'Huelva', '607');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '20', 'Guipuzcoa', '608');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '49', 'Zamora', '609');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '48', 'Vizcaya', '610');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '45', 'Toledo', '611');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '44', 'Teruel', '612');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '47', 'Valladolid', '613');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '46', 'Valencia', '614');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '10', 'Caceres', '615');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('ES', '50', 'Zaragoza', '616');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '3', 'Friesland', '617');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '2', 'Flevoland', '618');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '10', 'Utrecht', '619');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '1', 'Drenthe', '620');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '7', 'Noord-Brabant', '621');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '6', 'Limburg', '622');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '5', 'Groningen', '623');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '4', 'Gelderland', '624');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '9', 'Overijssel', '625');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '8', 'Noord-Holland', '626');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '11', 'Zeeland', '627');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NL', '12', 'Zuid-Holland', '628');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TW', 'TWN', 'Taiwan', '629');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TW', 'TPE', 'T´ai-pei', '630');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TW', 'KSH', 'Kao-hsiung', '631');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TW', 'FJN', 'Fu-chien', '632');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '19', 'Yamanashi-ken', '633');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '35', 'Yamaguchi-ken', '634');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '17', 'Ishikawa-ken', '635');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '36', 'Tokushima-ken', '636');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '18', 'Fukui-ken', '637');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '33', 'Okayama-ken', '638');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '15', 'Niigata-ken', '639');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '34', 'Hiroshima-ken', '640');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '16', 'Toyama-ken', '641');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '39', 'Kochi-ken', '642');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '13', 'Tokyo-to', '643');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '14', 'Kanagawa-ken', '644');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '37', 'Kagawa-ken', '645');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '11', 'Saitama-ken', '646');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '38', 'Ehima-ken', '647');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '12', 'Chiba-ken', '648');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '21', 'Gifu-ken', '649');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '20', 'Nagano-ken', '650');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '43', 'Kumamoto-ken', '651');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '42', 'Nagasaki-ken', '652');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '41', 'Saga-ken', '653');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '40', 'Fukuoka-ken', '654');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '45', 'Miyazaki-ken', '655');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '44', 'Oita-ken', '656');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '47', 'Okinawa-ken', '657');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '46', 'Kagoshima-ken', '658');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '22', 'Shizuoka-ken', '659');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '23', 'Aichi-ken', '660');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '24', 'Mie-ken', '661');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '25', 'Shiga-ken', '662');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '26', 'Kyoto-fu', '663');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '27', 'Osaka-fu', '664');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '28', 'Hyogo-ken', '665');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '29', 'Nara-ken', '666');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '3', 'Iwate-ken', '667');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '2', 'Aomori-ken', '668');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '10', 'Gunma-ken', '669');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '1', 'Hokkaido', '670');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '30', 'Wakayama-ken', '671');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '7', 'Fukushima-ken', '672');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '6', 'Yamagata-ken', '673');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '32', 'Shimana-ken', '674');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '5', 'Akita-ken', '675');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '31', 'Tottori-ken', '676');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '4', 'Miyagi-ken', '677');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '9', 'Tochigi-ken', '678');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('JP', '8', 'Ibaragi-ken', '679');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'AKL', 'Auckland', '680');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'HAB', 'Hawke´s Bay', '681');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'OTA', 'Otago', '682');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'WLG', 'Wellington', '683');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'MAN', 'Manawatu-Wanganui', '684');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'STL', 'Southland', '685');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'BOP', 'Bay of Plenty', '686');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'WAI', 'Waikato', '687');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'WEC', 'West Coast', '688');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'CAN', 'Canterbury', '689');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'TAR', 'Taranaki', '690');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('NZ', 'NTL', 'Northland', '691');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'TO', 'Tocantins', '692');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'RO', 'Rondônia', '693');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'RN', 'Rio Grande do Norte', '694');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'RJ', 'Rio de Janeiro', '695');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'MG', 'Minas Gerais', '696');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'DF', 'Brasília', '697');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'MA', 'Maranhão', '698');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'SC', 'Santa Catarina', '699');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'SE', 'Sergipe', '700');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'SP', 'São Paulo', '701');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'BA', 'Bahia', '702');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'MT', 'Mato Grosso', '703');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'MS', 'Mato Grosso', '704');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'AC', 'Acre', '705');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'RR', 'Roraima', '706');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'RS', 'Rio Grande do Sul', '707');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'CE', 'Ceará', '708');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'ES', 'Espírito San', '709');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'PI', 'Piauí', '710');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'PR', 'Paraná', '711');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'GO', 'Goiás', '712');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'AL', 'Alagoas', '713');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'PE', 'Pernambuco', '714');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'AP', 'Amapá', '715');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'PA', 'Para', '716');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'AM', 'Amazon', '717');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('BR', 'PB', 'Paraíba', '718');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LU', 'Luton', '719');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LT', 'Lothian', '720');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LO', 'Greater London', '721');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DU', 'Durham', '722');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DV', 'Devon', '723');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LM', 'Limavady', '724');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LS', 'Lisburn', '725');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DY', 'Dyfed', '726');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LR', 'Larne', '727');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'MG', 'Mid Glamorgan', '728');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DL', 'Darlington', '729');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DO', 'Dorset', '730');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DN', 'Down', '731');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'MK', 'Milton Keynes', '732');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'MI', 'Middlesbrough', '733');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DG', 'Dungannon', '734');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DF', 'Dumfries a. Galloway', '735');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'MA', 'Magherafelt', '736');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'MY', 'Merseyside', '737');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'MO', 'Moyle', '738');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NH', 'Northamptonshire', '739');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'ES', 'Essex', '740');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NK', 'Norfolk', '741');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'ER', 'East Riding', '742');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NL', 'North Lincolnshire', '743');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NM', 'Newry and Mourne', '744');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NA', 'Newtownabbey', '745');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NB', 'Newbury', '746');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NC', 'Nottingham City', '747');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'TW', 'Tyne and Wear', '748');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'ND', 'North Down', '749');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NE', 'NthEast Lincolnshire', '750');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NU', 'Northumberland', '751');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NT', 'Nottinghamshire', '752');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'NS', 'North Somerset', '753');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'OM', 'Omagh', '754');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'FM', 'Fermanagh', '755');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'FI', 'Fife', '756');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WO', 'Wokingham', '757');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WR', 'Wrekin', '758');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'OX', 'Oxfordshire', '759');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WT', 'Warrington', '760');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'HA', 'Hampshire', '761');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WG', 'West Glamorgan', '762');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WI', 'Wiltshire', '763');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'GY', 'Gwynedd', '764');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WL', 'Western Isles', '765');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WM', 'West Midlands', '766');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'GW', 'Gwent', '767');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'OR', 'Orkney', '768');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'PL', 'Poole', '769');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'PM', 'Portsmouth', '770');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WA', 'Warwickshire', '771');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'GS', 'Sth. Gloucestershire', '772');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'PO', 'Powys', '773');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'WD', 'Windsor  and  Maidenhead', '774');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'GR', 'Grampian', '775');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'GM', 'Greater Manchester', '776');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'GL', 'Gloucestershire', '777');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'PB', 'Peterborough', '778');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'HI', 'Highland', '779');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'RE', 'Reading', '780');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'RD', 'Redcar and Cleveland', '781');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'HL', 'Halton', '782');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'HR', 'Hartlepool', '783');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'RM', 'Rochester up. Medway', '784');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'HW', 'Hereford and Worcs.', '785');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'HT', 'Hertfordshire', '786');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'AT', 'Antrim', '787');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'AR', 'Ards', '788');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BA', 'Ballymena', '789');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'IW', 'Isle of Wight', '790');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'YN', 'North Yorkshire', '791');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'YK', 'York', '792');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'YW', 'West Yorkshire', '793');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'YS', 'South Yorkshire', '794');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'PY', 'Plymouth', '795');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'AM', 'Armagh', '796');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BY', 'Ballymoney', '797');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'TD', 'Thamesdown', '798');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BS', 'Bath and NthEstSomerset', '799');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BR', 'Bristol', '800');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BU', 'Buckinghamshire', '801');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'TH', 'Thurrock', '802');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'TO', 'Torbay', '803');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CA', 'Cambridgeshire', '804');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SU', 'Slough', '805');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BF', 'Bracknell Forest', '806');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BH', 'Brighton  and  Hove', '807');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'ST', 'Staffordshire', '808');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SY', 'Surrey', '809');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BB', 'Blackburn', '810');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SW', 'West Sussex', '811');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BE', 'Bedfordshire', '812');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BN', 'Banbridge', '813');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BO', 'Borders', '814');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BP', 'Blackpool', '815');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'KH', 'Kingston-upon-Hull', '816');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BK', 'Berkshire', '817');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'KE', 'Kent', '818');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BL', 'Belfast', '819');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'TA', 'Tayside', '820');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'BM', 'Bournemouth', '821');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SD', 'Southend', '822');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SC', 'Strathclyde', '823');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SE', 'East Sussex', '824');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SH', 'Shropshire', '825');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CV', 'Cleveland', '826');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SG', 'South Glamorgan', '827');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CU', 'Cumbria', '828');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CS', 'Castlereagh', '829');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SL', 'Shetland', '830');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SK', 'Suffolk', '831');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'DB', 'Derbyshire', '832');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SN', 'Stockton-on-Tees', '833');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SP', 'Southampton', '834');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SO', 'Somerset', '835');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'SR', 'Strabane', '836');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CI', 'Coleraine', '837');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LA', 'Lancashire', '838');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CG', 'Craigavon', '839');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LC', 'Leicester City', '840');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'RU', 'Rutland', '841');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CH', 'Cheshire', '842');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CE', 'Central', '843');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LI', 'Lincolnshire', '844');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CR', 'Carrickfergus', '845');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CO', 'Cornwall', '846');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LE', 'Leicestershire', '847');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'LD', 'Londonderry', '848');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CK', 'Cookstown', '849');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GB', 'CL', 'Clwyd', '850');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '35', 'Nong Khai', '851');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '36', 'Nonthaburi', '852');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '33', 'Narathiwat', '853');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '34', 'Nong Bua Lamphu', '854');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '39', 'Phangnga', '855');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '37', 'Pathum Thani', '856');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('TH', '38', 'Pattani', '857');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '63', 'The Samara Area', '1398');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '60', 'The Pskov Area', '1399');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '61', 'The Rostov Area', '1400');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '49', 'The Magadan Area', '1401');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '48', 'The Lipetsk Area', '1402');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '45', 'The Kurgan Area', '1403');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '44', 'The Kostroma Area', '1404');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '47', 'The Leningrad Area', '1405');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '46', 'The Kursk Area', '1406');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '10', 'Karelian Republic', '1407');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '51', 'The Murmansk Area', '1408');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '52', 'The Nizhniy Novgorod', '1409');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '53', 'The Novgorod Area', '1410');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '54', 'The Novosibirsk Area', '1411');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '88', 'Evensky Auton.distri', '1412');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '89', 'Jamalo-Nenekchky Aut', '1413');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('RU', '50', 'The Moscow Area', '1414');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '35', 'Lesvos', '1415');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '36', 'Levkas', '1416');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '33', 'Larisa', '1417');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '34', 'Lasithi', '1418');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '39', 'Pella', '1419');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '37', 'Magnisia', '1420');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '38', 'Messinia', '1421');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '43', 'Rethimni', '1422');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '42', 'Preveza', '1423');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '41', 'Piraievs', '1424');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '40', 'Pieria', '1425');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '22', 'Kavala', '1426');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '23', 'Kefallinia', '1427');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '24', 'Kerkira', '1428');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '25', 'Khalkidhiki', '1429');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '26', 'Khania', '1430');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '27', 'Khios', '1431');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '28', 'Kikladhes', '1432');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '29', 'Kilkis', '1433');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '3', 'Argolis', '1434');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '2', 'Akhaia', '1435');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '1', 'Aitolia kai Akarnan.', '1436');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '7', 'Dhodhekanisos', '1437');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '30', 'Korinthia', '1438');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '6', 'Attiki', '1439');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '5', 'Arta', '1440');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '32', 'Lakonia', '1441');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '4', 'Arkadhia', '1442');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '31', 'Kozani', '1443');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '9', 'Evritania', '1444');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '8', 'Dhrama', '1445');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '19', 'Iraklion', '1446');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '17', 'Imathia', '1447');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '18', 'Ioannina', '1448');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '15', 'Grevena', '1449');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '16', 'Ilia', '1450');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '13', 'Fokis', '1451');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '14', 'Fthiotis', '1452');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '11', 'Evvoia', '1453');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '12', 'Florina', '1454');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '21', 'Kastoria', '1455');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '20', 'Kardhitsa', '1456');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '49', 'Trikala', '1457');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '48', 'Thessaloniki', '1458');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '45', 'Samos', '1459');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '44', 'Rodhopi', '1460');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '47', 'Thesprotia', '1461');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '46', 'Serrai', '1462');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '10', 'Evros', '1463');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '51', 'Xanthi', '1464');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '52', 'Zakinthos', '1465');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('GR', '50', 'Voiotia', '1466');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '3', 'Central Luzon', '1467');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '2', 'Cagayan Valley', '1468');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '10', 'Northern Mindanao', '1469');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '1', 'Ilocos', '1470');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '7', 'Central Visayas', '1471');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '6', 'West Visayas', '1472');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '5', 'Bicol', '1473');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '4', 'South Luzon', '1474');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '9', 'Western Mindanao', '1475');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '8', 'Eastern Visayas', '1476');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '11', 'Cntrl Mindanao', '1477');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PH', '12', 'South Mindanao', '1478');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '19', 'Apurimac', '1479');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '22', 'Loreto', '1480');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '17', 'Huancavelica', '1481');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '23', 'Ucayali', '1482');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '18', 'Ayacucho', '1483');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '24', 'Madre de Díos', '1484');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '15', 'Pasco', '1485');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '16', 'Junín', '1486');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '13', 'San Martín', '1487');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '14', 'Huánuco', '1488');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '11', 'Amazon', '1489');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '12', 'Cajamarca', '1490');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '21', 'Puno', '1491');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '3', 'Lambayeque', '1492');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '20', 'Cuzco', '1493');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '2', 'Piura', '1494');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '1', 'Tumbes', '1495');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '10', 'Tacna', '1496');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '7', 'Ica', '1497');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '6', 'Lima y Callao', '1498');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '5', 'Ancash', '1499');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '4', 'La Libertad', '1500');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '9', 'Moquegua', '1501');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('PE', '8', 'Arequipa', '1502');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '19', 'CAUCA', '1503');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '17', 'CALDAS', '1504');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '18', 'CAQUETA', '1505');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '15', 'BOYACA', '1506');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '13', 'BOLIVAR', '1507');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '11', 'BOGOTA', '1508');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '20', 'CESAR', '1509');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '41', 'HUILA', '1510');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '63', 'QUINDIO', '1511');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '81', 'ARAUCA', '1512');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '99', 'VICHADA', '1513');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '86', 'PUTUMAYO', '1514');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '85', 'CASANARE', '1515');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '97', 'VAUPES', '1516');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '66', 'RISARALDA', '1517');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '95', 'GUAVIARE', '1518');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '68', 'SANTANDER', '1519');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '94', 'GUAINIA', '1520');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '44', 'LA GUAJIRA', '1521');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '47', 'MAGDALENA', '1522');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '91', 'AMAZONAS', '1523');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '23', 'CORDOBA', '1524');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '25', 'CUNDINAMARCA', '1525');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '27', 'CHOCO', '1526');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '5', 'ANTIOQUIA', '1527');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '52', 'NARIÑO', '1528');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '70', 'SUCRE', '1529');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '8', 'ATLANTICO', '1530');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '54', 'NORTE SANTANDER', '1531');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '73', 'TOLIMA', '1532');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '88', 'SAN ANDRES', '1533');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CO', '76', 'VALLE', '1534');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '260', 'Gansu', '1535');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '210', 'Guangxi', '1536');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '240', 'Yunnan', '1537');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '110', 'Anhui', '1538');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '280', 'Qinghai', '1539');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '310', 'Taiwan', '1540');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '190', 'Guangdong', '1541');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '170', 'Hubei', '1542');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '20', 'Shanghai', '1543');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '150', 'Fujian', '1544');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '40', 'Nei Mongol', '1545');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '80', 'Jilin', '1546');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '60', 'Hebei', '1547');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '130', 'Zhejiang', '1548');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '100', 'Jiangsu', '1549');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '220', 'Guizhou', '1550');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '250', 'Shaanxi', '1551');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '300', 'Xizang', '1552');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '200', 'Hainan', '1553');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '230', 'Sichuan', '1554');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '90', 'Heilongjiang', '1555');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '270', 'Ningxia', '1556');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '290', 'Xinjiang', '1557');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '180', 'Henan', '1558');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '10', 'Beijing', '1559');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '30', 'Tianjin', '1560');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '160', 'Hunan', '1561');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '70', 'Liaoning', '1562');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '120', 'Shandong', '1563');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '140', 'Jiangxi', '1564');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CN', '50', 'Shanxi', '1565');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '13', 'RM - Santiago', '1566');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '11', 'XI - Coyhaique', '1567');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '12', 'XII - Punta Arenas', '1568');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '3', 'III - Copiapo', '1569');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '2', 'II - Antofagasta', '1570');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '1', 'I - Iquique', '1571');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '10', 'X - Puerto Montt', '1572');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '7', 'VII - Talca', '1573');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '6', 'VI - Rancagua', '1574');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '5', 'V - Valparaiso', '1575');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '4', 'IV - La Serena', '1576');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '9', 'IX - Temuco', '1577');
Insert into CUST.REGION
   (COUNTRY_CODE, CODE, NAME, ID)
 Values
   ('CL', '8', 'VIII - Concepción', '1578');

