Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('1', 'HK', 'Hong Kong', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('2', 'LV', 'Latvia', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('3', 'ZA', 'South Africa', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('4', 'HR', 'Croatia', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('5', 'RO', 'Romania', '\d{6}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('6', 'HU', 'Hungary', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('7', 'VE', 'Venezuela', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('8', 'ID', 'Indonesia', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('9', 'DE', 'Germany', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('10', 'DK', 'Denmark', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('11', 'IE', 'Ireland', '((D|DUBLIN)?([1-9]|6[wW]|1[0-8]|2[024]))?');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('12', 'AT', 'Austria', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('13', 'US', 'USA', '\d{5}([ \-]\d{4})?');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('14', 'AR', 'Argentina', '([A-HJ-NP-Z])?\d{4}([A-Z]{3})?');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('15', 'MX', 'Mexico', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('16', 'IL', 'Israel', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('17', 'IN', 'India', '\d{6}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('18', 'MY', 'Malaysia', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('19', 'AU', 'Australia', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('20', 'IT', 'Italy', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('21', 'PT', 'Portugal', '\d{4}([\-]\d{3})?');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('22', 'UA', 'Ukraine', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('23', 'ES', 'Spain', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('24', 'NL', 'Netherlands', '\d{4}[ ]?[A-Z]{2}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('25', 'TW', 'Taiwan', '\d{3}(\d{2})?');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('26', 'JP', 'Japan', '\d{3}-\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('27', 'NZ', 'New Zealand', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('28', 'BR', 'Brazil', '\d{5}[\-]?\d{3}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('29', 'GB', 'United Kingdom', 'GIR[ ]?0AA|((AB|AL|B|BA|BB|BD|BH|BL|BN|BR|BS|BT|CA|CB|CF|CH|CM|CO|CR|CT|CV|CW|DA|DD|DE|DG|DH|DL|DN|DT|DY|E|EC|EH|EN|EX|FK|FY|G|GL|GY|GU|HA|HD|HG|HP|HR|HS|HU|HX|IG|IM|IP|IV|JE|KA|KT|KW|KY|L|LA|LD|LE|LL|LN|LS|LU|M|ME|MK|ML|N|NE|NG|NN|NP|NR|NW|OL|OX|PA|PE|PH|PL|PO|PR|RG|RH|RM|S|SA|SE|SG|SK|SL|SM|SN|SO|SP|SR|SS|ST|SW|SY|TA|TD|TF|TN|TQ|TR|TS|TW|UB|W|WA|WC|WD|WF|WN|WR|WS|WV|YO|ZE)(\d[\dA-Z]?[ ]?\d[ABD-HJLN-UW-Z]{2}))|BFPO[ ]?\d{1,4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('30', 'TH', 'Thailand', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('31', 'CA', 'Canada', '[ABCEGHJKLMNPRSTVXY]\d[ABCEGHJ-NPRSTV-Z][ ]?\d[ABCEGHJ-NPRSTV-Z]\d');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('32', 'TR', 'Turkey', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('33', 'NO', 'Norway', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('34', 'FR', 'France', '\d{2}[ ]?\d{3}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('35', 'BG', 'Bulgaria', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('36', 'BE', 'Belgium', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('37', 'FI', 'Finland', '\d{5}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('38', 'CZ', 'Czech Republic', '\d{3}[ ]?\d{2}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('39', 'KR', 'South Korea', '\d{3}[\-]\d{3}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('40', 'SE', 'Sweden', '\d{3}[ ]?\d{2}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('41', 'SG', 'Singapore', '\d{6}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('42', 'SI', 'Slovenia', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('43', 'SK', 'Slovakia', '\d{3}[ ]?\d{2}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('44', 'PL', 'Poland', '\d{2}-\d{3}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('45', 'CH', 'Switzerland', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('46', 'RU', 'Russian Fed.', '\d{6}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('47', 'GR', 'Greece', '\d{3}[ ]?\d{2}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('48', 'PH', 'Philippines', '\d{4}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('49', 'PE', 'Peru', NULL);
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('50', 'CO', 'Colombia', NULL);
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('51', 'CN', 'China', '\d{6}');
Insert into CUST.COUNTRY
   (ID, CODE, NAME, ZIP_CHECK_REGEX)
 Values
   ('52', 'CL', 'Chile', '\d{7}');

