/* Generated by Together */

package com.freshdirect.customer.ejb;

import java.sql.*;
import com.freshdirect.framework.core.*;

/**
 * Abstract superclass for read-only ERP PBeans.
 * 
 * @version    $Revision$
 * @author     $Author$
 * @stereotype fd-persistent
 */
abstract class ErpReadOnlyPersistentBean extends DependentPersistentBeanSupport {

	/**
     * Overriden isModified, always false, as this is a read-only object.
     */
	public final boolean isModified() {
		return false;
	}

	public final void store(Connection conn) throws SQLException {
        throw new UnsupportedOperationException("Object cannot be modified");
    }

	public final void remove(Connection conn) throws SQLException {
        throw new UnsupportedOperationException("Object cannot be modified");
	}

}
