/* Generated by Together */

package com.freshdirect.customer.ejb;

import com.freshdirect.customer.*;
import com.freshdirect.framework.core.DependentPersistentBeanSupport;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;

/**
 * Abstract superclass for read-only ERP PBeans.
 * 
 * @version    $Revision:4$
 * @author     $Author:Viktor Szathmary$
 * @stereotype fd-persistent
 */
abstract class ErpUpdatableTransactionBean extends DependentPersistentBeanSupport implements ErpTransactionI {

    protected Date transactionDate;
    protected EnumTransactionSource transactionSource;
    protected String transactionInitiator;
	/** Default constructor. */
	public ErpUpdatableTransactionBean() {
		super();
	}

    public void decorateModel(ErpTransactionModel model) {
        super.decorateModel(model);
		model.setTransactionSource( this.transactionSource );
        model.setTransactionDate( this.transactionDate );
        model.setTransactionInitiator(this.transactionInitiator);
    }
    
    public Date getTransactionDate(){
    	return this.transactionDate;
    }

    public String getTransactionInitiator() {
    	return this.transactionInitiator;
    }
    
    public final void remove(Connection conn) throws SQLException {
    	throw new UnsupportedOperationException("Object cannot be removed");
    }

}
