ALTER TABLE CUST.SURVEY_DEF ADD ("SERVICE_TYPE" VARCHAR2(20) DEFAULT 'ANY' NOT NULL);


ALTER TABLE SURVEY_DEF DROP CONSTRAINT "SYS_C00123906";

ALTER TABLE SURVEY_DEF ADD CONSTRAINT SYS_C00123906 UNIQUE ("NAME","SERVICE_TYPE") ENABLE;


