ALTER TABLE CUST.SURVEY_DEF ADD ("SERVICE_TYPE" VARCHAR2(20) DEFAULT 'HOME' NOT NULL);

ALTER TABLE CUST.SURVEY_DEF DROP UNIQUE ("NAME");

ALTER TABLE CUST.SURVEY_DEF ADD UNIQUE ("NAME","SERVICE_TYPE") ENABLE;

ALTER TABLE CUST.SURVEY ADD ("SERVICE_TYPE" VARCHAR2(20) DEFAULT 'HOME' NOT NULL);
