GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDISPATCHEX TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDISPATCHEX TO fdtrn_stprd01;
GRANT SELECT ON TRANSP.HANDOFF_BATCHDISPATCHEX TO APPDEV;
