CREATE INDEX CUST.PROMO_STATUS_IDX ON CUST.PROMOTION_NEW(STATUS);

CREATE INDEX CUST.START_DATE_IDX ON CUST.PROMOTION_NEW(START_DATE);

CREATE INDEX CUST.DAY_ID_IDX ON CUST.PROMO_DLV_TIMESLOT(DAY_ID);

CREATE INDEX CUST.PROMOTION_ID_IDX ON CUST.PROMO_DLV_ZONE_STRATEGY(PROMOTION_ID);
