CREATE TABLE TRANSP.TRUCK_PREFERENCE
(
  KRONOS_ID  VARCHAR2(10 BYTE)                  NOT NULL,
  PREFERENCE_KEY       VARCHAR2(16 BYTE) NOT NULL,
  TRUCK_NUMBER   VARCHAR2(16 BYTE) NOT NULL,
  UNIQUE (KRONOS_ID, PREFERENCE_KEY)
);

CREATE TABLE TRANSP.HANDOFFBATCH_AUTODISPATCH
(
  BATCH_ID            VARCHAR2(8 BYTE)       NOT NULL,
  DELIVERY_DATE     DATE           NOT NULL,
  ROUTE_NO            VARCHAR2(8 BYTE)       NOT NULL,
  PHYSICAL_TRUCK   VARCHAR2(8 BYTE),
  DISPATCH_TIME     DATE           NOT NULL  
);

ALTER TABLE TRANSP.DISPATCH add (PHYSICAL_TRUCK  VARCHAR2  (6 BYTE) DEFAULT null);

CREATE INDEX TRANSP.FK_EMPLOYEE_TRUCKPREF ON TRANSP.TRUCK_PREFERENCE  ( KRONOS_ID );

CREATE INDEX TRANSP.FK_TRUCKPREFERENCE_ID ON TRANSP.TRUCK_PREFERENCE  ( PREFERENCE_KEY );

GRANT ALL ON TRANSP.TRUCK_PREFERENCE TO fdtrn_ststg01;
GRANT READ ON TRANSP.TRUCK_PREFERENCE TO appdev;

GRANT ALL ON TRANSP.HANDOFFBATCH_AUTODISPATCH TO fdtrn_ststg01;
GRANT READ ON TRANSP.HANDOFFBATCH_AUTODISPATCH TO appdev;


