CREATE TABLE CUST.PROMO_ATTR (ID VARCHAR2(16),
PROMOTION_ID VARCHAR2(16) NOT NULL, 
PROMO_ATTR_NAME VARCHAR2(40) NOT NULL,
ATTR_VALUE VARCHAR2(64) NOT NULL,
ATTR_INDEX NUMBER(3) NOT NULL,
CONSTRAINT PROMOATTR_PK PRIMARY KEY(ID),
CONSTRAINT PROMO_ATTR_FK FOREIGN KEY(PROMOTION_ID) REFERENCES CUST.PROMOTION(ID),
CONSTRAINT PROMO_ATTR_NAME_FK FOREIGN KEY(PROMO_ATTR_NAME) REFERENCES CUST.PROFILE_ATTR_NAME(NAME)
);

GRANT insert,update,select,delete on CUST.PROMO_ATTR to FDSTORE_PRDA;
GRANT insert,update,select,delete on CUST.PROMO_ATTR to FDSTORE_PRDB;
