--
-- Content Types
--

CREATE TABLE "CONTENTTYPE"
  (
    "ID"          VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "NAME"        VARCHAR2(1000 BYTE) NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(1000 BYTE),
    "GENERATE_ID" VARCHAR2(1 BYTE),
    CONSTRAINT "PK_CONTENTTYPE" PRIMARY KEY ("ID")  ENABLE,
    UNIQUE ("NAME") ENABLE
  );



CREATE TABLE "LOOKUPTYPE"
  (
    "CODE"          VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "NAME"          VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "DESCRIPTION"   VARCHAR2(256 BYTE),
    "LOOKUP_SOURCE" VARCHAR2(8),
    "QUERY"         VARCHAR2(200),
    CONSTRAINT "PK_LOOKUPTYPE" PRIMARY KEY ("CODE") ENABLE
  );


CREATE TABLE "LOOKUP"
  (
    "LOOKUPTYPE_CODE" VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "CODE"            VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "LABEL"           VARCHAR2(40 BYTE),
    "DESCRIPTION"     VARCHAR2(256 BYTE),
    "ORDINAL"         NUMBER(10,0),
    CONSTRAINT "LKTYPE_LOOKUP_FK" FOREIGN KEY ("LOOKUPTYPE_CODE") REFERENCES "LOOKUPTYPE" ("CODE") ENABLE
  );



CREATE TABLE "ATTRIBUTEDEFINITION"
  (
    "NAME"               VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "ID"                 VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "CONTENTTYPE_ID"     VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "ATTRIBUTETYPE_CODE" VARCHAR2(40 BYTE),
    "INHERITABLE"        VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "REQUIRED"           VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "LABEL"              VARCHAR2(64 BYTE),
    "CARDINALITY_CODE"   VARCHAR2(4 BYTE) NOT NULL ENABLE,
    "LOOKUP_CODE"        VARCHAR2(40 BYTE),
    CONSTRAINT "PK_ATTRIBUTEDEFINITION" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "UNQ_ATTRIBUTEDEFINITION" UNIQUE ("CONTENTTYPE_ID", "NAME") ENABLE,
    CONSTRAINT "ATRDEF_LOOKUP_FK" FOREIGN KEY ("LOOKUP_CODE") REFERENCES "LOOKUPTYPE" ("CODE") ENABLE,
    CONSTRAINT "CTYPE_ATTRDEF_FK" FOREIGN KEY ("CONTENTTYPE_ID") REFERENCES "CONTENTTYPE" ("ID") ENABLE
  );



CREATE TABLE "RELATIONSHIPDEFINITION"
  (
    "NAME"             VARCHAR2(1000 BYTE) NOT NULL ENABLE,
    "ID"               VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "CONTENTTYPE_ID"   VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "INHERITABLE"      VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "REQUIRED"         VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "NAVIGABLE"        VARCHAR2(1 BYTE) NOT NULL ENABLE,
    "LABEL"            VARCHAR2(64 BYTE),
    "CARDINALITY_CODE" VARCHAR2(4 BYTE) NOT NULL ENABLE,
    "READONLY"         VARCHAR2(1 BYTE) DEFAULT 'F' NOT NULL ENABLE,
    CONSTRAINT "PK_RELATIONSHIPDEFINITION" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "UNQ_RELATIONSHIPDEFINITION" UNIQUE ("CONTENTTYPE_ID", "NAME") ENABLE,
    CONSTRAINT "CTYPE_RELDEF_FK" FOREIGN KEY ("CONTENTTYPE_ID") REFERENCES "CONTENTTYPE" ("ID") ENABLE
  );



CREATE TABLE "RELATIONSHIPDESTINATION"
  (
    "RELATIONSHIPDEFINITION_ID" VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "CONTENTTYPE_ID"            VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "ID"                        VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "REVERSE_ATTRIBUTE_NAME"    VARCHAR2(128 BYTE),
    "REVERSE_ATTRIBUTE_LABEL"   VARCHAR2(128 BYTE),
    CONSTRAINT "PK_RELATIONSHIPDESTINATION" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "UNQ_RELATIONSHIPDESTINATION" UNIQUE ("RELATIONSHIPDEFINITION_ID", "CONTENTTYPE_ID") ENABLE,
    CONSTRAINT "CTYPE_RELDEST_FK" FOREIGN KEY ("CONTENTTYPE_ID") REFERENCES "CONTENTTYPE" ("ID") ENABLE,
    CONSTRAINT "RSHIPDEF_RSHIPDEST_FK" FOREIGN KEY ("RELATIONSHIPDEFINITION_ID") REFERENCES "RELATIONSHIPDEFINITION" ("ID") ENABLE
  );



-- synonyms

CREATE OR REPLACE SYNONYM "CMS_CONTENTTYPE" FOR "CONTENTTYPE";
CREATE OR REPLACE SYNONYM "CMS_ATTRIBUTEDEFINITION" FOR "ATTRIBUTEDEFINITION";
CREATE OR REPLACE SYNONYM "CMS_RELATIONSHIPDEFINITION" FOR "RELATIONSHIPDEFINITION";
CREATE OR REPLACE SYNONYM "CMS_RELATIONSHIPDESTINATION" FOR "RELATIONSHIPDESTINATION";
CREATE OR REPLACE SYNONYM "CMS_LOOKUP" FOR "LOOKUP";
CREATE OR REPLACE SYNONYM "CMS_LOOKUPTYPE" FOR "LOOKUPTYPE";
