CREATE TABLE "CONTENTNODE"
  (
    "ID"             VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "CONTENTTYPE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE,
    CONSTRAINT "PK_CONTENTNODE" PRIMARY KEY ("ID") ENABLE
  );


CREATE TABLE "ATTRIBUTE"
  (
    "CONTENTNODE_ID"  VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "ID"              VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "VALUE"           VARCHAR2(3999 BYTE),
    "ORDINAL"         NUMBER(10,0) NOT NULL ENABLE,
    "DEF_NAME"        VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "DEF_CONTENTTYPE" VARCHAR2(40 BYTE) NOT NULL ENABLE,
    constraint "PK_ATTRIBUTE" primary key ("ID") enable,
    CONSTRAINT "CNODE_ATTR_FK" FOREIGN KEY ("CONTENTNODE_ID") REFERENCES "CONTENTNODE" ("ID") ENABLE
  );



CREATE TABLE "RELATIONSHIP"
  (
    "PARENT_CONTENTNODE_ID" VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "ORDINAL"               NUMBER(10,0) NOT NULL ENABLE,
    "ID"                    VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "DEF_NAME"              VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "DEF_CONTENTTYPE"       VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "CHILD_CONTENTNODE_ID"  VARCHAR2(128 BYTE),
    CONSTRAINT "PK_RELATIONSHIP" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "CNODE_RSHIPCHILD_FK" FOREIGN KEY ("CHILD_CONTENTNODE_ID") REFERENCES "CONTENTNODE" ("ID") ENABLE,
    CONSTRAINT "CNODE_RSHIPPARENT_FK" FOREIGN KEY ("PARENT_CONTENTNODE_ID") REFERENCES "CONTENTNODE" ("ID") ENABLE
  );


  
-- Create Media table
CREATE TABLE "MEDIA"
  (
    "ID"        VARCHAR2(128 BYTE),
    "URI"       VARCHAR2(255 BYTE) NOT NULL ENABLE,
    "WIDTH"     NUMBER(*,0),
    "HEIGHT"    NUMBER(*,0),
    "TYPE"      VARCHAR2(55 BYTE) NOT NULL ENABLE,
    "MIME_TYPE" VARCHAR2(55 BYTE),
    "LAST_MODIFIED" DATE,
    CONSTRAINT "PK_MEDIA" PRIMARY KEY ("ID") ENABLE,
    CONSTRAINT "UNQ_MEDIA_URI" UNIQUE ("URI") ENABLE
  );



-- Create default sequence
CREATE SEQUENCE "SYSTEM_SEQ";


-- Create Synonyms
CREATE OR REPLACE SYNONYM "CMS_CONTENTNODE" FOR "CONTENTNODE";
CREATE OR REPLACE SYNONYM "CMS_ATTRIBUTE" FOR "ATTRIBUTE";
CREATE OR REPLACE SYNONYM "CMS_RELATIONSHIP" FOR "RELATIONSHIP";
CREATE OR REPLACE SYNONYM "CMS_SYSTEM_SEQ" FOR "SYSTEM_SEQ";

CREATE OR REPLACE SYNONYM "CMS_MEDIA" FOR "MEDIA";


-- create view
CREATE OR REPLACE VIEW "NAVTREE"
as
select r.id,
  r.parent_contentnode_id,
  r.ordinal,
  r.def_name,
  r.def_contenttype,
  r.child_contentnode_id
from relationship r, relationshipdefinition rdef
where rdef.name = r.def_name (+)
  and rdef.id = substr(r.parent_contentnode_id,1,instr(r.parent_contentnode_id,':')-1)||'.'||r.def_name
  and rdef.navigable='T'
with
  read only;

