CREATE TABLE "DRAFT" 
(	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATED_DATE" TIMESTAMP (6) NOT NULL ENABLE, 
	"DRAFTSTATUS" VARCHAR2(255 CHAR), 
	"LAST_MODIFIED_DATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "DRAFTCHANGE" 
(	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"ATTRIBUTENAME" VARCHAR2(40 CHAR), 
	"CONTENTKEY" VARCHAR2(128 CHAR), 
	"CREATEDAT" NUMBER(19,0) NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(32 CHAR), 
	"VALUE" VARCHAR2(4000 CHAR), 
	"DRAFT_ID" NUMBER(19,0), 
	 PRIMARY KEY ("ID"),
	 CONSTRAINT "FK_DRAFTCHANGE_DRAFT_ID" FOREIGN KEY ("DRAFT_ID")
	  REFERENCES "DRAFT" ("ID") ENABLE
);

CREATE TABLE "PERMISSION" 
(	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	PRIMARY KEY ("ID")
);

CREATE TABLE "PERSONA" 
(	"ID" NUMBER(19,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID")
);

CREATE TABLE "PERSONA_PERMISSION" 
(	"PERSONA_ID" NUMBER(19,0) NOT NULL ENABLE, 
	"PERMISSIONS_ID" NUMBER(19,0) NOT NULL ENABLE, 
	 CONSTRAINT "FK_PERSPERM_PERMISSION_ID" FOREIGN KEY ("PERMISSIONS_ID")
	  REFERENCES "PERMISSION" ("ID") ENABLE, 
	 CONSTRAINT "FK_PERSPERM_PERSONA_ID" FOREIGN KEY ("PERSONA_ID")
	  REFERENCES "PERSONA" ("ID") ENABLE
);

CREATE TABLE "USERPERSONA" 
(	"USERID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"NAME" VARCHAR2(255 CHAR), 
	"PERSONA_ID" NUMBER(19,0), 
	 PRIMARY KEY ("USERID"),
	 CONSTRAINT "FK_USERPERM_PERSONA_ID" FOREIGN KEY ("PERSONA_ID")
	  REFERENCES "PERSONA" ("ID") ENABLE
);

-- synonyms
CREATE OR REPLACE SYNONYM "CMS_DRAFT" FOR "DRAFT";
CREATE OR REPLACE SYNONYM "CMS_DRAFTCHANGE" FOR "DRAFTCHANGE";
CREATE OR REPLACE SYNONYM "CMS_PERMISSION" FOR "PERMISSION";
CREATE OR REPLACE SYNONYM "CMS_PERSONA" FOR "PERSONA";
CREATE OR REPLACE SYNONYM "CMS_PERSONA_PERMISSION" FOR "PERSONA_PERMISSION";
CREATE OR REPLACE SYNONYM "CMS_USERPERSONA" FOR "USERPERSONA";
