CREATE TABLE "PUBLISH"
  (
    "TIMESTAMP" DATE NOT NULL ENABLE,
    "ID"          VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "USER_ID"     VARCHAR2(32 BYTE) NOT NULL ENABLE,
    "DESCRIPTION" VARCHAR2(1000 BYTE),
    "LAST_MODIFIED" DATE,
    "STATUS" VARCHAR2(10 BYTE),
    CONSTRAINT "PK_PUBLISH" PRIMARY KEY ("ID") ENABLE,
    UNIQUE ("TIMESTAMP")  ENABLE
  );
  
CREATE TABLE "PUBLISHMESSAGES"
  (
    "PUBLISH_ID" VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "SORT_ORDER" NUMBER(*,0) NOT NULL ENABLE,
    "TIMESTAMP" DATE NOT NULL ENABLE,
    "SEVERITY"     NUMBER(*,0) NOT NULL ENABLE,
    "MESSAGE"      VARCHAR2(400 CHAR),
    "CONTENT_ID"   VARCHAR2(128 BYTE),
    "CONTENT_TYPE" varchar2(40 byte),
    CONSTRAINT "PK_PUBLISHMESSAGE" PRIMARY KEY ("PUBLISH_ID", "SORT_ORDER") ENABLE,
    CONSTRAINT "PUBLISHMESSAGES_PUBLISH_FK" FOREIGN KEY ("PUBLISH_ID") REFERENCES "PUBLISH" ("ID") ENABLE
  );


-- changesets
--
CREATE TABLE "CHANGESET"
  (
    "ID" VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "TIMESTAMP" DATE NOT NULL ENABLE,
    "USER_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE,
    "NOTE"    VARCHAR2(2000 BYTE),
    constraint "PK_CHANGESET" primary key ("ID") enable
  );


CREATE TABLE "CONTENTNODECHANGE"
  (
    "ID"             VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "CHANGESET_ID"   VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "CONTENTNODE_ID" VARCHAR2(128 BYTE) NOT NULL ENABLE,
    "CHANGETYPE"     VARCHAR2(4 BYTE),
    "CONTENTTYPE"    VARCHAR2(40 BYTE),
    CONSTRAINT "PK_CONTENTNODECHANGE" PRIMARY KEY ("ID") ENABLE,
    constraint "CSET_CNODECHG_FK" foreign key ("CHANGESET_ID") references "CHANGESET" ("ID") enable
  );


CREATE TABLE "CHANGEDETAIL"
  (
    "CONTENTNODECHANGE_ID" VARCHAR2(16 BYTE) NOT NULL ENABLE,
    "CHANGETYPE"           VARCHAR2(4 BYTE) NOT NULL ENABLE,
    "ATTRIBUTENAME"        VARCHAR2(40 BYTE) NOT NULL ENABLE,
    "OLDVALUE"             VARCHAR2(2000 BYTE),
    "NEWVALUE"             VARCHAR2(2000 BYTE),
    constraint "CNCHG_CNCHGDET_FK" foreign key ("CONTENTNODECHANGE_ID") references "CONTENTNODECHANGE" ("ID") enable
  );

CREATE TABLE "PUBLISHX" 
   (
  	"CRO_MOD_DATE" DATE NOT NULL ENABLE, 
	"ID" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"USER_ID" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"LAST_MODIFIED" DATE, 
	"STATUS" VARCHAR2(10 BYTE), 
	CONSTRAINT "PK_PUBLISHX" PRIMARY KEY ("ID"),
	UNIQUE ("CRO_MOD_DATE")
  );

-- sequences
CREATE SEQUENCE "PUBLISH_SEQ";
CREATE SEQUENCE "PUBLISHX_SEQ";
  
-- synonyms
CREATE OR REPLACE SYNONYM "CMS_PUBLISH" FOR "PUBLISH";
CREATE OR REPLACE SYNONYM "CMS_PUBLISHMESSAGES" FOR "PUBLISHMESSAGES";

CREATE OR REPLACE SYNONYM "CMS_CHANGESET" FOR "CHANGESET";
CREATE OR REPLACE SYNONYM "CMS_CONTENTNODECHANGE" FOR "CONTENTNODECHANGE";
CREATE OR REPLACE SYNONYM "CMS_CHANGEDETAIL" FOR "CHANGEDETAIL";

CREATE OR REPLACE SYNONYM "CMS_PUBLISH_SEQ" FOR "PUBLISH_SEQ";
