
CREATE INDEX "IDX_CTYPE_ATTRDEF_FK" ON "ATTRIBUTEDEFINITION" ( "CONTENTTYPE_ID" );


CREATE INDEX "IDX_CTYPE_RELDEF_FK" ON "RELATIONSHIPDEFINITION" ( "CONTENTTYPE_ID" );

CREATE INDEX "IDX_RELDEFN_NAME" ON "RELATIONSHIPDEFINITION" ( "NAME" );

CREATE INDEX "IDX_RELDEFN_NAVIGABLE" ON "RELATIONSHIPDEFINITION" ( "NAVIGABLE" );


CREATE INDEX "IDX_CTYPE_RELDEST_FK" ON "RELATIONSHIPDESTINATION" ( "CONTENTTYPE_ID" );

CREATE INDEX "IDX_RSHIPDEF_RSHIPDEST_FK" ON "RELATIONSHIPDESTINATION" ( "RELATIONSHIPDEFINITION_ID" );


CREATE INDEX "IDX_LKTYPE_LOOKUP_FK" ON "LOOKUP" ( "LOOKUPTYPE_CODE" );


CREATE INDEX "IDX_ATTRIBUTE_DEF_CNTTYPE" ON "ATTRIBUTE" ( "DEF_CONTENTTYPE" );

CREATE INDEX "IDX_ATTRIBUTE_DEF_NAME" ON "ATTRIBUTE" ( "DEF_NAME" );

CREATE INDEX "IDX_CNODE_ATTR_FK" ON "ATTRIBUTE" ( "CONTENTNODE_ID" );


CREATE INDEX "IDX_CNODE_RSHIPCHILD_FK" ON "RELATIONSHIP" ( "PARENT_CONTENTNODE_ID" );

CREATE INDEX "IDX_CNODE_RSHIPPARENT_FK" ON "RELATIONSHIP" ( "CHILD_CONTENTNODE_ID" );

CREATE INDEX "IDX_RELATIONSHIP_DEF_CNTTYPE" ON "RELATIONSHIP" ( "DEF_CONTENTTYPE" );

CREATE INDEX "IDX_RELATIONSHIP_DEF_NAME" ON "RELATIONSHIP" ( "DEF_NAME" );


CREATE INDEX "IDX_CSET_CNODECHG_FK" ON "CONTENTNODECHANGE" ( "CHANGESET_ID" );


CREATE INDEX "IDX_CNCHG_CNCHGDET_FK" ON "CHANGEDETAIL" ( "CONTENTNODECHANGE_ID" );
