--
-- Content Types
--

-- synonyms
DROP SYNONYM "CMS_CONTENTTYPE";
DROP SYNONYM "CMS_ATTRIBUTEDEFINITION" ;
DROP SYNONYM "CMS_RELATIONSHIPDEFINITION";
DROP SYNONYM "CMS_RELATIONSHIPDESTINATION";
DROP SYNONYM "CMS_LOOKUP";
DROP SYNONYM "CMS_LOOKUPTYPE";

-- tables
DROP TABLE "LOOKUP";
DROP TABLE "RELATIONSHIPDESTINATION";
DROP TABLE "RELATIONSHIPDEFINITION";
DROP TABLE "ATTRIBUTEDEFINITION" ;
DROP TABLE "LOOKUPTYPE";
DROP TABLE "CONTENTTYPE";
