DROP VIEW "NAVTREE";

DROP SYNONYM "CMS_SYSTEM_SEQ";
DROP SYNONYM "CMS_CONTENTNODE";
DROP SYNONYM "CMS_ATTRIBUTE";
DROP SYNONYM "CMS_RELATIONSHIP";
DROP SYNONYM "CMS_MEDIA";
DROP SYNONYM "CMS_NAVTREE";

DROP SEQUENCE "SYSTEM_SEQ";

DROP TABLE "MEDIA";

DROP TABLE "RELATIONSHIP";
DROP TABLE "ATTRIBUTE";
DROP TABLE "CONTENTNODE";
