-- synonyms
DROP SYNONYM "CMS_PUBLISH_SEQ";

DROP SYNONYM "CMS_CHANGESET";
DROP SYNONYM "CMS_CONTENTNODECHANGE";
DROP SYNONYM "CMS_CHANGEDETAIL";

DROP SYNONYM "CMS_PUBLISH";
DROP SYNONYM "CMS_PUBLISHMESSAGES" ;

-- sequences
DROP SEQUENCE "PUBLISH_SEQ";

-- tables and indices

DROP TABLE CHANGEDETAIL;
DROP TABLE CONTENTNODECHANGE;
DROP TABLE CHANGESET;

DROP TABLE PUBLISHMESSAGES;
DROP TABLE PUBLISH;
DROP TABLE PUBLISHX;
