
DROP INDEX "IDX_CTYPE_ATTRDEF_FK";

DROP INDEX "IDX_CTYPE_RELDEF_FK";
DROP INDEX "IDX_RELDEFN_NAME";
DROP INDEX "IDX_RELDEFN_NAVIGABLE";

DROP INDEX "IDX_CTYPE_RELDEST_FK";
DROP INDEX "IDX_RSHIPDEF_RSHIPDEST_FK";

DROP INDEX "IDX_LKTYPE_LOOKUP_FK";

DROP INDEX "IDX_ATTRIBUTE_DEF_CNTTYPE";
DROP INDEX "IDX_ATTRIBUTE_DEF_NAME";
DROP INDEX "IDX_CNODE_ATTR_FK";

DROP INDEX "IDX_CNODE_RSHIPCHILD_FK";
DROP INDEX "IDX_CNODE_RSHIPPARENT_FK";
DROP INDEX "IDX_RELATIONSHIP_DEF_CNTTYPE";
DROP INDEX "IDX_RELATIONSHIP_DEF_NAME";

DROP INDEX "IDX_CSET_CNODECHG_FK";

DROP INDEX "IDX_CNCHG_CNCHGDET_FK";
