import java.util.ArrayList;
import java.util.Date;
import com.freshdirect.analytics.*;
import com.freshdirect.framework.util.DateUtil;

global java.util.List RollEventList
global java.util.List BounceEventList


rule "bounce1"
salience 1
no-loop
when
        event : SessionEvent(eval( soldCount >= 1 && (orderId == null || orderId == "")) )
    not OrderEvent(customerId == event.customerId)
    not BounceEvent(customerId == event.customerId)
then
        BounceEvent bounce = new BounceEvent(event.getCustomerId(),"NEW", new Date(), event.getCutOff(),event.getZone(),
        event.getLastTimeslot(), event.getPageType(), DateUtil.addDays(DateUtil.truncate(event.getCutOff()), 1) , event.getSector());
        insert(bounce);
        BounceEventList.add(bounce);
end

rule "roll1"
salience 2
no-loop
when
        event : SessionEvent(eval( (availCount + soldCount) > 0 && orderId != null ))
    order : OrderEvent(customerId == event.customerId && orderId == event.orderId && eval(DateUtil.getDiffInDaysFloor(order.getDeliveryDate(), event.getCutOff())==1) )
    not RollEvent(customerId == event.customerId)
then
        RollEvent roll  = new RollEvent(event.getCustomerId(), new Date(), new Float(event.getSoldCount()*100/(event.getSoldCount()+event.getAvailCount())),
        event.getZone(), event.getCutOff(), event.getLastTimeslot(),DateUtil.addDays(DateUtil.truncate(event.getCutOff()), 1) ,event.getSector());
        insert(roll);
        RollEventList.add(roll);
end

rule "bounce2"
salience 1
no-loop
when
        event : SessionEvent(eval( (availCount + soldCount) == 0  ))
then
        System.err.println("No timeslots viewed by the customer for the next day "+event.getCustomerId());
end
