alter table TRANSP.PLAN add 
( 
  IS_OPEN VARCHAR2(1 BYTE) 
); 


CREATE TABLE TRANSP.DISPATCH_REASON_CODE 
( 
  CODE VARCHAR2(7) NOT NULL primary key, 
  REASON VARCHAR2(50) NOT NULL unique, 
  ACTIVE CHAR(1) 
); 
GRANT DELETE, INSERT, SELECT, UPDATE ON DISPATCH_REASON_CODE TO FDTRN_PRDA; 

alter table TRANSP.DISAPTCH add 
( 
  ISOVERRIDE CHAR(1 BYTE), 
  OVERRIDE_REASON_ID VARCHAR2(5 BYTE), 
  OVERRIDE_USER VARCHAR2(20 BYTE) 
); 

CREATE SEQUENCE TRANSP.DISPATCHREASONSEQ 
  START WITH 1 
  MAXVALUE 10000 
  MINVALUE 1 
  NOCYCLE 
  NOCACHE 
  NOORDER; 


GRANT ALTER, SELECT ON TRANSP.DISPATCHREASONSEQ TO FDTRN_PRDA; 

create public database link "UPS.NYC.FRESHDIRECT.COM" 
connect to READONLY 
identified by "readonly" 
using 'DATAWPRO'; 

-- if DATAWPRO is not found in TNS then here are the config info 
/* DATAWPRO = 
  (DESCRIPTION = 

     (ADDRESS =(PROTOCOL = TCP)(HOST = nyc1fddw01.nyc1.freshdirect.com)(PORT = 1521)) 

  (CONNECT_DATA = 

      (SERVER = DEDICATED) 

      (SERVICE_NAME = DATAWPRO) 

  ) 
) */

--create a view 
CREATE OR REPLACE VIEW TRANSP.UPSROUTE_INFO 
(ROUTE_KEY, ROUTE_DATE, ROUTE_NUMBER, UPS_START_TIME, UPS_COMPLETE_TIME, 
 LAST_STOP_COMPLETED) 
AS 
SELECT "ROUTE_KEY","ROUTE_DATE","ROUTE_NUMBER","UPS_START_TIME","UPS_COMPLETE_TIME","LAST_STOP_COMPLETED" 
FROM FD_DW.ROUTE_DIM@UPS.NYC.FRESHDIRECT.COM 
/ 

GRANT SELECT ON TRANSP.UPSROUTE_INFO TO FDTRN_PRDA; 
