GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDISPATCH TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDISPATCH TO fdtrn_stprd01;
GRANT SELECT ON TRANSP.HANDOFF_BATCHDISPATCH TO APPDEV;