INSERT INTO cms.lookuptype (CODE,NAME,DESCRIPTION) VALUES ('Category.GROCERY_DEFAULT_SORT','Category.GROCERY_DEFAULT_SORT',NULL);

INSERT INTO cms.lookup (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) VALUES ('Category.GROCERY_DEFAULT_SORT','name','Sort by Name','Sort by Name',1);
INSERT INTO cms.lookup (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) VALUES ('Category.GROCERY_DEFAULT_SORT','price','Sort by Price','Sort by Price',2);
INSERT INTO cms.lookup (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) VALUES ('Category.GROCERY_DEFAULT_SORT','popularity','Sort by Popularity','Sort by Popularity',3);
INSERT INTO cms.lookup (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) VALUES ('Category.GROCERY_DEFAULT_SORT','sale','Sort by Sale','Sort by Sale',4);

INSERT INTO cms.attributedefinition (NAME,ID,CONTENTTYPE_ID,ATTRIBUTETYPE_CODE,INHERITABLE,REQUIRED,LABEL,CARDINALITY_CODE,LOOKUP_CODE) VALUES ('GROCERY_DEFAULT_SORT','Category.GROCERY_DEFAULT_SORT','Category','S','T','F','Default sorting for grocery','One','Category.GROCERY_DEFAULT_SORT');

