-- 439 rows inserted

Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('ASQ-010', 'Fraud Review', 'ASQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('CAQ-015', 'Add Chefs Table Status', 'CAQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-040', 'Damaged Box/Bag', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-041', 'Early Deliv: Respond to Drv Call', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-042', 'ETA 1st Attempt (Drv reachable)', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-043', 'ETA 2nd/3rd Attempt (Drv reachable)', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-044', 'ETA Route Done for Day', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-045', 'Driver Unreachable:Missing Box', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-046', 'Driver Unreachable:Spec Instruct', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-047', 'Driver Unreachable:Other', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-048', 'Late Box - Customer Called', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-049', 'Missing Box/Bag', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-050', 'Not Home- Driver Called Customer', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-051', 'Not Home- Ops Called Customer', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-052', 'Driver Unreachable: ETA', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-053', 'Late Box - Reunited w/ Truck', 'DSQ', 'MD');
Insert into CUST.CASE_SUBJECT   (CODE, NAME, CASE_QUEUE, CASE_PRIORITY) Values   ('DSQ-054', 'COS - COI', 'DSQ', 'MD');

Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'TRNSP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'TRNSP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'TRNSP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'SEC', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'NEW', 'OPEN', 'SYS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'SEC', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'CLSD', 'CLSD', 'SEC', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'OPEN', 'SCS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('ASQ-010', 'OPEN', 'CLSD', 'SCS', 'CLOSE');
   

Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'TRNSP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'TRNSP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'TRNSP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'TRNSP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'TRNSP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'SEC', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'NEW', 'OPEN', 'SYS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SEC', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'DEV', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'MOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'COS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'TRN', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'FIN', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'NCS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'CSR', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SCS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'OPEN', 'SEC', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'DEV', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'MOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'COS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'TRN', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'FIN', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'NCS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'CSR', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'SCS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'OPEN', 'CLSD', 'SEC', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'DEV', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'MOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'COS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'TRN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'FIN', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'NCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'CSR', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'SCS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('CAQ-015', 'CLSD', 'CLSD', 'SEC', 'NOTE');
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-040', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-041', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-042', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-043', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-044', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-045', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-046', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-047', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-048', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-049', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-050', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-051', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-052', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-053', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
   
   
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'NEW', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'NEW', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'NEW', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'NEW', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'SOP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'ADM', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'SUP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'OPS', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'OPEN', 'SOP', 'CAS_EDT');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'CLSD', 'ADM', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'CLSD', 'SUP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'CLSD', 'OPS', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'OPEN', 'CLSD', 'SOP', 'CLOSE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'CLSD', 'CLSD', 'ADM', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'CLSD', 'CLSD', 'SUP', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'CLSD', 'CLSD', 'OPS', 'NOTE');
Insert into CUST.CASE_OPERATION
   (CASE_SUBJECT, START_CASE_STATE, END_CASE_STATE, ROLE, CASEACTION_TYPE)
 Values
   ('DSQ-054', 'CLSD', 'CLSD', 'SOP', 'NOTE');
   
/*18 rows updated*/

update cust.case_subject set obsolete='X' where code 
in ('DSQ-001','DSQ-003','DSQ-005','DSQ-006','DSQ-009','DSQ-018','DSQ-019','DSQ-020','DSQ-021','DSQ-022','DSQ-025','DSQ-026','DSQ-027','DSQ-028','DSQ-033','DSQ-034','DSQ-035','DSQ-039');


