GRANT DELETE ON "NUTRITION_PANEL" TO "fdstore_ststg01";
GRANT INSERT ON "NUTRITION_PANEL" TO "fdstore_ststg01";
GRANT SELECT ON "NUTRITION_PANEL" TO "fdstore_ststg01";
GRANT UPDATE ON "NUTRITION_PANEL" TO "fdstore_ststg01";

GRANT DELETE ON "NUTRITION_SECTION" TO "fdstore_ststg01";
GRANT INSERT ON "NUTRITION_SECTION" TO "fdstore_ststg01";
GRANT SELECT ON "NUTRITION_SECTION" TO "fdstore_ststg01";
GRANT UPDATE ON "NUTRITION_SECTION" TO "fdstore_ststg01";

 
GRANT DELETE ON "NUTRITION_ITEM" TO "fdstore_ststg01";
GRANT INSERT ON "NUTRITION_ITEM" TO "fdstore_ststg01";
GRANT SELECT ON "NUTRITION_ITEM" TO "fdstore_ststg01";
GRANT UPDATE ON "NUTRITION_ITEM" TO "fdstore_ststg01";

GRANT SELECT ON "NUTRITION_PANEL" TO "appdev"; 
GRANT SELECT ON "NUTRITION_SECTION" TO "appdev";
GRANT SELECT ON "NUTRITION_ITEM" TO "appdev";