GRANT DELETE ON "MIS"."BV_PRODUCT_REVIEWS" TO fdstore_stprd01;
GRANT INSERT ON "MIS"."BV_PRODUCT_REVIEWS" TO fdstore_stprd01;
GRANT UPDATE ON "MIS"."BV_PRODUCT_REVIEWS" TO fdstore_stprd01;
GRANT SELECT ON "MIS"."BV_PRODUCT_REVIEWS" TO fdstore_stprd01;

GRANT SELECT ON "MIS"."BV_PRODUCT_REVIEWS" TO appdev;