CREATE TABLE MIS.BV_PRODUCT_RATINGS (
    "ID"                                      VARCHAR2(16 BYTE),
    "PRODUCT_ID"                              VARCHAR2(64 BYTE) NOT NULL,
    "PRODUCT_PAGE_URL"                        VARCHAR2(512 BYTE),
    "PRODUCT_REVIEWS_URL"                     VARCHAR2(512 BYTE),
    "IMAGE_URL"                               VARCHAR2(512 BYTE),
    "NUM_NATIVE_QUESTIONS"                    NUMBER(8,0),
    "NUM_QUESTIONS"                           NUMBER(8,0),    
    "NUM_NATIVE_ANSWERS"                      NUMBER(8,0),    
    "NUM_ANSWERS"                             NUMBER(8,0),    
    "NUM_REVIEWS"                             NUMBER(8,0),    
    "NUM_STORIES"                             NUMBER(8,0),    
    "AVERAGE_OVERALL_RATING"                  NUMBER(8,2),
    "OVERALL_RATING_RANGE"                    NUMBER(8,0),
    "TOTAL_REVIEW_COUNT"                      NUMBER(8,0),
    "RATINGS_ONLY_REVIEW_COUNT"               NUMBER(8,2),
    "RECOMMENDED_COUNT"                       NUMBER(8,0),
    "NOT_RECOMMENDED_COUNT"                   NUMBER(8,0),
    "AVERAGE_RATING_QUALITY"                  NUMBER(8,2),
    "AVERAGE_RATING_QUALITY_RANGE"            NUMBER(8,0),
    "AVERAGE_RATING_VALUE"                    NUMBER(8,2),
    "AVERAGE_RATING_VALUE_RANGE"              NUMBER(8,0),
    "RATING_VALUE"                            NUMBER(8,0),
    "COUNT"                                   NUMBER(8,0),
    "NAT_AVERAGE_OVERALL_RATING"              NUMBER(8,2),
    "NAT_OVERALL_RATING_RANGE"                NUMBER(8,0),
    "NAT_TOTAL_REVIEW_COUNT"                  NUMBER(8,0),
    "NAT_RATINGS_ONLY_REVIEW_COUNT"           NUMBER(8,2),
    "NAT_RECOMMENDED_COUNT"                   NUMBER(8,0),
    "NAT_NOT_RECOMMENDED_COUNT"               NUMBER(8,0),
    "NAT_AVERAGE_RATING_QUALITY"              NUMBER(8,2),
    "NAT_AVERAGE_RATING_QUALITY_R"            NUMBER(8,0),
    "NAT_AVERAGE_RATING_VALUE"                NUMBER(8,2),
    "NAT_AVERAGE_RATING_VALUE_RANGE"          NUMBER(8,0),
    "NAT_RATING_VALUE"                        NUMBER(8,0),
    "NAT_COUNT"                               NUMBER(8,0),
    "EXTRACT_DATE"                            TIMESTAMP,
    CONSTRAINT "UK_PRODUCT_ID" UNIQUE ("PRODUCT_ID"),
    PRIMARY KEY ("ID"));

CREATE TABLE MIS.BV_PRODUCT_REVIEWS(
    "ID"                            VARCHAR2(16 BYTE),
    "PRODUCT_ID"                    VARCHAR2(64 BYTE),
    "BV_REVIEW_ID"                  VARCHAR2(64 BYTE),
    "MODERATION_STATUS"             VARCHAR2(64 BYTE),
    "LAST_MODIFICATION_TIME"        TIMESTAMP,
    "EXTERNAL_ID"                   VARCHAR2(64 BYTE),
    "DISPLAY_NAME"                  VARCHAR2(64 BYTE),
    "ANONYMUS"                      VARCHAR2(8 BYTE),
    "HYPERLINKING_ENABLED"          VARCHAR2(8 BYTE),
    "RATINGS_ONLY"                  VARCHAR2(8 BYTE),
    "TITLE"                         VARCHAR2(256 BYTE),
    "REVIEW_TEXT"                   VARCHAR2(4000 BYTE),
    "NUM_COMMENTS"                  NUMBER(8,0),
    "CAMPAIGN_ID"                   VARCHAR2(32 BYTE),
    "RATING"                        NUMBER(8,2),
    "RATING_RANGE"                  NUMBER(8,0),
    "RECOMMENDED"                   VARCHAR2(8 BYTE),
    "NUM_FEEDBACKS"                 NUMBER(8,0),
    "NUM_POSITIVE_FEEDBACKS"        NUMBER(8,0),
    "NUM_NEGATIVE_FEEDBACKS"        NUMBER(8,0),
    "REVIEWER_LOCATION"             VARCHAR2(128 BYTE),
    "IP_ADDRESS"                    VARCHAR2(32 BYTE),
    "DISPLAY_LOCALE"                VARCHAR2(32 BYTE),
    "SUBMISSION_TIME"               TIMESTAMP,
    "BADGE_NAME"                    VARCHAR2(128 BYTE),
    "BADGE_CONTENT_TYPE"            VARCHAR2(128 BYTE),
    "PRODUCT_REVIEWS_URL"           VARCHAR2(512 BYTE),
    "PRODUCT_REVIEWS_DL_URL"        VARCHAR2(512 BYTE),
    "FEATURED"                      VARCHAR2(8 BYTE),
    "NET_PROMOTER_SCORE"            NUMBER(8,2),
    "NET_PROMOTER_COMMENT"          VARCHAR2(4000 BYTE),
    "AUTHENTICATION_TYPE"           VARCHAR2(32 BYTE),
    "USER_EMAIL_ADDRESS"            VARCHAR2(128 BYTE),
    "PUBLISHED_EMAIL_ALERT"         VARCHAR2(8 BYTE),
    "COMMENTED_EMAIL_ALERT"         VARCHAR2(8 BYTE),
    "ORIGINATING_DISPLAY_CODE"      NUMBER(8,0),
    "CONTENT_CODES"                 VARCHAR2(32 BYTE),
    "FIRST_PUBLISH_TIME"            TIMESTAMP,
    "LAST_PUBLISH_TIME"             TIMESTAMP,
    CONSTRAINT "FK_PRODUCT_ID"
    FOREIGN KEY ("PRODUCT_ID")
    REFERENCES "MIS"."BV_PRODUCT_RATINGS" ("PRODUCT_ID"),
    PRIMARY KEY ("ID"));