----------------------------------------------------------
--	Create tables, constraints and indices		--
--	for new generic nutrition panels		--
-- 	with support for multiple panel type		--
----------------------------------------------------------

CREATE TABLE "ERPS"."NUTRITION_PANEL" (
	"ID"			VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"SKU_CODE"		VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"TYPE" 			VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"DATE_MODIFIED" 	DATE, 

	 CONSTRAINT "NUTRITION_PANEL_PK" PRIMARY KEY ("ID")
 );
CREATE UNIQUE INDEX NUTRITION_PANEL_SKU_IDX ON NUTRITION_PANEL (SKU_CODE);
CREATE INDEX NUTRITION_PANEL_DATE_IDX ON NUTRITION_PANEL (DATE_MODIFIED);



CREATE TABLE "ERPS"."NUTRITION_SECTION" (
	"ID" 		VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"PANEL_ID" 	VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"TITLE" 	VARCHAR2(500 CHAR), 
	"TYPE" 		VARCHAR2(64 BYTE) NOT NULL ENABLE, 
	"POSITION" 	NUMBER(5,0), 
	"IMPORTANCE" 	NUMBER(5,0), 

	CONSTRAINT "NUTRITION_SECTION_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "NUTRITION_SECTION_FK1" FOREIGN KEY ("PANEL_ID") REFERENCES "ERPS"."NUTRITION_PANEL" ("ID") ON DELETE CASCADE
);
CREATE INDEX NUTRITION_SECTION_FK_IDX ON NUTRITION_SECTION (PANEL_ID);



CREATE TABLE "ERPS"."NUTRITION_ITEM" (
	"ID" 				VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"SECTION_ID" 			VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"VALUE1" 			VARCHAR2(2000 CHAR),
	"VALUE2" 			VARCHAR2(2000 CHAR), 
	"INGREDIENT_VALUE" 		NUMBER(10,2), 
	"UOM" 				VARCHAR2(200 CHAR), 
	"POSITION" 			NUMBER(5,0), 
	"FLAGS" 			VARCHAR2(64 CHAR), 

	CONSTRAINT "NUTRITION_ITEM_PK" PRIMARY KEY ("ID"),
	CONSTRAINT "NUTRITION_ITEM_FK1" FOREIGN KEY ("SECTION_ID") REFERENCES "ERPS"."NUTRITION_SECTION" ("ID") ON DELETE CASCADE
);
CREATE INDEX NUTRITION_ITEM_FK_IDX ON NUTRITION_ITEM (SECTION_ID);




-----------------------------
--	Set Privileges	   --
--	on new tables	   --
-----------------------------

GRANT DELETE ON "NUTRITION_PANEL" TO "FDSTORE_PRDA";
GRANT INSERT ON "NUTRITION_PANEL" TO "FDSTORE_PRDA";
GRANT SELECT ON "NUTRITION_PANEL" TO "FDSTORE_PRDA";
GRANT UPDATE ON "NUTRITION_PANEL" TO "FDSTORE_PRDA";
 
GRANT DELETE ON "NUTRITION_PANEL" TO "FDSTORE_PRDB";
GRANT INSERT ON "NUTRITION_PANEL" TO "FDSTORE_PRDB";
GRANT SELECT ON "NUTRITION_PANEL" TO "FDSTORE_PRDB";
GRANT UPDATE ON "NUTRITION_PANEL" TO "FDSTORE_PRDB";
 
GRANT DELETE ON "NUTRITION_PANEL" TO "FDSTORE_STPRD01";
GRANT INSERT ON "NUTRITION_PANEL" TO "FDSTORE_STPRD01";
GRANT SELECT ON "NUTRITION_PANEL" TO "FDSTORE_STPRD01";
GRANT UPDATE ON "NUTRITION_PANEL" TO "FDSTORE_STPRD01";


GRANT DELETE ON "NUTRITION_SECTION" TO "FDSTORE_PRDA";
GRANT INSERT ON "NUTRITION_SECTION" TO "FDSTORE_PRDA";
GRANT SELECT ON "NUTRITION_SECTION" TO "FDSTORE_PRDA";
GRANT UPDATE ON "NUTRITION_SECTION" TO "FDSTORE_PRDA";
 
GRANT DELETE ON "NUTRITION_SECTION" TO "FDSTORE_PRDB";
GRANT INSERT ON "NUTRITION_SECTION" TO "FDSTORE_PRDB";
GRANT SELECT ON "NUTRITION_SECTION" TO "FDSTORE_PRDB";
GRANT UPDATE ON "NUTRITION_SECTION" TO "FDSTORE_PRDB";
 
GRANT DELETE ON "NUTRITION_SECTION" TO "FDSTORE_STPRD01";
GRANT INSERT ON "NUTRITION_SECTION" TO "FDSTORE_STPRD01";
GRANT SELECT ON "NUTRITION_SECTION" TO "FDSTORE_STPRD01";
GRANT UPDATE ON "NUTRITION_SECTION" TO "FDSTORE_STPRD01";


GRANT DELETE ON "NUTRITION_ITEM" TO "FDSTORE_PRDA";
GRANT INSERT ON "NUTRITION_ITEM" TO "FDSTORE_PRDA";
GRANT SELECT ON "NUTRITION_ITEM" TO "FDSTORE_PRDA";
GRANT UPDATE ON "NUTRITION_ITEM" TO "FDSTORE_PRDA";
 
GRANT DELETE ON "NUTRITION_ITEM" TO "FDSTORE_PRDB";
GRANT INSERT ON "NUTRITION_ITEM" TO "FDSTORE_PRDB";
GRANT SELECT ON "NUTRITION_ITEM" TO "FDSTORE_PRDB";
GRANT UPDATE ON "NUTRITION_ITEM" TO "FDSTORE_PRDB";
 
GRANT DELETE ON "NUTRITION_ITEM" TO "FDSTORE_STPRD01";
GRANT INSERT ON "NUTRITION_ITEM" TO "FDSTORE_STPRD01";
GRANT SELECT ON "NUTRITION_ITEM" TO "FDSTORE_STPRD01";
GRANT UPDATE ON "NUTRITION_ITEM" TO "FDSTORE_STPRD01";
 


--------------------------------------------------
--		Migrate data			--
--------------------------------------------------
-- Data will be moved to new generic tables,	--
-- old drug-specific tables are kept to allow 	--
-- full rollback. They will be dropped in a 	--
-- later release.				--
--------------------------------------------------

INSERT INTO "ERPS"."NUTRITION_PANEL" 
	(ID, SKU_CODE, TYPE, DATE_MODIFIED)
SELECT 
	ID, SKU_CODE, 'DRUG' as TYPE, DATE_MODIFIED 
FROM "ERPS"."DRUG_PANEL"


INSERT INTO "ERPS"."NUTRITION_SECTION" 
	(ID, PANEL_ID, TITLE, TYPE, POSITION, IMPORTANCE)
SELECT 
	ID, PANEL_ID, TITLE, UPPER(TYPE), POSITION, IMPORTANCE
FROM "ERPS"."DRUG_NUTRITION_SECTION"


INSERT INTO "ERPS"."NUTRITION_ITEM" 
	(ID, SECTION_ID, VALUE1, VALUE2, INGREDIENT_VALUE, UOM, POSITION, FLAGS)
SELECT 
	ID, SECTION_ID, VALUE1, VALUE2, INGREDIENT_VALUE, UOM, POSITION,
	(NVL2(BULLETED, 'B', '') || NVL2(IMPORTANT, 'I', '') || NVL2(NEWLINE, 'N', '') || NVL2(SEPARATOR, 'S', '')) as FLAGS 
FROM "ERPS"."DRUG_NUTRITION_ITEM"






----------------------------------
--	     rollback		--
----------------------------------
-- simply drops the new tables.	--
----------------------------------
-- NOTE: This is an optional step, 
-- as the old code does not use the new tables 
-- and the new code does not use the old tables.

-- If you drop the tables any new data created with the new code 
-- since this script had been run will be lost.
-- If you do not drop the tables new data is kept, 
-- but not used by the old code.


--drop table "ERPS"."NUTRITION_ITEM";
--drop table "ERPS"."NUTRITION_SECTION";
--drop table "ERPS"."NUTRITION_PANEL";


