
Insert into LOOKUP (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) values ('Category.PRODUCT_PROMOTION_TYPE','E_COUPONS','E-Coupons','E-Coupons',3);
Insert into LOOKUP (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) values ('Product.LAYOUT','201','E-Coupons','E-Coupons',201);


