DROP SEQUENCE CUST.COUPON_SEQ;

DROP TABLE CUST.FDCOUPON_HISTORY CASCADE CONSTRAINTS;

DROP TABLE CUST.FDCOUPON CASCADE CONSTRAINTS;

DROP TABLE CUST.COUPONLINE CASCADE CONSTRAINTS;

DROP TABLE CUST.FDCOUPON_REWARD_UPC CASCADE CONSTRAINTS;

DROP TABLE CUST.FDCOUPON_REQ_UPC CASCADE CONSTRAINTS;

DROP TABLE CUST.COUPON_TRANS CASCADE CONSTRAINTS;

DROP TABLE CUST.COUPON_TRANS_DETAILS CASCADE CONSTRAINTS;

DROP TABLE MIS.COUPON_ACTIVITY_LOG CASCADE CONSTRAINTS;

DROP SEQUENCE MIS.COUPON_LOG_SEQUENCE;