CREATE TABLE DLV.DELIVERY_GROUP (ID  VARCHAR2(16 BYTE)  PRIMARY KEY,  GROUP_NAME   VARCHAR2(255 BYTE)      NOT NULL);

GRANT ALL ON DLV.DELIVERY_GROUP TO fdtrn_ststg01;
GRANT READ ON DLV.DELIVERY_GROUP TO appdev;

CREATE SEQUENCE DLV.DELIVERY_GROUP_SEQ
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 200
  NOORDER;

GRANT ALL ON DLV.DELIVERY_GROUP_SEQ TO fdtrn_ststg01;
GRANT READ ON DLV.DELIVERY_GROUP_SEQ TO appdev;

CREATE SEQUENCE DLV.BUILDING_GROUP_SEQ
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 200
  NOORDER;

GRANT ALL ON DLV.BUILDING_GROUP_SEQ TO fdtrn_ststg01;
GRANT READ ON DLV.BUILDING_GROUP_SEQ TO appdev;

CREATE TABLE DLV.BUILDING_GROUP
(
   BUILDING_ID     VARCHAR2(8 BYTE)      NOT NULL,
   GROUP_ID   VARCHAR2(16 BYTE)      NOT NULL,
   CONSTRAINT FK_GROUPID
   FOREIGN KEY (group_id)  REFERENCES DLV.DELIVERY_GROUP(id)
   ON DELETE CASCADE;
);

GRANT ALL ON DLV.BUILDING_GROUP_SEQ TO fdtrn_ststg01;
GRANT READ ON DLV.BUILDING_GROUP_SEQ TO appdev;

