GRANT DELETE, INSERT, SELECT, UPDATE ON ERPS.GRP_HISTORY TO fdstore_stprd01;

GRANT SELECT ON ERPS.GRP_HISTORY TO APPDEV;

GRANT ALTER, SELECT ON ERPS.GRPBATCH_SEQ TO fdstore_stprd01; 

GRANT SELECT ON ERPS.GRPBATCH_SEQ TO APPDEV; 

GRANT DELETE, INSERT, SELECT, UPDATE ON ERPS.GRP_SCALE_MASTER TO fdstore_stprd01;

GRANT SELECT ON ERPS.GRP_SCALE_MASTER TO APPDEV;
 
GRANT DELETE, INSERT, SELECT, UPDATE ON  ERPS.GRP_PRICING TO fdstore_stprd01;

GRANT SELECT ON  ERPS.GRP_PRICING TO APPDEV;
 
GRANT DELETE, INSERT, SELECT, UPDATE ON  ERPS.MATERIAL_GRP TO fdstore_stprd01;

GRANT SELECT ON  ERPS.MATERIAL_GRP TO APPDEV;


