Insert into LOOKUPTYPE (CODE,NAME,DESCRIPTION) values ('Category.PRODUCT_PROMOTION_TYPE','Category.PRODUCT_PROMOTION_TYPE',null);

Insert into LOOKUP (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) values ('Category.PRODUCT_PROMOTION_TYPE','NONE','None','None',1);
Insert into LOOKUP (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) values ('Category.PRODUCT_PROMOTION_TYPE','PRESIDENTS_PICKS','President''s Picks','President''s Picks',2);


Insert into ATTRIBUTEDEFINITION (NAME,ID,CONTENTTYPE_ID,ATTRIBUTETYPE_CODE,INHERITABLE,REQUIRED,LABEL,CARDINALITY_CODE,LOOKUP_CODE) values ('PRODUCT_PROMOTION_TYPE','Category.PRODUCT_PROMOTION_TYPE','Category','S','F','F','Product Promotion Type','One','Category.PRODUCT_PROMOTION_TYPE');



Insert into LOOKUP (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) values ('Product.LAYOUT','200','President''s Picks','President''s Picks',200);


