CREATE TABLE ERPS.PRODUCT_PROMOTION_HISTORY
(
  VERSION  NUMBER(10)                           NOT NULL,
  DATE_CREATED        DATE,
  STATUS VARCHAR2(10 BYTE) 
);

ALTER TABLE ERPS.PRODUCT_PROMOTION_HISTORY ADD (
  CONSTRAINT PK_PRODUCT_PROMOTION_HISTORY
 PRIMARY KEY
 (VERSION));

GRANT ALTER, SELECT, INSERT, DELETE, UPDATE ON ERPS.PRODUCT_PROMOTION_HISTORY TO FDSTORE_PRDA;

CREATE TABLE ERPS.PRODUCT_PROMOTION
(
 ID              VARCHAR2(16 BYTE)             NOT NULL,
  VERSION  NUMBER(10)                           NOT NULL,
  ERP_PP_ID VARCHAR2(16 BYTE)             NOT NULL,
  TYPE            VARCHAR2(30 BYTE)             NOT NULL,
  START_DATE        DATE,
  END_DATE DATE 
);

ALTER TABLE ERPS.PRODUCT_PROMOTION ADD (
  CONSTRAINT PK_PRODUCT_PROMOTION
 PRIMARY KEY
 (ID));
 
 ALTER TABLE ERPS.PRODUCT_PROMOTION ADD (
  CONSTRAINT PRODUCT_PROMOTION_FK 
 FOREIGN KEY (VERSION) 
 REFERENCES ERPS.PRODUCT_PROMOTION_HISTORY (VERSION));
 
 GRANT ALTER, SELECT,INSERT, DELETE, UPDATE ON ERPS.PRODUCT_PROMOTION TO FDSTORE_PRDA;

 CREATE TABLE ERPS.PRODUCT_PROMOTION_GROUP
(
 ID              VARCHAR2(16 BYTE)             NOT NULL,
  ZONE_ID   VARCHAR2(16 BYTE),
  MAT_NUM VARCHAR2(18 BYTE)          NOT NULL,
  SKU_CODE VARCHAR2(18 BYTE)      NOT NULL,
  PRIORITY  VARCHAR2(5 BYTE)    ,
  ERP_DEPT VARCHAR2(16 BYTE)  ,
  FEATURED  CHAR(1 BYTE),
  FEATURED_HEADER VARCHAR2(30 BYTE),
  TYPE            VARCHAR2(30 BYTE)             NOT NULL,
  VERSION  NUMBER(10)                           NOT NULL
);

ALTER TABLE ERPS.PRODUCT_PROMOTION_GROUP ADD (
  CONSTRAINT PK_PRODUCT_PROMOTION_GROUP
 PRIMARY KEY
 (ID));
 
 ALTER TABLE ERPS.PRODUCT_PROMOTION_GROUP ADD (
  CONSTRAINT PRODUCT_PROMOTION_GROUP_FK 
 FOREIGN KEY (VERSION) 
 REFERENCES ERPS.PRODUCT_PROMOTION_HISTORY (VERSION));

CREATE INDEX VERSION_IDX
   ON ERPS.PRODUCT_PROMOTION_GROUP (VERSION);

 GRANT ALTER, SELECT, INSERT, DELETE, UPDATE ON ERPS.PRODUCT_PROMOTION_GROUP TO FDSTORE_PRDA;

 CREATE SEQUENCE ERPS.PRODUCTPROMO_BATCH_SEQ
  START WITH 10000
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


GRANT ALTER, SELECT ON ERPS.PRODUCTPROMO_BATCH_SEQ TO FDSTORE_PRDA;

CREATE TABLE ERPS.PRODUCT_PROMOTION_FEAT_HEADER
(
  CODE VARCHAR2(3 BYTE) NOT NULL,
  NAME  VARCHAR2(30 BYTE) NOT NULL,  
  DESCRIPTION  VARCHAR2(30 BYTE) NOT NULL
);

GRANT ALTER, SELECT ON ERPS.PRODUCT_PROMOTION_FEAT_HEADER TO FDSTORE_PRDA;



 Insert into CUST.PROFILE_ATTR_NAME
   (NAME, DESCRIPTION, CATEGORY, IS_EDITABLE)
 Values
   ('DDPP_ELIGIBLE', 'DDPP_ELIGIBLE', 'General', 'X');