CREATE TABLE TRANSP.DISPATCH_GROUP
(
  ID           VARCHAR2(16 BYTE)        NOT NULL,
  NAME         VARCHAR2(32 BYTE)        NOT NULL, 
  DISPATCH_GROUPTIME  DATE   DEFAULT TO_DATE( '01/01/1970 05:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM') NOT NULL
);

ALTER TABLE TRANSP.DISPATCH_GROUP ADD ( CONSTRAINT PK_DISPATCH_GROUP PRIMARY KEY (ID),  UNIQUE (NAME));

CREATE SEQUENCE TRANSP.DISPATCHGROUPSEQ
  START WITH 1
  MAXVALUE 10000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

ALTER TABLE TRANSP.ZONE ADD (PRETRIP_TIME INTEGER, POSTTRIP_TIME INTEGER);

ALTER TABLE TRANSP.SCRIB_BID ADD (DISPATCH_GROUPTIME DATE);

ALTER TABLE TRANSP.SCRIB_BID DROP column DEPOT_ZONE;

ALTER TABLE TRANSP.SCRIB ADD (DISPATCH_GROUPTIME DATE, TRUCK_DISPATCHTIME DATE, TRUCK_ENDTIME DATE, ZONE_CODE VARCHAR2(5 BYTE));

ALTER TABLE TRANSP.PLAN ADD (DISPATCH_GROUPTIME DATE, TRUCK_DISPATCHTIME DATE, TRUCK_ENDTIME DATE);
ALTER TABLE TRANSP.PLAN MODIFY (START_TIME NULL);
ALTER TABLE TRANSP.PLAN MODIFY (FIRST_DLV_TIME NULL);

ALTER TABLE TRANSP.WAVE_INSTANCE ADD (TRUCK_DISPATCHTIME DATE, TRUCK_ENDTIME DATE, MAX_TIME DATE);
ALTER TABLE TRANSP.WAVE_INSTANCE MODIFY (DISPATCH_TIME NULL);
ALTER TABLE TRANSP.WAVE_INSTANCE MODIFY (FIRST_DLV_TIME NULL);
ALTER TABLE TRANSP.WAVE_INSTANCE MODIFY (LAST_DLV_TIME NULL);
ALTER TABLE TRANSP.WAVE_INSTANCE DROP CONSTRAINT WAVEINSTANCE_UK;
DROP INDEX TRANSP.WAVEINSTANCE_UK;

ALTER TABLE TRANSP.DISPATCH ADD (DISPATCH_GROUPTIME DATE, TRUCK_DISPATCHTIME DATE);
ALTER TABLE TRANSP.DISPATCH MODIFY (START_TIME NULL);

ALTER TABLE TRANSP.HANDOFF_BATCHTRAILER modify starttime null;


