DROP TABLE TRANSP.DISPATCH_GROUP CASCADE CONSTRAINTS;

ALTER TABLE TRANSP.WAVE_INSTANCE DROP (TRUCK_DISPATCHTIME, TRUCK_ENDTIME, MAX_TIME);
ALTER TABLE TRANSP.WAVE_INSTANCE MODIFY (FIRST_DLV_TIME NOT NULL);
ALTER TABLE TRANSP.WAVE_INSTANCE MODIFY (LAST_DLV_TIME NOT NULL);
ALTER TABLE TRANSP.WAVE_INSTANCE MODIFY (DISPATCH_TIME NOT NULL);

ALTER TABLE TRANSP.ZONE DROP (PRETRIP_TIME, POSTTRIP_TIME);

ALTER TABLE TRANSP.SCRIB_BID DROP column DISPATCH_GROUPTIME;

ALTER TABLE TRANSP.SCRIB RENAME column ZONE_CODE to ZONE_ID;
ALTER TABLE TRANSP.SCRIB DROP (DISPATCH_GROUPTIME, TRUCK_DISPATCHTIME, TRUCK_ENDTIME);

ALTER TABLE TRANSP.PLAN DROP (DISPATCH_GROUPTIME, TRUCK_DISPATCHTIME, TRUCK_ENDTIME);
ALTER TABLE TRANSP.PLAN MODIFY (START_TIME NOT NULL);
ALTER TABLE TRANSP.PLAN MODIFY (FIRST_DLV_TIME NOT NULL);

ALTER TABLE TRANSP.DISPATCH DROP (DISPATCH_GROUPTIME, TRUCK_DISPATCHTIME);
ALTER TABLE TRANSP.DISPATCH MODIFY (START_TIME NOT NULL);


