DROP TABLE "CUST"."SS_OFFLINE_RECOMMENDATION";

CREATE TABLE "CUST"."SS_OFFLINE_RECOMMENDATION" 
  (
	 "USER_ID" VARCHAR2(80 BYTE) NOT NULL, 
	 "SITE_FEATURE_ID" VARCHAR2(16 BYTE) NOT NULL, 
	 "PRODUCT_ID" VARCHAR2(128 BYTE) NOT NULL, 
	 "POSITION" INTEGER NOT NULL, 
	 "NAME" VARCHAR2(255 BYTE) NOT NULL, 
	 "LINK" VARCHAR2(255 BYTE) NOT NULL, 
	 "IMAGE_PATH" VARCHAR2(255 BYTE) NOT NULL, 
	 "IMAGE_WIDTH" INTEGER NOT NULL, 
	 "IMAGE_HEIGHT" INTEGER NOT NULL, 
	 "RATING" VARCHAR2(2 BYTE), 
	 "PRICE" VARCHAR2(50 BYTE) NOT NULL, 
	 "WAS_PRICE" VARCHAR2(50 BYTE), 
	 "TIERED_PRICE" VARCHAR2(100 BYTE), 
	 "ABOUT_PRICE" VARCHAR2(50 BYTE), 
	 "BURST" VARCHAR2(2 BYTE), 
	 "LAST_MODIFIED" TIMESTAMP NOT NULL, 
	 CONSTRAINT "SS_OFFL_REC_PK" PRIMARY KEY ("USER_ID", "SITE_FEATURE_ID", "POSITION")
  );

CREATE INDEX "CUST"."SS_OFFL_REC_LM_IDX" ON "CUST"."SS_OFFLINE_RECOMMENDATION" ("LAST_MODIFIED");

CREATE INDEX "CUST"."SS_OFFL_REC_SF_PID_IDX" ON "CUST"."SS_OFFLINE_RECOMMENDATION" ("SITE_FEATURE_ID", "PRODUCT_ID");

GRANT SELECT, INSERT, UPDATE, DELETE ON CUST.SS_OFFLINE_RECOMMENDATION TO FDSTORE_PRDA;

