GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG TO FDTRN_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG TO FDMKT_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG TO fdtrn_stprd01;
GRANT SELECT ON DLV.TIMESLOT_LOG TO APPDEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG_DTL TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG_DTL TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG_DTL TO FDTRN_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG_DTL TO FDMKT_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG_DTL TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON  DLV.TIMESLOT_LOG_DTL TO fdtrn_stprd01;
GRANT SELECT ON DLV.TIMESLOT_LOG_DTL TO APPDEV;

GRANT SELECT ON  DLV.TIMESLOT_LOG_SEQUENCE TO FDSTORE_PRDA;
GRANT SELECT ON  DLV.TIMESLOT_LOG_SEQUENCE TO FDSTORE_PRDB;
GRANT SELECT ON  DLV.TIMESLOT_LOG_SEQUENCE TO FDTRN_PRDA;
GRANT SELECT ON  DLV.TIMESLOT_LOG_SEQUENCE TO FDMKT_PRDA;
GRANT SELECT ON  DLV.TIMESLOT_LOG_SEQUENCE TO fdstore_stprd01;
GRANT SELECT ON  DLV.TIMESLOT_LOG_SEQUENCE TO fdtrn_stprd01;
GRANT SELECT ON  DLV.TIMESLOT_LOG_SEQUENCE TO APPDEV;
