/* Generated by Together */

package com.freshdirect.payment;

public interface InvoiceLineItemI {
    String getSalesOrderNum();

    void setSalesOrderNum(String salesOrderNum);

    String getWebOrderNum();

    void setWebOrderNum(String webOrderNum);

    String getInvoiceNum();

    void setInvoiceNum(String invoiceNum);

    String getInvoiceLineNum();

    void setInvoiceLineNum(String invoiceLineNum);

    String getMaterialNum();

    void setMaterialNum(String materialNum);

    double getInvoiceLineAmount();

    void setInvoiceLineAmount(double invoiceLineAmt);

    double getInvoiceLineTax();

    void setInvoiceLineTax(double lineTax);

    double getUnitPrice();

    void setUnitPrice(double unitPrice);

    double getCustomizationPrice();

    void setCustomizationPrice(double price);

    String getSalesUnitOfMeasure();

    void setSalesUnitOfMeasure(String uom);

    int getOrderQuantity();

    void setOrderQuantity(int quantity);

    int getActualShippedQuantity();

    void setActualShippedQuantity(int shippedQuantity);

    int getTotalShippedQuantity();

    void setTotalShippedQuantity(int totalShipped);

    double getGrossWeight();

    void setGrossWeight(double grossWeight);

    String getWeightUnit();

    void setWeightUnit(String weightUnit);

    String getOrderLineStatus();

    void setOrderLineStatus(String status);
}
