/* Generated by Together */

package com.freshdirect.payment;

public interface InvoiceHeaderI {
    public String getSalesOrderNum();

    public void setSalesOrderNum(String salesOrderNum);

    public String getWebOrderNum();

    public void setWebOrderNum(String webOrderNum);

    public String getInvoiceNum();

    public void setInvoiceNum(String invoiceNum);

    public double getInvoiceTotalBeforeCredit();

    public void setInvoiceTotalBeforeCredit(double amount);

    public double getInvoiceTax();

    public void setInvoiceTax(double tax);

    public double getInvoiceSubTotal();

    public void setInvoiceSubTotal(double subTotal);

    public double getCreditAmount();

    public void setCreditAmount(double creditAmount);

    public double getInvoiceTotalAfterCredit();

    public void setInvoiceTotalAfterCredit(double total);

    public String getOrderStatus();

    public void setOrderStatus(String status);

    public String getBillingType();

    public void setBillingType(String billingType);
}
