insert into CUST.COMPLAINT_DEPT_CODE   (COMP_CODE, COMP_DEPT, PRIORITY, ID)
	SELECT 'DAMBOXC',d.CODE, 10, CUST.SYSTEM_SEQ.nextval from CUST.COMPLAINT_DEPT d where d.CODE NOT IN ('XTR','GDW')
	 and d.CODE NOT IN (select t.COMP_DEPT from CUST.COMPLAINT_DEPT_CODE t where t.COMP_CODE = 'DAMBOXC');
	
insert into CUST.COMPLAINT_DEPT_CODE   (COMP_CODE, COMP_DEPT, PRIORITY, ID)
	SELECT 'DAMBOXD',d.CODE, 10, CUST.SYSTEM_SEQ.nextval from CUST.COMPLAINT_DEPT d where d.CODE NOT IN ('XTR','GDW')
	 and d.CODE NOT IN (select t.COMP_DEPT from CUST.COMPLAINT_DEPT_CODE t where t.COMP_CODE = 'DAMBOXD');
	
insert into CUST.COMPLAINT_DEPT_CODE   (COMP_CODE, COMP_DEPT, PRIORITY, ID)
	SELECT 'PRDDAM',d.CODE, 10, CUST.SYSTEM_SEQ.nextval from CUST.COMPLAINT_DEPT d where d.CODE NOT IN ('XTR','GDW', 'TRN')
	 and d.CODE NOT IN (select t.COMP_DEPT from CUST.COMPLAINT_DEPT_CODE t where t.COMP_CODE = 'PRDDAM');	


insert into CUST.COMPLAINT_DEPT_CODE   (COMP_CODE, COMP_DEPT, PRIORITY, ID)
	SELECT 'DAMBOPRD',d.CODE, 10, CUST.SYSTEM_SEQ.nextval from CUST.COMPLAINT_DEPT d 
		where d.CODE NOT IN ('XTR','GDW', 'TRN', 'CAT')
	 and d.CODE NOT IN (select t.COMP_DEPT from CUST.COMPLAINT_DEPT_CODE t where t.COMP_CODE = 'DAMBOPRD');		
	
insert into CUST.COMPLAINT_DEPT_CODE   (COMP_CODE, COMP_DEPT, PRIORITY, ID)
	SELECT 'MISBOX',d.CODE, 10, CUST.SYSTEM_SEQ.nextval from CUST.COMPLAINT_DEPT d where 
	d.CODE NOT IN ('XTR','GDW', 'TRN', 'FRO')
	 and d.CODE NOT IN (select t.COMP_DEPT from CUST.COMPLAINT_DEPT_CODE t where t.COMP_CODE = 'MISBOX');		
	
insert into CUST.COMPLAINT_DEPT_CODE   (COMP_CODE, COMP_DEPT, PRIORITY, ID)
	SELECT 'MISFRZ',d.CODE, 10, CUST.SYSTEM_SEQ.nextval from CUST.COMPLAINT_DEPT d 
	where d.CODE NOT IN ('FDI','CHE', 'COF', 'DAI', 'DEL', 'XTR', 'FRU', 'GDW', 'HBA', 'TEA', 'TRN', 'WIN')
	 and d.CODE NOT IN (select t.COMP_DEPT from CUST.COMPLAINT_DEPT_CODE t where t.COMP_CODE = 'MISFRZ');			
	
	