GRANT SELECT, UPDATE, INSERT ON DLV.REGION_DATA TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.REGION TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.REGION TO TRANSP;

GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.ZONE_DESC TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.ZONE_DESC TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.ZONE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.ZONE TO TRANSP;

GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.PLANNING_RESOURCE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.PLANNING_RESOURCE TO TRANSP;

GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.TIMESLOT TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.TIMESLOT TO TRANSP;

GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.TRUCK_RESOURCE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT, DELETE ON DLV.TRUCK_RESOURCE TO TRANSP;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.GEO_RESTRICTION_BOUNDARY TO TRANSP;
GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.GEO_RESTRICTION_BOUNDARY TO FDTRN_PRDA;


--WORKTABLES Permissions

GRANT SELECT, UPDATE, INSERT ON DLV.ZONE_WORKTABLE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.ZONE_WORKTABLE TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.COS_ZONE_WORKTABLE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.COS_ZONE_WORKTABLE TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.CT_ZONE_WORKTABLE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.CT_ZONE_WORKTABLE TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.CTCOS_ZONE_WORKTABLE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.CTCOS_ZONE_WORKTABLE TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.HAMP_ZONE_WORKTABLE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.HAMP_ZONE_WORKTABLE TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.NJ_ZONE_WORKTABLE TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.NJ_ZONE_WORKTABLE TO TRANSP;

GRANT SELECT, UPDATE, INSERT ON DLV.NJ_ZONE_WORKTABLE_BKP TO FDTRN_PRDA;
GRANT SELECT, UPDATE, INSERT ON DLV.NJ_ZONE_WORKTABLE_BKP TO TRANSP;

GRANT SELECT, INSERT, UPDATE ON DLV.GEO_RESTRICTION_WORKTAB TO TRANSP;
GRANT SELECT, INSERT, UPDATE ON DLV.GEO_RESTRICTION_WORKTAB TO FDTRN_PRDA;



