ALTER TABLE "SS_VARIANTS" DROP CONSTRAINT SS_VARIANTS_ALIAS_FK;
ALTER TABLE "SS_VARIANTS" DROP CONSTRAINT SS_VARIANTS_ALIAS;

ALTER TABLE "SS_VARIANTS" MODIFY (ALIAS_ID VARCHAR2(32));

ALTER TABLE "SS_VARIANTS" ADD CONSTRAINT SS_VARIANTS_ALIAS_FK FOREIGN KEY ("ALIAS_ID") REFERENCES "SS_VARIANTS"("ID") ENABLE;
ALTER TABLE "SS_VARIANTS" ADD CONSTRAINT SS_VARIANTS_ALIAS CHECK (("TYPE" = 'alias' AND "ALIAS_ID" IS NOT NULL) OR ("TYPE" <> 'alias' AND "ALIAS_ID" IS NULL)) ENABLE;

