CREATE TABLE MEDIA
(
  ID      VARCHAR2(128) PRIMARY KEY,
  URI     VARCHAR2(255) NOT NULL UNIQUE,
  WIDTH   INTEGER,
  HEIGHT  INTEGER,
  TYPE    VARCHAR2(55)
);

CREATE INDEX IDX_MEDIA_TYPE ON MEDIA(TYPE);
