CREATE TABLE DLV.SESSION_LOG (
    ID                NUMBER(16, 0) NOT NULL,
    ROLE              VARCHAR2(16)  NOT NULL,
    USER_ID           VARCHAR2(32)  NOT NULL,
    SESSION_ID        VARCHAR2(128) NOT NULL,
    START_DATETIME    DATE          NOT NULL,
    END_DATETIME      DATE,
    LASTINTERACTION_DATETIME DATE   NOT NULL
);
GRANT all on DLV.SESSION_LOG to FDSTORE_PRDA;
GRANT all on DLV.SESSION_LOG to FDSTORE_PRDB;
