/*AssetAttribute_Type*/

ALTER TABLE TRANSP.ASSETTEMPLATE_ATTRIBUTE DROP CONSTRAINT FK_ATTRIBUTETYPE_ID;

ALTER TABLE TRANSP.ASSET_ATTRIBUTE DROP CONSTRAINT SYS_C00203802;

ALTER TABLE TRANSP.ASSET_ATTRIBUTETYPE DROP CONSTRAINT SYS_C00203790;

ALTER TABLE TRANSP.ASSET_ATTRIBUTETYPE ADD CONSTRAINT ATTRIBUTETYPE_PK PRIMARY KEY (CODE, ASSET_TYPE);


GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.ZIPCODE TO FDTRN_STPRD01;
GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.ZIPCODE_WORKTAB TO FDTRN_STPRD01;
GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.NAVTECH_GEOCODE TO FDTRN_STPRD01;
