/*AssetAttribute_Type*/
ALTER TABLE TRANSP.ASSET_ATTRIBUTETYPE DROP CONSTRAINT SYS_C00203790;

ALTER TABLE TRANSP.ASSET_ATTRIBUTETYPE ADD CONSTRAINT ATTRIBUTETYPE_PK PRIMARY KEY (CODE, ASSET_TYPE);