package com.freshdirect.cms.core.domain;

public enum ContentType {
    FDFolder(false),
    DonationOrganization(false),
    FAQ(false),
    Store(false),
    SuperDepartment(false),
    GlobalNavigation(false),
    CategorySection(false),
    Domain(false),
    DomainValue(false),
    Department(false),
    Category(false),
    Product(false),
    Sku(false),
    ConfiguredProduct(true),
    ConfiguredProductGroup(false),
    ComponentGroup(false),
    ErpClass(false),
    ErpCharacteristic(false),
    ErpCharacteristicValue(false),
    ErpSalesUnit(false),
    Brand(false),
    RecipeDepartment(false),
    RecipeCategory(false),
    RecipeSubcategory(false),
    Recipe(false),
    RecipeVariant(false),
    RecipeSection(true),
    RecipeSource(false),
    RecipeAuthor(false),
    YmalSet(false),
    StarterList(false),
    BookRetailer(false),
    RecipeSearchPage(false),
    RecipeSearchCriteria(true),
    Synonym(true),
    SpellingSynonym(true),
    SearchRelevancyList(true),
    SearchRelevancyHint(true),
    WordStemmingException(true),
    FavoriteList(false),
    Recommender(false),
    RecommenderStrategy(false),
    Producer(false),
    ProducerType(false),
    TileList(false),
    Tile(false),
    HolidayGreeting(false),
    MyFD(false),
    GlobalMenuItem(false),
    GlobalMenuSection(false),
    YoutubeVideo(false),
    Page(false),
    ProductGrabber(false),
    ProductFilterGroup(false),
    ProductFilter(false),
    Tag(false),
    ProductFilterMultiGroup(false),
    SortOption(false),
    Banner(false),
    SearchSuggestionGroup(false),
    RecipeTag(false),
    WebPage(false),
    Schedule(true),
    Section(false),
    Anchor(false),
    TextComponent(false),
    ImageBanner(false),
    PickList(false),
    PickListItem(false),
    DarkStore(false),
    ModuleContainer(false),
    ModuleGroup(false),
    Module(false),
    Image(false),
    Html(false),
    Template(false),
    MediaFolder(false),
    CmsReport(false),
    CmsQuery(false),
    ErpMaterial(false);

    /** Denotes that type has generated content ID */
    public final boolean generatedContentId;

    ContentType(final boolean generatedContentId) {
        this.generatedContentId = generatedContentId;
    }
}

