INSERT INTO cust.DISCOUNTLINE
(ID, SALESACTION_ID, PROMOTION_TYPE, PROMOTION_AMT, PROMOTION_CAMPAIGN) 
(
SELECT SYSTEM_SEQ.NEXTVAL, sa.ID, sa.PROMOTION_TYPE, sa.PROMOTION_AMT, sa.PROMOTION_CAMPAIGN FROM cust.SALESACTION sa WHERE sa.ACTION_DATE >= '01-JAN-2005'
AND sa.PROMOTION_TYPE IS NOT NULL AND sa.PROMOTION_AMT IS NOT NULL
);

COMMIT;