CREATE TABLE CUST.LIST_VIRTUAL_OBJECT
(
  ID VARCHAR2(16)         NOT NULL,
  NAME VARCHAR2(30)       NOT NULL,
  SQL_TEXT VARCHAR2(2048) NOT NULL,
  SIMPLE_SQL CHAR(1)      DEFAULT 'N',
  CONSTRAINT "PK_VIRTUAL_OBJECT" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_VIRTUAL_OBJECT TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_VIRTUAL_OBJECT TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_VIRTUAL_OBJECT TO APPDEV;


CREATE TABLE CUST.LIST_TEMPLATE
(
  ID VARCHAR2(16)   NOT NULL,
  NAME VARCHAR2(30) NOT NULL,
  CONSTRAINT "PK_TEMPLATE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_TEMPLATE TO APPDEV;


CREATE TABLE CUST.LIST_TEMPLATE_OBJECT
(
  TEMPLATE_ID VARCHAR2(16)       NOT NULL,
  VIRTUAL_OBJECT_ID VARCHAR2(30) NOT NULL,
  CONSTRAINT "PK_TEMPLATE_OBJECT" PRIMARY KEY (TEMPLATE_ID, VIRTUAL_OBJECT_ID),
  CONSTRAINT "FK_TEMPLATE_OBJECT_TEMPLATE" 
    FOREIGN KEY (TEMPLATE_ID) REFERENCES LIST_TEMPLATE (ID),
  CONSTRAINT "FK_TEMPLATE_OBJECT_OBJECT"
    FOREIGN KEY (VIRTUAL_OBJECT_ID) REFERENCES LIST_VIRTUAL_OBJECT (ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_OBJECT TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_OBJECT TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_TEMPLATE_OBJECT TO APPDEV;


CREATE TABLE CUST.LIST_TEMPLATE_FIELD
(
  ID VARCHAR2(16)          NOT NULL,
  TEMPLATE_ID VARCHAR2(16) NOT NULL,
  FIELD_NAME VARCHAR2(30)  NOT NULL,
  FIELD_POSITION NUMBER(3,0),
  CONSTRAINT "PK_TEMPLATE_FIELD" PRIMARY KEY ("ID"),
  CONSTRAINT "FK_TEMPLATE_FIELD_TEMPLATE"
    FOREIGN KEY (TEMPLATE_ID) REFERENCES LIST_TEMPLATE (ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_FIELD TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_FIELD TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_TEMPLATE_FIELD TO APPDEV;


CREATE TABLE CUST.LIST_TEMPLATE_ORDER_BY
(
  ID VARCHAR2(16)          NOT NULL,
  TEMPLATE_ID VARCHAR2(16) NOT NULL,
  FIELD_NAME VARCHAR2(30)  NOT NULL,
  FIELD_POSITION NUMBER(3,0),
  CONSTRAINT "PK_TEMPLATE_ORDER_BY" PRIMARY KEY ("ID"),
  CONSTRAINT "FK_TEMPLATE_ORDER_BY_TEMPLATE" 
    FOREIGN KEY (TEMPLATE_ID) REFERENCES LIST_TEMPLATE (ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_ORDER_BY TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_ORDER_BY TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_TEMPLATE_ORDER_BY TO APPDEV;


CREATE TABLE CUST.LIST_TEMPLATE_GROUP_BY
(
  ID VARCHAR2(16)           NOT NULL,
  TEMPLATE_ID VARCHAR2(16)  NOT NULL,
  FIELD_NAME VARCHAR2(30)   NOT NULL,
  FIELD_POSITION NUMBER(3,0),
  CONSTRAINT "PK_TEMPLATE_GROUP_BY" PRIMARY KEY ("ID"),
  CONSTRAINT "FK_TEMPLATE_GROUP_BY_TEMPLATE" 
    FOREIGN KEY (TEMPLATE_ID) REFERENCES LIST_TEMPLATE (ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_GROUP_BY TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_TEMPLATE_GROUP_BY TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_TEMPLATE_GROUP_BY TO APPDEV;


CREATE TABLE CUST.LIST_OPERATOR
(
  ID VARCHAR2(16)            NOT NULL,
  OPERATOR_NAME VARCHAR2(10) NOT NULL,
  CONSTRAINT "PK_LIST_OPERATOR" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_OPERATOR TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_OPERATOR TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_OPERATOR TO APPDEV;


CREATE TABLE CUST.LIST_CLAUSE
(
  ID VARCHAR2(16)          NOT NULL,
  TYPE VARCHAR2(20)        NOT NULL,
  TEMPLATE_ID VARCHAR2(16) NOT NULL,
  COLUMN_NAME VARCHAR2(32) NOT NULL,
  OPERATOR_ID VARCHAR(16)  NOT NULL,
  PARAM VARCHAR(30),
  CONSTRAINT "PK_CLAUSE" PRIMARY KEY ("ID"),
  CONSTRAINT "FK_CLAUSE_TEMPLATE" 
    FOREIGN KEY (TEMPLATE_ID) REFERENCES LIST_TEMPLATE (ID),
  CONSTRAINT "FK_CLAUSE_OPERATOR" 
    FOREIGN KEY (OPERATOR_ID) REFERENCES LIST_OPERATOR (ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_CLAUSE TO APPDEV;


CREATE TABLE CUST.LIST_CONSTANT_CLAUSE
(
  ID VARCHAR2(16)       NOT NULL,
  CONSTANT VARCHAR2(128) NOT NULL,
  CONSTRAINT "PK_CONSTANT_CLAUSE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_CONSTANT_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_CONSTANT_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_CONSTANT_CLAUSE TO APPDEV;


CREATE TABLE CUST.LIST_PARAM_CLAUSE
(
  ID VARCHAR2(16)    NOT NULL,
  CONSTRAINT "PK_PARAM_CLAUSE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_PARAM_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_PARAM_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_PARAM_CLAUSE TO APPDEV;


CREATE TABLE CUST.LIST_JOIN_CLAUSE
(
  ID VARCHAR2(16)            NOT NULL,
  PARENT_COLUMN VARCHAR2(32) NOT NULL,
  CHILD_COLUMN VARCHAR2(32)  NOT NULL,
  CONSTRAINT "PK_JOIN_CLAUSE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_JOIN_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_JOIN_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_JOIN_CLAUSE TO APPDEV;


CREATE TABLE CUST.LIST_STATIC_DROPDOWN_CLAUSE
(
  ID VARCHAR2(16)       NOT NULL,
  OPTIONS VARCHAR2(512) NOT NULL,
  CONSTRAINT "PK_STATIC_DROPDOWN_CLAUSE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_STATIC_DROPDOWN_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_STATIC_DROPDOWN_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_STATIC_DROPDOWN_CLAUSE TO APPDEV;


CREATE TABLE CUST.LIST_SELECT_DROPDOWN_CLAUSE
(
  ID VARCHAR2(16)           NOT NULL,
  TABLE_NAME VARCHAR2(32)   NOT NULL,
  NAME_COLUMN VARCHAR2(32)  NOT NULL,
  VALUE_COLUMN VARCHAR2(32) NOT NULL,
  CONSTRAINT "PK_SELECT_DROPDOWN_CLAUSE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_SELECT_DROPDOWN_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_SELECT_DROPDOWN_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_SELECT_DROPDOWN_CLAUSE TO APPDEV;


CREATE TABLE CUST.LIST_QUERY_DROPDOWN_CLAUSE
(
  ID VARCHAR2(16)       NOT NULL,
  QUERY_ID VARCHAR2(16) NOT NULL,
  CONSTRAINT "PK_QUERY_DROPDOWN_CLAUSE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_QUERY_DROPDOWN_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_QUERY_DROPDOWN_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_QUERY_DROPDOWN_CLAUSE TO APPDEV;


CREATE TABLE CUST.LIST_ENUM_DROPDOWN_CLAUSE
(
  ID VARCHAR2(16)          NOT NULL,
  CLASS_NAME VARCHAR2(200) NOT NULL,
  CONSTRAINT "PK_ENUM_DROPDOWN_CLAUSE" PRIMARY KEY ("ID")
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_ENUM_DROPDOWN_CLAUSE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_ENUM_DROPDOWN_CLAUSE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_ENUM_DROPDOWN_CLAUSE TO APPDEV;



CREATE TABLE CUST.LIST_STORED_QUERY
(
  ID VARCHAR2(16)              NOT NULL,
  NAME VARCHAR2(30)            NOT NULL,
  TEMPLATE_ID VARCHAR2(16)     NOT NULL,
  DATASOURCE_NAME VARCHAR2(16) NOT NULL,
  CONSTRAINT "PK_STORED_QUERY" PRIMARY KEY ("ID"),
  CONSTRAINT "FK_STORED_QUERY_TEMPLATE" 
    FOREIGN KEY (TEMPLATE_ID) REFERENCES LIST_TEMPLATE (ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_STORED_QUERY TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_STORED_QUERY TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_STORED_QUERY TO APPDEV;


CREATE TABLE CUST.LIST_STORED_QUERY_VALUE
(
  ID VARCHAR2(16)               NOT NULL,
  STORED_QUERY_ID VARCHAR2(16)  NOT NULL,
  NAME VARCHAR2(16)             NOT NULL,
  VALUE VARCHAR2(16)            NOT NULL,
  CONSTRAINT "PK_STORED_QUERY_VALUE" PRIMARY KEY ("ID"),
  CONSTRAINT "FK_QUERY_VALUE_QUERY" 
    FOREIGN KEY (STORED_QUERY_ID) REFERENCES LIST_STORED_QUERY (ID)
);

GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_STORED_QUERY_VALUE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  CUST.LIST_STORED_QUERY_VALUE TO FDSTORE_PRDA;
GRANT SELECT ON  CUST.LIST_STORED_QUERY_VALUE TO APPDEV;


ALTER TABLE "LIST_QUERY_DROPDOWN_CLAUSE"
ADD CONSTRAINT "QUERY_DROPDOWN_CLAUSE_QUERY" FOREIGN KEY ("QUERY_ID")
REFERENCES "LIST_STORED_QUERY" ("ID");


INSERT INTO LIST_OPERATOR VALUES('1','=');
INSERT INTO LIST_OPERATOR VALUES('2','>');
INSERT INTO LIST_OPERATOR VALUES('3','<');
INSERT INTO LIST_OPERATOR VALUES('4','IN');
INSERT INTO LIST_OPERATOR VALUES('5','NOT IN');

ALTER TABLE OCF_LIST ADD STORED_QUERY_ID VARCHAR2(16);

ALTER TABLE "OCF_LIST"
ADD CONSTRAINT "LIST_STORED_QUERY" FOREIGN KEY ("STORED_QUERY_ID")
REFERENCES "LIST_STORED_QUERY" ("ID");
