 
GRANT SELECT ON DLV.TIMESLOT_EVENT_HDR TO APPDEV;
  
GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_HDR TO FDMKT_PRDA;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_HDR TO FDSTORE_PRDA;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_HDR TO FDSTORE_PRDB;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_HDR TO FDTRN_PRDA;
 
GRANT SELECT ON DLV.TIMESLOT_EVENT_HDR TO DWREAD;

GRANT SELECT ON DLV.TIMESLOT_EVENT_DTL TO APPDEV;
 
GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_DTL TO FDMKT_PRDA;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_DTL TO FDSTORE_PRDA;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_DTL TO FDSTORE_PRDB;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_EVENT_DTL TO FDTRN_PRDA;

GRANT SELECT ON DLV.TIMESLOT_EVENT_DTL TO DWREAD;