GRANT EXECUTE ON TRANSP.HANDOFF_ROUTING_ROUTE_NO TO fdstore_stprd01;
GRANT SELECT ON  TRANSP.HANDOFFBATCHSEQ TO fdstore_stprd01;

GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCH TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHACTION TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHSESSION TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHROUTE TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHSTOP TO fdstore_stprd01;

GRANT EXECUTE ON TRANSP.HANDOFF_ROUTING_ROUTE_NO TO fdtrn_stprd01;
GRANT SELECT ON  TRANSP.HANDOFFBATCHSEQ TO fdtrn_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCH TO fdtrn_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHACTION TO fdtrn_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHSESSION TO fdtrn_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE TO fdtrn_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHROUTE TO fdtrn_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHSTOP TO fdtrn_stprd01;


GRANT EXECUTE ON TRANSP.HANDOFF_ROUTING_ROUTE_NO TO APPDEV;
GRANT SELECT ON  TRANSP.HANDOFFBATCHSEQ TO APPDEV;
GRANT SELECT ON TRANSP.HANDOFF_BATCH TO APPDEV;
GRANT SELECT ON TRANSP.HANDOFF_BATCHACTION TO APPDEV;
GRANT SELECT ON TRANSP.HANDOFF_BATCHSESSION TO APPDEV;
GRANT SELECT ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE TO APPDEV;
GRANT SELECT ON TRANSP.HANDOFF_BATCHROUTE TO APPDEV;
GRANT SELECT ON TRANSP.HANDOFF_BATCHSTOP TO APPDEV;