ALTER TABLE TRANSP.SCRIB_BID DROP  CONSTRAINT SCRIB_BID_UNIQUE_EMPLOYEEID;
alter table TRANSP.scrib_bid drop column WEEK_OF; 
ALTER TABLE TRANSP.SCRIB_BID ADD (CONSTRAINT SCRIB_BID_UNIQUE_EMPLOYEEID UNIQUE (EMPLOYEE_ID, DAY));

