CREATE TABLE "CMS"."ATTRIBUTE_BACKUP"
   (    "CONTENTNODE_ID" VARCHAR2(128 BYTE) NOT NULL ENABLE,
        "ID" VARCHAR2(16 BYTE) NOT NULL ENABLE,
        "VALUE" VARCHAR2(3999 BYTE),
        "ORDINAL" NUMBER(10,0) NOT NULL ENABLE,
        "DEF_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE,
        "DEF_CONTENTTYPE" VARCHAR2(40 BYTE) NOT NULL ENABLE,
         CONSTRAINT "PK_ATTRIBUTE_BACKUP" PRIMARY KEY ("ID"));

 CREATE TABLE "CMS"."CONTENTNODE_BACKUP"
   (    "ID" VARCHAR2(128 BYTE) NOT NULL ENABLE,
        "CONTENTTYPE_ID" VARCHAR2(40 BYTE) NOT NULL ENABLE,
         CONSTRAINT "PK_CONTENTNODE_BACKUP" PRIMARY KEY ("ID"));

  CREATE TABLE "CMS"."RELATIONSHIP_BACKUP"
   (    "PARENT_CONTENTNODE_ID" VARCHAR2(128 BYTE) NOT NULL ENABLE,
        "ORDINAL" NUMBER(10,0) NOT NULL ENABLE,
        "ID" VARCHAR2(40 BYTE) NOT NULL ENABLE,
        "DEF_NAME" VARCHAR2(40 BYTE) NOT NULL ENABLE,
        "DEF_CONTENTTYPE" VARCHAR2(40 BYTE) NOT NULL ENABLE,
        "CHILD_CONTENTNODE_ID" VARCHAR2(128 BYTE),
         CONSTRAINT "PK_RELATIONSHIP_BACKUP" PRIMARY KEY ("ID"));

CREATE TABLE "CMS"."MEDIA_BACKUP"
   (    "ID" VARCHAR2(128 BYTE),
        "URI" VARCHAR2(255 BYTE) NOT NULL ENABLE,
        "WIDTH" NUMBER(*,0),
        "HEIGHT" NUMBER(*,0),
        "TYPE" VARCHAR2(55 BYTE) NOT NULL ENABLE,
        "MIME_TYPE" VARCHAR2(55 BYTE),
        "LAST_MODIFIED" DATE,
         CONSTRAINT "PK_MEDIA_BACKUP" PRIMARY KEY ("ID"));