ALTER TABLE CUST.PROMO_CUST_STRATEGY ADD (DELIVERY_DAY_TYPE varchar2(10 byte));
UPDATE CUST.PROMO_CUST_STRATEGY SET DELIVERY_DAY_TYPE='R' WHERE CODE like 'WS_%';--Window Steering promotions
UPDATE CUST.PROMO_CUST_STRATEGY SET DELIVERY_DAY_TYPE='A' WHERE CODE not like 'WS_%';--Non window steering promotions.