GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE TO fdtrn_stprd01;
GRANT SELECT ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE TO APPDEV;