/* Generated by Together */

package com.freshdirect.customer;

public class EnumTransactionSource implements java.io.Serializable {
     public final static EnumTransactionSource WEBSITE			= new EnumTransactionSource(0, "WEB", "Website");
	 public final static EnumTransactionSource SYSTEM			= new EnumTransactionSource(1, "SYS", "System");
     public final static EnumTransactionSource CUSTOMER_REP		= new EnumTransactionSource(2, "CSR", "Telephone");
     public final static EnumTransactionSource ADMINISTRATOR	= new EnumTransactionSource(3, "ADM", "Administrator");
     public final static EnumTransactionSource TRANSPORTATION = new EnumTransactionSource(4, "TRA", "Transportation");

	private EnumTransactionSource(int id, String code, String name) {
        this.id = id;
        this.code = code;
        this.name = name;
    }

    public String getCode() {
        return this.code;
    }

    public String getName() {
		return this.name;
	}

	public static EnumTransactionSource getTransactionSource(int t) {
		switch (t) {
			case 0:
				return WEBSITE;
			case 1:
				return SYSTEM;
			case 2:
				return CUSTOMER_REP;
			case 3:
				return ADMINISTRATOR;
			default:
				return null;
		}
	}
	public static EnumTransactionSource getTransactionSource(String code){
		if(WEBSITE.getCode().equalsIgnoreCase(code)){
			return WEBSITE;
		}else if(SYSTEM.getCode().equalsIgnoreCase(code)){
			return SYSTEM;
		}else if(CUSTOMER_REP.getCode().equalsIgnoreCase(code)){
			return CUSTOMER_REP;
		}else if(ADMINISTRATOR.getCode().equalsIgnoreCase(code)){
			return ADMINISTRATOR;
		}else if(TRANSPORTATION.getCode().equalsIgnoreCase(code)){
			return TRANSPORTATION;
		}else{
			try {
				return getTransactionSource( Integer.parseInt(code) );
			} catch (NumberFormatException ex) {
				return null;
			}

		}
	}

   	public boolean equals(Object o) {
		if (o instanceof EnumTransactionSource) {
			return this.id == ((EnumTransactionSource)o).id;
		}
		return false;
	}
	
	public String toString() {
		return this.code;
	}

    private final int id;
    private final String name;
    private final String code;

}
