/* Generated by Together */

package com.freshdirect.customer;

import java.util.*;

/**
 * @stereotype fd-model
 */
public class ErpChargeModel extends ErpTransactionModel {

	private List charges;
	private String issuedBy;

    public ErpChargeModel() {
		super(EnumTransactionType.CHARGE);
		this.charges = new ArrayList();
	}

    public List getCharges() { return this.charges; }
    public void setCharges(List l) { this.charges = l; }
    public void addCharge(ErpChargeLineModel charge) { this.charges.add(charge); }
    public void addCharges(List l) { this.charges.addAll(l); }

    public String getIssuedBy() { return this.issuedBy; }
    public void setIssuedBy(String s) { this.issuedBy = s; }

    /**
     * Sum of amounts for all charge lines (i.e., individual fees) in this charge.
     */
	public double getAmount() {
		double amount = 0;
		for (Iterator it = charges.iterator(); it.hasNext(); ) {
			ErpChargeLineModel charge = (ErpChargeLineModel) it.next();
			amount += charge.getAmount();
		}
		return amount;
	}

}
