/* Generated by Together */

package com.freshdirect.customer;

import com.freshdirect.affiliate.ErpAffiliate;
import com.freshdirect.framework.core.*;

/**
 * ErpCredit model class.
 * @version    $Revision$
 * @author     $Author$
 * @stereotype fd-model
 */
abstract public class ErpCreditModel extends ModelSupport {
	private double amount;
	private String department;
	private ErpAffiliate affiliate;

	public ErpCreditModel() {
		this("", 0.0, ErpAffiliate.getEnum(ErpAffiliate.CODE_FD));
	}

	public ErpCreditModel(String department, double amount) {
		this(department, amount, ErpAffiliate.getEnum(ErpAffiliate.CODE_FD));
	}
	
	public ErpCreditModel(String department, double amount, ErpAffiliate affiliate){
		this.department = department;
		this.amount = amount;
		this.affiliate = affiliate;
	}
	
	public ErpCreditModel (ErpCreditModel credit){
		this.department = credit.getDepartment();
		this.amount = credit.getAmount();
		this.affiliate = credit.getAffiliate();
	}

	public double getAmount(){
		return this.amount;
	}

	public void setAmount(double amount){
		this.amount = amount;
	}

	public double getOriginalAmount() {
		return this.amount;
	}

	public void setOriginalAmount(double d) {
		this.amount = d;
	}

	public String getDepartment(){
		return this.department;
	}

	public void setDepartment(String department){
		this.department = department;
	}
	
	public ErpAffiliate getAffiliate(){
		return this.affiliate;
	}
	
	public void setAffiliate(ErpAffiliate affiliate){
		this.affiliate = affiliate;
	}

}
