/* Generated by Together */

package com.freshdirect.customer;

import java.util.Date;

import com.freshdirect.common.address.PhoneNumber;
import com.freshdirect.common.customer.EnumServiceType;
import com.freshdirect.framework.core.ModelSupport;

/**
 * @stereotype fd-model 
 */
public class ErpDeliveryInfoModel extends ModelSupport {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3000283236041863594L;
	private String deliveryReservationId;
    private Date deliveryStartTime;
    private Date deliveryEndTime;
	private Date deliveryCutoffTime;
    private String deliveryZone;
   	private String depotLocationId;
    private ErpAddressModel deliveryAddress;
    private EnumDeliveryType deliveryType;
    private String deliveryRegionId;
    private ErpDeliveryPlantInfoModel deliveryPlantInfo;
    private Date deliveryHandoffTime;
    private double minDurationForModStart;
    private double minDurationForModification;
    private PhoneNumber orderMobileNumber;
    private Date originalCutoffTime;
    private EnumServiceType serviceType;
    
   
  
	public PhoneNumber getOrderMobileNumber() {
		return orderMobileNumber;
	}
	public void setOrderMobileNumber(PhoneNumber orderMobileNumber) {
		this.orderMobileNumber = orderMobileNumber;
	}
	public String getDeliveryReservationId() { return deliveryReservationId; }
    public void setDeliveryReservationId(String deliveryReservationId) { this.deliveryReservationId = deliveryReservationId; }
    
    public Date getDeliveryStartTime(){ return deliveryStartTime; }
    public void setDeliveryStartTime(Date deliveryStartTime){ this.deliveryStartTime = deliveryStartTime; }

    public Date getDeliveryEndTime(){ return deliveryEndTime; }
    public void setDeliveryEndTime(Date deliveryEndTime){ this.deliveryEndTime = deliveryEndTime; }
	
	public Date getDeliveryCutoffTime() { return deliveryCutoffTime; }
	public void setDeliveryCutoffTime(Date deliveryCutoffTime) { this.deliveryCutoffTime = deliveryCutoffTime; }

	public Date getOriginalCutoffTime() { return originalCutoffTime; }
	public void setOriginalCutoffTime(Date originalCutoffTime) { this.originalCutoffTime = originalCutoffTime; }

    public String getDeliveryZone(){ return deliveryZone; }
    public void setDeliveryZone(String deliveryZone){ this.deliveryZone = deliveryZone; }

    public String getDepotLocationId(){ return depotLocationId; }
    public void setDepotLocationId(String depotLocation){ this.depotLocationId = depotLocation; }

    public ErpAddressModel getDeliveryAddress(){ return deliveryAddress; }
    public void setDeliveryAddress(ErpAddressModel deliveryAddress){ this.deliveryAddress = deliveryAddress; }
    
    public EnumDeliveryType getDeliveryType() { return deliveryType; }
    public void setDeliveryType(EnumDeliveryType dt) { this.deliveryType = dt; }

    public String getDeliveryRegionId(){ return deliveryRegionId; }
    public void setDeliveryRegionId(String deliveryRegionId){ this.deliveryRegionId = deliveryRegionId; }
    
	public Date getDeliveryHandoffTime() { return deliveryHandoffTime; }
	public void setDeliveryHandoffTime(Date deliveryHandoffTime) { this.deliveryHandoffTime = deliveryHandoffTime; }
	public ErpDeliveryPlantInfoModel getDeliveryPlantInfo() {		return deliveryPlantInfo;	}
	public void setDeliveryPlantInfo(ErpDeliveryPlantInfoModel deliveryPlantInfo) {		this.deliveryPlantInfo = deliveryPlantInfo;	}
	public double getMinDurationForModStart() {
		return minDurationForModStart;
	}
	public void setMinDurationForModStart(double minDurationForModStart) {
		this.minDurationForModStart = minDurationForModStart;
	}
	public double getMinDurationForModification() {
		return minDurationForModification;
	}
	public void setMinDurationForModification(double minDurationForModification) {
		this.minDurationForModification = minDurationForModification;
	}
	public EnumServiceType getServiceType() {
		return serviceType;
	}
	public void setServiceType(EnumServiceType serviceType) {
		this.serviceType = serviceType;
	}
	@Override
	public void setId( String id) {
		if (id != null) 
			super.setId(id);
	}
}
