/* Generated by Together */

package com.freshdirect.customer;

import java.util.Date;

import com.freshdirect.framework.core.ModelSupport;

/**
 * @stereotype fd-model 
 */
public class ErpDeliveryInfoModel extends ModelSupport {
	private String deliveryReservationId;
    private Date deliveryStartTime;
    private Date deliveryEndTime;
	private Date deliveryCutoffTime;
    private String deliveryZone;
   	private String depotLocationId;
    private ErpAddressModel deliveryAddress;
    private EnumDeliveryType deliveryType;
    private String deliveryRegionId;
   
    public String getDeliveryReservationId() { return deliveryReservationId; }
    public void setDeliveryReservationId(String deliveryReservationId) { this.deliveryReservationId = deliveryReservationId; }
    
    public Date getDeliveryStartTime(){ return deliveryStartTime; }
    public void setDeliveryStartTime(Date deliveryStartTime){ this.deliveryStartTime = deliveryStartTime; }

    public Date getDeliveryEndTime(){ return deliveryEndTime; }
    public void setDeliveryEndTime(Date deliveryEndTime){ this.deliveryEndTime = deliveryEndTime; }
	
	public Date getDeliveryCutoffTime() { return deliveryCutoffTime; }
	public void setDeliveryCutoffTime(Date deliveryCutoffTime) { this.deliveryCutoffTime = deliveryCutoffTime; }

    public String getDeliveryZone(){ return deliveryZone; }
    public void setDeliveryZone(String deliveryZone){ this.deliveryZone = deliveryZone; }

    public String getDepotLocationId(){ return depotLocationId; }
    public void setDepotLocationId(String depotLocation){ this.depotLocationId = depotLocation; }

    public ErpAddressModel getDeliveryAddress(){ return deliveryAddress; }
    public void setDeliveryAddress(ErpAddressModel deliveryAddress){ this.deliveryAddress = deliveryAddress; }
    
    public EnumDeliveryType getDeliveryType() { return deliveryType; }
    public void setDeliveryType(EnumDeliveryType dt) { this.deliveryType = dt; }

    public String getDeliveryRegionId(){ return deliveryRegionId; }
    public void setDeliveryRegionId(String deliveryRegionId){ this.deliveryRegionId = deliveryRegionId; }
    
}
