-- Create Cart Events table - script for production system
-- @author segabor
--
-- Don't forget to add DELETE, INSERT, UPDATE and SELECT rights to FDSTORE user!
--
CREATE TABLE LOG_CART_EVENTS (
	"ID" NUMBER(38,0) NOT NULL ENABLE, 
	"EVENT_TYPE" VARCHAR2(32 BYTE) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(16 BYTE), 
	"COOKIE" VARCHAR2(45 BYTE), 
	"URL" VARCHAR2(64 BYTE), 
	"QUERY_STRING" VARCHAR2(512 BYTE), 
	"TIMESTAMP" DATE, 
	"APPLICATION" VARCHAR2(4 BYTE) NOT NULL ENABLE, 
	"SERVER" VARCHAR2(64 BYTE), 
	"TRACKING_CODE" VARCHAR2(16 BYTE), 
	"PRODUCT_ID" VARCHAR2(128 BYTE), 
	"SKU_CODE" VARCHAR2(18 BYTE), 
	"CATEGORY_ID" VARCHAR2(40 BYTE), 
	"DEPARTMENT_ID" VARCHAR2(40 BYTE), 
	"CARTLINE_ID" VARCHAR2(16 BYTE), 
	"QUANTITY" NUMBER, 
	"SALES_UNIT" VARCHAR2(4 BYTE), 
	"CONFIGURATION" VARCHAR2(512 BYTE), 
	"YMAL_CATEGORY" VARCHAR2(128 BYTE), 
	"YMAL_PRODUCT" VARCHAR2(128 BYTE), 
	"YMAL_SET_ID" VARCHAR2(32 BYTE), 
	"CCL_ID" VARCHAR2(32 BYTE), 
	"SOURCE" VARCHAR2(32 BYTE), 
	"VARIANT_ID" VARCHAR2(16 BYTE), 
	CONSTRAINT "LOG_CART_EVENTS_PK" PRIMARY KEY ("ID")
 ) TABLESPACE "FDCUSDAT" ;

-- Create index
-- CREATE INDEX LOG_CART_EVENTS_INDEX1 ON LOG_CART_EVENTS ("EVENT_TYPE") TABLESPACE "FDCUSDAT" ;
CREATE INDEX LOG_CART_EVENTS_INDEX2 ON LOG_CART_EVENTS ("TIMESTAMP") TABLESPACE "FDCUSDAT" ;
-- CREATE INDEX LOG_CART_EVENTS_INDEX3 ON LOG_CART_EVENTS ("APPLICATION") TABLESPACE "FDCUSDAT" ;
-- CREATE INDEX LOG_CART_EVENTS_INDEX4 ON LOG_CART_EVENTS ("SERVER") TABLESPACE "FDCUSDAT" ;
-- CREATE INDEX LOG_CART_EVENTS_INDEX5 ON LOG_CART_EVENTS ("TRACKING_CODE") TABLESPACE "FDCUSDAT" ;
-- CREATE INDEX LOG_CART_EVENTS_INDEX6 ON LOG_CART_EVENTS ("CARTLINE_ID") TABLESPACE "FDCUSDAT" ;
-- CREATE INDEX LOG_CART_EVENTS_INDEX7 ON LOG_CART_EVENTS ("SOURCE") TABLESPACE "FDCUSDAT" ;
-- CREATE INDEX LOG_CART_EVENTS_INDEX8 ON LOG_CART_EVENTS ("VARIANT_ID") TABLESPACE "FDCUSDAT" ;


-- Add rights to FDStore
GRANT SELECT, INSERT, DELETE, UPDATE ON LOG_CART_EVENTS TO FDSTORE;

-- Create sequence
CREATE SEQUENCE LOG_CART_EVENTS_SEQ START WITH 1 INCREMENT BY 1;
SELECT LOG_CART_EVENTS_SEQ.NEXTVAL FROM DUAL;

GRANT SELECT ON LOG_CART_EVENTS_SEQ TO FDSTORE;
