-- Impression log table - script for Warehouse
-- @author istvan
--
CREATE TABLE LOG_IMPRESSIONS (
	"CONTENT_ID" VARCHAR2(128 BYTE) NOT NULL,
	"VARIANT_ID" VARCHAR2(18 BYTE) NOT NULL,
	"FREQUENCY" INTEGER NOT NULL,
	"TIMESTAMP" DATE NOT NULL
);


CREATE INDEX LOG_IMPRESSIONS_INDEXES ON LOG_IMPRESSIONS ("CONTENT_ID","VARIANT_ID","TIMESTAMP") TABLESPACE "FDCUSDAT" ;
CREATE INDEX LOG_IMPRESSIONS_VARIANT_INDEX ON LOG_IMPRESSIONS ("VARIANT_ID") TABLESPACE "FDCUSDAT";
CREATE INDEX LOG_IMPRESSIONS_DATE_INDEX ON LOG_IMPRESSIONS ("TIMESTAMP") TABLESPACE "FDCUSDAT";

GRANT SELECT, INSERT, DELETE, UPDATE ON LOG_IMPRESSIONS TO FDSTORE;


