-- Click through log table - script for production system
-- @author istvan
--
CREATE TABLE LOG_CLICKTHROUGHS (
	"CONTENT_ID" VARCHAR2(128 BYTE) NOT NULL,
	"VARIANT_ID" VARCHAR2(18 BYTE) NOT NULL,
	"FREQUENCY" INTEGER NOT NULL,
	"TIMESTAMP" DATE NOT NULL
);


-- CREATE INDEX LOG_CLICKTHROUGHS_INDEXES ON LOG_CLICKTHROUGHS ("CONTENT_ID","VARIANT_ID","TIMESTAMP") TABLESPACE "FDCUSDAT" ;
-- CREATE INDEX LOG_CLICKTHROUGHS_VARIANT_INDEX ON LOG_CLICKTHROUGHS ("VARIANT_ID") TABLESPACE "FDCUSDAT";
CREATE INDEX LOG_CLICKTHROUGHS_DATE_INDEX ON LOG_CLICKTHROUGHS ("TIMESTAMP") TABLESPACE "FDCUSDAT";

GRANT SELECT, INSERT, DELETE, UPDATE ON LOG_CLICKTHROUGHS TO FDSTORE;


