--
-- SmartStore Analysis
-- DYF Variant Models
-- 

CREATE TABLE CUST.SSM_PURCHASE_HISTORY
(
  CUSTOMER_ID VARCHAR2(16 BYTE) NOT NULL, 
  PRODUCT_ID VARCHAR2(48 BYTE) NOT NULL, 
  SCORE NUMBER(*,0)
) TABLESPACE "FDCUSDAT";
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSM_PURCHASE_HISTORY TO FDSTORE_PRDA;
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSM_PURCHASE_HISTORY TO FDSTORE_PRDB;

CREATE INDEX PURCHASE_HISTORY_INDEX1 ON CUST.SSM_PURCHASE_HISTORY("CUSTOMER_ID") TABLESPACE "FDCUSIDX";
