--
-- SmartStore Analysis Schema
--


-- Product Information
CREATE TABLE CUST.SSA_SKU (
  ID VARCHAR2(18 BYTE) NOT NULL,
  CONSTRAINT "ANALYSIS_SKU_PK" PRIMARY KEY(ID)
) TABLESPACE "FDCUSDAT";
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_SKU TO FDSTORE_PRDA;
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_SKU TO FDSTORE_PRDB;


-- Customer Information
CREATE TABLE CUST.SSA_CUSTOMER (
  ID VARCHAR2(16 BYTE) NOT NULL,
  CONSTRAINT "ANALYSIS_CUSTOMER_PK" PRIMARY KEY(ID)
) TABLESPACE "FDCUSDAT";
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_CUSTOMER TO FDSTORE_PRDA;
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_CUSTOMER TO FDSTORE_PRDB;


-- Sale
CREATE TABLE CUST.SSA_SALE (
  ID VARCHAR2(16 BYTE) NOT NULL,         -- from CUST.SALE#ID
  CUSTOMER_ID VARCHAR2(16 BYTE) NOT NULL,   -- from CUST.SALE#CUSTOMER_ID <- CUST.CUSTMER#ID
  REQUESTED_DATE DATE NOT NULL,          -- from CUST.SALE#REQUESTED_DATE
  CONSTRAINT "ANALYSIS_SALE_PK" PRIMARY KEY(ID),
  CONSTRAINT "ANALYSIS_SALE_CUSTOMER_ID_FK" FOREIGN KEY(CUSTOMER_ID) REFERENCES CUST.SSA_CUSTOMER (ID) ENABLE
) TABLESPACE "FDCUSDAT";
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_SALE TO FDSTORE_PRDA;
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_SALE TO FDSTORE_PRDB;

CREATE INDEX ANALYSIS_SALE_INDEX_CUSTOMER_ID ON CUST.SSA_SALE(CUSTOMER_ID) TABLESPACE "FDCUSIDX";
CREATE INDEX ANALYSIS_SALE_INDEX_REQUESTED_DATE ON CUST.SSA_SALE(REQUESTED_DATE) TABLESPACE "FDCUSIDX";


-- Orderlines
CREATE TABLE CUST.SSA_ORDERLINE (
  ID VARCHAR2(16 BYTE) NOT NULL,         -- from CUST.ORDERLINE#ID
  SALE_ID VARCHAR2(16 BYTE) NOT NULL,      -- from CUST.SALE#ID
  SKU_CODE VARCHAR2(18 BYTE) NOT NULL,     -- from <SS_ANALYSIS>.SKU#SKU_CODE
  CONSTRAINT "ANALYSIS_ORDERLINE_PK" PRIMARY KEY(ID),
  CONSTRAINT "ANALYSIS_ORDERLINE_SALE_ID_FK" FOREIGN KEY (SALE_ID) REFERENCES CUST.SSA_SALE (ID) ENABLE,
  CONSTRAINT "ANALYSIS_ORDERLINE_SKU_CODE_FK" FOREIGN KEY (SKU_CODE) REFERENCES CUST.SSA_SKU (ID) ENABLE
) TABLESPACE "FDCUSDAT";
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_ORDERLINE TO FDSTORE_PRDA;
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_ORDERLINE TO FDSTORE_PRDB;

CREATE INDEX ANALYSIS_ORDERLINE_SALE_ID ON CUST.SSA_ORDERLINE(SALE_ID) TABLESPACE "FDCUSIDX";
CREATE INDEX ANALYSIS_ORDERLINE_SKU_CODE ON CUST.SSA_ORDERLINE(SKU_CODE) TABLESPACE "FDCUSIDX";


-- Store Content (CMS)
CREATE TABLE CUST.SSA_STORE (
  CONTENT_TYPE VARCHAR2(18 BYTE) NOT NULL,
  CONTENT_ID VARCHAR2(48 BYTE) NOT NULL,
  PARENT_CONTENT_TYPE VARCHAR2(18 BYTE),
  PARENT_CONTENT_ID VARCHAR2(48 BYTE),
  CONSTRAINT SS_ANALYSIS.STORE_PK PRIMARY KEY (CONTENT_TYPE, CONTENT_ID)
) TABLESPACE "FDCUSDAT";
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_STORE TO FDSTORE_PRDA;
GRANT SELECT, INSERT, DELETE, UPDATE ON CUST.SSA_STORE TO FDSTORE_PRDB;

CREATE INDEX ANALYSIS_STORE_CONTENT_ID ON CUST.SSA_STORE (CONTENT_ID) TABLESPACE "FDCUSIDX";
CREATE INDEX ANALYSIS_STORE_CONTENT_TYPE ON CUST.SSA_STORE (CONTENT_TYPE) TABLESPACE "FDCUSIDX";
CREATE INDEX ANALYSIS_STORE_PARENT_CONTENT_ID ON CUST.SSA_STORE (PARENT_CONTENT_ID) TABLESPACE "FDCUSIDX";
CREATE INDEX ANALYSIS_STORE_PARENT_CONTENT_TYPE ON CUST.SSA_STORE (PARENT_CONTENT_TYPE) TABLESPACE "FDCUSIDX";

CREATE UNIQUE INDEX SS_ANALYSIS_STORE_PK ON CUST.SSA_STORE (CONTENT_ID, CONTENT_TYPE) TABLESPACE "FDCUSIDX";

