--
-- SmartStore Analysis
-- Incremental Update
--
INSERT INTO CUST.SSA_SALE (ID,CUSTOMER_ID,REQUESTED_DATE)
SELECT S.ID, S.CUSTOMER_ID, SA.REQUESTED_DATE
FROM CUST.SALE S, CUST.SALESACTION SA
WHERE
  S.STATUS NOT IN ('CAN','NEW','SUB')
AND
  SA.SALE_ID = S.ID
AND
  S.CROMOD_DATE = SA.ACTION_DATE
AND
  SA.ACTION_TYPE IN ('CRO','MOD')
AND
  SA.REQUESTED_DATE >= <DATE>;

INSERT INTO CUST.SSA_ORDERLINE (ID, SALE_ID, SKU_CODE)
SELECT OL.ID, S.ID AS SALE_ID, OL.SKU_CODE
FROM CUST.SALE S, CUST.SALESACTION SA, CUST.ORDERLINE OL
WHERE
  S.STATUS NOT IN ('CAN','NEW','SUB')
AND
  SA.SALE_ID = S.ID
AND
  S.CROMOD_DATE = SA.ACTION_DATE
AND
  SA.ACTION_TYPE IN ('CRO','MOD')
AND
  OL.SALESACTION_ID = SA.ID
AND
  SA.REQUESTED_DATE >= <DATE>
