DELETE FROM OCF_PROFILEACTION
WHERE ACTION_ID IN (SELECT ID FROM OCF_ACTION WHERE FLIGHT_ID IN (SELECT ID FROM OCF_FLIGHT WHERE LIST_ID IN (SELECT ID FROM OCF_LIST WHERE STORED_QUERY_ID IS NOT NULL)));


DELETE FROM OCF_ACTION
WHERE FLIGHT_ID IN (SELECT ID FROM OCF_FLIGHT WHERE LIST_ID IN (SELECT ID FROM OCF_LIST WHERE STORED_QUERY_ID IS NOT NULL));


DELETE FROM OCF_FLIGHT
WHERE LIST_ID IN (SELECT ID FROM OCF_LIST WHERE STORED_QUERY_ID IS NOT NULL);

DELETE FROM OCF_LIST WHERE STORED_QUERY_ID IS NOT NULL;

DELETE FROM LIST_STORED_QUERY_VALUE;
DELETE FROM LIST_STORED_QUERY;
DELETE FROM LIST_QUERY_DROPDOWN_CLAUSE;
DELETE FROM LIST_STATIC_DROPDOWN_CLAUSE;
DELETE FROM LIST_SELECT_DROPDOWN_CLAUSE;
DELETE FROM LIST_PARAM_CLAUSE;
DELETE FROM LIST_CONSTANT_CLAUSE;
DELETE FROM LIST_ENUM_DROPDOWN_CLAUSE;
DELETE FROM LIST_JOIN_CLAUSE;
DELETE FROM LIST_CLAUSE;
DELETE FROM LIST_TEMPLATE_FIELD;
DELETE FROM LIST_TEMPLATE_GROUP_BY;
DELETE FROM LIST_TEMPLATE_ORDER_BY;
DELETE FROM LIST_TEMPLATE_OBJECT;
DELETE FROM LIST_TEMPLATE;
DELETE FROM LIST_VIRTUAL_OBJECT;
DELETE FROM LIST_OPERATOR;



ALTER TABLE OCF_LIST
DROP CONSTRAINT LIST_STORED_QUERY;

ALTER TABLE LIST_QUERY_DROPDOWN_CLAUSE
DROP CONSTRAINT QUERY_DROPDOWN_CLAUSE_QUERY;

DROP TABLE LIST_STORED_QUERY_VALUE;
DROP TABLE LIST_STORED_QUERY;
DROP TABLE LIST_STATIC_DROPDOWN_CLAUSE;
DROP TABLE LIST_QUERY_DROPDOWN_CLAUSE;
DROP TABLE LIST_SELECT_DROPDOWN_CLAUSE;
DROP TABLE LIST_PARAM_CLAUSE;
DROP TABLE LIST_CONSTANT_CLAUSE;
DROP TABLE LIST_ENUM_DROPDOWN_CLAUSE;
DROP TABLE LIST_JOIN_CLAUSE;
DROP TABLE LIST_CLAUSE;
DROP TABLE LIST_TEMPLATE_FIELD;
DROP TABLE LIST_TEMPLATE_GROUP_BY;
DROP TABLE LIST_TEMPLATE_ORDER_BY;
DROP TABLE LIST_TEMPLATE_OBJECT;
DROP TABLE LIST_TEMPLATE;
DROP TABLE LIST_VIRTUAL_OBJECT;
DROP TABLE LIST_OPERATOR;
