INSERT INTO CUST.AFFILIATE(CODE, NAME, DESCRIPTION, COND_TAX, COND_DEPOSIT) VALUES('FD', 'FreshDirect', 'FreshDirect Inc', 'ZT01', 'ZBD1');
INSERT INTO CUST.AFFILIATE(CODE, NAME, DESCRIPTION, COND_TAX, COND_DEPOSIT) VALUES('WBL', 'WBL', 'WBL Inc', 'ZT02', 'ZBD2');
INSERT INTO CUST.AFFILIATE(CODE, NAME, DESCRIPTION, COND_TAX, COND_DEPOSIT) VALUES('BC', 'Best Cellars', 'Best Cellars Inc', 'ZT03', 'ZBD3');
