CREATE TABLE TRANSP.USER_PREF
(

  USER_ID  VARCHAR2(50 BYTE)                    NOT NULL,
  KEY      VARCHAR2(100 BYTE),
  VALUE    VARCHAR2(500 BYTE)
);

 

ALTER TABLE TRANSP.USER_PREF ADD (
  CONSTRAINT USER_PK
 PRIMARY KEY
 (USER_ID, KEY));
  

GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON  USER_PREF TO FDTRN_PRDA;

 
