CREATE TABLE TRANSP.TRN_FACILITYLOCATION
(
  LOCATION_CODE  VARCHAR2(32 BYTE)              NOT NULL,
  DESCRIPTION    VARCHAR2(256 BYTE)
);

ALTER TABLE TRANSP.TRN_FACILITYLOCATION ADD (  CONSTRAINT PK_FACILITYLOCATION PRIMARY KEY (LOCATION_CODE));
