GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE_EX TO fdstore_stprd01;
GRANT DELETE, INSERT, SELECT, UPDATE ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE_EX TO fdtrn_stprd01;
GRANT SELECT ON TRANSP.HANDOFF_BATCHDEPOTSCHEDULE_EX TO APPDEV;