ALTER TABLE DLV.RESERVATION  ADD  RESERVED_ORDER_SIZE NUMBER(10,2);
ALTER TABLE DLV.RESERVATION  ADD  RESERVED_SERVICE_TIME NUMBER(10,2);

ALTER TABLE DLV.RESERVATION  ADD  ORDER_SIZE NUMBER(10,2);
ALTER TABLE DLV.RESERVATION  ADD  SERVICE_TIME NUMBER(10,2);

ALTER TABLE DLV.RESERVATION  ADD  UPDATE_STATUS VARCHAR2(3 BYTE);
ALTER TABLE DLV.RESERVATION  ADD  IS_FORCED VARCHAR2(1 BYTE);

ALTER TABLE DLV.TIMESLOT  ADD  IS_DYNAMIC VARCHAR2(1 BYTE);
ALTER TABLE DLV.TIMESLOT  ADD  IS_CLOSED VARCHAR2(1 BYTE);

ALTER TABLE TRANSP.TRN_AREA ADD DELIVERY_RATE NUMBER(5,2)  DEFAULT 12.0;

GRANT SELECT ON TRANSP.TRN_AREA TO DLV;
GRANT SELECT ON TRANSP.ZONE TO DLV;