-- UNATTENDED 'X' for true, ' ' for false
CREATE TABLE DLV.ZONE_DESC (
   ZONE_CODE VARCHAR2(5) PRIMARY KEY, 
   UNATTENDED VARCHAR2(1) DEFAULT ' ' NOT NULL 
);


INSERT INTO DLV.ZONE_DESC (ZONE_CODE) SELECT DISTINCT(ZONE_CODE) FROM ZONE;

GRANT SELECT,INSERT, UPDATE,DELETE ON DLV.ZONE_DESC TO FDSTORE_PRDA, FDSTORE_PRDB;





