GRANT SELECT, INSERT, DELETE, UPDATE on cust.referral_prgm to FDSTORE_STSTG01;
GRANT SELECT, INSERT, DELETE, UPDATE on cust.referral_prgm to FDMKT_STSTG01;
GRANT SELECT on cust.referral_prgm to APPDEV;

GRANT SELECT, INSERT, DELETE, UPDATE on cust.referral_customer_list to FDSTORE_STSTG01;
GRANT SELECT, INSERT, DELETE, UPDATE on cust.referral_customer_list to FDMKT_STSTG01;
GRANT SELECT on cust.referral_customer_list to APPDEV;

GRANT SELECT, INSERT, DELETE, UPDATE on cust.referral_link to FDSTORE_STSTG01;
GRANT SELECT, INSERT, DELETE, UPDATE on cust.referral_link to FDMKT_STSTG01;
GRANT SELECT on cust.referral_link to APPDEV;

GRANT SELECT, INSERT, DELETE, UPDATE on cust.CUSTOMER_INVITES to FDSTORE_STSTG01;
GRANT SELECT, INSERT, DELETE, UPDATE on cust.CUSTOMER_INVITES to FDMKT_STSTG01;
GRANT SELECT on cust.CUSTOMER_INVITES to APPDEV;

GRANT SELECT, INSERT, DELETE, UPDATE on cust.RAF_FAILED_ATTEMPTS to FDSTORE_STSTG01;
GRANT SELECT, INSERT, DELETE, UPDATE on cust.RAF_FAILED_ATTEMPTS to FDMKT_STSTG01;
GRANT SELECT on cust.RAF_FAILED_ATTEMPTS to APPDEV;
