ALTER TABLE TRANSP.WAVE_INSTANCE DROP CONSTRAINT ACT_WAVE_INSTANCE_UK;

ALTER TABLE TRANSP.WAVE_INSTANCE ADD ( CONSTRAINT WAVEINSTANCE_UK UNIQUE (ORIGIN_FACILITY, DELIVERY_DATE, AREA, DISPATCH_TIME, FIRST_DLV_TIME, LAST_DLV_TIME, CUTOFF_DATETIME));