GRANT SELECT, DELETE, INSERT, UPDATE ON MIS.UNAV_ITEMS_INV TO fdstore_stprd01;
GRANT SELECT, DELETE, INSERT, UPDATE ON MIS.UNAV_ITEMS_INV TO fdtrn_stprd01;
GRANT SELECT ON MIS.UNAV_ITEMS_INV TO appdev;
