DROP PUBLIC DATABASE LINK "AIRCLIC.NYC.FRESHDIRECT.COM";

CREATE PUBLIC DATABASE LINK "AIRCLIC.NYC.FRESHDIRECT.COM"
 CONNECT TO AIRCLIC_RO
 IDENTIFIED BY <PWD>
 USING 'airclic';

DROP PUBLIC DATABASE LINK "AIRCLICRW.NYC.FRESHDIRECT.COM";

CREATE PUBLIC DATABASE LINK "AIRCLICRW.NYC.FRESHDIRECT.COM"
 CONNECT TO AIRCLIC_STAGE
 IDENTIFIED BY <PWD>
 USING 'airclic';


DROP VIEW DLV.CARTONSTATUS;

/* Formatted on 2/14/2012 10:31:41 AM (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW DLV.CARTONSTATUS
(
   SCANDATE,
   WEBORDERNUM,
   CARTONID,
   ACTION,
   CARTONSTATUS,
   EMPLOYEE,
   ROUTE,
   STOP,
   NEXTELID,
   USERID,
   EVENTID
)
AS
   SELECT scandate,
          webordernum,
          cartonid,
          action,
          cartonstatus,
          employee,
          route,
          stop,
          nextelid,
          userid,
          eventid
     FROM airclic_stage.cartonstatus@AIRCLICRW.NYC.FRESHDIRECT.COM;

DROP VIEW DLV.ORDERS;

/* Formatted on 2/14/2012 10:32:12 AM (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW DLV.ORDERS
(
   ROUTE,
   ORDER_NUMBER,
   STOP,
   NOTE
)
AS
   SELECT route,
          order_number,
          stop,
          note
     FROM airclic_stage.orders@AIRCLICrw.NYC.FRESHDIRECT.COM;


DROP VIEW DLV.ORDERUPDATE;

/* Formatted on 2/14/2012 10:32:25 AM (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW DLV.ORDERUPDATE
(
   USERID,
   ORDER_NUMBER,
   NOTE
)
AS
   SELECT "USERID", "ORDER_NUMBER", "NOTE"
     FROM airclic_stage.ORDERUPDATE@AIRCLICRW.NYC.FRESHDIRECT.COM;


DROP VIEW DLV.ROUTEDOWNLOAD;

/* Formatted on 2/14/2012 10:32:32 AM (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW DLV.ROUTEDOWNLOAD
(
   USERID,
   SCANDATE,
   ROUTE,
   HANDLE,
   ORDER_NUMBER
)
AS
   SELECT "USERID",
          "SCANDATE",
          "ROUTE",
          "HANDLE",
          "ORDER_NUMBER"
     FROM airclic_stage.ROUTEDOWNLOAD@AIRCLICRW.NYC.FRESHDIRECT.COM;



DROP VIEW DLV.ROUTEUPDATE;

/* Formatted on 2/14/2012 10:32:40 AM (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW DLV.ROUTEUPDATE
(
   USERID,
   ROUTE_NUMBER,
   NOTE
)
AS
   SELECT "USERID", "ROUTE_NUMBER", "NOTE"
     FROM airclic_stage.ROUTEUPDATE@AIRCLICRW.NYC.FRESHDIRECT.COM;


DROP VIEW DLV.SIGNATURE;

/* Formatted on 2/14/2012 10:32:46 AM (QP5 v5.139.911.3011) */
CREATE OR REPLACE FORCE VIEW DLV.SIGNATURE
(
   EVENTID,
   SIGNATURE_TIMESTAMP,
   DELIVEREDTO,
   RECIPIENT,
   CONTAINS_ALCOHOL,
   SIGNATURE
)
AS
   SELECT "EVENTID",
          "SIGNATURE_TIMESTAMP",
          "DELIVEREDTO",
          "RECIPIENT",
          "CONTAINS_ALCOHOL",
          "SIGNATURE"
     FROM airclic_stage.SIGNATURE@AIRCLICRW.NYC.FRESHDIRECT.COM;




ALTER TABLE DLV.AIRCLIC_MESSAGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DLV.AIRCLIC_MESSAGE CASCADE CONSTRAINTS;

CREATE TABLE DLV.AIRCLIC_MESSAGE
(
  ID           NUMBER,
  MESSAGE      VARCHAR2(50 BYTE),
  DESCRIPTION  VARCHAR2(100 BYTE)
)
TABLESPACE FDSTODAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DLV.AIRCLIC_MESSAGE ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE FDSTODAT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));




ALTER TABLE DLV.AIRCLIC_TXTMESSAGE
 DROP PRIMARY KEY CASCADE;

DROP TABLE DLV.AIRCLIC_TXTMESSAGE CASCADE CONSTRAINTS;

CREATE TABLE DLV.AIRCLIC_TXTMESSAGE
(
  ID               NUMBER(10),
  CREATEDATE       DATE,
  SENDER           VARCHAR2(50 BYTE),
  MESSAGE          VARCHAR2(250 BYTE),
  SOURCE           VARCHAR2(50 BYTE),
  ROUTE            VARCHAR2(50 BYTE),
  STOP             NUMBER(9),
  ORDERID          VARCHAR2(16 BYTE),
  SENT_TO_AIRCLIC  VARCHAR2(1 BYTE)             DEFAULT 'N',
  DELIVERYDATE     DATE
)
TABLESPACE FDDLVDAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE DLV.AIRCLIC_TXTMESSAGE ADD (
  PRIMARY KEY
 (ID)
    USING INDEX 
    TABLESPACE FDDLVDAT
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));






DROP TABLE CUST.SALE_SIGNATURE CASCADE CONSTRAINTS;

CREATE TABLE CUST.SALE_SIGNATURE
(
  SALE_ID              VARCHAR2(16 BYTE)        NOT NULL,
  SIGNATURE_TIMESTAMP  DATE,
  DELIVEREDTO          VARCHAR2(250 BYTE),
  RECIPIENT            VARCHAR2(250 BYTE),
  CONTAINS_ALCOHOL     VARCHAR2(250 BYTE),
  SIGNATURE            LONG RAW
)
TABLESPACE FDCUSDAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


DROP TABLE CUST.SALESIGN_EXPORT CASCADE CONSTRAINTS;

CREATE TABLE CUST.SALESIGN_EXPORT
(
  LAST_EXPORT  DATE,
  SUCCESS      CHAR(1 BYTE)                     DEFAULT 'N'
)
TABLESPACE FDCUSDAT
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


SET DEFINE OFF;
Insert into DLV.AIRCLIC_MESSAGE
   (ID, MESSAGE, DESCRIPTION)
 Values
   (1, 'Call OPS Center', 'Call OPS Center');
Insert into DLV.AIRCLIC_MESSAGE
   (ID, MESSAGE, DESCRIPTION)
 Values
   (2, 'Late Deliveries', 'Call OPS Center if you will have late deliveries');
Insert into DLV.AIRCLIC_MESSAGE
   (ID, MESSAGE, DESCRIPTION)
 Values
   (3, 'Cancelled Order', 'Do Not Deliver Stop X, Order has been cancelled');
Insert into DLV.AIRCLIC_MESSAGE
   (ID, MESSAGE, DESCRIPTION)
 Values
   (4, 'Redelivery Attempt', 'Please redeliver Stop X, Customer is now home.');
COMMIT;





