ALTER TABLE DLV.SERVICETIME ADD (CONSTRAINT ACT_SERVICETIME_FK FOREIGN KEY (SERVICETIME_TYPE) REFERENCES DLV.SERVICETIME_TYPE (CODE));
ALTER TABLE DLV.SERVICETIME_SCENARIO ADD (CONSTRAINT ACT_SCENARIO_STTYPE_FK FOREIGN KEY (DEFAULT_SERVICETIME_TYPE) REFERENCES DLV.SERVICETIME_TYPE (CODE));

ALTER TABLE DLV.SERVICETIME_TYPE drop(FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME);
   
ALTER TABLE DLV.SERVICETIME_SCENARIO ADD (CONSTRAINT ACT_SCENARIO_STTYPE_FK FOREIGN KEY (DEFAULT_SERVICETIME_TYPE) REFERENCES DLV.SERVICETIME_TYPE (CODE));

DROP TABLE DLV.SCENARIO_DAYS CASCADE CONSTRAINTS;

DROP SEQUENCE DLV.DELIVERY_SCENARIO_SEQ;

DROP TABLE DLV.SCENARIO_ZONES CASCADE CONSTRAINTS;

ALTER TABLE DLV.DELIVERY_BUILDING drop (SERVICETIME_OVERRIDE,SERVICETIME_OPERATOR,SERVICETIME_ADJUSTMENT);

ALTER TABLE DLV.DELIVERY_BUILDING_DTL ADD (CONSTRAINT ACT_DELIVERY_BUILDING_DTL_FK FOREIGN KEY (DELIVERY_BUILDING_ID) REFERENCES DLV.DELIVERY_BUILDING (ID));

ALTER TABLE DLV.DELIVERY_LOCATION drop (SERVICETIME_OVERRIDE,SERVICETIME_OPERATOR,SERVICETIME_ADJUSTMENT);

ALTER TABLE DLV.DELIVERY_LOCATION drop CONSTRAINT ACT_DELIVERY_LOCATIONST_FK;


--AS TRANSP schema owner
ALTER TABLE TRANSP.ZONE drop column SERVICETIME_TYPE;

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '601';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '202';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '033';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '181';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '095';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '182';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '201';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '801';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1'   WHERE ZONE_CODE = '102';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '1001'   WHERE ZONE_CODE = '800';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '912';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '914';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '931';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '941';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '913';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '942';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '999';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '911';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '080';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '915';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '24'   WHERE ZONE_CODE = '901';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '465'   WHERE ZONE_CODE = '107';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '465'   WHERE ZONE_CODE = '021';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '465'   WHERE ZONE_CODE = '022';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '465'   WHERE ZONE_CODE = '108';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '466'   WHERE ZONE_CODE = '720';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '466'   WHERE ZONE_CODE = '921';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '466'   WHERE ZONE_CODE = '951';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '466'   WHERE ZONE_CODE = '710';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '466'   WHERE ZONE_CODE = '961';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '467'   WHERE ZONE_CODE = '008';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '467'   WHERE ZONE_CODE = '105';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '467'   WHERE ZONE_CODE = '018';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '467'   WHERE ZONE_CODE = '180';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '467'   WHERE ZONE_CODE = '101';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '467'   WHERE ZONE_CODE = '020';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '468'   WHERE ZONE_CODE = '560';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '468'   WHERE ZONE_CODE = '400';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '468'   WHERE ZONE_CODE = '003';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '468'   WHERE ZONE_CODE = '010';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '469'   WHERE ZONE_CODE = '501';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '469'   WHERE ZONE_CODE = '420';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '469'   WHERE ZONE_CODE = '012';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '469'   WHERE ZONE_CODE = '410';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '510';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '090';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '009';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '500';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '103';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '011';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '006';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '016';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '007';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '104';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '330';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '430';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '470'   WHERE ZONE_CODE = '515';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '471'   WHERE ZONE_CODE = '004';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '471'   WHERE ZONE_CODE = '320';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '472'   WHERE ZONE_CODE = '505';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '473'   WHERE ZONE_CODE = '830';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '473'   WHERE ZONE_CODE = '875';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '473'   WHERE ZONE_CODE = '840';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '473'   WHERE ZONE_CODE = '015';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '474'   WHERE ZONE_CODE = '580';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '474'   WHERE ZONE_CODE = '380';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '474'   WHERE ZONE_CODE = '310';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '474'   WHERE ZONE_CODE = '002';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '475'   WHERE ZONE_CODE = '360';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '610';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '697';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '250';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '600';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '698';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '630';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '620';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '482'   WHERE ZONE_CODE = '660';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '562'   WHERE ZONE_CODE = '109';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '562'   WHERE ZONE_CODE = '561';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '562'   WHERE ZONE_CODE = '200';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '562'   WHERE ZONE_CODE = '785';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '562'   WHERE ZONE_CODE = '780';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '562'   WHERE ZONE_CODE = '730';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '562'   WHERE ZONE_CODE = '106';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '564'   WHERE ZONE_CODE = '350';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '564'   WHERE ZONE_CODE = '700';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '566'   WHERE ZONE_CODE = '581';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '568'   WHERE ZONE_CODE = '001';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '570'   WHERE ZONE_CODE = '019';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '570'   WHERE ZONE_CODE = '370';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '570'   WHERE ZONE_CODE = '340';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '571'   WHERE ZONE_CODE = '582';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '573'   WHERE ZONE_CODE = '017';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '005';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '070';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '050';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '060';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '014';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '013';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '066';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '040';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '582'   WHERE ZONE_CODE = '030';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '604'   WHERE ZONE_CODE = '680';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '604'   WHERE ZONE_CODE = '690';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '641'   WHERE ZONE_CODE = '650';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '641'   WHERE ZONE_CODE = '640';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '681'   WHERE ZONE_CODE = '685';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '81'   WHERE ZONE_CODE = '922';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '821'   WHERE ZONE_CODE = '850';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '821'   WHERE ZONE_CODE = '860';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '821'   WHERE ZONE_CODE = '810';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '821'   WHERE ZONE_CODE = '825';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '821'   WHERE ZONE_CODE = '820';

UPDATE into TRANSP.ZONE  set ZONE_TYPE = '882'   WHERE ZONE_CODE = '802';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '885'   WHERE ZONE_CODE = '890';
UPDATE into TRANSP.ZONE  set ZONE_TYPE = '921'   WHERE ZONE_CODE = '506';

