package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA


/**
 * EmployeeRoleType generated by hbm2java
 */
public class AssetAttributeType implements java.io.Serializable {

	private AssetAttributeTypeId id;
	
	private String description;
	
	private String dataType;
		
	public AssetAttributeType(AssetAttributeTypeId id, String description,
			String dataType) {
		super();
		this.id = id;
		this.description = description;
		this.dataType = dataType;
	}
	
	public AssetAttributeType() {
	}	

	public String getDescription() {
		return description;
	}

	
	public void setDescription(String description) {
		this.description = description;
	}

	public String getDataType() {
		return dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}
	
	public AssetAttributeTypeId getId() {
		return id;
	}

	public void setId(AssetAttributeTypeId id) {
		this.id = id;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AssetAttributeType other = (AssetAttributeType) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	

}
