package com.freshdirect.transadmin.model;

//Generated Dec 5, 2008 2:34:33 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

import com.freshdirect.transadmin.constants.EnumAssetStatus;

/**
 * Dispatch generated by hbm2java
 */
public class AssetTemplate implements java.io.Serializable{

	private String assetTemplateId;
	private String assetTemplateName;
	private AssetType assetType;
	
	private Set assetTemplateAttributes = new HashSet(0);
		
	public AssetTemplate() {
	}

	public AssetTemplate(String assetId) {
		super();
		this.assetTemplateId = assetTemplateId;
	}

	public AssetTemplate(String assetTemplateId, String assetTemplateName,
			AssetType assetType) {
		super();
		this.assetTemplateId = assetTemplateId;		
		this.assetTemplateName = assetTemplateName;
		this.assetType = assetType;
	}

	public AssetTemplate(String assetTemplateId,
			String assetTemplateName, AssetType assetType,
			Set assetTemplateAttributes) {
		super();
		this.assetTemplateId = assetTemplateId;
		this.assetTemplateName = assetTemplateName;
		this.assetType = assetType;
		this.assetTemplateAttributes = assetTemplateAttributes;
	}

	public String getAssetTemplateId() {
		return assetTemplateId;
	}

	public void setAssetTemplateId(String assetTemplateId) {
		this.assetTemplateId = assetTemplateId;
	}

	public String getAssetTemplateName() {
		return assetTemplateName;
	}

	public void setAssetTemplateName(String assetTemplateName) {
		this.assetTemplateName = assetTemplateName;
	}

	public AssetType getAssetType() {
		return assetType;
	}

	public void setAssetType(AssetType assetType) {
		this.assetType = assetType;
	}

	public Set getAssetTemplateAttributes() {
		return assetTemplateAttributes;
	}

	public void setAssetTemplateAttributes(Set assetTemplateAttributes) {
		this.assetTemplateAttributes = assetTemplateAttributes;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((assetTemplateId == null) ? 0 : assetTemplateId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AssetTemplate other = (AssetTemplate) obj;
		if (assetTemplateId == null) {
			if (other.assetTemplateId != null)
				return false;
		} else if (!assetTemplateId.equals(other.assetTemplateId))
			return false;
		return true;
	}
	
	
}
