package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * DispatchResource generated by hbm2java
 */
public class AssetAttribute implements java.io.Serializable {

	private AssetAttributeId id;
	private String attributeValue;
	
	public AssetAttribute() {
	}

	public AssetAttribute(AssetAttributeId id, String attributeValue) {
		this.id = id;
		this.attributeValue = attributeValue;		
	}

	public AssetAttributeId getId() {
		return id;
	}

	public String getAttributeValue() {
		return attributeValue;
	}

	public void setId(AssetAttributeId id) {
		this.id = id;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AssetAttribute other = (AssetAttribute) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}
	
	

}
