package com.freshdirect.transadmin.model;

import com.freshdirect.transadmin.model.AssetAttributeTypeId;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * DispatchResourceId generated by hbm2java
 */
public class AssetAttributeTypeId implements java.io.Serializable {

	private String code;
	private String assetType;
	
	public AssetAttributeTypeId() {
	}

	public AssetAttributeTypeId(String code, String assetType) {
		this.code = code;
		this.assetType = assetType;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getAssetType() {
		return assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		result = prime * result
				+ ((assetType == null) ? 0 : assetType.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AssetAttributeTypeId other = (AssetAttributeTypeId) obj;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		if (assetType == null) {
			if (other.assetType != null)
				return false;
		} else if (!assetType.equals(other.assetType))
			return false;
		return true;
	}
	

}
