package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * DispatchResourceId generated by hbm2java
 */
public class AssetTemplateAttributeId implements java.io.Serializable {

	private String assetTemplateId;
	private String attributeType;
	
	public AssetTemplateAttributeId() {
	}

	public AssetTemplateAttributeId(String assetId, String attributeType) {
		this.assetTemplateId = assetId;
		this.attributeType = attributeType;
	}	

	public String getAssetTemplateId() {
		return assetTemplateId;
	}

	public void setAssetTemplateId(String assetTemplateId) {
		this.assetTemplateId = assetTemplateId;
	}

	public String getAttributeType() {
		return attributeType;
	}

	public void setAttributeType(String attributeType) {
		this.attributeType = attributeType;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((assetTemplateId == null) ? 0 : assetTemplateId.hashCode());
		result = prime * result
				+ ((attributeType == null) ? 0 : attributeType.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		AssetTemplateAttributeId other = (AssetTemplateAttributeId) obj;
		if (assetTemplateId == null) {
			if (other.assetTemplateId != null)
				return false;
		} else if (!assetTemplateId.equals(other.assetTemplateId))
			return false;
		if (attributeType == null) {
			if (other.attributeType != null)
				return false;
		} else if (!attributeType.equals(other.attributeType))
			return false;
		return true;
	}
	

}
