package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * DispatchResource generated by hbm2java
 */
public class DispatchResource implements ResourceI, java.io.Serializable {

	private ResourceId id;
	private Dispatch dispatch;
	private String nextTelNo;
	
	private EmployeeRoleType employeeRoleType;

	public DispatchResource() {
	}

	public DispatchResource(ResourceId id, Dispatch dispatch,
			EmployeeRoleType employeeRoleType) {
		this.id = id;
		this.dispatch = dispatch;
		this.employeeRoleType = employeeRoleType;
	}

	public ResourceId getId() {
		return this.id;
	}

	public void setId(ResourceId id) {
		this.id = id;
	}

	public Dispatch getDispatch() {
		return this.dispatch;
	}

	public void setDispatch(Dispatch dispatch) {
		this.dispatch = dispatch;
	}

	public EmployeeRoleType getEmployeeRoleType() {
		return this.employeeRoleType;
	}

	public void setEmployeeRoleType(EmployeeRoleType employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	public String getNextTelNo() {
		return nextTelNo;
	}

	public void setNextTelNo(String nextTelNo) {
		this.nextTelNo = nextTelNo;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DispatchResource other = (DispatchResource) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		return true;
	}

}
