package com.freshdirect.transadmin.model;

//Generated Dec 4, 2008 3:51:59 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * DispositionType generated by hbm2java
 */
public class DispositionType implements java.io.Serializable {

	private String code;
	private String name;
	private String description;
	private Set dispatchs = new HashSet(0);

	public DispositionType() {
	}

	public DispositionType(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public DispositionType(String code, String name, String description,
			Set dispatchs) {
		this.code = code;
		this.name = name;
		this.description = description;
		this.dispatchs = dispatchs;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getDispatchs() {
		return this.dispatchs;
	}

	public void setDispatchs(Set dispatchs) {
		this.dispatchs = dispatchs;
	}

}
