package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * DispatchResourceId generated by hbm2java
 */
public class DispatchResourceId implements java.io.Serializable {

	private String dispatchId;
	private String resourceId;
	
	public DispatchResourceId() {
	}

	public DispatchResourceId(String dispatchId, String resourceId) {
		this.dispatchId = dispatchId;
		this.resourceId = resourceId;
	}

	public String getDispatchId() {
		return this.dispatchId;
	}

	public void setDispatchId(String dispatchId) {
		this.dispatchId = dispatchId;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DispatchResourceId))
			return false;
		DispatchResourceId castOther = (DispatchResourceId) other;

		return ((this.getDispatchId() == castOther.getDispatchId()) || (this
				.getDispatchId() != null
				&& castOther.getDispatchId() != null && this.getDispatchId()
				.equals(castOther.getDispatchId())))
				&& ((this.getResourceId() == castOther.getResourceId()) || (this
						.getResourceId() != null
						&& castOther.getResourceId() != null && this
						.getResourceId().equals(castOther.getResourceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getDispatchId() == null ? 0 : this.getDispatchId()
						.hashCode());
		result = 37
				* result
				+ (getResourceId() == null ? 0 : this.getResourceId()
						.hashCode());
		return result;
	}

}
