package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * DispatchResource generated by hbm2java
 */
public class DispatchResource implements ResourceI, java.io.Serializable {

	private ResourceId id;
	private Dispatch dispatch;
	private String nextTelNo;
	
	private EmployeeRoleType employeeRoleType;

	public DispatchResource() {
	}

	public DispatchResource(ResourceId id, Dispatch dispatch,
			EmployeeRoleType employeeRoleType) {
		this.id = id;
		this.dispatch = dispatch;
		this.employeeRoleType = employeeRoleType;
	}

	public ResourceId getId() {
		return this.id;
	}

	public void setId(ResourceId id) {
		this.id = id;
	}

	public Dispatch getDispatch() {
		return this.dispatch;
	}

	public void setDispatch(Dispatch dispatch) {
		this.dispatch = dispatch;
	}

	public EmployeeRoleType getEmployeeRoleType() {
		return this.employeeRoleType;
	}

	public void setEmployeeRoleType(EmployeeRoleType employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	public String getNextTelNo() {
		return nextTelNo;
	}

	public void setNextTelNo(String nextTelNo) {
		this.nextTelNo = nextTelNo;
	}

}
