package com.freshdirect.transadmin.model;

// Generated May 20, 2008 2:33:06 PM by Hibernate Tools 3.2.0.b9

/**
 * ServicetimeId generated by hbm2java
 */
public class DlvServiceTimeId implements java.io.Serializable {

	private String serviceTimeType;

	private String zoneType;

	public DlvServiceTimeId() {
	}

	public DlvServiceTimeId(String servicetimeType, String zoneType) {
		this.serviceTimeType = servicetimeType;
		this.zoneType = zoneType;
	}

	

	public String getServiceTimeType() {
		return serviceTimeType;
	}

	public void setServiceTimeType(String serviceTimeType) {
		this.serviceTimeType = serviceTimeType;
	}

	
	
	public String getId() {
		return serviceTimeType+"$"+zoneType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DlvServiceTimeId))
			return false;
		DlvServiceTimeId castOther = (DlvServiceTimeId) other;

		return ((this.getServiceTimeType() == castOther.getServiceTimeType()) || (this
				.getServiceTimeType() != null
				&& castOther.getServiceTimeType() != null && this
				.getServiceTimeType().equals(castOther.getServiceTimeType())))
				&& ((this.getZoneType() == castOther.getZoneType()) || (this
						.getZoneType() != null
						&& castOther.getZoneType() != null && this
						.getZoneType().equals(castOther.getZoneType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getServiceTimeType() == null ? 0 : this.getServiceTimeType()
						.hashCode());
		result = 37
				* result
				+ (getZoneType() == null ? 0 : this.getZoneType()
						.hashCode());
		return result;
	}

	public String getZoneType() {
		return zoneType;
	}

	public void setZoneType(String zoneType) {
		this.zoneType = zoneType;
	}

}
