package com.freshdirect.transadmin.model;

// Generated May 20, 2008 2:33:06 PM by Hibernate Tools 3.2.0.b9

import java.math.BigDecimal;

/**
 * Servicetime generated by hbm2java
 */
public class DlvServiceTime implements java.io.Serializable, TrnBaseEntityI {

	private DlvServiceTimeId id;
	
	private BigDecimal fixedServiceTime;
	
	private BigDecimal variableServiceTime;

	public DlvServiceTime() {
	}

	public DlvServiceTime(DlvServiceTimeId id) {
		this.id = id;		
	}

	public DlvServiceTime(DlvServiceTimeId id, BigDecimal fixedServiceTime, BigDecimal variableServiceTime) {
		this.id = id;		
		this.fixedServiceTime = fixedServiceTime;
		this.variableServiceTime = variableServiceTime;
	}

	public DlvServiceTimeId getId() {
		return this.id;
	}

	public void setId(DlvServiceTimeId id) {
		this.id = id;
	}

	
	
	public BigDecimal getFixedServiceTime() {
		return fixedServiceTime;
	}

	public void setFixedServiceTime(BigDecimal fixedServiceTime) {
		this.fixedServiceTime = fixedServiceTime;
	}

	public BigDecimal getVariableServiceTime() {
		return variableServiceTime;
	}

	public void setVariableServiceTime(BigDecimal variableServiceTime) {
		this.variableServiceTime = variableServiceTime;
	}

	public String getServiceTimeType() {
		if(this.getId() == null) {
			return null;
		}
		return this.getId().getServiceTimeType();
	}

	public void setServiceTimeType(String serviceTimeType) {
		if(this.getId() == null) {
			this.setId(new DlvServiceTimeId());
		}
		this.getId().setServiceTimeType(serviceTimeType);
	}

	public String getZoneType() {
		if(this.getId() == null) {
			return null;
		}
		return this.getId().getZoneType();
	}

	public void setZoneType(String serviceType) {
		if(this.getId() == null) {
			this.setId(new DlvServiceTimeId());
		}
		this.getId().setZoneType(serviceType);
	}
	
	public boolean isObsoleteEntity() {
		return false;
	}

}
