package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeRoleType generated by hbm2java
 */
public class EmployeeRoleType implements java.io.Serializable {

	private String code;
	private String name;
	private String description;
	private Set subRoles;
	
	public EmployeeRoleType() {
	}

	public EmployeeRoleType(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public EmployeeRoleType(String code, String name, String description) {
			
		this.code = code;
		this.name = name;
		this.description = description;
		
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getSubRoles() {
		return subRoles;
	}

	public void setSubRoles(Set subRoles) {
		this.subRoles = subRoles;
	}

}
