package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * EmployeeroleId generated by hbm2java
 */
public class EmployeeTruckPreferenceId implements java.io.Serializable {

	private String kronosId;
	private String prefKey;

	public EmployeeTruckPreferenceId() {
	}

	public EmployeeTruckPreferenceId(String kronosId, String prefKey) {
		this.kronosId = kronosId;
		this.prefKey = prefKey;
	}

	public String getKronosId() {
		return this.kronosId;
	}

	public void setKronosId(String kronosId) {
		this.kronosId = kronosId;
	}

	public String getPrefKey() {
		return prefKey;
	}

	public void setPrefKey(String prefKey) {
		this.prefKey = prefKey;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeTruckPreferenceId))
			return false;
		EmployeeTruckPreferenceId castOther = (EmployeeTruckPreferenceId) other;

		return ((this.getKronosId() == castOther.getKronosId()) || (this
				.getKronosId() != null
				&& castOther.getKronosId() != null && this.getKronosId()
				.equals(castOther.getKronosId())))
				&& ((this.getPrefKey() == castOther.getPrefKey()) || (this.getPrefKey() != null
						&& castOther.getPrefKey() != null && this.getPrefKey()
						.equals(castOther.getPrefKey())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKronosId() == null ? 0 : this.getKronosId().hashCode());
		result = 37 * result
				+ (getPrefKey() == null ? 0 : this.getPrefKey().hashCode());
		return result;
	}

}
