package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * Employee Role generated by hbm2java
 */
public class EmployeeTruckPreference implements java.io.Serializable {

	private EmployeeTruckPreferenceId id;
	private String truckNumber;
	
	public EmployeeTruckPreference() {	}    

	public EmployeeTruckPreference(EmployeeTruckPreferenceId id, String truckNumber) {
		this.id = id;
		this.truckNumber = truckNumber;
	}

	public EmployeeTruckPreferenceId getId() {
		return this.id;
	}

	public void setId(EmployeeTruckPreferenceId id) {
		this.id = id;
	}

	public String getTruckNumber() {
		return truckNumber;
	}

	public void setTruckNumber(String truckNumber) {
		this.truckNumber = truckNumber;
	}
}
