package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * Employee Role generated by hbm2java
 */
public class EmployeeRole implements java.io.Serializable {

	private EmployeeroleId id;
	private EmployeeRoleType employeeRoleType;

	public EmployeeRole() {
	}
    

	public EmployeeRole(EmployeeroleId id, EmployeeRoleType employeeRoleType) {
		this.id = id;
		this.employeeRoleType = employeeRoleType;
	}

	public EmployeeroleId getId() {
		return this.id;
	}

	public void setId(EmployeeroleId id) {
		this.id = id;
	}

	public EmployeeRoleType getEmployeeRoleType() {
		return this.employeeRoleType;
	}

	public void setEmployeeRoleType(EmployeeRoleType employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

}
