package com.freshdirect.transadmin.model;

/**
 * Employee Role generated by hbm2java
 */
public class EmployeeSupervisor implements java.io.Serializable {

	private EmployeeSupervisorId id;
	private String homeRegion;
	private String homeShift;

	public EmployeeSupervisor() {
	}    

	public EmployeeSupervisor(EmployeeSupervisorId id, String homeRegion, String homeShift) {
		this.id = id;
		this.homeRegion = homeRegion;
		this.homeShift = homeShift;
	}

	public EmployeeSupervisorId getId() {
		return this.id;
	}
	public void setId(EmployeeSupervisorId id) {
		this.id = id;
	}
	public String getHomeRegion() {
		return homeRegion;
	}
	public void setHomeRegion(String homeRegion) {
		this.homeRegion = homeRegion;
	}
	public String getHomeShift() {
		return homeShift;
	}
	public void setHomeShift(String homeShift) {
		this.homeShift = homeShift;
	}	
}