package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * EmployeeroleId generated by hbm2java
 */
public class EmployeeroleId implements java.io.Serializable {

	private String kronosId;
	private String role;

	public EmployeeroleId() {
	}

	public EmployeeroleId(String kronosId, String role) {
		this.kronosId = kronosId;
		this.role = role;
	}

	public String getKronosId() {
		return this.kronosId;
	}

	public void setKronosId(String kronosId) {
		this.kronosId = kronosId;
	}

	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeroleId))
			return false;
		EmployeeroleId castOther = (EmployeeroleId) other;

		return ((this.getKronosId() == castOther.getKronosId()) || (this
				.getKronosId() != null
				&& castOther.getKronosId() != null && this.getKronosId()
				.equals(castOther.getKronosId())))
				&& ((this.getRole() == castOther.getRole()) || (this.getRole() != null
						&& castOther.getRole() != null && this.getRole()
						.equals(castOther.getRole())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getKronosId() == null ? 0 : this.getKronosId().hashCode());
		result = 37 * result
				+ (getRole() == null ? 0 : this.getRole().hashCode());
		return result;
	}

}
