package com.freshdirect.transadmin.model;

// Generated Jan 7, 2009 10:45:25 AM by Hibernate Tools 3.2.2.GA

import java.io.Serializable;

/**
 * GeoRestrictionBoundary generated by hbm2java
 */
public class GeoRestrictionBoundary implements java.io.Serializable {

	private String code;
	private String name;

	
	public GeoRestrictionBoundary() {
	}

	public GeoRestrictionBoundary(String code, String name, Serializable geoloc) {
		this.code = code;
		this.name = name;
		
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	

}
