package com.freshdirect.transadmin.model;

// Generated Jan 7, 2009 10:45:25 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

/**
 * GeoRestrictionDays generated by hbm2java
 */
public class GeoRestrictionDays implements java.io.Serializable {

	private GeoRestrictionDaysId restrictionDaysId;
	private String condition;
	private Date startTime;
	private Date endTime;

	public GeoRestrictionDays() {
	}

	public GeoRestrictionDays(GeoRestrictionDaysId id) {
		this.restrictionDaysId = id;
	}

	public GeoRestrictionDays(GeoRestrictionDaysId id, String condition,
			Date startTime, Date endTime) {
		this.restrictionDaysId = id;
		this.condition = condition;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	

	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public GeoRestrictionDaysId getRestrictionDaysId() {
		return restrictionDaysId;
	}

	public void setRestrictionDaysId(GeoRestrictionDaysId restrictionDaysId) {
		this.restrictionDaysId = restrictionDaysId;
	}

}
