package com.freshdirect.transadmin.model;

// Generated Jan 7, 2009 10:45:25 AM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.freshdirect.framework.util.TimeOfDay;
import com.freshdirect.transadmin.web.editor.TimeOfDayPropertyEditor;


/**
 * GeoRestrictionDays generated by hbm2java
 */
public class GeoRestrictionDays implements java.io.Serializable {

	private GeoRestrictionDaysId restrictionDaysId;
	private String condition;
	
	private TimeOfDay startTime;
	private TimeOfDay endTime;

	public GeoRestrictionDays() {
	}

	public GeoRestrictionDays(GeoRestrictionDaysId id) {
		this.restrictionDaysId = id;
	}

	public GeoRestrictionDays(GeoRestrictionDaysId id, String condition,
			TimeOfDay startTime, TimeOfDay endTime) {
		this.restrictionDaysId = id;
		this.condition = condition;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	

	public String getCondition() {
		return this.condition;
	}

	public void setCondition(String condition) {
		this.condition = condition;
	}


	public GeoRestrictionDaysId getRestrictionDaysId() {
		return restrictionDaysId;
	}

	public void setRestrictionDaysId(GeoRestrictionDaysId restrictionDaysId) {
		this.restrictionDaysId = restrictionDaysId;
	}

	public TimeOfDay getEndTime() {
		return endTime;
	}

	public void setEndTime(TimeOfDay endTime) {
		this.endTime = endTime;
	}

	public TimeOfDay getStartTime() {
		return startTime;
	}

	public void setStartTime(TimeOfDay startTime) {
		this.startTime = startTime;
	}

//	public String getDayOfWeekInText(){
//		if(this.restrictionDaysId==null) return "";			
//		
//	}
	
}
