package com.freshdirect.transadmin.model;

// Generated Jan 7, 2009 10:45:25 AM by Hibernate Tools 3.2.2.GA

import java.math.BigDecimal;

/**
 * GeoRestrictionDaysId generated by hbm2java
 */
public class GeoRestrictionDaysId implements java.io.Serializable {

	private String restrictionId;
	private BigDecimal dayOfWeek;
	private BigDecimal seqno;

	public GeoRestrictionDaysId() {
	}

	public GeoRestrictionDaysId(String restrictionId, BigDecimal dayOfWeek,
			BigDecimal seqno) {
		this.restrictionId = restrictionId;
		this.dayOfWeek = dayOfWeek;
		this.seqno = seqno;
	}

	public String getRestrictionId() {
		return this.restrictionId;
	}

	public void setRestrictionId(String restrictionId) {
		this.restrictionId = restrictionId;
	}

	public BigDecimal getDayOfWeek() {
		return this.dayOfWeek;
	}

	public void setDayOfWeek(BigDecimal dayOfWeek) {
		this.dayOfWeek = dayOfWeek;
	}

	public BigDecimal getSeqno() {
		return this.seqno;
	}

	public void setSeqno(BigDecimal seqno) {
		this.seqno = seqno;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GeoRestrictionDaysId))
			return false;
		GeoRestrictionDaysId castOther = (GeoRestrictionDaysId) other;

		return ((this.getRestrictionId() == castOther.getRestrictionId()) || (this
				.getRestrictionId() != null
				&& castOther.getRestrictionId() != null && this
				.getRestrictionId().equals(castOther.getRestrictionId())))
				&& ((this.getDayOfWeek() == castOther.getDayOfWeek()) || (this
						.getDayOfWeek() != null
						&& castOther.getDayOfWeek() != null && this
						.getDayOfWeek().equals(castOther.getDayOfWeek())))
				&& ((this.getSeqno() == castOther.getSeqno()) || (this
						.getSeqno() != null
						&& castOther.getSeqno() != null && this.getSeqno()
						.equals(castOther.getSeqno())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getRestrictionId() == null ? 0 : this.getRestrictionId()
						.hashCode());
		result = 37 * result
				+ (getDayOfWeek() == null ? 0 : this.getDayOfWeek().hashCode());
		result = 37 * result
				+ (getSeqno() == null ? 0 : this.getSeqno().hashCode());
		return result;
	}

}
