package com.freshdirect.transadmin.model;

//Generated Dec 5, 2008 2:34:33 PM by Hibernate Tools 3.2.2.GA

import java.text.ParseException;
import java.util.Date;
import com.freshdirect.transadmin.util.TransStringUtil;

/**
 * Dispatch generated by hbm2java
 */
public class IssueSubType implements java.io.Serializable {

	private String issueSubTypeId;
	private String issueSubTypeName;
	private String issueSubTypeDescription;
	private int isActive;
	private Date createdDate;
	private String createdBy;

	public String getCreatedBy() {
		return createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public IssueSubType(String issueSubTypeId, String issueSubTypeName,
			String issueSubTypeDescription, int isActive, Date createdDate,
			String createdBy, IssueType issueType) {
		super();
		this.issueSubTypeId = issueSubTypeId;
		this.issueSubTypeName = issueSubTypeName;
		this.issueSubTypeDescription = issueSubTypeDescription;
		this.isActive = isActive;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.issueType = issueType;
	}

	private IssueType issueType;

	public IssueSubType() {
	}

	public IssueSubType(String assetId) {
		super();
		this.issueSubTypeId = issueSubTypeId;
	}

	public int getIsActive() {
		return isActive;
	}

	public void setIsActive(int isActive) {
		this.isActive = isActive;
	}

	public String getIssueSubTypeId() {
		return issueSubTypeId;
	}

	public void setIssueSubTypeId(String issueSubTypeId) {
		this.issueSubTypeId = issueSubTypeId;
	}

	public String getIssueSubTypeName() {
		return issueSubTypeName;
	}

	public void setIssueSubTypeName(String issueSubTypeName) {
		this.issueSubTypeName = issueSubTypeName;
	}

	public String getIssueSubTypeDescription() {
		return issueSubTypeDescription;
	}

	public void setIssueSubTypeDescription(String issueSubTypeDescription) {
		this.issueSubTypeDescription = issueSubTypeDescription;
	}

	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public IssueType getIssueType() {
		return issueType;
	}

	public void setIssueType(IssueType issueType) {
		this.issueType = issueType;
	}
	
	public String getCreatedDateDisplay(){
		try {
			return TransStringUtil.getDatewithTime(this.createdDate);
		} catch (ParseException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return "";
	}
	
	public String toString(){
		return this.issueSubTypeId;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((issueSubTypeId == null) ? 0 : issueSubTypeId.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		IssueSubType other = (IssueSubType) obj;
		if (issueSubTypeId == null) {
			if (other.issueSubTypeId != null)
				return false;
		} else if (!issueSubTypeId.equals(other.issueSubTypeId))
			return false;
		return true;
	}

}
