package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * PlanResource generated by hbm2java
 */
public class PlanResource implements ResourceI, java.io.Serializable {

	private ResourceId id;
	private EmployeeRoleType employeeRoleType;
	

	public PlanResource() {
	}

	public PlanResource(ResourceId id, EmployeeRoleType employeeRoleType) {
		this.id = id;
		this.employeeRoleType = employeeRoleType;
		
	}

	public ResourceId getId() {
		return this.id;
	}

	public void setId(ResourceId id) {
		this.id = id;
	}

	public EmployeeRoleType getEmployeeRoleType() {
		return this.employeeRoleType;
	}

	public void setEmployeeRoleType(EmployeeRoleType employeeRoleType) {
		this.employeeRoleType = employeeRoleType;
	}

	public String getNextTelNo() {
		// TODO Auto-generated method stub
		return null;
	}

	public void setNextTelNo(String nextelNo) {
		// TODO Auto-generated method stub
		
	}


}
