package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Plan generated by hbm2java
 */
public class Plan implements java.io.Serializable, TrnBaseEntityI  {

	private String planId;
	private Zone zone;
	private Region region;
	private Date planDate;
	private Date firstDeliveryTime;
	private Date startTime;
	private int sequence;
	private String isBullpen;
	private Set planResources = new HashSet(0);
	private String ignoreErrors;
	private Date errorDate;

	
	public Plan() {
	}
	
	public Date getErrorDate() {
		return errorDate;
	}
	public void setErrorDate(Date errorDate) {
		this.errorDate = errorDate;
	}
	public String getIgnoreErrors() {
		return ignoreErrors;
	}
	public void setIgnoreErrors(String ignoreErrors) {
		this.ignoreErrors = ignoreErrors;
	}

	

	public Plan(String planId, Region region, Date planDate, Date firstDeliveryTime,
			Date startTime, int sequence) {
		this.planId = planId;
		this.region = region;
		this.planDate = planDate;
		this.firstDeliveryTime = firstDeliveryTime;
		this.startTime = startTime;
		this.sequence = sequence;
	}

	public Plan(String planId, Zone zone, Region region, Date planDate,
			Date firstDeliveryTime, Date startTime, int sequence, String isBullpen,
			Set planResources) {
		this.planId = planId;
		this.zone = zone;
		this.region = region;
		this.planDate = planDate;
		this.firstDeliveryTime = firstDeliveryTime;
		this.startTime = startTime;
		this.sequence = sequence;
		this.isBullpen = isBullpen;
		this.planResources = planResources;
	}

	public String getPlanId() {
		return this.planId;
	}

	public void setPlanId(String planId) {
		this.planId = planId;
	}

	public Zone getZone() {
		return this.zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

	public Region getRegion() {
		return this.region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public Date getPlanDate() {
		return this.planDate;
	}

	public void setPlanDate(Date planDate) {
		this.planDate = planDate;
	}

	public Date getFirstDeliveryTime() {
		return this.firstDeliveryTime;
	}

	public void setFirstDeliveryTime(Date firstDeliveryTime) {
		this.firstDeliveryTime = firstDeliveryTime;
	}

	public Date getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public int getSequence() {
		return this.sequence;
	}

	public void setSequence(int sequence) {
		this.sequence = sequence;
	}

	public String getIsBullpen() {
		return this.isBullpen;
	}

	public void setIsBullpen(String isBullpen) {
		this.isBullpen = isBullpen;
	}

	public Set getPlanResources() {
		return this.planResources;
	}

	public void setPlanResources(Set planResources) {
		this.planResources = planResources;
	}

	public boolean isObsoleteEntity() {
		// TODO Auto-generated method stub
		return false;
	}
	public String getZoneCode() {
		if(getZone() == null) {
			return null;
		}
		return getZone().getZoneCode();
	}

	public void setZoneCode(String trnzoneId) {
		if("null".equals(trnzoneId)) {
			setZone(null);
		} else {
			Zone trnZone = new Zone();
			trnZone.setZoneCode(trnzoneId);
			setZone(trnZone);
		}
	}

}
