package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

import java.util.Set;

/**
 * Region generated by hbm2java
 */
public class Region implements java.io.Serializable,Comparable, TrnBaseEntityI {

	private String code;
	private String name;
	private String description;
	private String obsolete;
	private Set zones;
		
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((code == null) ? 0 : code.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Region other = (Region) obj;
		if (code == null) {
			if (other.code != null)
				return false;
		} else if (!code.equals(other.code))
			return false;
		return true;
	}

	public Region() {
	}

	public Region(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public Region(String code, String name, String description) {
		this.code = code;
		this.name = name;
		this.description = description;
		
	}

	public String getObsolete() {
		return obsolete;
	}
	
	public void setObsolete(String obsolete) {
		this.obsolete = obsolete;
	}
	
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	

	public String toString()
	{
	   StringBuffer buffer=new StringBuffer();
	   buffer.append("[").append("code").append(code).append(",");
	   buffer.append("name").append(name).append(",");
	   buffer.append("description").append(description).append(",").append(hashCode()).append("]");
	   return buffer.toString();
	}

	public boolean isObsoleteEntity() {
		return false;
	}

	public Set getZones() {
		return zones;
	}

	public void setZones(Set zones) {
		this.zones = zones;
	}

	@Override
	public int compareTo(Object o) {
		// TODO Auto-generated method stub
		return this.hashCode() - (o).hashCode();
	}
	
}
