package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * PlanResource generated by hbm2java
 */
public interface ResourceI  {

	public ResourceId getId();

	public void setId(ResourceId id) ;

	public EmployeeRoleType getEmployeeRoleType();

	public void setEmployeeRoleType(EmployeeRoleType employeeRoleType);

	public void setNextTelNo(String nextelNo);
	
	public String getNextTelNo();

}
