package com.freshdirect.transadmin.model;

import java.util.Date;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * DispatchResourceId generated by hbm2java
 */
public class ResourceId implements java.io.Serializable {

	private String contextId;
	private String resourceId;
	private Date adjustmentTime;
	
	public ResourceId() {
	}

	public ResourceId(String dispatchId, String resourceId) {
		this.contextId = dispatchId;
		this.resourceId = resourceId;
	}

	public String getContextId() {
		return this.contextId;
	}

	public void setContextId(String contextId) {
		this.contextId = contextId;
	}

	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ResourceId))
			return false;
		ResourceId castOther = (ResourceId) other;

		return ((this.getContextId() == castOther.getContextId()) || (this
				.getContextId() != null
				&& castOther.getContextId() != null && this.getContextId()
				.equals(castOther.getContextId())))
				&& ((this.getResourceId() == castOther.getResourceId()) || (this
						.getResourceId() != null
						&& castOther.getResourceId() != null && this
						.getResourceId().equals(castOther.getResourceId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getContextId() == null ? 0 : this.getContextId()
						.hashCode());
		result = 37
				* result
				+ (getResourceId() == null ? 0 : this.getResourceId()
						.hashCode());
		return result;
	}

	public Date getAdjustmentTime() {
		return adjustmentTime;
	}

	public void setAdjustmentTime(Date adjustmentTime) {
		this.adjustmentTime = adjustmentTime;
	}

	public String toString() {
		// TODO Auto-generated method stub
		return contextId +":"+resourceId;
	}

	

}
