package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * Route generated by hbm2java
 */
public class Route implements java.io.Serializable {

	private String routeId;
	private String routeNo;
	private String numberOfStops;
	private String routeTime;
	private Zone zone;

	public Route() {
	}

	public Route(String routeId, String routeNo, String numberOfStops,String routeTime) {
		this.routeId = routeId;
		this.routeNo = routeNo;
		this.numberOfStops = numberOfStops;
		this.routeTime = routeTime;
		
	}

	public String getNumberOfStops() {
		return numberOfStops;
	}

	public void setNumberOfStops(String numberOfStops) {
		this.numberOfStops = numberOfStops;
	}

	public String getRouteId() {
		return routeId;
	}

	public void setRouteId(String routeId) {
		this.routeId = routeId;
	}

	public String getRouteNo() {
		return routeNo;
	}

	public void setRouteNo(String routeNo) {
		this.routeNo = routeNo;
	}

	public String getRouteTime() {
		return routeTime;
	}

	public void setRouteTime(String routeTime) {
		this.routeTime = routeTime;
	}

	public Zone getZone() {
		return zone;
	}

	public void setZone(Zone zone) {
		this.zone = zone;
	}

		
	

	
}
