package com.freshdirect.transadmin.model;

import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector implements java.io.Serializable {

	private String name;
	private String description;
	private String active;
	
	private Set sectorZipcodes;
	
	public Sector() {
		super();
	}
	public Sector(String name, String description, String active) {
		super();
		this.name = name;
		this.description = description;
		this.active = active;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public String getActive() {
		return active;
	}
	public void setActive(String active) {
		this.active = active;
	}
	public Set getSectorZipcodes() {
		return sectorZipcodes;
	}
	public void setSectorZipcodes(Set sectorZipcodes) {
		this.sectorZipcodes = sectorZipcodes;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((name == null) ? 0 : name.hashCode());
		return result;
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Sector other = (Sector) obj;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}
	
}
