package com.freshdirect.transadmin.model;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * TrnRoute generated by hbm2java
 */
public class TrnAdHocRoute  implements java.io.Serializable, TrnBaseEntityI {

	private String routeId; 
	
	private String routeAmPm;

	private String routeNumber;

	private String description;
	
	private String obsolete;

	public String getObsolete() {
		return obsolete;
	}
	
	public void setObsolete(String obsolete) {
		this.obsolete = obsolete;
	}

	public TrnAdHocRoute() {
	}
	
	public TrnAdHocRoute(String routeAmPm,
			String routeNumber, String description) {
		this.routeAmPm = routeAmPm;
		this.routeNumber = routeNumber;
		this.description = description;
	}
	
	
	public String getRouteId() {
		return this.routeId;
	}

	public void setRouteId(String routeId) {
		this.routeId = routeId;
	}

	public String getRouteAmPm() {
		return this.routeAmPm;
	}

	public void setRouteAmPm(String routeAmPm) {
		this.routeAmPm = routeAmPm;
	}

	public String getRouteNumber() {
		return this.routeNumber;
	}

	public void setRouteNumber(String routeNumber) {
		this.routeNumber = routeNumber;
	}
	
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public boolean isObsoleteEntity() {
		// TODO Auto-generated method stub
		return false;
	}

}
