package com.freshdirect.transadmin.model;

import com.freshdirect.transadmin.constants.EnumDispatchStatusType;


// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

/**
 * TrnDispatch generated by hbm2java
 */
public class TrnDispatch implements java.io.Serializable, TrnBaseEntityI {

	private TrnDispatchId id;
	
	private TrnEmployee trnSupervisor;
	private TrnZone trnZone;
	private TrnTimeslot trnTimeslot;
	private TrnEmployee trnDriver;
	private TrnEmployee trnPrimaryHelper;
	private TrnEmployee trnSecondaryHelper;	
	private TrnTruck trnTruck;
	private TrnRoute trnRoute;
	private String nextelId;
	private String comments;
	private String status;
		

	public String getStatus() {		
		return status;
	}
	
	public String getStatusDescription() {
		if(status == null) {
			return EnumDispatchStatusType.NOTCONFIRMED.getDescription();
		}
		return EnumDispatchStatusType.getEnum(status).getDescription();
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getComments() {
		return comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public TrnDispatch() {
	}

	public TrnDispatch(TrnDispatchId id) {
		this.id = id;
	}

	public TrnDispatchId getId() {
		return this.id;
	}

	public void setId(TrnDispatchId id) {
		this.id = id;
	}
	

	public String getNextelId() {
		return nextelId;
	}

	public void setNextelId(String nextelId) {
		this.nextelId = nextelId;
	}

	public TrnEmployee getTrnDriver() {
		return trnDriver;
	}

	public void setTrnDriver(TrnEmployee trnDriver) {
		this.trnDriver = trnDriver;
	}

	public TrnEmployee getTrnPrimaryHelper() {
		return trnPrimaryHelper;
	}

	public void setTrnPrimaryHelper(TrnEmployee trnPrimaryHelper) {
		this.trnPrimaryHelper = trnPrimaryHelper;
	}

	public TrnEmployee getTrnSecondaryHelper() {
		return trnSecondaryHelper;
	}

	public void setTrnSecondaryHelper(TrnEmployee trnSecondaryHelper) {
		this.trnSecondaryHelper = trnSecondaryHelper;
	}

	public TrnEmployee getTrnSupervisor() {
		return trnSupervisor;
	}

	public void setTrnSupervisor(TrnEmployee trnSupervisor) {
		this.trnSupervisor = trnSupervisor;
	}

	public TrnTimeslot getTrnTimeslot() {
		return trnTimeslot;
	}

	public void setTrnTimeslot(TrnTimeslot trnTimeslot) {
		this.trnTimeslot = trnTimeslot;
	}

	public TrnTruck getTrnTruck() {
		return trnTruck;
	}

	public void setTrnTruck(TrnTruck trnTruck) {
		this.trnTruck = trnTruck;
	}

	public TrnZone getTrnZone() {
		return trnZone;
	}

	public void setTrnZone(TrnZone trnZone) {
		this.trnZone = trnZone;
	}
	
	public String getZone() {
		if(getTrnZone() == null) {
			return null;
		}
		return getTrnZone().getZoneId();
	}

	public void setZone(String trnzoneId) {
		if("null".equals(trnzoneId)) {
			setTrnZone(null);
		} else {
			TrnZone trnZone = new TrnZone();
			trnZone.setZoneId(trnzoneId);
			setTrnZone(trnZone);
		}
	}
	
	public String getTimeslot() {
		if(getTrnTimeslot() == null) {
			return null;
		}
		return getTrnTimeslot().getSlotId();
	}

	public void setTimeslot(String slotId) {
		if("null".equals(slotId)) {
			setTrnTimeslot(null);
		} else {
			TrnTimeslot trnTimeslot = new TrnTimeslot();
			trnTimeslot.setSlotId(slotId);
			setTrnTimeslot(trnTimeslot);
		}
	}
	
	public String getSupervisor() {
		if(getTrnSupervisor() == null) {
			return null;
		}
		return getTrnSupervisor().getEmployeeId();
	}

	public void setSupervisor(String supervisorId) {
		if("null".equals(supervisorId)) {
			setTrnSupervisor(null);
		} else {
			TrnEmployee trnEmployee = new TrnEmployee();
			trnEmployee.setEmployeeId(supervisorId);
			setTrnSupervisor(trnEmployee);
		}
	}
	
	public String getDriver() {
		if(getTrnDriver() == null) {
			return null;
		}
		return getTrnDriver().getEmployeeId();
	}

	public void setDriver(String employeeId) {
		if("null".equals(employeeId)) {
			setTrnDriver(null);
		} else {
			TrnEmployee trnEmployee = new TrnEmployee();
			trnEmployee.setEmployeeId(employeeId);
			setTrnDriver(trnEmployee);
		}
	}
	
	public String getPrimaryHelper() {
		if(getTrnPrimaryHelper() == null) {
			return null;
		}
		return getTrnPrimaryHelper().getEmployeeId();
	}

	public void setPrimaryHelper(String employeeId) {
		if("null".equals(employeeId)) {
			setTrnPrimaryHelper(null);
		} else {
			TrnEmployee trnEmployee = new TrnEmployee();
			trnEmployee.setEmployeeId(employeeId);
			setTrnPrimaryHelper(trnEmployee);
		}
	}
	
	public String getSecondaryHelper() {
		if(getTrnSecondaryHelper() == null) {
			return null;
		}
		return getTrnSecondaryHelper().getEmployeeId();
	}

	public void setSecondaryHelper(String employeeId) {
		if("null".equals(employeeId)) {
			setTrnSecondaryHelper(null);
		} else {
			TrnEmployee trnEmployee = new TrnEmployee();
			trnEmployee.setEmployeeId(employeeId);
			setTrnSecondaryHelper(trnEmployee);
		}
	}
	
	public String getTruck() {
		if(getTrnTruck() == null) {
			return null;
		}
		return getTrnTruck().getTruckId();
	}

	public void setTruck(String truckId) {
		if("null".equals(truckId)) {
			setTrnTruck(null);
		} else {
			TrnTruck trnTruck = new TrnTruck();
			trnTruck.setTruckId(truckId);
			setTrnTruck(trnTruck);
		}
	}

	public TrnRoute getTrnRoute() {
		return trnRoute;
	}

	public void setTrnRoute(TrnRoute trnRoute) {
		this.trnRoute = trnRoute;
	}
	
	public String getRoute() {
		if(getTrnRoute() == null) {
			return null;
		}
		return getTrnRoute().getRouteId();
	}

	public void setRoute(String routeId) {
		if("null".equals(routeId)) {
			setTrnRoute(null);
		} else {
			TrnRoute trnTruck = new TrnRoute();
			trnTruck.setRouteId(routeId);
			setTrnRoute(trnTruck);
		}
	}
	
	public boolean isObsoleteEntity() {
		return ((trnSupervisor != null && trnSupervisor.getObsolete() != null) ||
				(trnDriver != null && trnDriver.getObsolete() != null) ||
				(trnZone != null && trnZone.getObsolete() != null) ||
				(trnPrimaryHelper != null && trnPrimaryHelper.getObsolete() != null) ||
				(trnSecondaryHelper != null && trnSecondaryHelper.getObsolete() != null) ||
				(trnTruck != null && trnTruck.getObsolete() != null) ||
				(trnRoute != null && trnRoute.getObsolete() != null));
	}


}
