package com.freshdirect.transadmin.model;


// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

/**
 * TrnDispatchPlan generated by hbm2java
 */
public class TrnDispatchPlan implements java.io.Serializable, TrnBaseEntityI {

	private Long planId;
	private String dispatchDay;
	private TrnEmployee trnSupervisor;
	private TrnZone trnZone;
	private TrnTimeslot trnTimeslot;
	private TrnEmployee trnDriver;
	private TrnEmployee trnPrimaryHelper;
	private TrnEmployee trnSecondaryHelper;
	
	public Long getPlanId() {
		return planId;
	}
	public void setPlanId(Long routeId) {
		this.planId = routeId;
	}
	public TrnEmployee getTrnDriver() {
		return trnDriver;
	}
	public void setTrnDriver(TrnEmployee trnDriver) {
		this.trnDriver = trnDriver;
	}
	public TrnEmployee getTrnPrimaryHelper() {
		return trnPrimaryHelper;
	}
	public void setTrnPrimaryHelper(TrnEmployee trnPrimaryHelper) {
		this.trnPrimaryHelper = trnPrimaryHelper;
	}
	public TrnEmployee getTrnSecondaryHelper() {
		return trnSecondaryHelper;
	}
	public void setTrnSecondaryHelper(TrnEmployee trnSecondaryHelper) {
		this.trnSecondaryHelper = trnSecondaryHelper;
	}
	public TrnEmployee getTrnSupervisor() {
		return trnSupervisor;
	}
	public void setTrnSupervisor(TrnEmployee trnSupervisor) {
		this.trnSupervisor = trnSupervisor;
	}
	public TrnTimeslot getTrnTimeslot() {
		return trnTimeslot;
	}
	public void setTrnTimeslot(TrnTimeslot trnTimeslot) {
		this.trnTimeslot = trnTimeslot;
	}
	public TrnZone getTrnZone() {
		return trnZone;
	}
	public void setTrnZone(TrnZone trnZone) {
		this.trnZone = trnZone;
	}
	public String getDispatchDay() {
		return dispatchDay != null ?  dispatchDay.trim() : dispatchDay;
	}
	public void setDispatchDay(String dispatchDay) {
		this.dispatchDay = dispatchDay;
	}
	
	public String getZone() {
		if(getTrnZone() == null) {
			return null;
		}
		return getTrnZone().getZoneId();
	}

	public void setZone(String trnzoneId) {
		if("null".equals(trnzoneId)) {
			setTrnZone(null);
		} else {
			TrnZone trnZone = new TrnZone();
			trnZone.setZoneId(trnzoneId);
			setTrnZone(trnZone);
		}
	}
	
	public String getTimeslot() {
		if(getTrnTimeslot() == null) {
			return null;
		}
		return getTrnTimeslot().getSlotId();
	}

	public void setTimeslot(String slotId) {
		if("null".equals(slotId)) {
			setTrnTimeslot(null);
		} else {
			TrnTimeslot trnTimeslot = new TrnTimeslot();
			trnTimeslot.setSlotId(slotId);
			setTrnTimeslot(trnTimeslot);
		}
	}
	
		
	public String getDriver() {
		if(getTrnDriver() == null) {
			return null;
		}
		return getTrnDriver().getEmployeeId();
	}

	public void setDriver(String employeeId) {
		if("null".equals(employeeId)) {
			setTrnDriver(null);
		} else {
			TrnEmployee trnEmployee = new TrnEmployee();
			trnEmployee.setEmployeeId(employeeId);
			setTrnDriver(trnEmployee);
		}
	}
	
	public String getPrimaryHelper() {
		if(getTrnPrimaryHelper() == null) {
			return null;
		}
		return getTrnPrimaryHelper().getEmployeeId();
	}

	public void setPrimaryHelper(String employeeId) {
		if("null".equals(employeeId)) {
			setTrnPrimaryHelper(null);
		} else {
			TrnEmployee trnEmployee = new TrnEmployee();
			trnEmployee.setEmployeeId(employeeId);
			setTrnPrimaryHelper(trnEmployee);
		}
	}
	
	public String getSecondaryHelper() {
		if(getTrnSecondaryHelper() == null) {
			return null;
		}
		return getTrnSecondaryHelper().getEmployeeId();
	}

	public void setSecondaryHelper(String employeeId) {
		if("null".equals(employeeId)) {
			setTrnSecondaryHelper(null);
		} else {
			TrnEmployee trnEmployee = new TrnEmployee();
			trnEmployee.setEmployeeId(employeeId);
			setTrnSecondaryHelper(trnEmployee);
		}
	}
	
	public boolean isObsoleteEntity() {
		return ((trnSupervisor != null && trnSupervisor.getObsolete() != null) ||
				(trnDriver != null && trnDriver.getObsolete() != null) ||
				(trnZone != null && trnZone.getObsolete() != null) ||
				(trnPrimaryHelper != null && trnPrimaryHelper.getObsolete() != null) ||
				(trnSecondaryHelper != null && trnSecondaryHelper.getObsolete() != null));
	}
	

}
