package com.freshdirect.transadmin.model;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * TrnEmployeeassignment generated by hbm2java
 */
public class TrnEmployeeassignment implements java.io.Serializable, TrnBaseEntityI {

	private String employeeassignmentid;

	private TrnEmployee trnEmployee;

	private TrnRoute trnRoute;

	private Date assignDate;

	public TrnEmployeeassignment() {
	}

	public TrnEmployeeassignment(String employeeassignmentid, Date assignDate) {
		this.employeeassignmentid = employeeassignmentid;
		this.assignDate = assignDate;
	}

	public TrnEmployeeassignment(String employeeassignmentid,
			TrnEmployee trnEmployee, TrnRoute trnRoute, Date assignDate) {
		this.employeeassignmentid = employeeassignmentid;
		this.trnEmployee = trnEmployee;
		this.trnRoute = trnRoute;
		this.assignDate = assignDate;
	}

	public String getEmployeeassignmentid() {
		return this.employeeassignmentid;
	}

	public void setEmployeeassignmentid(String employeeassignmentid) {
		this.employeeassignmentid = employeeassignmentid;
	}

	public TrnEmployee getTrnEmployee() {
		return this.trnEmployee;
	}

	public void setTrnEmployee(TrnEmployee trnEmployee) {
		this.trnEmployee = trnEmployee;
	}

	public TrnRoute getTrnRoute() {
		return this.trnRoute;
	}

	public void setTrnRoute(TrnRoute trnRoute) {
		this.trnRoute = trnRoute;
	}

	public Date getAssignDate() {
		return this.assignDate;
	}

	public void setAssignDate(Date assignDate) {
		this.assignDate = assignDate;
	}
	
	public boolean isObsoleteEntity() {
 		return false;
	}

}
