package com.freshdirect.transadmin.model;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TrnEmployee generated by hbm2java
 */
public class TrnEmployee implements java.io.Serializable, TrnBaseEntityI {

	private String employeeId;

	private TrnEmployeeJobType trnEmployeeJobType;

	private TrnEmployee trnSupervisor;

	private String employeenumber;

	private String firstName;

	private String lastName;

	private Date hireDate;

	private Date terminateDate;

	private Set trnEmployeeassignments = new HashSet(0);
	
	private String obsolete;

	public String getObsolete() {
		return obsolete;
	}

	public void setObsolete(String obsolete) {
		this.obsolete = obsolete;
	}

	public TrnEmployee() {
		
	}

	public TrnEmployee(String employeeId) {
		this.employeeId = employeeId;
	}

	public TrnEmployee(String employeeId,
			TrnEmployeeJobType trnEmployeeJobType, TrnEmployee trnSupervisor,
			String employeenumber, String firstName, String lastName,
			Date hireDate, Date terminateDate, Set trnEmployeeassignments) {
		this.employeeId = employeeId;
		this.trnEmployeeJobType = trnEmployeeJobType;
		this.trnSupervisor = trnSupervisor;
		this.employeenumber = employeenumber;
		this.firstName = firstName;
		this.lastName = lastName;
		this.hireDate = hireDate;
		this.terminateDate = terminateDate;
		this.trnEmployeeassignments = trnEmployeeassignments;
	}

	public String getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(String employeeId) {
		this.employeeId = employeeId;
	}

	public TrnEmployeeJobType getTrnEmployeeJobType() {
		return this.trnEmployeeJobType;
	}

	public void setTrnEmployeeJobType(TrnEmployeeJobType trnEmployeeJobType) {
		this.trnEmployeeJobType = trnEmployeeJobType;
	}

	
	public String getEmployeenumber() {
		return this.employeenumber;
	}

	public void setEmployeenumber(String employeenumber) {
		this.employeenumber = employeenumber;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public String getName() {
		return (this.lastName != null ? this.lastName : "")  +" "+ (this.firstName != null ? this.firstName : "");
	}

	public Date getHireDate() {
		return this.hireDate;
	}

	public void setHireDate(Date hireDate) {
		this.hireDate = hireDate;
	}

	public Date getTerminateDate() {
		return this.terminateDate;
	}

	public void setTerminateDate(Date terminateDate) {
		this.terminateDate = terminateDate;
	}

	public Set getTrnEmployeeassignments() {
		return this.trnEmployeeassignments;
	}

	public void setTrnEmployeeassignments(Set trnEmployeeassignments) {
		this.trnEmployeeassignments = trnEmployeeassignments;
	}

	public TrnEmployee getTrnSupervisor() {
		return trnSupervisor;
	}

	public void setTrnSupervisor(TrnEmployee trnSupervisor) {
		this.trnSupervisor = trnSupervisor;
	}
	
	public String getSupervisor() {
		if(getTrnSupervisor() == null) {
			return null;
		}
		return getTrnSupervisor().getEmployeeId();
	}

	public void setSupervisor(String trnSupervisorId) {
		if("null".equals(trnSupervisorId)) {
			setTrnSupervisor(null);
		} else {
			TrnEmployee trnSupervisor = new TrnEmployee();
			trnSupervisor.setEmployeeId(trnSupervisorId);
			setTrnSupervisor(trnSupervisor);
		}
	}
	
	public String getEmployeeJobType() {
		if(getTrnEmployeeJobType() == null) {
			return null;
		}		
		return getTrnEmployeeJobType().getJobTypeId();
	}

	public void setEmployeeJobType(String trnEmployeeJobTypeId) {
		if("null".equals(trnEmployeeJobTypeId)) {
			setTrnEmployeeJobType(null);
		} else {		
			TrnEmployeeJobType trnEmployeeJobType = new TrnEmployeeJobType();
			trnEmployeeJobType.setJobTypeId(trnEmployeeJobTypeId);
			setTrnEmployeeJobType(trnEmployeeJobType);
		}
	}
	
	public boolean isObsoleteEntity() {
		return (trnSupervisor != null && trnSupervisor.getObsolete() != null);
	}
	
}
