package com.freshdirect.transadmin.model;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

import java.util.HashSet;
import java.util.Set;

/**
 * TrnEmployeeJobType generated by hbm2java
 */
public class TrnEmployeeJobType  implements java.io.Serializable, TrnBaseEntityI {

	private String jobTypeId;

	private String jobTypeName;

	private String jobDescription;

	private Set trnEmployees = new HashSet(0);

	public TrnEmployeeJobType() {
	}

	public TrnEmployeeJobType(String jobTypeId, String jobTypeName) {
		this.jobTypeId = jobTypeId;
		this.jobTypeName = jobTypeName;
	}

	public TrnEmployeeJobType(String jobTypeId, String jobTypeName,
			String jobDescription, Set trnEmployees) {
		this.jobTypeId = jobTypeId;
		this.jobTypeName = jobTypeName;
		this.jobDescription = jobDescription;
		this.trnEmployees = trnEmployees;
	}

	public String getJobTypeId() {
		return this.jobTypeId;
	}

	public void setJobTypeId(String jobTypeId) {
		this.jobTypeId = jobTypeId;
	}

	public String getJobTypeName() {
		return this.jobTypeName;
	}

	public void setJobTypeName(String jobTypeName) {
		this.jobTypeName = jobTypeName;
	}

	public String getJobDescription() {
		return this.jobDescription;
	}

	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription;
	}

	public Set getTrnEmployees() {
		return this.trnEmployees;
	}

	public void setTrnEmployees(Set trnEmployees) {
		this.trnEmployees = trnEmployees;
	}
	
	public boolean isObsoleteEntity() {
 		return false;
	}
}
