package com.freshdirect.transadmin.model;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

/**
 * TrnTimeslotId generated by hbm2java
 */
public class TrnTimeslotId implements java.io.Serializable {

	private String slotId;

	private String slotName;

	public TrnTimeslotId() {
	}

	public TrnTimeslotId(String slotId, String slotName) {
		this.slotId = slotId;
		this.slotName = slotName;
	}

	public String getSlotId() {
		return this.slotId;
	}

	public void setSlotId(String slotId) {
		this.slotId = slotId;
	}

	public String getSlotName() {
		return this.slotName;
	}

	public void setSlotName(String slotName) {
		this.slotName = slotName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TrnTimeslotId))
			return false;
		TrnTimeslotId castOther = (TrnTimeslotId) other;

		return ((this.getSlotId() == castOther.getSlotId()) || (this
				.getSlotId() != null
				&& castOther.getSlotId() != null && this.getSlotId().equals(
				castOther.getSlotId())))
				&& ((this.getSlotName() == castOther.getSlotName()) || (this
						.getSlotName() != null
						&& castOther.getSlotName() != null && this
						.getSlotName().equals(castOther.getSlotName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getSlotId() == null ? 0 : this.getSlotId().hashCode());
		result = 37 * result
				+ (getSlotName() == null ? 0 : this.getSlotName().hashCode());
		return result;
	}

}
