package com.freshdirect.transadmin.model;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * TrnTruckassignment generated by hbm2java
 */
public class TrnTruckassignment  implements java.io.Serializable, TrnBaseEntityI {

	private String truckassignmentId;

	private TrnTruck trnTruck;

	private TrnRoute trnRoute;

	private Date assignDate;

	public TrnTruckassignment() {
	}

	public TrnTruckassignment(String truckassignmentId) {
		this.truckassignmentId = truckassignmentId;
	}

	public TrnTruckassignment(String truckassignmentId, TrnTruck trnTruck,
			TrnRoute trnRoute, Date assignDate) {
		this.truckassignmentId = truckassignmentId;
		this.trnTruck = trnTruck;
		this.trnRoute = trnRoute;
		this.assignDate = assignDate;
	}

	public String getTruckassignmentId() {
		return this.truckassignmentId;
	}

	public void setTruckassignmentId(String truckassignmentId) {
		this.truckassignmentId = truckassignmentId;
	}

	public TrnTruck getTrnTruck() {
		return this.trnTruck;
	}

	public void setTrnTruck(TrnTruck trnTruck) {
		this.trnTruck = trnTruck;
	}

	public TrnRoute getTrnRoute() {
		return this.trnRoute;
	}

	public void setTrnRoute(TrnRoute trnRoute) {
		this.trnRoute = trnRoute;
	}

	public Date getAssignDate() {
		return this.assignDate;
	}

	public void setAssignDate(Date assignDate) {
		this.assignDate = assignDate;
	}
	
	public boolean isObsoleteEntity() {
 		return false;
	}

}
