package com.freshdirect.transadmin.model;
import java.util.Date;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

/**
 * TrnTimeslot generated by hbm2java
 */
public class TrnTimeslot  implements java.lang.Comparable, java.io.Serializable, TrnBaseEntityI {

	
	public String toString() {
		return slotName;
	}
	public int compareTo(Object rhs){  
		TrnTimeslot rhsTrnTimeslot = (TrnTimeslot) rhs;
		return slotId.compareTo(rhsTrnTimeslot.slotId);
	}
	
	private String slotId;

	private String slotName;
	
	public TrnTimeslot() {
	}

	public TrnTimeslot(String slotId) {
		this.slotId = slotId;
	}
	
	public String getSlotId() {
		return slotId;
	}

	public void setSlotId(String slotId) {
		this.slotId = slotId;
	}

	public String getSlotName() {
		return slotName;
	}

	public void setSlotName(String slotName) {
		this.slotName = slotName;
	}
	
	public boolean isObsoleteEntity() {
 		return false;
	}

}
