package com.freshdirect.transadmin.model;

// Generated Jul 30, 2007 6:23:08 PM by Hibernate Tools 3.2.0.b9

/**
 * TrnZone generated by hbm2java
 */
public class TrnZone  implements java.io.Serializable, TrnBaseEntityI {

	private String zoneId;

	private String zoneNumber;

	private String neighborhood;
	
	private String obsolete;

	private TrnEmployee trnSupervisor;

	public TrnZone() {
	}

	public TrnZone(String zoneId) {
		this.zoneId = zoneId;
	}

	public TrnZone(String zoneId, String zoneNumber, String neighborhood,
			TrnEmployee trnSupervisor) {
		this.zoneId = zoneId;
		this.zoneNumber = zoneNumber;
		this.neighborhood = neighborhood;
		this.trnSupervisor = trnSupervisor;
	}

	public String getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(String zoneId) {
		this.zoneId = zoneId;
	}

	public String getZoneNumber() {
		return this.zoneNumber;
	}

	public void setZoneNumber(String zoneNumber) {
		this.zoneNumber = zoneNumber;
	}

	public String getNeighborhood() {
		return this.neighborhood;
	}

	public void setNeighborhood(String neighborhood) {
		this.neighborhood = neighborhood;
	}

	public TrnEmployee getTrnSupervisor() {
		return trnSupervisor;
	}

	public void setTrnSupervisor(TrnEmployee trnSupervisor) {
		this.trnSupervisor = trnSupervisor;
	}
	
	public String getSupervisor() {
		if(getTrnSupervisor() == null) {
			return null;
		}
		return getTrnSupervisor().getEmployeeId();
	}

	public void setSupervisor(String trnSupervisorId) {
		if("null".equals(trnSupervisorId)) {
			setTrnSupervisor(null);
		} else {
			TrnEmployee trnSupervisor = new TrnEmployee();
			trnSupervisor.setEmployeeId(trnSupervisorId);
			setTrnSupervisor(trnSupervisor);
		}
	}

	public String getObsolete() {
		return obsolete;
	}

	public void setObsolete(String obsolete) {
		this.obsolete = obsolete;
	}
	
	public boolean isObsoleteEntity() {
		return (trnSupervisor != null && trnSupervisor.getObsolete() != null);
	}
}
