package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;

import com.freshdirect.routing.constants.EnumWaveInstancePublishSrc;

/**
 * Plan generated by hbm2java
 */
public class WaveInstancePublish implements java.io.Serializable, TrnBaseEntityI  {

	private Date deliveryDate;
	private EnumWaveInstancePublishSrc source;
	private String publishedBy;	
	private Date publishedAt;
	
	public Date getDeliveryDate() {
		return deliveryDate;
	}

	public EnumWaveInstancePublishSrc getSource() {
		return source;
	}

	public String getPublishedBy() {
		return publishedBy;
	}

	public Date getPublishedAt() {
		return publishedAt;
	}

	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}

	public void setSource(EnumWaveInstancePublishSrc source) {
		this.source = source;
	}

	public void setPublishedBy(String publishedBy) {
		this.publishedBy = publishedBy;
	}

	public void setPublishedAt(Date publishedAt) {
		this.publishedAt = publishedAt;
	}

	public boolean isObsoleteEntity() {
		// TODO Auto-generated method stub
		return false;
	}

}
