package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.freshdirect.routing.constants.EnumWaveInstanceStatus;

/**
 * Plan generated by hbm2java
 */
public class WaveInstance implements java.io.Serializable, TrnBaseEntityI  {

	private String waveInstanceId;
	private String area;
	private Date deliveryDate;
	private Date dispatchTime;
	private Date firstDeliveryTime;
	private Date lastDeliveryTime;
	private Date cutOffTime;
	private int noOfResources;
	private EnumWaveInstanceStatus status;
	
	private Date modifiedTime;
	private String source;
	private String changedBy;
	private String referenceId;
	private String notificationMessage;
	private Boolean forceSynchronize;
	
	public String getWaveInstanceId() {
		return waveInstanceId;
	}
	public String getArea() {
		return area;
	}
	public Date getDeliveryDate() {
		return deliveryDate;
	}
	
	public Date getFirstDeliveryTime() {
		return firstDeliveryTime;
	}
	public Date getLastDeliveryTime() {
		return lastDeliveryTime;
	}
	public Date getCutOffTime() {
		return cutOffTime;
	}
	public int getNoOfResources() {
		return noOfResources;
	}
	public EnumWaveInstanceStatus getStatus() {
		return status;
	}
	public Date getModifiedTime() {
		return modifiedTime;
	}
	public String getSource() {
		return source;
	}
	public String getChangedBy() {
		return changedBy;
	}
	public String getReferenceId() {
		return referenceId;
	}
	public String getNotificationMessage() {
		return notificationMessage;
	}
	public Boolean getForceSynchronize() {
		return forceSynchronize;
	}
	
	public Date getDispatchTime() {
		return dispatchTime;
	}
	public void setDispatchTime(Date dispatchTime) {
		this.dispatchTime = dispatchTime;
	}
	public void setWaveInstanceId(String waveInstanceId) {
		this.waveInstanceId = waveInstanceId;
	}
	public void setArea(String area) {
		this.area = area;
	}
	public void setDeliveryDate(Date deliveryDate) {
		this.deliveryDate = deliveryDate;
	}
	
	public void setFirstDeliveryTime(Date firstDeliveryTime) {
		this.firstDeliveryTime = firstDeliveryTime;
	}
	public void setLastDeliveryTime(Date lastDeliveryTime) {
		this.lastDeliveryTime = lastDeliveryTime;
	}
	public void setCutOffTime(Date cutOffTime) {
		this.cutOffTime = cutOffTime;
	}
	public void setNoOfResources(int noOfResources) {
		this.noOfResources = noOfResources;
	}
	public void setStatus(EnumWaveInstanceStatus status) {
		this.status = status;
	}
	public void setModifiedTime(Date modifiedTime) {
		this.modifiedTime = modifiedTime;
	}
	public void setSource(String source) {
		this.source = source;
	}
	public void setChangedBy(String changedBy) {
		this.changedBy = changedBy;
	}
	public void setReferenceId(String referenceId) {
		this.referenceId = referenceId;
	}
	public void setNotificationMessage(String notificationMessage) {
		this.notificationMessage = notificationMessage;
	}
	public void setForceSynchronize(Boolean forceSynchronize) {
		this.forceSynchronize = forceSynchronize;
	}
	
	public boolean isObsoleteEntity() {
		// TODO Auto-generated method stub
		return false;
	}

}
