package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * ZonetypeResource generated by hbm2java
 */
public class ZonetypeResource implements java.io.Serializable {

	private ZonetypeResourceId id;
	
	private Integer maximumNo;
	private Integer requiredNo;
	
	private TrnZoneType zoneType;

	public ZonetypeResource() {
	}

	public ZonetypeResource(ZonetypeResourceId id) {
		this.id = id;
		
	}

	public ZonetypeResource(ZonetypeResourceId id, TrnZoneType zoneType, Integer maximumNo,Integer requiredNo) {
		this.id = id;
		this.zoneType=zoneType;		
		this.maximumNo = maximumNo;
		this.requiredNo = requiredNo;
	}

	public ZonetypeResourceId getId() {
		return this.id;
	}

	public void setId(ZonetypeResourceId id) {
		this.id = id;
	}


	public Integer getMaximumNo() {
		return this.maximumNo;
	}

	public void setMaximumNo(Integer maximumNo) {
		this.maximumNo = maximumNo;
	}

	public Integer getRequiredNo() {
		return this.requiredNo;
	}

	public void setRequiredNo(Integer requiredNo) {
		this.requiredNo = requiredNo;
	}

	/**
	 * @return the zoneType
	 */
	public TrnZoneType getZoneType() {
		return zoneType;
	}

	/**
	 * @param zoneType the zoneType to set
	 */
	public void setZoneType(TrnZoneType zoneType) {
		this.zoneType = zoneType;
	}

}
