package com.freshdirect.transadmin.model;

// Generated Nov 18, 2008 3:11:21 PM by Hibernate Tools 3.2.2.GA

/**
 * ZonetypeResource generated by hbm2java
 */
public class ZonetypeResource implements java.io.Serializable {

	private ZonetypeResourceId id;
	
	private Integer maximumNo;
	private Integer requiredNo;
	
	
	public ZonetypeResource() {
	}

	public ZonetypeResource(ZonetypeResourceId id) {
		this.id = id;
		
	}

	public ZonetypeResource(ZonetypeResourceId id, Integer maximumNo,Integer requiredNo) {
		this.id = id;
		this.maximumNo = maximumNo;
		this.requiredNo = requiredNo;
	}

	public ZonetypeResourceId getId() {
		return this.id;
	}

	public void setId(ZonetypeResourceId id) {
		this.id = id;
	}


	public Integer getMaximumNo() {
		return this.maximumNo;
	}

	public void setMaximumNo(Integer maximumNo) {
		this.maximumNo = maximumNo;
	}

	public Integer getRequiredNo() {
		return this.requiredNo;
	}

	public void setRequiredNo(Integer requiredNo) {
		this.requiredNo = requiredNo;
	}
	
	public String toString(){
	    StringBuffer buf=new StringBuffer();
	    if(this.maximumNo!=null) buf.append(this.maximumNo).append(" ");
		if(this.requiredNo!=null) buf.append(this.requiredNo);
		
		//System.out.println("ZoneType Resource :"+buf);
		return buf.toString();
	}

	
}
