CREATE TABLE CUST.REF_CHANNEL(
 ID                 VARCHAR2(16 BYTE)          NOT NULL PRIMARY KEY, 
 CHANNEL_NAME       VARCHAR2(55 BYTE)          NOT NULL,
 CHANNEL_TYPE       VARCHAR2(55 BYTE)          NOT NULL,
 CHANNEL_DESC       VARCHAR2(256 BYTE)
);

CREATE TABLE CUST.REF_OBJECTIVE(
 ID                   VARCHAR2(16 BYTE)          NOT NULL PRIMARY KEY, 
 OBJECTIVE_NAME       VARCHAR2(55 BYTE)          NOT NULL,
 OBJECTIVE_DESC       VARCHAR2(256 BYTE)
);

CREATE TABLE CUST.REF_PARTNER(
 ID                 VARCHAR2(16 BYTE)          NOT NULL PRIMARY KEY, 
 PARTNER_NAME       VARCHAR2(55 BYTE)          NOT NULL,
 PARTNER_DESC       VARCHAR2(256 BYTE)
);

CREATE TABLE CUST.REF_CAMPAIGN(
 ID                 VARCHAR2(16 BYTE)          NOT NULL PRIMARY KEY, 
 CAMPAIGN_NAME      VARCHAR2(55 BYTE)          NOT NULL,
 UNICA_REF_ID       VARCHAR2(16 BYTE),
 CAMPAIGN_DESC      VARCHAR2(256 BYTE),
 REF_OBJ_ID         VARCHAR2(16 BYTE) 
);



CREATE TABLE CUST.REF_PROGRAM(
 ID                  VARCHAR2(16 BYTE)          NOT NULL PRIMARY KEY, 
 PROGRAM_NAME        VARCHAR2(55 BYTE)          NOT NULL,
 PROGRAM_DESC        VARCHAR2(256 BYTE),
 PROGRAM_START_DATE  DATE                       NOT NULL,
 PROGRAM_EXP_DATE    DATE                       NOT NULL,
 CREATIVE_DESC       VARCHAR2(256 BYTE),  
 STATUS              VARCHAR2(30 BYTE)          NOT NULL,
 REF_CHANNEL_ID      VARCHAR2(16 BYTE)          NOT NULL,  
 REF_CAMPAIGN_ID     VARCHAR2(16 BYTE)          NOT NULL,  
 REF_PARTNER_ID      VARCHAR2(16 BYTE)          NOT NULL,  
 CREATIVE_URL        VARCHAR2(256 BYTE), 
 REF_PROMOTION_code  VARCHAR2(16 BYTE)          
);

CREATE TABLE CUST.REF_HISTORY(
 ID                  VARCHAR2(16 BYTE)         NOT NULL  PRIMARY KEY, 
 REF_PROG_ID         VARCHAR2(16 BYTE),
 REF_PROG_INVT_ID    VARCHAR2(16 BYTE),
 DATE_CREATED        DATE,
 FD_USERID           VARCHAR2(16 BYTE),
 REF_TRK_KEY_DTLS    VARCHAR2(256 BYTE) 
);

CREATE TABLE CUST.REF_PROG_INVITATION(
  ID                   VARCHAR2(16 BYTE)           NOT NULL  PRIMARY KEY,
  REFERRER_CUST_ID     VARCHAR2(16 BYTE)           NOT NULL,
  REFERRAL_DATE        DATE                        NOT NULL,
  STATUS               VARCHAR2(30 BYTE),
  REFERRAL_NAME        VARCHAR2(80 BYTE),
  REFERRAL_EMAIL_ADDR  VARCHAR2(80 BYTE)           NOT NULL,
  REF_PROG_ID          VARCHAR2(16 BYTE),
  MODIFIED_DATE        DATE
);



ALTER TABLE CUST.REF_CAMPAIGN ADD CONSTRAINT REF_CAMPAIGN_OBJ_FK FOREIGN KEY (REF_OBJ_ID) REFERENCES CUST.REF_OBJECTIVE(ID);

ALTER TABLE CUST.REF_PROGRAM ADD CONSTRAINT REF_PROGRAM_CHANNEL_FK FOREIGN KEY (REF_CHANNEL_ID) REFERENCES CUST.REF_CHANNEL(ID);

ALTER TABLE CUST.REF_PROGRAM ADD CONSTRAINT REF_PROGRAM_CAMPAIGN_FK FOREIGN KEY (REF_CAMPAIGN_ID) REFERENCES CUST.REF_CAMPAIGN(ID);

ALTER TABLE CUST.REF_PROGRAM ADD CONSTRAINT REF_PROGRAM_PARTNER_FK FOREIGN KEY (REF_PARTNER_ID) REFERENCES CUST.REF_PARTNER(ID);

ALTER TABLE CUST.REF_PROGRAM ADD CONSTRAINT REF_PROGRAM_PROMOTION_FK FOREIGN KEY (REF_PROMOTION_CODE) REFERENCES 
CUST.PROMOTION(CODE);


ALTER TABLE CUST.REF_HISTORY ADD CONSTRAINT REF_HISTORY_PROG_FK FOREIGN KEY (REF_PROG_ID) REFERENCES CUST.REF_PROGRAM(ID);

ALTER TABLE CUST.REF_HISTORY ADD CONSTRAINT REF_HISTORY_INVT_FK FOREIGN KEY (REF_PROG_INVT_ID) REFERENCES CUST.REF_PROG_INVITATION(ID);

ALTER TABLE CUST.REF_HISTORY ADD CONSTRAINT REF_HISTORY_FDUSER_FK FOREIGN KEY(FD_USERID)  REFERENCES CUST.FDUSER(ID);

ALTER TABLE CUST.REF_PROG_INVITATION ADD CONSTRAINT REF_INVT_REF_PROG_ID_FK FOREIGN KEY(REF_PROG_ID) REFERENCES CUST.REF_PROGRAM(ID);

ALTER TABLE CUST.REF_PROG_INVITATION ADD CONSTRAINT REF_INVT_REF_CUST_ID_FK FOREIGN KEY(REFERRER_CUST_ID) REFERENCES CUST.CUSTOMER(ID);

ALTER TABLE CUST.FDUSER ADD LAST_REF_PROG_ID VARCHAR2(16);
 
ALTER TABLE CUST.FDUSER ADD REF_PROG_INVT_ID VARCHAR2(16);

ALTER TABLE CUST.FDUSER ADD REF_TRK_KEY_DTLS VARCHAR2(256);

ALTER TABLE CUST.FDUSER ADD CONSTRAINT FDUSER_REF_PROG_ID_FK FOREIGN KEY(LAST_REF_PROG_ID) REFERENCES CUST.REF_PROGRAM(ID);
    
ALTER TABLE CUST.FDUSER ADD CONSTRAINT FDUSER_PROG_INVT_ID_FK FOREIGN KEY(REF_PROG_INVT_ID) REFERENCES CUST.REF_PROG_INVITATION(ID);
  
 
ALTER TABLE CUST.CUSTOMERINFO ADD REG_REF_PROG_ID VARCHAR2(16);
 
ALTER TABLE CUST.CUSTOMERINFO ADD REF_PROG_INVT_ID VARCHAR2(16);
 

ALTER TABLE CUST.CUSTOMERINFO ADD CONSTRAINT CUSTINFO_REF_PROG_ID_FK FOREIGN KEY(REG_REF_PROG_ID) REFERENCES CUST.REF_PROGRAM(ID);
   
ALTER TABLE CUST.CUSTOMERINFO ADD CONSTRAINT CUSTINFO_PROG_INVT_ID_FK FOREIGN KEY(REF_PROG_INVT_ID) REFERENCES CUST.REF_PROG_INVITATION(ID);


GRANT SELECT,INSERT, UPDATE,DELETE ON CUST.REF_CHANNEL TO FDSTORE_PRDA, FDSTORE_PRDB;

GRANT SELECT,INSERT, UPDATE,DELETE ON CUST.REF_OBJECTIVE TO FDSTORE_PRDA, FDSTORE_PRDB;

GRANT SELECT,INSERT, UPDATE,DELETE ON CUST.REF_PARTNER TO FDSTORE_PRDA, FDSTORE_PRDB;

GRANT SELECT,INSERT, UPDATE,DELETE ON CUST.REF_CAMPAIGN TO FDSTORE_PRDA, FDSTORE_PRDB;

GRANT SELECT,INSERT, UPDATE,DELETE ON CUST.REF_PROGRAM TO FDSTORE_PRDA, FDSTORE_PRDB;

GRANT SELECT,INSERT, UPDATE,DELETE ON CUST.REF_HISTORY TO FDSTORE_PRDA, FDSTORE_PRDB;

GRANT SELECT,INSERT, UPDATE,DELETE ON CUST.REF_PROG_INVITATION TO FDSTORE_PRDA, FDSTORE_PRDB;

