--------------- Start TRN_DELIVERYMODEL Table ----------------------------

CREATE TABLE TRN_DELIVERYMODEL
(
  CODE         VARCHAR2(8 BYTE)                 NOT NULL,
  NAME         VARCHAR2(32 BYTE)                NOT NULL  
);

ALTER TABLE TRN_DELIVERYMODEL ADD (CONSTRAINT PK_TRN_DELIVERYMODEL PRIMARY KEY (CODE));

ALTER TABLE TRN_DELIVERYMODEL ADD UNIQUE (NAME);  
--------------- End TRN_DELIVERYMODEL Table ----------------------------

--------------- Start TRN_AREA Table ----------------------------

CREATE TABLE TRN_AREA
(
  CODE           VARCHAR2(8 BYTE)               NOT NULL,
  NAME           VARCHAR2(32 BYTE)              NOT NULL,
  DESCRIPTION    VARCHAR2(256 BYTE),
  ACTIVE         VARCHAR2(1 BYTE),
  PREFIX         VARCHAR2(8 BYTE)               NOT NULL,
  DELIVERYMODEL  VARCHAR2(8 BYTE)               DEFAULT '003'                 NOT NULL
);

ALTER TABLE TRN_AREA ADD (CONSTRAINT PK_TRN_AREA PRIMARY KEY (CODE));

ALTER TABLE TRN_AREA ADD UNIQUE (NAME);

ALTER TABLE TRN_AREA ADD (CONSTRAINT ACT_TRN_AREADM_FK FOREIGN KEY (DELIVERYMODEL) REFERENCES TRN_DELIVERYMODEL (CODE));
--------------- End TRN_AREA Table ----------------------------

--------------- Start TRN_CUTOFF Table ----------------------------

CREATE TABLE TRN_CUTOFF
(
  ID           VARCHAR2(16 BYTE)                NOT NULL,
  NAME         VARCHAR2(32 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(256 BYTE),
  SEQUENCENO   NUMBER                           NOT NULL
);

ALTER TABLE TRN_CUTOFF ADD (CONSTRAINT PK_TRN_CUTOFF PRIMARY KEY (ID));
  
ALTER TABLE TRN_CUTOFF ADD UNIQUE (NAME);
 
ALTER TABLE TRN_CUTOFF ADD UNIQUE (SEQUENCENO);

CREATE SEQUENCE CUTOFFSEQ
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 200
  NOORDER;
--------------- End TRN_CUTOFF Table -----------------------------------------------

--------------- Start TRN_ZONETYPE Table --------------------------------------------

CREATE TABLE TRN_ZONETYPE
(
  ID           VARCHAR2(16 BYTE)                NOT NULL,
  NAME         VARCHAR2(32 BYTE)                NOT NULL,
  DESCRIPTION  VARCHAR2(256 BYTE)
);

ALTER TABLE TRN_ZONETYPE ADD (CONSTRAINT PK_TRN_ZONETYPE PRIMARY KEY (ID)); 
 
ALTER TABLE TRN_ZONETYPE ADD UNIQUE (NAME);

CREATE SEQUENCE ZONETYPESEQ
   START WITH 1
   MAXVALUE 1000000000000000000000000000
   MINVALUE 1
   NOCYCLE
   CACHE 20
   NOORDER;
--------------- End TRN_ZONETYPE Table ----------------------------------------------

--------------- Start TRN_ROUTENUMBER Table --------------------------------------------

CREATE TABLE TRN_ROUTENUMBER
(
  ROUTE_DATE     DATE                           NOT NULL,
  CUTOFF_ID      VARCHAR2(16 BYTE)              NOT NULL,
  AREA_CODE      VARCHAR2(8 BYTE)               NOT NULL,
  CURRENT_VALUE  NUMBER                         NOT NULL
);

ALTER TABLE TRN_ROUTENUMBER ADD (CONSTRAINT PK_TRN_ROUTENUMBER PRIMARY KEY (ROUTE_DATE, CUTOFF_ID, AREA_CODE));
--------------- End TRN_ROUTENUMBER Table --------------------------------------------

--------------- Start TRN_ZONE Table --------------------------------------------

ALTER TABLE TRANSP.TRN_ZONE ADD ZONE_TYPE  VARCHAR2(16 BYTE); 

ALTER TABLE TRANSP.TRN_ZONE ADD AREA  VARCHAR2(8 BYTE); 
  
ALTER TABLE TRN_ZONE ADD (CONSTRAINT ACT_TRN_ZONE_FK FOREIGN KEY (ZONE_TYPE) REFERENCES TRN_ZONETYPE (ID));
 
ALTER TABLE TRN_ZONE ADD (CONSTRAINT ACT_TRN_AREA_FK FOREIGN KEY (AREA) REFERENCES TRN_AREA (CODE));
 
--------------- End TRN_ZONE Table --------------------------------------------

---------------- START ALL TABLE GRANTS --------------------------------------------
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_DELIVERYMODEL TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_DELIVERYMODEL TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_DELIVERYMODEL TO FDTRN_PRDA;
GRANT SELECT ON TRN_DELIVERYMODEL TO APPDEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_AREA TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_AREA TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_AREA TO FDTRN_PRDA;
GRANT SELECT ON TRN_AREA TO APPDEV;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_CUTOFF TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_CUTOFF TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_CUTOFF TO FDTRN_PRDA;
GRANT SELECT ON TRN_CUTOFF TO APPDEV;
GRANT SELECT ON CUTOFFSEQ TO FDSTORE_PRDA;
GRANT SELECT ON CUTOFFSEQ TO FDSTORE_PRDB;
GRANT SELECT ON CUTOFFSEQ TO FDTRN_PRDA;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_ZONETYPE TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_ZONETYPE TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_ZONETYPE TO FDTRN_PRDA;
GRANT SELECT ON TRN_ZONETYPE TO APPDEV;
GRANT SELECT ON ZONETYPESEQ TO FDSTORE_PRDA;
GRANT SELECT ON ZONETYPESEQ TO FDSTORE_PRDB;
GRANT SELECT ON ZONETYPESEQ TO FDTRN_PRDA;

GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_ROUTENUMBER TO FDSTORE_PRDA;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_ROUTENUMBER TO FDSTORE_PRDB;
GRANT DELETE, INSERT, SELECT, UPDATE ON  TRN_ROUTENUMBER TO FDTRN_PRDA;
GRANT SELECT ON TRN_ROUTENUMBER TO APPDEV;


---------------- END ALL TABLE GRANTS --------------------------------------------