-- (Credit Issue) Reason to (Case) Subject mapping provided by Harry Orenstein
--
-- CRM Enhancements Feature #1
--
update cust.complaint_code set subject_code='ORQ-012' where code='PRDTMP';
update cust.complaint_code set priority='1' where code='PRDTMP';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='PRDTMP';
update cust.complaint_code set subject_code='ORQ-012' where code='ADVERSE';
update cust.complaint_code set priority='1' where code='ADVERSE';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='ADVERSE';
update cust.complaint_code set subject_code='ORQ-012' where code='DIRT';
update cust.complaint_code set priority='1' where code='DIRT';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='DIRT';
update cust.complaint_code set subject_code='ORQ-012' where code='FOROBJ';
update cust.complaint_code set priority='1' where code='FOROBJ';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='FOROBJ';
update cust.complaint_code set subject_code='ORQ-012' where code='INSECT';
update cust.complaint_code set priority='1' where code='INSECT';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='INSECT';
update cust.complaint_code set subject_code='ORQ-012' where code='NTCLND';
update cust.complaint_code set priority='1' where code='NTCLND';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='NTCLND';
update cust.complaint_code set subject_code='ORQ-012' where code='WORMS';
update cust.complaint_code set priority='1' where code='WORMS';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='WORMS';
update cust.complaint_code set subject_code='TCQ-003' where code='BLDGDAM';
update cust.complaint_code set priority='2' where code='BLDGDAM';
update cust.complaint_code set subject_code='TCQ-003' where code='PROPDAM';
update cust.complaint_code set priority='2' where code='PROPDAM';
update cust.complaint_code set subject_code='TCQ-004' where code='ACCDNT';
update cust.complaint_code set priority='3' where code='ACCDNT';
update cust.complaint_code set subject_code='TCQ-001' where code='DRVSMELL';
update cust.complaint_code set priority='4' where code='DRVSMELL';
update cust.complaint_code set subject_code='TCQ-001' where code='DRVMISH';
update cust.complaint_code set priority='4' where code='DRVMISH';
update cust.complaint_code set subject_code='TCQ-001' where code='DRVRUDE';
update cust.complaint_code set priority='4' where code='DRVRUDE';
update cust.complaint_code set subject_code='DSQ-014' where code='NODEL';
update cust.complaint_code set priority='5' where code='NODEL';
update cust.complaint_code set subject_code='DPQ-007' where code='DPPOORXP';
update cust.complaint_code set priority='5' where code='DPPOORXP';
update cust.complaint_code set subject_code='ORQ-011' where code='DOORMAN';
update cust.complaint_code set priority='6' where code='DOORMAN';
update cust.complaint_code set subject_code='ORQ-001' where code='MISBOX';
update cust.complaint_code set priority='7' where code='MISBOX';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='MISBOX';
update cust.complaint_code set subject_code='ORQ-001' where code='WRNBOX';
update cust.complaint_code set priority='7' where code='WRNBOX';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='WRNBOX';
update cust.complaint_code set subject_code='ORQ-002' where code='MISFRZ';
update cust.complaint_code set priority='8' where code='MISFRZ';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='MISFRZ';

update cust.complaint_code set subject_code='ORQ-007' where code='DAMBOX';
update cust.complaint_code set priority='9' where code='DAMBOX';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='DAMBOX';

update cust.complaint_code set subject_code='ORQ-015' where code='DAMBOXC';
update cust.complaint_code set priority='9' where code='DAMBOXC';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='DAMBOXC';

update cust.complaint_code set subject_code='DSQ-003' where code='DAMBOXD';
update cust.complaint_code set priority='10' where code='DAMBOXD';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='DAMBOXD';

update cust.complaint_code set subject_code='ORQ-004' where code='RTLBWRBX';
update cust.complaint_code set priority='11' where code='RTLBWRBX';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='RTLBWRBX';
update cust.complaint_code set subject_code='DPQ-007' where code='DPAUTODL';
update cust.complaint_code set priority='12' where code='DPAUTODL';
update cust.complaint_code set subject_code='DPQ-007' where code='DPAUTOCX';
update cust.complaint_code set priority='12' where code='DPAUTOCX';
update cust.complaint_code set subject_code='DPQ-007' where code='DPWRONG';
update cust.complaint_code set priority='12' where code='DPWRONG';
update cust.complaint_code set subject_code='ORQ-013' where code='EARLDEL';
update cust.complaint_code set priority='13' where code='EARLDEL';
update cust.complaint_code set subject_code='DSQ-016' where code='DLVPRB';
update cust.complaint_code set priority='14' where code='DLVPRB';
update cust.complaint_code set subject_code='LDQ-004' where code='LATEDL0';
update cust.complaint_code set priority='15' where code='LATEDL0';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Late') where code='LATEDL0';
update cust.complaint_code set subject_code='LDQ-005' where code='LATEDL30';
update cust.complaint_code set priority='16' where code='LATEDL30';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Late') where code='LATEDL30';
update cust.complaint_code set subject_code='LDQ-010' where code='LATEDL60';
update cust.complaint_code set priority='17' where code='LATEDL60';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Late') where code='LATEDL60';
update cust.complaint_code set subject_code='LDQ-006' where code='LATEDL90';
update cust.complaint_code set priority='18' where code='LATEDL90';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Late') where code='LATEDL90';
update cust.complaint_code set subject_code='ORQ-006' where code='PRDXCL';
update cust.complaint_code set priority='19' where code='PRDXCL';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='PRDXCL';
update cust.complaint_code set subject_code='ORQ-006' where code='PRDEXP';
update cust.complaint_code set priority='19' where code='PRDEXP';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='PRDEXP';
update cust.complaint_code set subject_code='ORQ-007' where code='AVDFZN';
update cust.complaint_code set priority='20' where code='AVDFZN';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='AVDFZN';
update cust.complaint_code set subject_code='ORQ-007' where code='WARM';
update cust.complaint_code set priority='20' where code='WARM';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='WARM';
update cust.complaint_code set subject_code='ORQ-008' where code='DEFROST';
update cust.complaint_code set priority='21' where code='DEFROST';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='DEFROST';
update cust.complaint_code set subject_code='ORQ-005' where code='PITTS';
update cust.complaint_code set priority='22' where code='PITTS';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='PITTS';
update cust.complaint_code set subject_code='ORQ-006' where code='SMELL';
update cust.complaint_code set priority='23' where code='SMELL';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='SMELL';
update cust.complaint_code set subject_code='ORQ-006' where code='DISCOL';
update cust.complaint_code set priority='23' where code='DISCOL';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='DISCOL';
update cust.complaint_code set subject_code='ORQ-006' where code='XSOFT';
update cust.complaint_code set priority='23' where code='XSOFT';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='XSOFT';
update cust.complaint_code set subject_code='ORQ-006' where code='HRDSTL';
update cust.complaint_code set priority='23' where code='HRDSTL';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='HRDSTL';
update cust.complaint_code set subject_code='ORQ-006' where code='MOLDY';
update cust.complaint_code set priority='23' where code='MOLDY';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='MOLDY';
update cust.complaint_code set subject_code='ORQ-006' where code='ORIPE';
update cust.complaint_code set priority='23' where code='ORIPE';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='ORIPE';
update cust.complaint_code set subject_code='ORQ-006' where code='PRDDED';
update cust.complaint_code set priority='23' where code='PRDDED';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='PRDDED';
update cust.complaint_code set subject_code='ORQ-006' where code='QUALDIS';
update cust.complaint_code set priority='23' where code='QUALDIS';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='QUALDIS';
update cust.complaint_code set subject_code='ORQ-006' where code='SFOPCL';
update cust.complaint_code set priority='23' where code='SFOPCL';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='SFOPCL';
update cust.complaint_code set subject_code='ORQ-006' where code='SPOILED';
update cust.complaint_code set priority='23' where code='SPOILED';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='SPOILED';
update cust.complaint_code set subject_code='ORQ-006' where code='TOOFAT';
update cust.complaint_code set priority='23' where code='TOOFAT';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='TOOFAT';
update cust.complaint_code set subject_code='ORQ-006' where code='TOOGRIS';
update cust.complaint_code set priority='23' where code='TOOGRIS';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='TOOGRIS';
update cust.complaint_code set subject_code='ORQ-006' where code='TOOSPIC';
update cust.complaint_code set priority='23' where code='TOOSPIC';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='TOOSPIC';
update cust.complaint_code set subject_code='ORQ-006' where code='URIPE';
update cust.complaint_code set priority='23' where code='URIPE';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='URIPE';
update cust.complaint_code set subject_code='ORQ-006' where code='WILTED';
update cust.complaint_code set priority='23' where code='WILTED';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='WILTED';
update cust.complaint_code set subject_code='ORQ-007' where code='BRUISED';
update cust.complaint_code set priority='24' where code='BRUISED';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='BRUISED';
update cust.complaint_code set subject_code='ORQ-007' where code='CRACKED';
update cust.complaint_code set priority='24' where code='CRACKED';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='CRACKED';
update cust.complaint_code set subject_code='ORQ-007' where code='PRDLEK';
update cust.complaint_code set priority='24' where code='PRDLEK';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='PRDLEK';
update cust.complaint_code set subject_code='ORQ-004' where code='RTLBWRPR';
update cust.complaint_code set priority='25' where code='RTLBWRPR';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='RTLBWRPR';
update cust.complaint_code set subject_code='ORQ-003' where code='MISITM';
update cust.complaint_code set priority='26' where code='MISITM';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='MISITM';
update cust.complaint_code set subject_code='ORQ-005' where code='DISCUT';
update cust.complaint_code set priority='27' where code='DISCUT';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='DISCUT';
update cust.complaint_code set subject_code='ORQ-005' where code='NTCUBSLC';
update cust.complaint_code set priority='27' where code='NTCUBSLC';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='NTCUBSLC';
update cust.complaint_code set subject_code='ORQ-005' where code='NTGNDSPC';
update cust.complaint_code set priority='27' where code='NTGNDSPC';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='NTGNDSPC';
update cust.complaint_code set subject_code='ORQ-005' where code='NTPAKSPC';
update cust.complaint_code set priority='27' where code='NTPAKSPC';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='NTPAKSPC';
update cust.complaint_code set subject_code='ORQ-005' where code='NTASEX';
update cust.complaint_code set priority='27' where code='NTASEX';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='NTASEX';
update cust.complaint_code set subject_code='ORQ-005' where code='SIZBIG';
update cust.complaint_code set priority='27' where code='SIZBIG';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='SIZBIG';
update cust.complaint_code set subject_code='ORQ-005' where code='SIZSML';
update cust.complaint_code set priority='27' where code='SIZSML';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='SIZSML';
update cust.complaint_code set subject_code='ORQ-005' where code='WRMISPK';
update cust.complaint_code set priority='27' where code='WRMISPK';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='WRMISPK';
update cust.complaint_code set subject_code='ORQ-005' where code='WRNSIZ';
update cust.complaint_code set priority='27' where code='WRNSIZ';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='WRNSIZ';
update cust.complaint_code set subject_code='ORQ-007' where code='DNTCAN';
update cust.complaint_code set priority='28' where code='DNTCAN';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='DNTCAN';
update cust.complaint_code set subject_code='ORQ-007' where code='DAMBOPRD';
update cust.complaint_code set priority='28' where code='DAMBOPRD';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='DAMBOPRD';
update cust.complaint_code set subject_code='ORQ-007' where code='PRDDAM';
update cust.complaint_code set priority='28' where code='PRDDAM';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Damaged') where code='PRDDAM';
update cust.complaint_code set subject_code='ORQ-005' where code='BULK';
update cust.complaint_code set priority='29' where code='BULK';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='BULK';
update cust.complaint_code set subject_code='ORQ-005' where code='CUSNOSUB';
update cust.complaint_code set priority='29' where code='CUSNOSUB';
update cust.complaint_code set subject_code='ORQ-005' where code='DISPSIZ';
update cust.complaint_code set priority='29' where code='DISPSIZ';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='DISPSIZ';
update cust.complaint_code set subject_code='ORQ-006' where code='RTGDIS';
update cust.complaint_code set priority='30' where code='RTGDIS';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Quality') where code='RTGDIS';
update cust.complaint_code set subject_code='OUT-007' where code='SRTITM';
update cust.complaint_code set priority='32' where code='SRTITM';
update cust.complaint_code set DLV_ISSUE_CODE=(select code from complaint_dlv_type where name='Missing') where code='SRTITM';
update cust.complaint_code set subject_code='PRQ-011' where code='NTELIG';
update cust.complaint_code set priority='32' where code='NTELIG';
update cust.complaint_code set subject_code='PRQ-009' where code='PRMNTWRK';
update cust.complaint_code set priority='33' where code='PRMNTWRK';
update cust.complaint_code set subject_code='PRQ-008' where code='PRMNTDLV';
update cust.complaint_code set priority='34' where code='PRMNTDLV';
update cust.complaint_code set subject_code='ORQ-009' where code='CUSTERR';
update cust.complaint_code set priority='35' where code='CUSTERR';
update cust.complaint_code set subject_code='DPQ-007' where code='DPMOVE';
update cust.complaint_code set priority='36' where code='DPMOVE';
update cust.complaint_code set subject_code='DSQ-017' where code='UDALCRMV';
update cust.complaint_code set priority='37' where code='UDALCRMV';
update cust.complaint_code set subject_code='DPQ-007' where code='DPDIS';
update cust.complaint_code set priority='38' where code='DPDIS';
update cust.complaint_code set subject_code='PRQ-010' where code='MKTEVT';
update cust.complaint_code set priority='39' where code='MKTEVT';
update cust.complaint_code set subject_code='TCQ-001' where code='MISINV';
update cust.complaint_code set priority='40' where code='MISINV';
update cust.complaint_code set subject_code='CAQ-007' where code='TAXEMPT';
update cust.complaint_code set priority='41' where code='TAXEMPT';
update cust.complaint_code set subject_code='OUT-010' where code='GENDIS';
update cust.complaint_code set priority='42' where code='GENDIS';
update cust.complaint_code set subject_code='OUT-010' where code='GDWILL';
update cust.complaint_code set priority='42' where code='GDWILL';
update cust.complaint_code set subject_code='OUT-010' where code='OTHER';
update cust.complaint_code set priority='42' where code='OTHER';
