DROP SEQUENCE BATCH_SEQ ;
DROP SEQUENCE SYSTEM_SEQ ;
CREATE SEQUENCE BATCH_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
CREATE SEQUENCE SYSTEM_SEQ INCREMENT BY 1 START WITH 1 NOCYCLE NOCACHE NOORDER;
