/* Generated by Together */

package com.freshdirect.fdstore.content;

import com.freshdirect.cms.AttributeI;
import com.freshdirect.cms.ContentKey;
import com.freshdirect.fdstore.attributes.Attribute;
import com.freshdirect.framework.core.PrimaryKey;

public interface ContentNodeI {

	String TYPE_STORE = "X";
	String TYPE_TEMPLATE = "T";
	String TYPE_DEPARTMENT = "D";
	String TYPE_CATEGORY = "C";
	String TYPE_PRODUCT = "P";
	String TYPE_CONFIGURED_PRODUCT = "PC";
	String TYPE_SKU = "S";
	String TYPE_BRAND = "B";
	String TYPE_PRODUCTPROXY = "Q";
	String TYPE_DOMAIN = "Z";
	String TYPE_DOMAINVALUE = "V";
	String TYPE_COMPONENTGROUP = "G";
	String TYPE_RECIPE_DEPARTMENT = "RD";
	String TYPE_RECIPE_CATEGORY = "RC";
	String TYPE_RECIPE_SUBCATEGORY = "RSC";
	String TYPE_RECIPE = "R";
	String TYPE_RECIPE_VARIANT = "RV";
	String TYPE_RECIPE_SECTION = "RS";
	String TYPE_RECIPE_SOURCE = "RSO";
	String TYPE_RECIPE_AUTHOR = "RA";
	String TYPE_FD_FOLDER = "FDF";
	String TYPE_BOOK_RETAILER = "BKR";
	String TYPE_RECIPE_SEARCH_PAGE = "RSP";
	String TYPE_RECIPE_SEARCH_CRITERIA = "RSPC";
	String TYPE_YMAL_SET = "YS";
	String TYPE_STARTER_LIST = "SL";

	//
	//
	//

	/** @deprecated use getContentName() */
	public PrimaryKey getPK();

	public ContentKey getContentKey();

	public String getContentName();

	public String getContentType();

	/**
	 * @deprecated
	 */
	public Attribute getAttribute(String key);
	
	public AttributeI getCmsAttribute(String name);

	public boolean hasAttribute(String key);

	public Object getAttribute(String key, Object defaultValue);

	public String getAttribute(String key, String defaultValue);

	public int getAttribute(String key, int defaultValue);

	public boolean getAttribute(String key, boolean defaultValue);

	public double getAttribute(String key, double defaultValue);

	public ContentNodeModel getParentNode();

	public boolean hasParentWithName(String[] contentNames);

}
