/* Generated by Together */

package com.freshdirect.fdstore.content;

public class Html extends MediaModel {
    
    public Html() {
        super();
        mediaType = MediaModel.TYPE_HTML;
    }
    
    public Html(String path) {
    	this();
    	setPath(path);	
    }

    public String toString() {
    	return "Html["+ getPK() +", "+ getPath() +"]";
    }

}
