/* Generated by Together */

package com.freshdirect.fdstore.content;

public class Image extends MediaModel {
    
    public Image() {
        super();
        mediaType = TYPE_IMAGE;
    }
    
    public Image(String path, int width, int height) {
    	this();
		this.setPath(path);
		this.setWidth(width);
		this.setHeight(height);
    }

    public int getWidth(){
        return width;
    }
    
    public void setWidth(int width){
        this.width = width;
    }
    
    public int getHeight(){
        return height;
    }
    
    public void setHeight(int height){
        this.height = height;
    }
    
    public String toString() {
    	return "Image["+ getPK() +", "+ getPath() +", "+ getWidth() +"x"+ getHeight() +"]";
    }
    
    public String toHtml(String alternateName, String className) {
        return "<img src=\"" + getPath() + "\" width=\"" + getWidth() + "\" height=\"" + getHeight() +'"' +  
            (alternateName != null && alternateName.trim().length()>0 ? " alt=\"" + alternateName + '"' : "") + 
            (className != null && className.trim().length()>0 ? " class=\"" + className + '"' : "") + 
            '>';
    }
    public String toHtml(String alternateName) {
        return toHtml(alternateName, null);
    }
    
    public String toHtml() {
        return toHtml(null);
    }
    
    
    private int width;
    private int height;
}
