/* Generated by Together */
package com.freshdirect.fdstore.content;

import com.freshdirect.cms.util.PublishId;


public class Image extends MediaModel {
    private int width;
    private int height;
    private String style = null;
    private String cssClass = null;
    private String altText = "";

    public Image() {
        super();
        mediaType = TYPE_IMAGE;
    }

    public Image(String path, int width, int height) {
        this();
        this.setPath(path);
        this.setWidth(width);
        this.setHeight(height);
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public String getStyle() {
        return style;
    }

    public void setStyle(String styleText) {
        this.style = styleText;
    }

    public String getCssClass() {
        return cssClass;
    }

    public void setCssClass(String cssClass) {
        this.cssClass = cssClass;
    }

    public String toString() {
        return "Image[" + getPK() + ", " + getPath() + ", " + getWidth() + "x" +
        getHeight() + "]";
    }

    public void setAltText(String altText) {
        this.altText = altText;
    }

    public String getAltText() {
        return altText;
    }
	
    public String toHtml(String alternateName, String className,
        boolean withPublishId) {
        return "<img src=\"" +
        (withPublishId ? getPathWithPublishId() : getPath()) + "\" width=\"" +
        getWidth() + "\" height=\"" + getHeight() + '"' +
        (((alternateName != null) && (alternateName.trim().length() > 0))
        ? (" alt=\"" + alternateName + '"') : "") +
        (((className != null) && (className.trim().length() > 0))
        ? (" class=\"" + className + '"') : "") + '>';
    }

    public String toHtml(String alternateName, String className) {
        return toHtml(alternateName, className, false);
    }

    public String toHtml(String alternateName) {
        return toHtml(alternateName, null, false);
    }

    public String toHtml(String alternateName, boolean withPublishId) {
        return toHtml(alternateName, null, withPublishId);
    }

    public String toHtml() {
        return toHtml(null);
    }

    public String getPathWithPublishId() {
        String publishId = PublishId.getInstance().getPublishId();

        if (publishId != null) {
            return getPath() + "?publishId=" + publishId;
        } else {
            return getPath();
        }
    }
}
