/* Generated by Together */

package com.freshdirect.fdstore.content;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

public class StoreModel extends ContentNodeModelImpl {

	private List departments = new ArrayList();
	private List brands;
	private List domains;

	public StoreModel(com.freshdirect.cms.ContentKey cKey) {
		super(cKey);
	}
	
	public int getVersion() {
	    return 100;
	}

	public String getName() {
		return this.getAttribute("FULL_NAME", "FreshDirect");
	}

	public List getDepartments() {
		ContentNodeModelUtil.refreshModels(this, "departments", departments, true);
		return new ArrayList(departments);
	}
	
	public Set getSortedDepartments(Comparator comp) {
            ContentNodeModelUtil.refreshModels(this, "departments", departments, true);
	    Set result = new TreeSet(comp);
	    result.addAll(departments);
	    return result;
	}
	
	public List getBrands() {
	    return new ArrayList(brands);
	}

	public void setBrands(List brands) {
		this.brands = brands;
		for (Iterator i = brands.iterator(); i.hasNext(); ) {
		    BrandModel brand = (BrandModel) i.next();
		    brand.setParentNode(this);
		}
	}

	public List getDomains() {
	    return new ArrayList(domains);
	}

	public void setDomains(List domains) {
		this.domains = domains;
		for (Iterator i = domains.iterator(); i.hasNext(); ) {
		    Domain domain = (Domain) i.next();
		    domain.setParentNode(this);
		}
	}
	
}
