ALTER TABLE TRANSP.TRN_DISPATCH_PLAN ADD PLAN_DATE DATE;

UPDATE TRANSP.TRN_DISPATCH_PLAN SET PLAN_DATE = to_date('1900/01/01', 'yyyy/mm/dd') Where DISPATCH_DAY = 'Monday';
UPDATE TRANSP.TRN_DISPATCH_PLAN SET PLAN_DATE = to_date('1900/01/02', 'yyyy/mm/dd') Where DISPATCH_DAY = 'Tuesday';
UPDATE TRANSP.TRN_DISPATCH_PLAN SET PLAN_DATE = to_date('1900/01/03', 'yyyy/mm/dd') Where DISPATCH_DAY = 'Wednesday';
UPDATE TRANSP.TRN_DISPATCH_PLAN SET PLAN_DATE = to_date('1900/01/04', 'yyyy/mm/dd') Where DISPATCH_DAY = 'Thursday';
UPDATE TRANSP.TRN_DISPATCH_PLAN SET PLAN_DATE = to_date('1900/01/05', 'yyyy/mm/dd') Where DISPATCH_DAY = 'Friday';
UPDATE TRANSP.TRN_DISPATCH_PLAN SET PLAN_DATE = to_date('1900/01/06', 'yyyy/mm/dd') Where DISPATCH_DAY = 'Saturday';
UPDATE TRANSP.TRN_DISPATCH_PLAN SET PLAN_DATE = to_date('1900/01/07', 'yyyy/mm/dd') Where DISPATCH_DAY = 'Sunday';

