INSERT INTO cms.relationshipdefinition (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,LABEL,CARDINALITY_CODE) VALUES ('SEPARATOR_MEDIA','Category.SEPARATOR_MEDIA','Category','F','F','F','Separator Media','One');
INSERT INTO cms.relationshipdestination (RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,LABEL,ID) VALUES ('Category.SEPARATOR_MEDIA','Html',NULL,'Category.SEPARATOR_MEDIA.Html');
