GRANT SELECT ON CUST.PROMO_DLV_DAY TO appdev;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUST.PROMO_DLV_DAY TO fdstore_ststg01;
GRANT DELETE, INSERT, SELECT, UPDATE ON CUST.PROMO_DLV_DAY TO fdtrn_ststg01;