Insert into CMS.RELATIONSHIPDEFINITION (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,LABEL,CARDINALITY_CODE,READONLY) values ('EDITORIAL','Store.EDITORIAL','Store','F','F','F','Editorial','One','F');
Insert into CMS.RELATIONSHIPDESTINATION (RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,ID,REVERSE_ATTRIBUTE_NAME,REVERSE_ATTRIBUTE_LABEL) values ('Store.EDITORIAL','Html','Store.EDITORIAL.Html',null,null);

