ALTER TABLE "CUST"."SO_HOLIDAY_ALT_DATE" 
add "DESCRIPTION" VARCHAR2(35 CHAR); 

ALTER TABLE "CUST"."SO_HOLIDAY_ALT_DATE" 
add CONSTRAINT PK_SO_HOLIDAY_ALT_DATE PRIMARY KEY (CURRENT_DELIVERY_DATE);

ALTER TABLE "CUST"."SALE"
add "SO_HOLIDAY_MOVEMENT" CHAR(1 BYTE); 
