INSERT into ERPS.ATTRIBUTES (ID,ROOT_ID,CHILD1_ID,CHILD2_ID,ATR_TYPE,ATR_NAME,ATR_VALUE,DATE_MODIFIED) 
values ((SELECT MAX(TO_NUMBER(ID)) + 1 from ERPS.ATTRIBUTES),'000000000900000100',null,null,'S','specialproduct','DeliveryPass',sysdate);

INSERT into ERPS.ATTRIBUTES (ID,ROOT_ID,CHILD1_ID,CHILD2_ID,ATR_TYPE,ATR_NAME,ATR_VALUE,DATE_MODIFIED)
values ((SELECT MAX(TO_NUMBER(ID)) + 1 from ERPS.ATTRIBUTES),'000000000900000101',null,null,'S','specialproduct','DeliveryPass',sysdate);

INSERT into ERPS.ATTRIBUTES (ID,ROOT_ID,CHILD1_ID,CHILD2_ID,ATR_TYPE,ATR_NAME,ATR_VALUE,DATE_MODIFIED) 
values ((SELECT MAX(TO_NUMBER(ID)) + 1 from ERPS.ATTRIBUTES),'000000000900000102',null,null,'S','specialproduct','DeliveryPass',sysdate);

INSERT into ERPS.ATTRIBUTES (ID,ROOT_ID,CHILD1_ID,CHILD2_ID,ATR_TYPE,ATR_NAME,ATR_VALUE,DATE_MODIFIED) 
values ((SELECT MAX(TO_NUMBER(ID)) + 1 from ERPS.ATTRIBUTES),'000000000900000103',null,null,'S','specialproduct','DeliveryPass',sysdate);
