CREATE TABLE CUST.SAVED_RECIPIENT(ID VARCHAR2(16) NOT NULL,
FDUSER_ID VARCHAR2(16) NOT NULL,
SENDER_NAME VARCHAR2(55) NOT NULL,
SENDER_EMAIL VARCHAR2(80) NOT NULL,
RECIP_NAME VARCHAR2(55) NOT NULL,
RECIP_EMAIL VARCHAR2(80) NOT NULL,
AMOUNT NUMBER(10,2) NOT NULL,
PERSONAL_MSG VARCHAR2(256),
TEMPLATE_ID VARCHAR2(55) NOT NULL,
DELIVERY_MODE CHAR(1) NOT NULL,
CONSTRAINT SAVED_RECIP_PK PRIMARY KEY (ID) ENABLE,
CONSTRAINT SAVED_RECIP_FK_1 FOREIGN KEY ("FDUSER_ID") REFERENCES "FDUSER" ("ID") ENABLE);


CREATE TABLE CUST.GIFT_CARD_RECIPIENT(ID VARCHAR2(16) NOT NULL,
CUSTOMER_ID VARCHAR2(16) NOT NULL,
SENDER_NAME VARCHAR2(55) NOT NULL,
SENDER_EMAIL VARCHAR2(80) NOT NULL,
RECIP_NAME VARCHAR2(55) NOT NULL,
RECIP_EMAIL VARCHAR2(80) ,
AMOUNT NUMBER(10,2) NOT NULL,
PERSONAL_MSG VARCHAR2(256),
TEMPLATE_ID VARCHAR2(55) NOT NULL,
DELIVERY_MODE CHAR(1) NOT NULL,
SALESACTION_ID VARCHAR2(16) NOT NULL,
ORDERLINE_NUMBER VARCHAR2(16) NOT NULL,
CONSTRAINT GIFT_CARD_RECIP_PK PRIMARY KEY (ID) ENABLE,
CONSTRAINT GIFT_CARD_RECIP_FK_1 FOREIGN KEY ("CUSTOMER_ID") REFERENCES "CUSTOMER" ("ID") ENABLE);


CREATE TABLE CUST.GIFT_CARD(ID VARCHAR2(16) NOT NULL,
GIVEX_NUM VARCHAR2(55) NOT NULL,
BALANCE NUMBER(10,2) NOT NULL,
CREATE_DATE DATE NOT NULL,
EFFECTIVE_DATE DATE,
EXP_DATE DATE,
CERTIFICATE_NUM VARCHAR2(10) NOT NULL,
SALE_ID VARCHAR2(16) NOT NULL,
CARD_TYPE VARCHAR2(3) NOT NULL,
ORIG_AMOUNT NUMBER(10,2) NOT NULL,
CONSTRAINT GIFT_CARD_PK PRIMARY KEY (ID) ENABLE);
    
CREATE TABLE CUST.GIFT_CARD_DELIVERY_INFO(ID VARCHAR2(16) NOT NULL,
SALESACTION_ID VARCHAR2(16) NOT NULL,
GIFT_CARD_ID VARCHAR2(16) NOT NULL,
RECIPIENT_ID VARCHAR2(16) NOT NULL,
DELIVERY_MODE CHAR(1) NOT NULL,
EMAIL_SENT DATE ,
CONSTRAINT GIFT_CARD_DI_PK PRIMARY KEY (ID) ENABLE,
CONSTRAINT GIFT_CARD_DI_FK_1 FOREIGN KEY ("SALESACTION_ID") REFERENCES "SALESACTION" ("ID") ENABLE,
CONSTRAINT GIFT_CARD_DI_FK_2 FOREIGN KEY ("GIFT_CARD_ID") REFERENCES "GIFT_CARD" ("ID") ENABLE,
CONSTRAINT GIFT_CARD_DI_FK_3 FOREIGN KEY ("RECIPIENT_ID") REFERENCES "GIFT_CARD_RECIPIENT" ("ID") ENABLE);

CREATE TABLE CUST.GIFT_CARD_TRANS(ID VARCHAR2(16) NOT NULL,
SALESACTION_ID VARCHAR2(16) NOT NULL,
TRAN_TYPE VARCHAR2(10) NOT NULL,
TRAN_STATUS CHAR(1) NOT NULL,
AUTH_CODE VARCHAR2(16),
PRE_AUTH_CODE VARCHAR2(16),
ERROR_MSG VARCHAR2(128),
TRANS_AMOUNT NUMBER(10,2) NOT NULL,
CERTIFICATE_NUM VARCHAR2(10) ,
TO_CERTIFICATE_NUM VARCHAR2(10),
POST_DATE_TIME DATE NOT NULL,
REFERENCE_ID VARCHAR2(20),
CONSTRAINT GIFT_CARD_TRANS_PK PRIMARY KEY (ID) ENABLE,
CONSTRAINT GIFT_CARD_TRANS_FK_1 FOREIGN KEY ("SALESACTION_ID") REFERENCES "SALESACTION" ("ID") ENABLE);

CREATE TABLE CUST.APPLIED_GIFT_CARD(ID VARCHAR2(16) NOT NULL,
SALESACTION_ID VARCHAR2(16) NOT NULL,
CERTIFICATE_NUM VARCHAR2(10) NOT NULL,
AMOUNT NUMBER(10,2) NOT NULL,
AFFILIATE VARCHAR2(8) NOT NULL,
CONSTRAINT APP_GIFT_CARD_PK PRIMARY KEY (ID) ENABLE,
CONSTRAINT APP_GIFT_CARD_FK_2 FOREIGN KEY ("SALESACTION_ID") REFERENCES "SALESACTION" ("ID") ENABLE);

ALTER TABLE CUST.ACTIVITY_LOG ADD GIFT_CARD_ID VARCHAR2(16);

ALTER TABLE CUST.CUSTOMERINFO ADD APPLY_GIFT_CARD CHAR(1);

ALTER TABLE CUST.DELIVERYINFO MODIFY DELIVERY_TYPE VARCHAR2(2);

-- Need to create a profile for enabling/disabling apply gift card.
INSERT INTO CUST.PROFILE_ATTR_NAME ( NAME, DESCRIPTION, CATEGORY, ATTR_VALUE_TYPE,
IS_EDITABLE ) VALUES ( 
'allow_apply_gc', 'allow_apply_gc', 'General', NULL, 'X'); 

alter table cust.salesaction add BUFFER_AMT number(8,2) null;

--NEED to create indices on SALESACTION_ID for all GC tables that links to sales action table Eg:GIFT_CARD_DELIVERY_INFO