CREATE TABLE CUST.PROMO_VARIANTS(VARIANT_ID VARCHAR2(32) NOT NULL,
PROMO_CODE VARCHAR2(16) NOT NULL,
PRIORITY NUMBER(5),
FEATURE_PRIORITY NUMBER(5),
CREATE_DATE DATE,
CONSTRAINT PROMO_VARIANTS_PK PRIMARY KEY (VARIANT_ID,PROMO_CODE) ENABLE,
CONSTRAINT PROMO_VARIANTS_FK_1 FOREIGN KEY ("VARIANT_ID") REFERENCES "SS_VARIANTS" ("ID") ENABLE,
CONSTRAINT PROMO_VARIANTS_FK_2 FOREIGN KEY ("PROMO_CODE") REFERENCES "PROMOTION" ("CODE") ENABLE);

-- CUSTOMIZE
GRANT SELECT ON CUST.PROMO_VARIANTS TO FDSTORE;
GRANT SELECT ON CUST.PROMO_VARIANTS TO FDSTORE_PRDA;
GRANT SELECT ON CUST.PROMO_VARIANTS TO FDSTORE_PRDB;
GRANT SELECT ON CUST.PROMO_VARIANTS TO APPDEV;


