CREATE TABLE SS_SITE_FEATURE (ID VARCHAR2(16) NOT NULL, TITLE VARCHAR2(256), 
 PREZ_TITLE VARCHAR2(256), PREZ_DESC VARCHAR2(256),
 CONSTRAINT SS_SITE_FEAT_PK PRIMARY KEY (ID) ENABLE);

CREATE TABLE SS_TAB_STRATEGY_PRIORITY (
    TAB_STRATEGY_ID VARCHAR2(16) NOT NULL,
    SITE_FEATURE_ID VARCHAR2(16) NOT NULL,
    PRIMARY_PRIORITY NUMBER(10,0) NOT NULL,
    SECONDARY_PRIORITY NUMBER(10,0) NOT NULL,
  CONSTRAINT SS_STRAT_PRIO_UNIQ UNIQUE ("TAB_STRATEGY_ID", "PRIMARY_PRIORITY", "SECONDARY_PRIORITY") ENABLE,
  CONSTRAINT SS_STRAT_PRIO_TS_FK2 FOREIGN KEY ("TAB_STRATEGY_ID") REFERENCES "SS_VARIANTS" ("ID") ENABLE);

-- CUSTOMIZE
GRANT SELECT ON SS_SITE_FEATURE TO FDSTORE;
GRANT SELECT ON SS_TAB_STRATEGY_PRIORITY TO FDSTORE;

