
CREATE TABLE CUST.SURVEY_DEF
(
  ID                          VARCHAR2(16 BYTE) NOT NULL,
  NAME                        VARCHAR2(80 BYTE) NOT NULL,
  DESCR                       VARCHAR2(256 BYTE),
  CREATE_DATE                 DATE              DEFAULT SYSDATE               NOT NULL,
  IS_ORDER_SURVEY             VARCHAR2(1 BYTE),
  IS_CUSTOMER_PROFILE_SURVEY  VARCHAR2(1 BYTE),
  MIN_COVERAGE                INTEGER,
  PRIMARY KEY
 (ID),
  UNIQUE (NAME)
);



CREATE TABLE CUST.SURVEY_QUESTION
(
  ID                  VARCHAR2(16 BYTE)         NOT NULL,
  NAME                VARCHAR2(80 BYTE)         NOT NULL,
  DESCRIPTION         VARCHAR2(256 BYTE),
  IS_MULTISELECT      VARCHAR2(1 BYTE)          DEFAULT 'N',
  IS_OPENENDED        VARCHAR2(1 BYTE)          DEFAULT 'N',
  IS_RATING           VARCHAR2(1 BYTE)          DEFAULT 'N',
  SHOW_OPTIONAL_TEXT  VARCHAR2(1 BYTE)          DEFAULT 'N',
  IS_REQUIRED         VARCHAR2(1 BYTE)          DEFAULT 'N',
  IS_PULLDOWN         VARCHAR2(1 BYTE)          DEFAULT 'N',
  SHORT_DESCR         VARCHAR2(256 BYTE),
  FORM_DISPLAY_TYPE   INTEGER,
  VIEW_DISPLAY_TYPE   INTEGER,
  DATE_MODIFIED       DATE                      DEFAULT SYSDATE               NOT NULL,
  PRIMARY KEY
 (ID),
  UNIQUE (NAME)
);


CREATE TABLE CUST.SURVEY_ANSWER
(
  ID             VARCHAR2(16 BYTE)              NOT NULL,
  NAME           VARCHAR2(256 BYTE)             NOT NULL,
  DESCRIPTION    VARCHAR2(256 BYTE),
  DATE_MODIFIED  DATE                           DEFAULT SYSDATE               NOT NULL,
  PRIMARY KEY
 (ID),
  UNIQUE (NAME)
);


CREATE TABLE CUST.SURVEY_QA
(
  QUESTION       VARCHAR2(16 BYTE)              NOT NULL,
  ANSWER         VARCHAR2(16 BYTE),
  SEQUENCE       NUMBER,
  ANSWER_GROUP   VARCHAR2(80 BYTE),
  DATE_MODIFIED  DATE                           DEFAULT SYSDATE               NOT NULL,
  ID             VARCHAR2(16 BYTE),
  PRIMARY KEY
 (ID),
  UNIQUE (QUESTION, SEQUENCE),
  FOREIGN KEY (ANSWER) 
 REFERENCES CUST.SURVEY_ANSWER (ID),
  FOREIGN KEY (QUESTION) 
 REFERENCES CUST.SURVEY_QUESTION (ID)
);


CREATE TABLE CUST.SURVEY_SETUP
(
  SURVEY            VARCHAR2(16 BYTE)           NOT NULL,
  SEQUENCE          NUMBER,
  ACTIVE            VARCHAR2(1 BYTE)            DEFAULT 'Y',
  DEFAULT_SURVEY    VARCHAR2(16 BYTE),
  QUESTION          VARCHAR2(16 BYTE),
  DEFAULT_QUESTION  VARCHAR2(16 BYTE),
  ID                VARCHAR2(16 BYTE),
  DATE_MODIFIED     DATE                        DEFAULT SYSDATE,
  CONSTRAINT SURVEY_SETUP_PK
 PRIMARY KEY
 (ID),
  CONSTRAINT SURVEY_SETUP_U01
 UNIQUE (SURVEY, SEQUENCE),
  FOREIGN KEY (DEFAULT_SURVEY) 
 REFERENCES CUST.SURVEY_DEF (ID),
  FOREIGN KEY (SURVEY) 
 REFERENCES CUST.SURVEY_DEF (ID)
);







