INSERT INTO CMS.LOOKUP (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) values ('Product.LAYOUT','103','Wine Deals','Wine Deals',32);
INSERT INTO CMS.LOOKUP (LOOKUPTYPE_CODE,CODE,LABEL,DESCRIPTION,ORDINAL) values ('Product.LAYOUT','104','Wine Expert''s Favs','Wine Expert''s Favs',32);

INSERT INTO CMS.ATTRIBUTEDEFINITION
  (NAME, ID, CONTENTTYPE_ID, ATTRIBUTETYPE_CODE, INHERITABLE, REQUIRED, LABEL, CARDINALITY_CODE, LOOKUP_CODE)
  VALUES ('HIDE_WINE_RATING', 'Category.HIDE_WINE_RATING', 'Category', 'B', 'T', 'F', 'Hide Wine Rating &'||' Pricing (Use Regular Display Instead)', 'One', NULL);

INSERT INTO cms.relationshipdefinition (NAME, ID, CONTENTTYPE_ID, INHERITABLE, REQUIRED, NAVIGABLE, READONLY, LABEL, CARDINALITY_CODE)
  VALUES ('WINE_FILTER_VALUE', 'Category.WINE_FILTER_VALUE', 'Category', 'F', 'F', 'F', 'F', 'Wine Filter Value', 'One');
INSERT INTO cms.relationshipdestination (ID, RELATIONSHIPDEFINITION_ID, CONTENTTYPE_ID, REVERSE_ATTRIBUTE_NAME, REVERSE_ATTRIBUTE_LABEL)
  VALUES ('Category.WINE_FILTER_VALUE.DomainValue', 'Category.WINE_FILTER_VALUE', 'DomainValue', NULL, NULL);


INSERT INTO CMS.ATTRIBUTEDEFINITION
  (NAME, ID, CONTENTTYPE_ID, ATTRIBUTETYPE_CODE, INHERITABLE, REQUIRED, LABEL, CARDINALITY_CODE, LOOKUP_CODE)
  VALUES ('DEPARTMENT_TEMPLATE_PATH', 'Department.DEPARTMENT_TEMPLATE_PATH', 'Department', 'S', 'F', 'F', 'Department Template Path', 'One', NULL);
