
INSERT INTO ss_variants(ID, feature, type)
	VALUES('classic-ymal','YMAL', 'classicYMAL');

INSERT INTO ss_variants(ID, feature, type)
	VALUES('smart-ymal','YMAL', 'smartYMAL');

INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C1',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C2',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C3',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C4',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C5',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C6',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C7',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C8',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C9',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C10',  sysdate, 'classic-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C11',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C12',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C13',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C14',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C15',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C16',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C17',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C18',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C19',  sysdate, 'smart-ymal');
INSERT INTO SS_VARIANT_ASSIGNMENT ( COHORT_ID, "DATE", VARIANT_ID ) VALUES ('C20',  sysdate, 'smart-ymal');

