import java.util.ArrayList;
import java.util.Date;
import com.freshdirect.analytics.*;
import com.freshdirect.framework.util.DateUtil;

rule "bounce1"
no-loop
when
	event : SessionEvent(eval( (availCount + soldCount) > 0 && (availCount * 100/(soldCount + availCount)) < 25  && lastTimeslot != "" && !"Y".equals(orderPlaced)) )
    not OrderEvent(customerId == event.customerId)
then
	retract(event);
	BounceDAO.insert(event.getCustomerId(),"NEW", DateUtil.getNextDate(), event.getCutOff(),event.getZone(), 
	event.getLastTimeslot(), event.getPageType());
end

rule "roll1"
no-loop
when
	event : SessionEvent(eval( (availCount + soldCount) > 0 && (availCount * 100/(soldCount + availCount)) < 25 && lastTimeslot != "" && "Y".equals(orderPlaced) ))
    order : OrderEvent(customerId == event.customerId && eval(EventHelper.isFutureDay(order.getDeliveryDate(), 2)))
then
	retract(event); retract(order);
	RollDAO.insert(event.getCustomerId(), event.getSoldCount()*100/(event.getSoldCount()+event.getAvailCount()), 
	DateUtil.getNextDate(),  event.getCutOff(),event.getZone(), event.getLastTimeslot());
end

