INSERT INTO CONTENTNODE (ID, CONTENTTYPE_ID) VALUES ('SortOption:Sort_FullFavorites', 'SortOption');
INSERT INTO ATTRIBUTE (CONTENTNODE_ID, ID, VALUE, ORDINAL, DEF_NAME, DEF_CONTENTTYPE) VALUES ('SortOption:Sort_FullFavorites', SYSTEM_SEQ.NEXTVAL ,'CUSTOMER_POPULARITY', 0, 'strategy', 'SortOption');
INSERT INTO ATTRIBUTE (CONTENTNODE_ID, ID, VALUE, ORDINAL, DEF_NAME, DEF_CONTENTTYPE) VALUES ('SortOption:Sort_FullFavorites', SYSTEM_SEQ.NEXTVAL ,'Your Favorites', 0, 'label', 'SortOption');
INSERT INTO ATTRIBUTE (CONTENTNODE_ID, ID, VALUE, ORDINAL, DEF_NAME, DEF_CONTENTTYPE) VALUES ('SortOption:Sort_FullFavorites', SYSTEM_SEQ.NEXTVAL ,'Your Favorites', 0, 'selectedLabel', 'SortOption');

