CREATE INDEX ZIPCODE_WORKTAB_SX ON ZIPCODE_WORKTAB(geoloc) INDEXTYPE IS MDSYS.SPATIAL_INDEX

CREATE INDEX ZONE_SX ON ZONE(geoloc) INDEXTYPE IS MDSYS.SPATIAL_INDEX

CREATE INDEX ZIPCODE_SX ON ZIPCODE(geoloc) INDEXTYPE IS MDSYS.SPATIAL_INDEX

CREATE INDEX ZONE_WORKTABLE_SX ON ZONE_WORKTABLE(geoloc) INDEXTYPE IS MDSYS.SPATIAL_INDEX