Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('4.00', '4.00', '4.00 Service Time', 4, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('4.25', '4.25', '4.25 Service Time', 4.25, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('5.00', '5.00', '5.00 Service Time', 5, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('5.25', '5.25', '5.25 Service Time', 5.25, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('5.75', '5.75', '5.75 Service Time', 5.75, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('4.50', '4.50', '4.50 Service Time', 4.5, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('20.00', '20.00', '20.00 Service Time', 20, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('4.75', '4.75', '4.75 Service Time', 4.75, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('7.50', '7.50', '7.50 Service Time', 7.5, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('3.00', '3.00', '3.00 Service Time', 3, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('5.50', '5.50', '5.50 Service Time', 5.5, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('6.25', '6.25', '6.25 Service Time', 6.25, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('3.25', '3.25', '3.25 Service Time', 3.25, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('9.00', '9.00', '9.00 Service Time', 9, 0.29);
Insert into DLV.SERVICETIME_TYPE   (CODE, NAME, DESCRIPTION, FIXED_SERVICE_TIME, VARIABLE_SERVICE_TIME) Values   ('30.00', '30.00', '30.00 Service Time', 30, 0.29);


Insert into TRANSP.TRN_ZONETYPE (ID, NAME, DESCRIPTION) Values (TRANSP.ZONETYPESEQ.NEXTVAL, 'Depot', 'Depot Zone');
Insert into TRANSP.TRN_ZONETYPE (ID, NAME, DESCRIPTION) Values (TRANSP.ZONETYPESEQ.NEXTVAL, '922 - FD Pickup', 'Special Zone Type for Customer Pickup');
Insert into TRANSP.TRN_ZONETYPE (ID, NAME, DESCRIPTION) Values (TRANSP.ZONETYPESEQ.NEXTVAL, '2 Man Zone', '2 Man Zone  ');
Insert into TRANSP.TRN_ZONETYPE (ID, NAME, DESCRIPTION) Values (TRANSP.ZONETYPESEQ.NEXTVAL, '1 Man Zone', '1 Man Zone ');
Insert into TRANSP.TRN_ZONETYPE (ID, NAME, DESCRIPTION) Values (TRANSP.ZONETYPESEQ.NEXTVAL, 'COS', '3 Man');


Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone', '001', 1, 1);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone', '002', 0, 0);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone', '003', 0, 0);

Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone', '003', 0, 0);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone', '002', 2, 1);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone', '001', 2, 1);

Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS', '003', 0, 0);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS', '002', 2, 1);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS', '001', 2, 1);


Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot', '001', 2, 1);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot', '002', 1, 0);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot', '003', 6, 3);

Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '922 - FD Pickup', '001', 1, 0);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '922 - FD Pickup', '002', 2, 1);
Insert into TRANSP.ZONETYPE_RESOURCE (ZONETYPE_ID, ROLE, MAXIMUM_NO, REQUIRED_NO) Values   (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '922 - FD Pickup', '003', 2, 0);

Insert into DLV.SCENARIO_DAYS  (ID, SCENARIO_CODE) Values   (DLV.DEL_SCENDAYS_SEQ.NEXTVAL, 'DEF');

UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Default') WHERE ZONE_CODE = '181';

UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Default') WHERE ZONE_CODE = '095';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Default') WHERE ZONE_CODE = '033';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Default') WHERE ZONE_CODE = '202';

UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '005';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '914';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '014';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '030';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '040';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '050';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '060';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '066';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '070';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '080';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '901';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '915';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '912';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '911';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '999';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '942';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '913';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '941';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '931';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'Depot') WHERE ZONE_CODE = '013';

UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '510';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '560';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '003';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '004';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '006';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '007';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '008';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '009';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '010';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '011';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '012';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '015';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '016';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '018';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '020';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '021';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '022';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '090';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '101';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '103';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '104';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '105';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '107';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '108';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '180';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '310';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '320';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '330';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '360';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '380';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '410';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '420';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '430';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '710';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '720';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '810';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '820';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '825';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '830';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '840';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '850';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '860';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '921';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '400';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '515';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '875';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '505';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '182';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '201';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '961';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '500';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '951';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '601';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '580';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '501';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '506';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '2 Man Zone') WHERE ZONE_CODE = '002';

UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '001';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '700';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '019';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '890';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '106';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '109';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '340';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '350';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '370';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '600';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '730';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '582';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '780';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '785';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '200';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '800';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '102';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '801';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '802';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '561';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '581';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '1 Man Zone') WHERE ZONE_CODE = '017';

UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '660';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '610';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '620';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '630';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '640';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '650';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '690';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '680';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '685';
UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = 'COS') WHERE ZONE_CODE = '250';

UPDATE TRANSP.ZONE SET ZONE_TYPE =  (SELECT ID FROM TRANSP.TRN_ZONETYPE WHERE NAME = '922 - FD Pickup') WHERE ZONE_CODE = '922';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.00' WHERE ZONE_CODE = '022';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.00' WHERE ZONE_CODE = '875';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.00' WHERE ZONE_CODE = '922';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.00' WHERE ZONE_CODE = '921';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.00' WHERE ZONE_CODE = '951';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.00' WHERE ZONE_CODE = '013';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.25' WHERE ZONE_CODE ='582';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.25' WHERE ZONE_CODE ='370';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.25' WHERE ZONE_CODE ='360';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.25' WHERE ZONE_CODE ='340';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.25' WHERE ZONE_CODE ='019';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.25' WHERE ZONE_CODE ='380';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '3.25' WHERE ZONE_CODE ='580';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '30.00' WHERE ZONE_CODE ='700';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.00' WHERE ZONE_CODE ='200';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.00' WHERE ZONE_CODE ='561';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.00' WHERE ZONE_CODE ='106';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.25' WHERE ZONE_CODE = '109';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.25' WHERE ZONE_CODE = '560';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.25' WHERE ZONE_CODE = '101';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.25' WHERE ZONE_CODE = '105';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '350';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '017';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '095';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '180';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '730';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '020';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '840';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '007';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '890';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '030';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '780';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '400';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '710';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '016';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '942';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '913';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '4.50' WHERE ZONE_CODE = '011';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '506';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '914';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '941';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '202';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '999';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '500';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '961';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '102';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '201';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '181';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '505';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '785';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '860';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '830';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '650';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '630';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '420';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '410';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '320';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '103';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '080';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '002';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '4.75' WHERE ZONE_CODE = '006';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '510';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '018';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '090';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '108';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '310';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '581';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '430';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '825';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '515';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '601';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.00' WHERE ZONE_CODE = '330';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '660';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '003';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '004';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '010';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '012';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '015';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '600';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '820';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '250';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '801';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '802';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE =  '5.25' WHERE ZONE_CODE = '911';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.50' WHERE ZONE_CODE = '810';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.50' WHERE ZONE_CODE = '001';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '009';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '008';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '620';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '931';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '033';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '912';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '915';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '901';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '182';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '720';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '501';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '610';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '107';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '104';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '5.75' WHERE ZONE_CODE = '021';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '070';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '005';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '040';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '050';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '640';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '850';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '014';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '066';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '7.50' WHERE ZONE_CODE = '060';

UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '9.00' WHERE ZONE_CODE = '680';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '9.00' WHERE ZONE_CODE = '685';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '9.00' WHERE ZONE_CODE = '690';
UPDATE TRANSP.ZONE SET SERVICETIME_TYPE = '9.00' WHERE ZONE_CODE = '800';







