// Add CANDIDATE_LIST to Category

INSERT INTO cms.relationshipdefinition (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,LABEL,CARDINALITY_CODE) VALUES ('CANDIDATE_LIST','Category.CANDIDATE_LIST','Category','F','F','T','','Many');

INSERT INTO cms.relationshipdestination (RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,LABEL,ID) VALUES ('Category.CANDIDATE_LIST','Category',NULL,'Category.CANDIDATE_LIST.Category');
INSERT INTO cms.relationshipdestination (RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,LABEL,ID) VALUES ('Category.CANDIDATE_LIST','Product',NULL,'Category.CANDIDATE_LIST.Product');


// Add MANUAL_SELECTION_SLOTS to Category

INSERT INTO cms.attributedefinition (NAME,ID,CONTENTTYPE_ID,ATTRIBUTETYPE_CODE,INHERITABLE,REQUIRED,LABEL,CARDINALITY_CODE,LOOKUP_CODE) VALUES ('MANUAL_SELECTION_SLOTS', 'Category.MANUAL_SELECTION_SLOTS', 'Category','I','F','F','Manual Selection Slots','One',NULL);
