ALTER TABLE "SS_VARIANTS" MODIFY "CONFIG_ID" VARCHAR2(16) NULL;

ALTER TABLE "SS_VARIANTS" ADD "TYPE" VARCHAR2(16) DEFAULT '';

UPDATE "SS_VARIANTS" "v" SET "TYPE" = (SELECT "TYPE" FROM "SS_SERVICE_CONFIGS" "sc" WHERE "v"."CONFIG_ID" = "sc"."ID");

ALTER TABLE "SS_VARIANTS" MODIFY "TYPE" VARCHAR2(16) DEFAULT '' NOT NULL;

CREATE TABLE "SS_VARIANT_PARAMS" ("ID" VARCHAR2(16) NOT NULL, "KEY" VARCHAR2(16) NOT NULL, "VALUE" VARCHAR2(256), 
        CONSTRAINT "SS_VARIANT_PARAMS_PK1" PRIMARY KEY ("ID", "KEY") ENABLE);

ALTER TABLE "SS_VARIANT_PARAMS" ADD CONSTRAINT "SS_VARIANT_PARMS_SS_VARS_FK1" FOREIGN KEY ("ID") REFERENCES "SS_VARIANTS" ("ID") ENABLE;

GRANT SELECT ON "SS_VARIANT_PARAMS" TO FDSTORE;

INSERT INTO "SS_VARIANT_PARAMS" ("ID", "KEY", "VALUE") SELECT v."ID", sc."KEY", sc."VALUE" FROM "SS_SERVICE_PARAMS" sc INNER JOIN "SS_VARIANTS" v ON v."CONFIG_ID" = sc."ID";

