CREATE TABLE SS_SERVICE_PARAMS(ID VARCHAR2(16) NOT NULL, KEY VARCHAR2(16) NOT NULL,VALUE VARCHAR2(256), 
 CONSTRAINT SS_SERVICE_PARAMS_PK PRIMARY KEY (ID,KEY) ENABLE);

ALTER TABLE SS_SERVICE_PARAMS ADD CONSTRAINT SS_SERVICE_PARAMS_SS_SERV_FK1 FOREIGN KEY (ID) REFERENCES SS_SERVICE_CONFIGS (ID) ENABLE;

// CUSTOMIZE
GRANT SELECT ON SS_SERVICE_PARAMS TO FDSTORE;
