ALTER TABLE "CUST.SS_VARIANTS" MODIFY "CONFIG_ID" VARCHAR2(16) NULL;

ALTER TABLE "CUST.SS_VARIANTS" ADD "TYPE" VARCHAR2(16) DEFAULT '';

UPDATE "CUST.SS_VARIANTS" "v" SET "TYPE" = (SELECT "TYPE" FROM "CUST.SS_SERVICE_CONFIGS" "sc" WHERE "v"."CONFIG_ID" = "sc"."ID")

ALTER TABLE "CUST.SS_VARIANTS" MODIFY "TYPE" VARCHAR2(16) DEFAULT '' NOT NULL;

CREATE TABLE "CUST.SS_VARIANT_PARAMS" ("ID" VARCHAR2(16) NOT NULL, "KEY" VARCHAR2(16) NOT NULL, "VALUE" VARCHAR2(256), 
        CONSTRAINT "SS_VARIANT_PARAMS_PK" PRIMARY KEY ("ID", "KEY") ENABLE);

ALTER TABLE "CUST.SS_VARIANT_PARAMS" ADD CONSTRAINT "CUST.SS_VARIANT_PARMS_SS_VARS_FK1" FOREIGN KEY ("ID") REFERENCES "CUST.SS_VARIANTS" ("ID") ENABLE;

GRANT SELECT ON "CUST.SS_VARIANT_PARAMS" TO FDSTORE;

INSERT INTO "CUST"."SS_VARIANT_PARAMS" ("ID", "KEY", "VALUE") SELECT v."ID", sc."KEY", sc."VALUE" FROM "CUST"."SS_SERVICE_PARAMS" sc INNER JOIN "CUST"."SS_VARIANTS" v ON v."CONFIG_ID" = sc."ID";

DELETE FROM "CUST"."SS_VARIANTS" WHERE "TYPE" = 'composite';

