--CREATE THE MATERIALIZED VIEW 

CREATE MATERIALIZED VIEW DLV.BULK_ZONE_WORKTABLE 
TABLESPACE FDDLVDAT
PCTUSED    0
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCACHE
LOGGING
NOCOMPRESS
NOPARALLEL
BUILD IMMEDIATE
USING INDEX
            TABLESPACE FDDLVDAT
            PCTFREE    10
            INITRANS   2
            MAXTRANS   255
            STORAGE    (
                        INITIAL          64K
                        MINEXTENTS       1
                        MAXEXTENTS       UNLIMITED
                        PCTINCREASE      0
                        BUFFER_POOL      DEFAULT
                       )
REFRESH COMPLETE
START WITH TO_DATE('20-Aug-2013 01:01:00','dd-mon-yyyy hh24:mi:ss')
NEXT trunc(sysdate+1)+1/24+1/24/60  
WITH ROWID
AS 
/* Formatted on 8/19/2013 3:59:56 PM (QP5 v5.139.911.3011) */
SELECT "BULK_ZONE_WORKTABLE"."CODE" "CODE",
       "BULK_ZONE_WORKTABLE"."NAME" "NAME",
       "BULK_ZONE_WORKTABLE"."MI_SYMBOLOGY" "MI_SYMBOLOGY",
       "BULK_ZONE_WORKTABLE"."MI_PRINX" "MI_PRINX",
       "BULK_ZONE_WORKTABLE"."GEOLOC" "GEOLOC"
  FROM "DLV"."BULK_ZONE_WORKTABLE"@DBSTG.NYC.FRESHDIRECT.COM "BULK_ZONE_WORKTABLE";

COMMENT ON MATERIALIZED VIEW DLV.BULK_ZONE_WORKTABLE IS 'snapshot table for snapshot DLV.BULK_ZONE_WORKTABLE';

-- Note: Index I_SNAP$_BULK_ZONE_WORKTABLE will be created automatically 
--       by Oracle with the associated materialized view.

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO AMILMAN;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO DMODY;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO DWREAD;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO FDSTORE;

GRANT INSERT, SELECT, UPDATE ON DLV.BULK_ZONE_WORKTABLE TO FDSTORE_PRDA;

GRANT INSERT, SELECT, UPDATE ON DLV.BULK_ZONE_WORKTABLE TO FDTRN_PRDA;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO GBRODETSKY;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO HBENNACEUR;

GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.BULK_ZONE_WORKTABLE TO KAMIN;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO LKDLV;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO NBHATT;

GRANT SELECT ON DLV.BULK_ZONE_WORKTABLE TO PTIJORIWALA;

GRANT INSERT, SELECT, UPDATE ON DLV.BULK_ZONE_WORKTABLE TO TRANSP;
