ALTER TABLE DLV.DELIVERY_BUILDING ADD (FORCE_BULK VARCHAR2(1 BYTE))

ALTER TABLE DLV.SERVICETIME_SCENARIO ADD (BULK_THRESHOLD  NUMBER(5,2))

Insert into DLV.REGION
   (ID, NAME, HOME_DELIVERY, SERVICE_TYPE)
 Values
   ('100248259', 'Bulk Region', 'X', 'HYBRID');

