INSERT INTO cms.relationshipdefinition (NAME,ID,CONTENTTYPE_ID,INHERITABLE,REQUIRED,NAVIGABLE,LABEL,CARDINALITY_CODE) VALUES ('PROD_IMAGE_PACKAGE','Product.PROD_IMAGE_PACKAGE','Product','F','F','F','','One');

INSERT INTO cms.relationshipdestination (RELATIONSHIPDEFINITION_ID,CONTENTTYPE_ID,LABEL,ID) VALUES ('Product.PROD_IMAGE_PACKAGE','Image',NULL,'Product.PROD_IMAGE_PACKAGE.Image');