 
GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_RESTRICTION TO fdstore_ststg01;
GRANT DELETE, INSERT, SELECT, UPDATE ON DLV.TIMESLOT_RESTRICTION TO fdtrn_ststg01;
GRANT SELECT ON  DLV.TIMESLOT_RESTRICTION TO APPDEV;