DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.PRODUCT_LAYOUT' AND CODE = '2';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.PRODUCT_LAYOUT' AND CODE = '4';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '14';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '17';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '22';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '23';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '26';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '27';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '28';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '30';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '98';
DELETE FROM CMS.LOOKUP WHERE LOOKUPTYPE_CODE = 'Product.LAYOUT' AND CODE = '99';

